import assert from "node:assert/strict";
import { describe, it } from "node:test";
import { readFileSync } from "node:fs";
import { classifyProviderAndModel, resolvePaidProviderPermission } from "../ai/governance/classification";
import { aiUserPolicySchema, fieldErrorsFromZod } from "../ai/governance/userPolicy";

const provider = (patch: Record<string, unknown> = {}) => ({ providerType: "ollama" as const, baseUrl: "http://localhost:11434", locationClassification: "LOCAL" as const, administratorConfirmedLocal: false, trustedNetwork: false, customConfiguration: {}, ...patch });

describe("v2.4.2 Ollama provider/model classification", () => {
  it("classifies self-hosted Ollama llama3 as LOCAL_FREE", () => assert.equal(classifyProviderAndModel(provider(), "llama3:latest").classification, "LOCAL_FREE"));
  it("recognizes private, Docker, loopback, and configured internal Ollama hosts", () => { for (const baseUrl of ["http://127.0.0.1:11434", "http://10.0.0.8:11434", "http://172.20.0.3:11434", "http://192.168.1.5:11434", "http://host.docker.internal:11434", "http://ollama:11434"]) assert.equal(classifyProviderAndModel(provider({ baseUrl }), "llama3:latest").classification, "LOCAL_FREE"); assert.equal(classifyProviderAndModel(provider({ baseUrl: "http://ai.internal:11434", customConfiguration: { internalHostnames: ["ai.internal"] } }), "llama3:latest").classification, "LOCAL_FREE"); });
  it("does not require paid permission or pricing for local Ollama", () => { const result = classifyProviderAndModel(provider(), "llama3:latest"); assert.equal(result.requiresPaidProviderPermission, false); assert.equal(result.missingPricingPermitted, true); });
  it("requires paid permission for an explicitly paid remote Ollama model", () => { const result = classifyProviderAndModel(provider({ baseUrl: "https://ollama.example", locationClassification: "REMOTE" }), "cloud", { billingClassification: "EXTERNAL", status: "PRICED", fixedRequestCost: "0.01" }); assert.equal(result.classification, "EXTERNAL_PAID"); assert.equal(result.requiresPaidProviderPermission, true); });
  it("classifies explicitly free or unpriced remote Ollama separately", () => assert.equal(classifyProviderAndModel(provider({ baseUrl: "https://ollama.example", locationClassification: "REMOTE" }), "cloud").classification, "EXTERNAL_FREE_OR_UNPRICED"));
  it("fails closed when locality cannot be established", () => assert.equal(classifyProviderAndModel(provider({ providerType: "openai", baseUrl: "https://unknown.example", locationClassification: "UNKNOWN" }), "model").classification, "UNKNOWN"));
  it("never performs arithmetic when pricing is missing", () => assert.doesNotThrow(() => classifyProviderAndModel(provider(), "unpriced")));
});

describe("v2.4.2 user AI policy normalization", () => {
  const id = "123e4567-e89b-42d3-a456-426614174000";
  const parse = (patch: Record<string, unknown> = {}) => aiUserPolicySchema.safeParse({ scope: "user", userId: id, ...patch });
  it("accepts a valid UUID and trims surrounding whitespace", () => { const result = parse({ userId: `  ${id}  ` }); assert.equal(result.success, true); if (result.success) assert.equal(result.data.userId, id); });
  it("returns a user_uuid field error for malformed UUIDs", () => { const result = parse({ userId: "not-a-uuid" }); assert.equal(result.success, false); if (!result.success) assert.match(fieldErrorsFromZod(result.error).user_uuid, /valid Mixarr user UUID/); });
  it("accepts a permission-only policy", () => assert.equal(parse({ paidProvidersAllowed: true }).success, true));
  it("normalizes empty numeric strings to null", () => { const result = parse({ dailyCostLimit: "", monthlyCostLimit: "  ", dailyRequestLimit: "" }); assert.equal(result.success, true); if (result.success) assert.deepEqual([result.data.dailyCostLimit, result.data.monthlyCostLimit, result.data.dailyRequestLimit], [null, null, null]); });
  it("preserves explicit zero", () => { const result = parse({ dailyCostLimit: "0", dailyRequestLimit: "0" }); assert.equal(result.success, true); if (result.success) assert.deepEqual([result.data.dailyCostLimit, result.data.dailyRequestLimit], ["0", 0]); });
  it("rejects negative limits with field errors", () => { const result = parse({ dailyCostLimit: -1 }); assert.equal(result.success, false); if (!result.success) assert.ok(fieldErrorsFromZod(result.error).daily_cost_limit); });
  it("rejects decimal request limits", () => { const result = parse({ dailyRequestLimit: "1.5" }); assert.equal(result.success, false); if (!result.success) assert.match(fieldErrorsFromZod(result.error).daily_requests, /whole number/); });
  it("supports six-decimal cost precision and rejects excess precision", () => { assert.equal(parse({ dailyCostLimit: "1.123456" }).success, true); assert.equal(parse({ dailyCostLimit: "1.1234567" }).success, false); });
  it("keeps permission inheritance distinct from explicit false and true", () => { assert.equal(resolvePaidProviderPermission({ globalAllowed: true, allowUserOverrides: true, userValue: undefined }).allowed, true); assert.deepEqual(resolvePaidProviderPermission({ globalAllowed: true, allowUserOverrides: true, userValue: false }), { allowed: false, value: false, source: "USER_OVERRIDE" }); assert.deepEqual(resolvePaidProviderPermission({ globalAllowed: false, allowUserOverrides: true, userValue: true }), { allowed: true, value: true, source: "USER_OVERRIDE" }); assert.equal(resolvePaidProviderPermission({ globalAllowed: false, allowUserOverrides: false, userValue: true }).allowed, false); });
});

describe("v2.4.2 persistence, test, audit, logging, and frontend contracts", () => {
  const read = (path: string) => readFileSync(path, "utf8");
  it("validates user existence and uses one-row upsert persistence", () => { const route = read("src/app/api/ai/budgets/route.ts"); assert.match(route, /prisma\.user\.findUnique/); assert.match(route, /No Mixarr user exists with this UUID/); assert.match(route, /aiUserLimit\.upsert/); });
  it("uses the authenticated administrator UUID for a provider test", () => { const route = read("src/app/api/ai/providers/[providerId]/test/route.ts"); assert.match(route, /requireAiAdmin\(\)/); assert.match(route, /testAiProviderConnection\(params\.providerId, request\.signal, userId\)/); });
  it("runs one configured Ollama request and records staged outcomes", () => { const adapter = read("src/ai/providers/ollama.ts"); const configuredBranch = adapter.slice(adapter.indexOf("if (config.defaultModel)"), adapter.indexOf("const models = await this.discoverModels")); assert.equal((configuredBranch.match(/this\.complete/g) || []).length, 1); assert.doesNotMatch(configuredBranch, /discoverModels/); const service = read("src/ai/governance/service.ts"); assert.match(service, /status: "BLOCKED"/); assert.match(service, /status: result\.success \? "COMPLETED"/); });
  it("returns governance, provider, and internal diagnostics with correlation IDs", () => { const route = read("src/app/api/ai/providers/[providerId]/test/route.ts"); for (const marker of [/stage/, /PAID_PROVIDER_NOT_PERMITTED/, /PROVIDER_CONNECTION_FAILED|provider/, /correlation_id/]) assert.match(route, marker); });
  it("never includes prompts, provider responses, or secrets in unexpected-error log fields", () => { const logging = read("src/ai/governance/logging.ts"); assert.doesNotMatch(logging, /prompt:|response:|apiKey:|authorization:|cookie:/i); assert.match(logging, /sanitizedExceptionMessage/); assert.match(logging, /sanitizedStack/); });
  it("keeps audit persistence failures separate from the original AI request", () => { const coordinator = read("src/ai/request-coordinator/index.ts"); assert.match(coordinator, /let auditId: string \| undefined/); assert.match(coordinator, /governanceDecisionStage: "audit_persistence"/); assert.match(coordinator, /completeAiAudit\([\s\S]*?\.catch/); });
  it("casts the PostgreSQL advisory-lock void result before Prisma deserialization", () => { const service = read("src/ai/governance/service.ts"); assert.match(service, /pg_advisory_xact_lock[\s\S]*?::text AS "lockResult"/); assert.doesNotMatch(service, /pg_advisory_xact_lock\(hashtext\([^;]+\)\)`/); });
  it("keeps exception messages out of sanitized stack traces", () => { const logging = read("src/ai/governance/logging.ts"); assert.match(logging, /filter\(\(line\) => \/\^\\s\*at\\s\//); assert.doesNotMatch(logging, /\.\.\.lines\.slice\(1\)/); });
  it("maps backend field errors, preserves form state, activates Budgets, scrolls, and prevents duplicate submits", () => { const ui = read("src/components/AiGovernanceDashboard.tsx"); for (const marker of [/fieldErrors/, /setSection\("Budgets"\)/, /scrollIntoView/, /aria-invalid/, /saving !== null/, /User Limits could not be saved/, /Inherit global policy/]) assert.match(ui, marker); });
  it("shows classification, denial, local cost text, and correlation IDs in tests and audits", () => { const ui = read("src/components/AiProviderDashboard.tsx"); for (const marker of [/Governance rejected the test/, /Classification:/, /Local \/ no estimated provider cost/, /Pricing not configured/, /Correlation ID/]) assert.match(ui, marker); });
  it("ships an idempotent, history-preserving, fail-closed tri-state migration", () => { const migration = read("prisma/migrations/20260721210000_ai_governance_ollama_user_policy_hotfix/migration.sql"); assert.match(migration, /ADD COLUMN IF NOT EXISTS/); assert.match(migration, /paidProvidersAllowed" BOOLEAN NOT NULL DEFAULT false/); assert.match(migration, /DROP NOT NULL/); assert.doesNotMatch(migration, /DELETE|TRUNCATE|DROP TABLE/i); });
});
