import assert from "node:assert/strict";
import { describe, it } from "node:test";
import { readFileSync } from "node:fs";
import { AiError } from "../ai/errors";
import { alertDeduplicationKey, applyMetadataPrivacyPolicy, budgetPeriod, currencyMicros, estimateRequestCost, estimateTokens, evaluateCostLimit, evaluateRetryCost, resolveEffectiveTokenLimits, resolvePerRequestCostLimit, selectCheaperEligibleModel, strictestPrivacyMode, trimContext, validatePromptLimits, wouldExceedBudget } from "../ai/governance/policy";

describe("AI governance policy", () => {
  it("applies the strictest privacy mode", () => { assert.equal(strictestPrivacyMode("FULL_METADATA", "METADATA_LIMITED", "ANONYMOUS_METADATA"), "ANONYMOUS_METADATA"); assert.equal(strictestPrivacyMode("LOCAL_ONLY", "FULL_METADATA"), "LOCAL_ONLY"); });
  it("blocks every external provider in Local Only", () => { assert.throws(() => applyMetadataPrivacyPolicy({ mode: "LOCAL_ONLY", providerLocation: "REMOTE", records: [] }), (error: unknown) => error instanceof AiError && error.category === "AI_EXTERNAL_PROVIDER_BLOCKED"); });
  it("uses an external metadata allowlist and blocks sensitive and unknown fields", () => { const result = applyMetadataPrivacyPolicy({ mode: "METADATA_LIMITED", providerLocation: "REMOTE", allowlist: ["artist", "title"], records: [{ artist: "A", title: "T", file_path: "/private/music.flac", plex_rating_key: "42", mystery: "x" }] }); assert.deepEqual(result.payload, [{ artist: "A", title: "T" }]); assert.deepEqual(result.report.blocked_fields, ["file_path", "mystery", "plex_rating_key"]); assert.deepEqual(result.report.unknown_fields, ["mystery"]); });
  it("requires a versioned acknowledgment for Full Metadata", () => { assert.throws(() => applyMetadataPrivacyPolicy({ mode: "FULL_METADATA", providerLocation: "REMOTE", records: [{ artist: "A" }] }), (error: unknown) => error instanceof AiError && error.category === "AI_PRIVACY_POLICY_BLOCKED"); });
  it("anonymizes identifying music fields deterministically", () => { const input = { mode: "ANONYMOUS_METADATA" as const, providerLocation: "REMOTE" as const, records: [{ artist: "Massive Attack", title: "Teardrop", genres: ["trip hop"], release_year: 1998, bpm: 76, energy: 0.2 }], allowlist: ["artist", "title", "genres", "release_year", "bpm", "energy"], fullMetadataAcknowledged: false }; const first = applyMetadataPrivacyPolicy(input); const second = applyMetadataPrivacyPolicy(input); assert.deepEqual(first.payload, second.payload); assert.deepEqual(first.payload, [{ genres: ["electronic"], release_year: "1990-1999 era", bpm: "70-79 BPM", energy: 0.2 }]); assert.match(first.report.warning || "", /not mathematical anonymity/); });
  it("resolves token limits using the strictest scope and safely clamps output", () => { const limits = resolveEffectiveTokenLimits([{ maximumInputTokens: 1000, maximumOutputTokens: 500, maximumCombinedTokens: 1200 }, { maximumInputTokens: 800, maximumOutputTokens: 900 }], 700); assert.deepEqual(limits, { maximumInputTokens: 800, maximumOutputTokens: 500, maximumCombinedTokens: 1200 }); const result = validatePromptLimits({ text: "word ".repeat(400), messageCount: 2, metadataRecordCount: 0, limits: { maximumPromptCharacters: 10000, maximumPromptBytes: 20000, maximumContextMessages: 10, maximumMetadataRecords: 10, maximumInputTokens: 800, maximumOutputTokens: 500, maximumCombinedTokens: 700 }, requestedOutputTokens: 500 }); assert.ok(result.maxOutputTokens < 500); assert.equal(result.clamped, true); });
  it("rejects prompt character, byte, message, record, and token violations before dispatch", () => { assert.throws(() => validatePromptLimits({ text: "x".repeat(101), messageCount: 1, metadataRecordCount: 0, limits: { maximumPromptCharacters: 100, maximumPromptBytes: 1000, maximumContextMessages: 10, maximumMetadataRecords: 10, maximumInputTokens: 1000 } }), (error: unknown) => error instanceof AiError && error.category === "AI_PROMPT_TOO_LARGE"); });
  it("calculates pricing with six-decimal fixed-point precision and retry allowance", () => { const estimate = estimateRequestCost({ inputTokens: 1_000_000, maximumOutputTokens: 1_000_000, expectedOutputTokens: 500_000, cachedInputTokens: 100_000, retryAllowance: 1, pricing: { inputPricePerMillion: "1.000001", cachedInputPricePerMillion: "0.500001", outputPricePerMillion: "2.000001", fixedRequestCost: "0.000001", currency: "USD", estimated: false } }); assert.equal(estimate.minimumEstimatedCost, 0.950003); assert.equal(estimate.expectedEstimatedCost, 1.950004); assert.equal(estimate.maximumEstimatedCost, 5.900008); assert.equal(estimate.confidence, "CONFIGURED"); });
  it("admits an initial attempt without applying a lower retry-only limit", () => { const initial = evaluateCostLimit({ scope: "request", estimatedCost: "0.500000", limit: "1.000000", reasonCode: "AI_REQUEST_COST_LIMIT_EXCEEDED" }); assert.equal(initial.allowed, true); const retry = evaluateRetryCost({ incrementalCost: "0.500000", retryNumber: 1, retryLimit: "0.100000", initialAttemptCost: "0.500000", cumulativeRequestLimit: "1.000000" }); assert.equal(retry.allowed, false); });
  it("allows and blocks actual retries using incremental and cumulative retry cost", () => { assert.equal(evaluateRetryCost({ incrementalCost: "0.100000", retryNumber: 1, retryLimit: "0.200000", initialAttemptCost: "0.300000", cumulativeRequestLimit: "0.500000" }).allowed, true); assert.equal(evaluateRetryCost({ incrementalCost: "0.100001", retryNumber: 2, retryLimit: "0.200000", initialAttemptCost: "0.100000" }).allowed, false); });
  it("treats a missing retry limit as unlimited and explicit zero as zero monetary allowance", () => { assert.equal(evaluateRetryCost({ incrementalCost: "99.000000", retryNumber: 1, retryLimit: null, initialAttemptCost: 1 }).allowed, true); assert.equal(evaluateRetryCost({ incrementalCost: "0.000001", retryNumber: 1, retryLimit: 0, initialAttemptCost: 0 }).allowed, false); assert.equal(evaluateRetryCost({ incrementalCost: 0, retryNumber: 1, retryLimit: 0, initialAttemptCost: 0 }).allowed, true); });
  it("uses canonical integer micro-units for currency decisions", () => { assert.equal(currencyMicros("1.000001"), 1_000_001); assert.equal(evaluateCostLimit({ scope: "request", estimatedCost: "0.100001", currentUsage: "0.899999", limit: "1.000000", reasonCode: "blocked" }).allowed, true); });
  it("treats missing and disabled per-request limits as unlimited even when stale values exist", () => {
    for (const setting of [
      { source: "global" as const },
      { source: "global" as const, enabled: false, value: 0 },
      { source: "global" as const, enabled: false, value: "0.010000" },
    ]) {
      const resolved = resolvePerRequestCostLimit([setting]);
      assert.equal(resolved.enabled, false);
      assert.equal(evaluateCostLimit({ scope: "request", estimatedCost: "0.002470", limit: resolved.limitUsd, reasonCode: "AI_REQUEST_COST_LIMIT_EXCEEDED" }).allowed, true);
    }
  });
  it("rejects enabled null, zero, negative, blank, and invalid per-request limits instead of producing a zero-dollar block", () => {
    for (const value of [null, "", 0, "0.000000", -1, "invalid"]) {
      assert.throws(() => resolvePerRequestCostLimit([{ source: "global", enabled: true, value }]), /greater than zero|non-negative decimals/i);
    }
  });
  it("allows 0.002470 below 0.01 and blocks it above 0.001 with decimal-safe comparisons", () => {
    const allowed = resolvePerRequestCostLimit([{ source: "global", enabled: true, value: "0.010000" }]);
    const blocked = resolvePerRequestCostLimit([{ source: "global", enabled: true, value: "0.001000" }]);
    assert.equal(evaluateCostLimit({ scope: "request", estimatedCost: "0.002470", limit: allowed.limitUsd, reasonCode: "AI_REQUEST_COST_LIMIT_EXCEEDED" }).allowed, true);
    assert.equal(evaluateCostLimit({ scope: "request", estimatedCost: "0.002470", limit: blocked.limitUsd, reasonCode: "AI_REQUEST_COST_LIMIT_EXCEEDED" }).allowed, false);
    assert.equal(evaluateCostLimit({ scope: "request", estimatedCost: "0.001000", limit: blocked.limitUsd, reasonCode: "AI_REQUEST_COST_LIMIT_EXCEEDED" }).allowed, true);
  });
  it("uses the strictest enabled global, selected-provider, and user limit and ignores missing provider overrides", () => {
    const inherited = resolvePerRequestCostLimit([{ source: "global", enabled: true, value: "0.010000" }, { source: "provider" }]);
    assert.deepEqual([inherited.limitUsd, inherited.source], ["0.010000", "global"]);
    const providerDisabled = resolvePerRequestCostLimit([{ source: "global", enabled: true, value: "0.010000" }, { source: "provider", enabled: false, value: "0.001000" }]);
    assert.deepEqual([providerDisabled.limitUsd, providerDisabled.source], ["0.010000", "global"]);
    const strictest = resolvePerRequestCostLimit([{ source: "global", enabled: true, value: "0.010000" }, { source: "provider", enabled: true, value: "0.005000" }, { source: "user", enabled: true, value: "0.007000" }]);
    assert.deepEqual([strictest.limitUsd, strictest.source], ["0.005000", "provider"]);
  });
  it("checks pending and reserved cost against hard limits without floating comparison drift", () => { assert.equal(wouldExceedBudget("1.000000", "0.700000", "0.200000", "0.100001"), true); assert.equal(wouldExceedBudget("1.000000", "0.700000", "0.200000", "0.100000"), false); });
  it("calculates custom monthly reset periods in UTC", () => { assert.deepEqual(budgetPeriod(new Date("2026-07-05T12:00:00Z"), 10), { start: new Date("2026-06-10T00:00:00Z"), end: new Date("2026-07-10T00:00:00Z") }); assert.deepEqual(budgetPeriod(new Date("2026-07-15T12:00:00Z"), 10), { start: new Date("2026-07-10T00:00:00Z"), end: new Date("2026-08-10T00:00:00Z") }); });
  it("trims only removable context and preserves required safety/schema sections", () => { const result = trimContext([{ id: "system", content: "required ".repeat(30), priority: "REQUIRED", kind: "SYSTEM" }, { id: "schema", content: "schema ".repeat(20), priority: "NORMAL", kind: "SCHEMA" }, { id: "optional", content: "optional ".repeat(100), priority: "OPTIONAL" }], 110, "REMOVE_LOWEST_PRIORITY"); assert.deepEqual(result.sections.map((section) => section.id), ["system", "schema"]); assert.deepEqual(result.report.removedSections, ["optional"]); });
  it("fails trimming when required context alone is too large", () => { assert.throws(() => trimContext([{ id: "system", content: "required ".repeat(1000), priority: "REQUIRED", kind: "SAFETY" }], 10, "REMOVE_OLDEST"), (error: unknown) => error instanceof AiError && error.category === "AI_CONTEXT_TRIMMING_FAILED"); });
  it("creates stable alert deduplication keys by period", () => { const date = new Date("2026-07-01T00:00:00Z"); assert.equal(alertDeduplicationKey("BUDGET_PERCENT", "GLOBAL", null, 0.75, date), alertDeduplicationKey("BUDGET_PERCENT", "GLOBAL", null, 0.75, date)); });
  it("selects only cheaper capability- and privacy-compatible models", () => { const preferred = { providerId: "local", model: "large", estimatedCost: 1, local: true, paid: false, capabilities: ["structured_json", "streaming"], contextTokens: 8000 }; const blockedPaid = { ...preferred, providerId: "remote", model: "cheap-paid", estimatedCost: .01, local: false, paid: true }; const local = { ...preferred, model: "cheap-local", estimatedCost: .1, contextTokens: 4000 }; const result = selectCheaperEligibleModel({ preferred, candidates: [blockedPaid, local], requiredCapabilities: ["structured_json"], minimumContextTokens: 3000, privacyMode: "LOCAL_ONLY", allowPaidProviderFallback: false }); assert.equal(result?.selected.model, "cheap-local"); assert.equal(result?.crossedProviderBoundary, false); });
  it("labels token estimates as estimates rather than exact provider usage", () => { assert.ok(estimateTokens("hello world") > 0); });
  it("ships an additive, indexed, decimal-safe migration and central coordinator enforcement", () => { const migration = readFileSync("prisma/migrations/20260721120000_ai_governance_v241/migration.sql", "utf8"); assert.doesNotMatch(migration, /^\s*(DROP|DELETE|TRUNCATE|UPDATE)\b/im); for (const marker of [/AiGovernanceSetting/, /AiModelPricing/, /AiBudgetReservation/, /AiProviderAttempt/, /DECIMAL\(18,6\)/, /AiGovernanceAudit/]) assert.match(migration, marker); const coordinator = readFileSync("src/ai/request-coordinator/index.ts", "utf8"); for (const marker of ["reserveAiBudget", "reconcileAiBudgetReservation", "previewAiRequest", "recordBlockedAiRequest", "AI_PAID_FALLBACK_BLOCKED", "aiProviderAttempt"]) assert.match(coordinator, new RegExp(marker)); });
  it("runs retry-cost admission only in the post-failure retry path", () => { const governance = readFileSync("src/ai/governance/service.ts", "utf8"), coordinator = readFileSync("src/ai/request-coordinator/index.ts", "utf8"); assert.match(governance, /retryAllowance:\s*0/); assert.match(coordinator, /isRetryEligible\(normalized\)[\s\S]+beforeRetry/); assert.match(coordinator, /prepareAiRetry/); assert.doesNotMatch(governance, /maximumEstimatedCost\s*-\s*cost\.expectedEstimatedCost/); });
  it("preserves null retry defaults and explicit zero during upgrades", () => { const migration = readFileSync("prisma/migrations/20260730010000_recipe_copilot_retry_cost_hotfix/migration.sql", "utf8"); assert.match(migration, /maximumRetryCost[\s\S]+DROP DEFAULT/); assert.match(migration, /NULL means no separate monetary retry ceiling/); assert.doesNotMatch(migration, /\b(UPDATE|DELETE|TRUNCATE|DROP TABLE)\b/i); });
});
