/** Stable schema-v1 fixture representing a Mixarr v2.4.15 backup payload. */
export const V2415_MANIFEST_FIXTURE = {
  backup_type: "mixarr-library-intelligence",
  schema_version: 1,
  analysis_data_version: 1,
  mixarr_version: "2.4.15",
  min_restore_schema_version: 1,
  created_at: "2026-07-01T00:00:00.000Z",
  counts: {
    tracks: 2,
    audio_features: 1,
    bpm: 1,
    popularity: 1,
    genres: 1,
    completed: 1,
    incomplete: 1,
    no_data: 2,
    no_data_popularity: 1,
    no_data_genres: 1,
    no_data_bpm: 0,
    source_local: 1,
    source_api: 0,
    source_estimated: 0,
  },
  source_classifications: ["local_essentia"],
  analysis_engine_versions: ["essentia@analysis-v1"],
  library_identifiers: ["7"],
  library_hashes: [],
};

export const V2415_TRACK_FIXTURE = [
  {
    id: "legacy-track-1",
    plex_guid: "plex://track/shared-recording",
    plex_guids: ["plex://track/shared-recording"],
    rating_key: "101",
    plex_id: "101",
    plex_library_id: "7",
    plex_server_id: "server-A",
    title: "Legacy Song",
    artist: "Artist",
    album: "Album",
    duration_ms: 180000,
    path_hash: "a".repeat(64),
    audio_feature: {
      energy: 0.8,
      valence: null,
      audioFeatureStatus: "complete",
      audioFeatureSource: "local_essentia",
      audioFeatureAnalyzedAt: "2026-06-30T00:00:00.000Z",
    },
    bpm: { effectiveBpm: 120, bpmAnalysisStatus: "complete" },
    popularity: { provider: "deezer", score: 73, popularityStatus: "success" },
    genres: { names: ["Rock"], normalized: ["rock"], status: "success", no_data: false },
  },
  {
    id: "legacy-track-2",
    plex_guid: "plex://track/shared-recording",
    plex_guids: ["plex://track/shared-recording"],
    rating_key: "102",
    plex_id: "102",
    plex_library_id: "7",
    plex_server_id: "server-A",
    title: "Legacy Song",
    artist: "Artist",
    album: "Deluxe Album",
    duration_ms: 180000,
    path_hash: "b".repeat(64),
    audio_feature: null,
    bpm: { bpmAnalysisStatus: "pending" },
    popularity: { provider: "not_found", popularityStatus: "no_data", popularityAttemptedAt: "2026-06-30T00:00:00.000Z" },
    genres: { names: [], normalized: [], status: "no_data", no_data: true },
  },
];
