import assert from "node:assert/strict";
import { describe, it } from "node:test";
import { parseStructuredResponseDetailed, parseStructuredResponseWithProviderRepair } from "../ai/validation";
import { recipeCopilotJsonSchema, recipeCopilotResponseSchema } from "./recipeCopilot/contracts";

const validDraft = {
  schemaVersion: "1.0", action: "create",
  proposedPatch: { metadata: { name: "Familiar all-genre favorites" }, generation: { rules: [{ field: "popularity", operator: "gte", value: "70" }, { field: "genre", operator: "not_contains", value: "country" }], negativeFilters: { excludeHoliday: true, excludeLive: true, excludeIntroOutro: true } } },
  intent: { summary: "Familiar popular music across available genres, excluding country, holidays, live tracks, intros, and outros.", primaryGoals: ["Favor familiar highly popular tracks", "Select broadly across available genre tags"], secondaryGoals: [], conflicts: [] },
  analysis: { confidence: .9, assumptions: [], warnings: [], unsupportedRequests: [], expectedBehavioralChanges: ["Popular tracks are favored"], compatibilityNotes: [] },
  recommendations: { parentRecipes: [], inheritance: [], missingRules: [], saferSettings: [] }, changeRationales: [], explanation: null, diagnoses: [], behaviorComparison: null, nameSuggestions: [], onboarding: [],
};
const format = { type: "json" as const, name: "mixarr_recipe_copilot_v1", schema: recipeCopilotResponseSchema, jsonSchema: recipeCopilotJsonSchema, knownRootWrappers: ["recipe", "draft", "result", "recipeDraft"] };
const parse = (content: string) => parseStructuredResponseDetailed(content, format, 128_000);

describe("v2.4.17 Recipe Copilot structured output", () => {
  it("keeps the regression instruction reviewable and within the production schema", () => { const parsed = recipeCopilotResponseSchema.parse(validDraft); assert.equal(parsed.proposedPatch?.generation.negativeFilters?.excludeHoliday, true); assert.equal(parsed.proposedPatch?.generation.negativeFilters?.excludeLive, true); assert.equal(parsed.proposedPatch?.generation.negativeFilters?.excludeIntroOutro, true); assert.equal(parsed.proposedPatch?.generation.rules?.some((rule) => rule.field === "genre" && rule.operator === "not_contains" && rule.value === "country"), true); assert.equal("active" in parsed, false); });
  it("accepts direct JSON and schema-defined defaults", () => { const result = parse(JSON.stringify(validDraft)); assert.equal(result.data.proposedPatch?.scoring != null, true); assert.equal(result.repaired, false); });
  it("normalizes one JSON fence", () => { const result = parse(`\`\`\`json\n${JSON.stringify(validDraft)}\n\`\`\``); assert.equal(result.normalization.codeFenceRemoved, true); });
  it("decodes one JSON-string wrapper", () => { const result = parse(JSON.stringify(JSON.stringify(validDraft))); assert.equal(result.normalization.jsonStringDecoded, true); });
  it("unwraps only a recognized single root", () => { const result = parse(JSON.stringify({ recipeDraft: validDraft })); assert.equal(result.normalization.wrapperUnwrapped, true); });
  it("extracts exactly one complete object from harmless prose", () => { const result = parse(`Here is the draft.\n${JSON.stringify(validDraft)}\nEnd.`); assert.equal(result.normalization.objectExtracted, true); });
  it("reports missing fields and invalid enums with paths", () => { const invalid: any = structuredClone(validDraft); delete invalid.intent; invalid.proposedPatch.generation.rules[0].operator = "at_least"; assert.throws(() => parse(JSON.stringify(invalid)), (error: any) => { const paths = error.details.issues.map((issue: any) => issue.path); return paths.includes("intent") && paths.includes("proposedPatch.generation.rules.0.operator") && error.details.json_parsed === true; }); });
  it("does not strip unknown fields from the strict canonical schema", () => { assert.throws(() => parse(JSON.stringify({ ...validDraft, activationState: "ACTIVE" })), (error: any) => error.details.issues.some((issue: any) => issue.path === "" && issue.code === "unrecognized_keys")); });
  it("runs one controlled provider repair after local normalization", async () => { const invalid: any = structuredClone(validDraft); invalid.proposedPatch.generation.rules[0].operator = "at_least"; let calls = 0; const result = await parseStructuredResponseWithProviderRepair({ content: JSON.stringify(invalid), format, maxBytes: 128_000, providerRepairAttempts: 1, repair: async () => { calls += 1; return JSON.stringify(validDraft); } }); assert.equal(calls, 1); assert.equal(result.providerRepairUsed, true); assert.equal(result.data.action, "create"); });
  it("never repairs more than once and classifies a failed repair", async () => { let calls = 0; await assert.rejects(() => parseStructuredResponseWithProviderRepair({ content: "not json", format, maxBytes: 128_000, providerRepairAttempts: 1, repair: async () => { calls += 1; return "still not json"; } }), (error: any) => error.details.repair_failed === true && error.details.repair_attempted === true); assert.equal(calls, 1); });
  it("handles the reported 12KB HTTP-success shape as schema validation, never truncation", async () => { const invalid: any = structuredClone(validDraft); invalid.proposedPatch.generation.rules[0] = { field: "popularity", operator: "at_least", value: 70 }; invalid.proposedPatch.scoring = { inventedMode: true }; const raw = JSON.stringify(invalid, null, 12) + " ".repeat(12_500); assert.ok(raw.length > 12_000); assert.throws(() => parse(raw), (error: any) => error.details.failure_stage === "SCHEMA_VALIDATION" && error.details.json_parsed === true && error.details.issues.some((issue: any) => issue.path === "proposedPatch.generation.rules.0.operator") && error.category !== "AI_FEATURE_TRUNCATED_STRUCTURED_OUTPUT"); });
});
