export type RoadmapStatus = "completed" | "current" | "upcoming";

export type RoadmapRelease = {
  version: string;
  title: string;
  cycle: string;
  status: RoadmapStatus;
  description: string;
  featureLabels: string[];
  releaseOrder: number;
  completionDate?: string;
  route?: string;
};

export type RoadmapCycle = {
  id: string;
  title: string;
  status: RoadmapStatus;
  description: string;
  releases: RoadmapRelease[];
  futureThemes?: string[];
};

const v20Titles = [
  ["2.0.0", "Smart Mix Engine v2 Foundation"],
  ["2.0.1", "Playlist Scoring"],
  ["2.0.2", "Recommendation Tuning"],
  ["2.0.3", "Mood Blending"],
  ["2.0.4", "BPM Ramp & Transition Tools"],
  ["2.0.5", "Deep Cut & Discovery Controls"],
  ["2.0.6", "Advanced Playlist Regeneration"],
  ["2.0.7", "Playlist Version History & Restore"],
  ["2.0.8", "Manual BPM & Metadata Corrections"],
  ["2.0.9", "Recently Added Automation"],
  ["2.0.10", "Beta Feature Polish & Advanced Flags"],
] as const;

export const roadmapReleases: RoadmapRelease[] = [
  ...v20Titles.map(([version, title], index) => ({
    version,
    title,
    cycle: "2.0.x",
    status: "completed" as const,
    description: "Delivered as part of the completed Smart Mix Engine v2 cycle.",
    featureLabels: [],
    releaseOrder: index,
    route: "/release-notes",
  })),
  {
    version: "2.1.0",
    title: "Personalization Foundation",
    cycle: "2.1.x",
    status: "completed",
    description: "Creates the data models and services required for adaptive recommendations while keeping initial scoring changes conservative and fully optional. Also fixes repeated missing-track restoration during Plex sync: restored availability now persists, post-commit totals are authoritative, and reconciliation verifies every restore.",
    featureLabels: ["User recommendation profiles", "Playlist preference profiles", "Interaction history", "Personal scoring adjustments", "Global and user scoring separation", "Privacy controls", "Reset personalization data", "Reliable Plex availability reconciliation"],
    releaseOrder: 100,
    route: "/release-notes",
  },
  {
    version: "2.1.1",
    title: "Duplicate Preservation & Plex Conflict Inspector",
    cycle: "2.1.x",
    status: "completed",
    description: "Preserves every Plex rating-key instance, groups confirmed duplicate recordings without merging physical rows, shares trusted enrichment with provenance, and turns Library Health counts into paginated diagnostic workflows with an idempotent repair preview.",
    featureLabels: ["Physical Plex instance identity", "Non-destructive duplicate groups", "Enrichment inheritance and provenance", "Plex Conflict Inspector", "Calculated repair preview", "Clickable Library Health diagnostics", "Duplicate-aware playlists", "Chunked large-library operations"],
    releaseOrder: 101,
    route: "/release-notes",
  },
  {
    version: "2.1.1-hotfix",
    title: "Nightly Audio Features & Logging Cleanup",
    cycle: "2.1.x",
    status: "completed",
    description: "Reliability hotfix that runs pending Audio Features as the final awaited nightly stage, unifies provider resolution with manual execution, preserves local Essentia fallback, and replaces repetitive production logs with useful summaries.",
    featureLabels: ["Nightly Audio Features reliability", "Shared provider resolution", "Local Essentia fallback", "Accurate zero-work states", "Stage summaries", "Logging cleanup"],
    releaseOrder: 102,
    route: "/release-notes",
  },
  {
    version: "2.1.2",
    title: "Likes, Dislikes & Track Feedback",
    cycle: "2.1.x",
    status: "completed",
    description: "Turns playlist editing into user-specific recommendation feedback through track and artist preferences, playlist-fit signals, transition reports, bulk tools, and explainable Smart Mix v2 adjustments.",
    featureLabels: ["Like and dislike tracks", "Never-recommend exclusions", "Artist preference controls", "Playlist-fit feedback", "Poor-transition reporting", "Preview feedback controls", "Bulk feedback tools", "Optional feedback reasons", "Feedback history and management", "User-specific scoring adjustments"],
    releaseOrder: 103,
    completionDate: "2026-07-15",
    route: "/release-notes",
  },
  {
    version: "2.1.3",
    title: "Playlist Identity & Memory",
    cycle: "2.1.x",
    status: "completed",
    description: "Gives every managed playlist a stable, explainable identity with learned mood, energy, BPM, artist, genre, discovery, importance, rejection, and historical membership memory that survives regeneration and Plex changes.",
    featureLabels: ["Stable playlist identity", "Learned and manual effective values", "Per-field locks", "Playlist rejection memory", "Important and anchor tracks", "Historical membership events", "Identity-aware regeneration", "Personality summaries", "Confidence explanations", "Clone, retrain, and reset workflows", "Identity snapshots", "Lazy legacy initialization"],
    releaseOrder: 104,
    route: "/release-notes",
  },
  {
    version: "2.1.4",
    title: "Adaptive Smart Mix Scoring",
    cycle: "2.1.x",
    status: "completed",
    description: "Builds on the v2.1.0 personalization profile, v2.1.2 feedback, and v2.1.3 playlist identity to adjust Smart Mix rankings through a separate, confidence-limited, reversible, explainable scoring layer.",
    featureLabels: ["Unchanged base Smart Mix score", "Personalized score comparison", "Eight adaptive scoring components", "Confidence multipliers", "Maximum influence slider", "Presets and advanced controls", "Playlist-specific overrides", "Source and scope labels", "Track-level explanations", "Aggregated history statistics", "Recalculation jobs", "Scoped reset and retraining", "Scoring version snapshots", "Large-library batching"],
    releaseOrder: 105,
    completionDate: "2026-07-16",
    route: "/personalization",
  },
  {
    version: "2.1.5",
    title: "Listening History & Playback Awareness",
    cycle: "2.1.x",
    status: "completed",
    description: "Uses per-user Plex listening history as a separate, confidence-weighted, capped Smart Mix layer for recent-play avoidance, completion and replay affinity, cautious skip signals, forgotten favorites, and playback-aware discovery.",
    featureLabels: ["Incremental Plex history sync", "Per-user Plex mapping", "Normalized playback events", "Aggregated track profiles", "Recently played controls", "Forgotten favorites", "Completion and replay affinity", "Confidence-limited skip signals", "Playback-aware discovery", "Visible score explanations", "Job History integration", "Local privacy controls", "Large-history batching"],
    releaseOrder: 106,
    completionDate: "2026-07-16",
    route: "/settings/personalization/playback",
  },
  {
    version: "2.1.6",
    title: "Contextual Mixes",
    cycle: "2.1.x",
    status: "completed",
    description: "Translates time, day, season, and activity contexts into visible, editable Smart Mix v2 settings with bounded contextual scoring, reusable custom profiles, manual overrides, and durable generation snapshots.",
    featureLabels: ["Context cards", "Seven built-in contexts", "Custom reusable contexts", "Time, day, season, and activity availability", "Energy and discovery targets", "Context influence cap", "Visible setting changes", "Manual overrides and restoration", "Context score explanations", "Playlist identity and personalization integration", "Context generation snapshots", "Local-time suggestions"],
    releaseOrder: 107,
    completionDate: "2026-07-16",
    route: "/builder",
  },
  {
    version: "2.1.7",
    title: "Playlist Relationships & Coordination",
    cycle: "2.1.x",
    status: "completed",
    description: "Coordinates related Smart Mix playlists through canonical overlap detection, configurable hard or soft limits, shared core tracks, artist balancing, unused-track preference, progression chains, previewed moves, and an explainable duplicate dashboard.",
    featureLabels: ["Playlist relationships", "Canonical overlap detection", "Hard and soft overlap limits", "Sister playlists", "Shared core tracks", "Progression chains", "Selected-playlist exclusions", "Unused-track preference", "Cross-playlist artist balancing", "Coordination dashboard", "Previewed track moves", "Rebalance previews", "Bounded explainable scoring", "Batched usage queries"],
    releaseOrder: 108,
    completionDate: "2026-07-16",
    route: "/playlist-coordination",
  },
  {
    version: "2.1.8",
    title: "Smart Mix Explanations & Insights",
    cycle: "2.1.x",
    status: "completed",
    description: "Captures immutable Smart Mix v2 decision traces so selected, rejected, replaced, and competing candidates can be understood through the exact scoring components, filters, fallbacks, metadata, personalization, identity, transitions, and confidence used at generation time.",
    featureLabels: ["Why selected and rejected", "Stable factor codes", "Hard and soft rejection stages", "Score and confidence separation", "Personalization caps", "Playlist identity influence", "Transition explanations", "Metadata and fallback disclosure", "Candidate comparison", "Generation insights", "Suggested fixes", "Historical snapshots", "Bounded trace retention", "Sanitized debug export", "Responsive accessible drawer"],
    releaseOrder: 109,
    completionDate: "2026-07-16",
    route: "/smart-builder",
  },
  {
    version: "2.1.9",
    title: "Adaptive Automation Policies",
    cycle: "2.1.x",
    status: "completed",
    description: "Makes playlist automation explicitly permissioned, bounded, protected, explainable, approval-aware, pausable, and reversible through one server-side policy evaluator.",
    featureLabels: ["Four automation permission levels", "Conservative, Balanced, and Aggressive presets", "Per-update, daily, and weekly limits", "Confidence thresholds", "Playlist and track protection", "Quiet hours and time zones", "Approval queue", "Automation activity", "Emergency pause", "Recoverable versions and rollback", "Safe legacy migration"],
    releaseOrder: 110,
    completionDate: "2026-07-16",
    route: "/automation",
  },
  {
    version: "2.1.10",
    title: "Personalization Dashboard & Release Polish",
    cycle: "2.1.x",
    status: "completed",
    description: "Brings adaptive recommendations, feedback, playlist identity, playback awareness, score influence, privacy controls, migration readiness, and data portability into one understandable user-controlled dashboard.",
    featureLabels: ["Personalization dashboard", "Real aggregate metrics", "Recently learned preferences", "Influential feedback", "Playlist identity browser", "Behavioral quality trends", "Score influence distribution", "Playback health", "JSON export and import", "Selective reset", "First-time onboarding", "Stable-readiness checks", "Cleanup previews", "Responsive accessible UI"],
    releaseOrder: 111,
    completionDate: "2026-07-17",
    route: "/personalization",
  },
  {
    version: "2.1.11",
    title: "Dashboard UI Cleanup",
    cycle: "2.1.x",
    status: "completed",
    description: "Reorganizes the main dashboard around library readiness, active work, and common playlist actions while removing duplicate widget rendering and moving product previews into a compact secondary area.",
    featureLabels: ["Canonical widget registry", "Recently Added deduplication", "Library readiness summary", "Quick Actions", "Activity and automation grouping", "Compact playlist management", "Collapsed product preview", "Compact Plex servers", "Responsive layout", "Isolated widget states", "Accessibility", "Duplicate request removal"],
    releaseOrder: 112,
    completionDate: "2026-07-17",
    route: "/release-notes",
  },
  {
    version: "2.2.0",
    title: "Playlist Orchestration Foundation",
    cycle: "2.2.x",
    status: "completed",
    description: "Introduces the opt-in managed playlist registry, validated dependencies, shared persistent queue, priority aging, database-backed conflict and concurrency leases, dry runs, recovery, auditing, APIs, health, settings, and responsive orchestration workspace without forcing legacy actions through the new layer.",
    featureLabels: ["Managed playlist registry", "Playlist dependencies", "Cycle detection", "Shared persistent queue", "Priority aging", "Persistent conflict locks", "Concurrency limits", "Idempotency", "Dry runs", "Crash recovery", "Audit history", "Global and playlist controls", "Orchestration workspace", "Legacy compatibility"],
    releaseOrder: 200,
    completionDate: "2026-07-17",
    route: "/orchestration",
  },
  {
    version: "2.2.1",
    title: "Playlist Groups & Collections",
    cycle: "2.2.x",
    status: "completed",
    description: "Organize playlists into reusable collections, share settings and exclusion rules, monitor collection health, and regenerate related playlists together.",
    featureLabels: ["Playlist groups", "Multiple memberships", "Primary settings group", "Runtime inheritance", "Shared discovery", "Artist limits", "Exclusion rules", "Group regeneration", "Explainable health", "Pause and clone", "Accessible ordering", "Mobile management"],
    releaseOrder: 201,
    completionDate: "2026-07-17",
    route: "/playlist-groups",
  },
  {
    version: "2.2.2",
    title: "Cross-Playlist Deduplication & Variety",
    cycle: "2.2.x",
    status: "completed",
    description: "Reduce excessive track, artist, and album reuse across Smart Mix playlists with configurable limits, uniqueness targets, overlap analysis, heatmaps, explainable repair suggestions, and safe preview-based replacement tools.",
    featureLabels: ["Track, artist, and album overlap", "Smaller-playlist denominator", "Global, playlist, and pair policies", "Unique-track targets", "Core and allowed shared tracks", "Playlist exclusivity", "Recent cross-playlist penalties", "Accessible overlap heatmap", "Playlist comparison", "Explainable repair previews", "Stale-preview protection", "Cancellable background analysis", "Repair version history"],
    releaseOrder: 202,
    completionDate: "2026-07-17",
    route: "/playlist-coordination",
  },
  {
    version: "2.2.3",
    title: "Playlist Roles & Progression Chains",
    cycle: "2.2.x",
    status: "completed",
    description: "Builds coordinated multi-playlist journeys with optional roles, explicit ordered memberships, explainable energy/BPM/mood handoffs, previewed boundary optimization, shared transitions, master journeys, background analysis, and restorable versions without changing ordinary playlist generation.",
    featureLabels: ["Playlist role presets", "Custom roles", "Advisory or applied guidance", "Ordered progression chains", "Energy handoffs", "BPM half/double-time handoffs", "Mood progression", "Explainable chain scoring", "Shared transition tracks", "Optimization previews", "Master journey playlists", "Plex compatibility", "Background progress", "Chain version restore", "Mobile chain editor"],
    releaseOrder: 203,
    completionDate: "2026-07-18",
    route: "/playlist-chains",
  },
  {
    version: "2.2.4",
    title: "Smart Refresh Scheduling",
    cycle: "2.2.x",
    status: "completed",
    description: "Evaluates playlist quality, compatible new tracks, playback repetition, identity drift, relevant metadata changes, and major library syncs before selecting the least disruptive safe refresh action.",
    featureLabels: ["Per-playlist refresh modes", "Low, Balanced, High, and Custom sensitivity", "Bounded improvement estimates", "Weak-track refresh", "Compatible-track discovery", "Playback repetition", "Identity drift", "Metadata impact", "Major-sync targeting", "Cooldowns and weekly limits", "Time-zone quiet hours", "Manual improvement checks", "Exact previews", "Stale-safe execution", "Version snapshots", "Job History audit", "Dashboard summary", "Bounded scheduler batches"],
    releaseOrder: 204,
    completionDate: "2026-07-18",
    route: "/generated-playlists",
  },
  {
    version: "2.2.5",
    title: "Library Coverage & Rotation Intelligence",
    cycle: "2.2.x",
    status: "completed",
    description: "Understand which parts of the Plex music library are being used, identify strong neglected tracks, reduce excessive repetition, and build high-quality mixes from overlooked music.",
    featureLabels: ["Historical library coverage", "Rotation fairness", "Never-selected tracks", "Neglected opportunities", "Overuse intelligence", "Artist and album coverage", "Genre and mood coverage", "Decade coverage", "Recently added coverage", "Segment drill-down", "Guided neglected mixes", "Bounded rotation scoring", "Explainable decisions", "Background jobs", "Snapshots and trends", "CSV and JSON export"],
    releaseOrder: 205,
    completionDate: "2026-07-18",
    route: "/library-coverage",
  },
  {
    version: "2.2.6",
    title: "Smart Experiments & Playlist A/B Testing",
    cycle: "2.2.x",
    status: "completed",
    description: "Compare Smart Mix strategies using controlled playlist variants, track feedback and playback outcomes, select a winner, merge successful settings, or safely restore the original playlist.",
    featureLabels: ["Protected source snapshots", "Controlled Version A and B", "Configuration differences", "Preview-only generation", "Separate Plex publishing", "Independent feedback", "Playback-aware metrics", "Acceptance and rejection rates", "Explainable suggested winners", "Minimum evidence", "Manual winner selection", "Merged configurations", "Original restore", "Permanent timeline", "Job History", "Responsive dashboard"],
    releaseOrder: 206,
    completionDate: "2026-07-18",
    route: "/experiments",
  },
  {
    version: "2.2.7",
    title: "Smart Action Center",
    cycle: "2.2.x",
    status: "completed",
    description: "Centralizes explainable playlist, library, and metadata recommendations so users can preview, approve, snooze, schedule, apply, audit, and restore changes safely.",
    featureLabels: ["Central recommendation queue", "Typed action payloads", "Confidence and risk", "Expected impact", "Explanations", "Before and after preview", "Approve and reject", "Conditional snooze", "Bulk safeguards", "Conflict detection", "Immediate apply", "Maintenance windows", "Playback awareness", "Automation policies off by default", "Version snapshots", "Undo and restore", "Audit history", "CSV export", "Dashboard summary", "Responsive UI"],
    releaseOrder: 207,
    completionDate: "2026-07-18",
    route: "/smart-actions",
  },
  {
    version: "2.2.8",
    title: "Playlist Health Monitoring & Alerts",
    cycle: "2.2.x",
    status: "completed",
    description: "Continuously scores playlist quality and surfaces identity, repetition, concentration, Plex, media, metadata, transition, staleness, and automation problems before playback.",
    featureLabels: ["Playlist health score", "Identity drift", "Repetition warnings", "Artist concentration", "Album concentration", "Broken Plex playlists", "Missing tracks", "Unavailable media", "Metadata confidence decline", "BPM jumps", "Mood conflicts", "Stale playlists", "Failed automation", "Dashboard health cards", "Discord", "Webhooks", "In-app alerts", "Configurable severity", "Acknowledgment", "Resolution history"],
    releaseOrder: 208,
    completionDate: "2026-07-18",
    route: "/playlist-health",
  },
  {
    version: "2.2.9",
    title: "Orchestration Dashboard & Release Polish",
    cycle: "2.2.x",
    status: "completed",
    description: "Completes the v2.2.x series with one Playlist Ecosystem control center for managed playlist health, groups, relationships, overlap, coverage, automation, Smart Actions, experiments, trends, onboarding, configuration portability, backup validation, queue maintenance, audit search, and upgrade readiness.",
    featureLabels: ["Playlist Ecosystem dashboard", "Group health overview", "Relationship graph and accessible table", "Overlap heatmap", "Coverage drill-down", "Upcoming jobs", "Explainable activity", "Pending Smart Actions", "Experiment results", "Historical snapshots", "Resumable onboarding", "Safe queue cleanup", "Audit filtering", "Secret-free JSON export", "Previewed transactional import", "Backup validation", "Migration readiness", "Large-library bounds", "Mobile operations console"],
    releaseOrder: 209,
    completionDate: "2026-07-18",
    route: "/orchestration",
  },
  {
    version: "2.3.0",
    title: "Mix Recipe Foundation",
    cycle: "2.3.x",
    status: "completed",
    description: "Separates reusable Smart Mix strategy from generated playlists through a first-class, versioned, validated recipe schema, independent identity defaults, generation snapshots, safe conversion, and a dedicated Recipe Library and editor.",
    featureLabels: ["First-class Mix Recipes", "Portable schema v1", "Recipe revisions", "Metadata and artwork", "Scoring configuration", "Mood and energy targets", "BPM flow", "Discovery controls", "Artist and album variety", "Identity defaults", "Refresh policy", "Explicit automation confirmation", "Recipe validation", "Schema migrations", "Create from playlist", "Create playlist from recipe", "Resolved generation snapshots", "Responsive Recipe Library"],
    releaseOrder: 300,
    completionDate: "2026-07-19",
    route: "/recipes",
  },
  {
    version: "2.3.1",
    title: "Recipe Import & Export",
    cycle: "2.3.x",
    status: "completed",
    description: "Moves Mix Recipes safely between Mixarr installations through allowlisted JSON and artwork archives, deterministic checksums, staged compatibility previews, controlled adaptations, conflict resolution, transactions, diagnostics, and transfer history.",
    featureLabels: ["Single recipe JSON", "Recipe bundles", "Optional artwork archives", "Portable-field allowlist", "SHA-256 integrity", "Sensitive-data scanning", "Staged import preview", "Compatibility analysis", "Safe adaptations", "Rename conflicts", "Replace with revision", "Skip and use existing", "Atomic and independent import", "Import history", "Export history", "Sanitized diagnostics", "Archive traversal protection", "Responsive import wizard"],
    releaseOrder: 301,
    completionDate: "2026-07-19",
    route: "/recipes",
  },
  {
    version: "2.3.2",
    title: "Adaptive Recipe Mapping",
    cycle: "2.3.x",
    status: "completed",
    description: "Adapts shared Smart Mix recipes to the receiving Plex music library with explainable vocabulary mappings, metadata-aware range suggestions, deterministic compatibility and candidate estimates, identity protection, and reusable confirmed mapping rules.",
    featureLabels: ["Library-aware recipe import", "Genre mapping", "Mood mapping", "Energy coverage", "BPM adaptation", "Corrected BPM precedence", "Artist availability", "Weighted compatibility score", "Candidate count estimates", "Coverage estimates", "Restrictiveness warnings", "Constraint relaxations", "Metadata warnings", "Original vs adapted comparison", "Identity impact", "Manual mapping controls", "Saved mapping precedence", "Mapping management", "Count-only Smart Mix queries", "Responsive mapping cards"],
    releaseOrder: 302,
    completionDate: "2026-07-19",
    route: "/recipes",
  },
  {
    version: "2.3.3",
    title: "Preset Inheritance & Overrides",
    cycle: "2.3.x",
    status: "completed",
    description: "Adds deterministic, explainable recipe inheritance with reusable preset layers, base recipes, safe overrides and resets, policy locks, impact previews, version-aware cloning, and reproducible generation snapshots while preserving every legacy recipe as explicit configuration.",
    featureLabels: ["Global recipe defaults", "Category presets", "Multi-level base recipes", "Transition presets", "Discovery presets", "Variety presets", "Automation policies", "Recipe overrides", "Playlist overrides", "Group policies", "User preferences", "Field provenance", "Individual reset", "Policy locks", "Conflict detection", "Cycle protection", "Impact preview", "Inheritance-aware cloning", "Effective snapshots", "Configuration fingerprints", "Mobile inheritance chain"],
    releaseOrder: 303,
    completionDate: "2026-07-19",
    route: "/settings/recipe-presets",
  },
  {
    version: "2.3.4",
    title: "Curated Recipe Library",
    cycle: "2.3.x",
    status: "completed",
    description: "Bundles a polished offline starter catalog with library-aware compatibility, plain-language previews, safe installation and customization, favorites, recently used and hidden state, source version history, updates, and restore-original controls.",
    featureLabels: ["28 offline starter recipes", "16 recipe categories", "Stable recipe IDs", "Version history", "Difficulty labels", "Metadata requirements", "Compatibility estimates", "Eligible-track counts", "Behavior previews", "One-click installation", "Duplicate prevention", "Customize before creating", "Favorites", "Recently used", "Hidden recipe management", "Update status", "Restore original", "Aggregate query caching", "Mobile recipe browser"],
    releaseOrder: 304,
    completionDate: "2026-07-19",
    route: "/recipes/library",
  },
  {
    version: "2.3.5",
    title: "Community Recipe Sharing",
    cycle: "2.3.x",
    status: "completed",
    description: "Adds safe decentralized sharing of data-only community recipes through portable JSON, ZIP bundles, HTTPS URLs, uploads, paste, and checksum-protected share codes with mandatory local preview and approval.",
    featureLabels: ["Community recipe bundles", "Plain JSON sharing", "MXR1 share codes", "Secure URL imports", "Upload and paste imports", "Mandatory approval", "Author attribution", "Recipe licenses", "Minimum-version checks", "Trust warnings", "Managed artwork", "Screenshot gallery", "Changelogs", "Community tags", "Local modification detection", "Conflict-safe updates", "Sanitized reporting", "Optional official GitHub index", "SSRF protection", "Archive safety", "Secret rejection", "Data-only recipes"],
    releaseOrder: 305,
    completionDate: "2026-07-19",
    route: "/recipes/community",
  },
  {
    version: "2.3.6",
    title: "Household Collaboration & Shared Playlists",
    cycle: "2.3.x",
    status: "current",
    description: "Adds opt-in multi-profile household personalization with fair normalized influence, guests, deterministic conflict resolution, family rules, voting, approvals, contribution explanations, and retained activity history.",
    featureLabels: ["Named households", "Stable member profiles", "Guest profiles", "Participant subsets", "Six balance modes", "Effective influence preview", "Influence caps", "Shared favorites", "Conflict detection", "Deterministic resolution", "Family-friendly rules", "Party mode", "Voting", "Approval-gated publishing", "Temporary exclusions", "Contribution breakdown", "Household activity", "Mobile household management"],
    releaseOrder: 306,
    completionDate: "2026-07-19",
    route: "/households",
  },
];

export const roadmapCycles: RoadmapCycle[] = [
  {
    id: "2.0.x",
    title: "v2.0.x — Smart Mix Engine v2",
    status: "completed",
    description: "The v2.0.x cycle introduced Smart Mix Engine v2, visible playlist scoring, recommendation tuning, mood blending, BPM transition tools, discovery controls, advanced regeneration, playlist version history, metadata corrections, recently added automation, and expanded beta feature controls.",
    releases: roadmapReleases.filter((release) => release.cycle === "2.0.x"),
  },
  {
    id: "2.1.x",
    title: "v2.1.x — Adaptive Personalization",
    status: "completed",
    description: "Mixarr can now learn from direct feedback, playlist history, recommendation decisions, playlist identity, and playback behavior while keeping the resulting adjustments visible and under user control.",
    releases: roadmapReleases.filter((release) => release.cycle === "2.1.x"),
  },
  {
    id: "2.2.x",
    title: "v2.2.x — Playlist Orchestration",
    status: "completed",
    description: "The completed v2.2.x system coordinates playlist groups, cross-playlist intelligence, Smart Actions, automation, experiments, health monitoring, coverage management, and safety controls through one Playlist Ecosystem dashboard.",
    releases: roadmapReleases.filter((release) => release.cycle === "2.2.x"),
    futureThemes: ["Operational refinement", "Provider-neutral optional assistance", "Deeper explainability", "No AI provider required for Smart Mix"],
  },
  {
    id: "2.3.x",
    title: "v2.3.x — Mix Recipes",
    status: "current",
    description: "The recipe foundation makes Smart Mix strategies portable, reusable, versioned, and independent from the concrete playlists they create.",
    releases: roadmapReleases.filter((release) => release.cycle === "2.3.x"),
    futureThemes: ["Built-in templates", "Recipe sharing and community catalogs", "Recipe comparison", "Recipe history and rollback", "Recipe inheritance", "Recipe scheduling", "Recipe recommendations", "Optional AI-assisted recipe creation"],
  },
  {
    id: "future-2x",
    title: "Later 2.x and the path toward 3.0",
    status: "upcoming",
    description: "Future planning may explore optional AI-assisted workflows and broader ecosystem integrations after the deterministic orchestration foundation is proven. No release date is promised, and current Smart Mix functionality does not require an AI provider.",
    releases: [],
    futureThemes: ["Local Ollama models", "OpenRouter", "OpenAI-compatible APIs", "Anthropic-compatible APIs", "Other configurable providers", "Explicit consent, cost controls, and reviewable output"],
  },
];

export const aiExploration = {
  title: "Future Exploration — AI-Assisted Mixarr",
  timing: "Long-term exploration for later in v2.x or the path toward v3.0",
  description: "Mixarr may eventually support optional AI-assisted features through local providers such as Ollama or user-configured API providers such as OpenRouter, OpenAI, Anthropic, and compatible services. These are not part of the immediate v2.2.x roadmap, and no provider is preferred or guaranteed.",
  ideas: ["Natural-language playlist creation and refinement", "Playlist identity and scoring summaries", "Mood mapping and genre normalization", "Playlist naming and description suggestions", "Library exploration conversations", "Troubleshooting and comparison summaries", "Metadata cleanup suggestions", "Semantic playlist search", "Natural-language automation rules"],
  safeguards: ["AI remains optional", "Core generation and scoring work without AI", "Local models are supported where practical", "External providers require explicit configuration and consent", "Users see what data would be sent", "Credentials require secure storage", "Usage and cost controls are required", "Provider failures cannot break playlist generation", "AI cannot silently override deterministic scoring", "AI output remains reviewable and explainable"],
};

export function currentRoadmapRelease() {
  return roadmapReleases.find((release) => release.status === "current")
    || [...roadmapReleases].filter((release) => release.status === "completed").sort((left, right) => right.releaseOrder - left.releaseOrder)[0]
    || null;
}
