import type { Prisma } from "@prisma/client";
import prisma from "@/lib/prisma";
import type { AiResponse } from "../contracts";
import type { AiErrorCategory } from "../errors";
import { aiFailureStatus } from "./status";

export async function createAiAudit(input: { requestId: string; correlationId?: string; featureKey: string; providerConfigId?: string; providerType?: string; providerDisplayName?: string; model?: string; streaming: boolean; userId?: string; metadata?: Record<string, unknown>; promptHash?: string; requestSource?: string; locationClassification?: string; idempotencyKey?: string; contentFingerprint?: string; promptTemplateVersion?: string; requestBody?: unknown; redactionResult?: unknown; injectionResult?: unknown; externalDataCategories?: string[] }) {
  return prisma.aiRequestAudit.create({ data: { requestId: input.requestId, logicalRequestId: input.requestId, correlationId: input.correlationId, featureKey: input.featureKey, providerConfigId: input.providerConfigId, providerType: input.providerType, providerDisplayName: input.providerDisplayName, model: input.model, streamingUsed: input.streaming, userId: input.userId, safeMetadataJson: input.metadata as Prisma.InputJsonValue | undefined, promptHash: input.promptHash, requestSource: input.requestSource || "FOREGROUND", background: input.requestSource === "BACKGROUND", locationClassification: input.locationClassification, idempotencyKey: input.idempotencyKey, contentFingerprint: input.contentFingerprint, promptTemplateVersion: input.promptTemplateVersion, requestBodyJson: input.requestBody as Prisma.InputJsonValue | undefined, redactionResultJson: input.redactionResult as Prisma.InputJsonValue | undefined, injectionResultJson: input.injectionResult as Prisma.InputJsonValue | undefined, externalDataCategoriesJson: input.externalDataCategories as Prisma.InputJsonValue | undefined, policyValidationResult: "PASSED", status: "RUNNING" } });
}
export async function completeAiAudit(requestId: string, response: AiResponse, responseByteCount: number) { return prisma.aiRequestAudit.update({ where: { requestId }, data: { status: "COMPLETED", completedAt: new Date(), latencyMs: response.latencyMs, providerDurationMs: response.latencyMs, retryCount: response.retryCount, inputTokenCount: response.usage?.inputTokens, outputTokenCount: response.usage?.outputTokens, totalTokenCount: response.usage?.totalTokens, cachedTokenCount: response.usage?.cachedTokens, reasoningTokenCount: response.usage?.reasoningTokens, estimatedCost: response.estimatedCost, actualCost: response.actualCost, usageSource: response.usage?.providerReported ? "PROVIDER_REPORTED" : "ESTIMATED", providerRequestId: response.usage?.providerRequestId?.slice(0, 300), responseByteCount, httpStatus: response.transport?.httpStatus, testStage: "COMPLETE", endpointMode: response.streaming ? "STREAMING" : "NON_STREAMING", budgetControlResult: "RECONCILED", limitControlResult: "ALLOWED", structuredOutputResult: response.data === undefined ? "NOT_REQUIRED" : "PASSED", schemaValidationResult: response.data === undefined ? "NOT_REQUIRED" : "PASSED", safetyAnalysisResult: "PASSED", quarantineStatus: "NONE" } }); }
export async function failAiAudit(requestId: string, input: { category: AiErrorCategory; retryCount: number; latencyMs: number; cancelled?: boolean; timedOut?: boolean; details?: Record<string, unknown> }) {
  const status = aiFailureStatus(input.category, input);
  const providerReported = input.details?.usage_provider_reported === true;
  return prisma.aiRequestAudit.update({ where: { requestId }, data: { status, completedAt: new Date(), latencyMs: input.latencyMs, providerDurationMs: input.latencyMs, retryCount: input.retryCount, cancellationStatus: input.cancelled ? "USER_OR_SERVER_CANCELLED" : null, errorCategory: input.category, sanitizedErrorCode: input.category, inputTokenCount: typeof input.details?.usage_input_tokens === "number" ? input.details.usage_input_tokens : undefined, outputTokenCount: typeof input.details?.usage_output_tokens === "number" ? input.details.usage_output_tokens : undefined, totalTokenCount: typeof input.details?.usage_total_tokens === "number" ? input.details.usage_total_tokens : undefined, estimatedCost: typeof input.details?.estimated_cost === "number" ? input.details.estimated_cost : undefined, actualCost: typeof input.details?.actual_cost === "number" ? input.details.actual_cost : undefined, usageSource: providerReported ? "PROVIDER_REPORTED" : "UNAVAILABLE", providerRequestId: typeof input.details?.provider_request_id === "string" ? input.details.provider_request_id.slice(0, 300) : undefined, costState: providerReported ? "USAGE_RECORDED_REQUEST_FAILED" : input.details?.usage_available === false ? "USAGE_UNAVAILABLE_POSSIBLE_PROVIDER_BILLING" : "USAGE_UNAVAILABLE", httpStatus: typeof input.details?.http_status === "number" ? input.details.http_status : undefined, responseByteCount: typeof input.details?.response_body_length === "number" ? input.details.response_body_length : undefined, testStage: typeof input.details?.stage === "string" ? input.details.stage : typeof input.details?.failure_stage === "string" ? input.details.failure_stage : undefined, structuredOutputResult: input.category === "AI_FEATURE_INVALID_STRUCTURED_OUTPUT" ? "FAILED" : status === "INVALID_RESPONSE" ? "EXTRACTION_FAILED" : undefined, schemaValidationResult: ["AI_FEATURE_INVALID_STRUCTURED_OUTPUT", "AI_RECIPE_SCHEMA_INVALID"].includes(input.category) ? "FAILED" : undefined } });
}
export async function setAiAuditStatus(requestId: string, status: "STREAMING" | "RETRIED") { return prisma.aiRequestAudit.update({ where: { requestId }, data: { status } }); }

export async function cleanupAiAuditRecords(retentionDays: number, batchSize = 500) {
  const cutoff = new Date(Date.now() - Math.max(1, retentionDays) * 86_400_000); let deleted = 0;
  while (true) {
    const batch = await prisma.aiRequestAudit.findMany({ where: { createdAt: { lt: cutoff }, status: { notIn: ["QUEUED", "RUNNING", "STREAMING", "RETRIED"] } }, select: { id: true }, orderBy: { createdAt: "asc" }, take: Math.min(1000, Math.max(1, batchSize)) });
    if (!batch.length) break;
    deleted += (await prisma.aiRequestAudit.deleteMany({ where: { id: { in: batch.map((row) => row.id) } } })).count;
    if (batch.length < batchSize) break;
  }
  console.info("[AI Audit] Retention cleanup completed", { deleted, retentionDays });
  return { deleted, retentionDays, cutoff: cutoff.toISOString() };
}
