export function aiFailureStatus(category: string, options: { cancelled?: boolean; timedOut?: boolean } = {}) {
  if (options.cancelled || category === "REQUEST_CANCELLED") return "CANCELLED" as const;
  if (options.timedOut || ["AI_PROVIDER_TIMEOUT", "REQUEST_TIMEOUT", "PROVIDER_TIMEOUT"].includes(category)) return "TIMED_OUT" as const;
  if (["AI_PROVIDER_MALFORMED_JSON", "AI_PROVIDER_UNSUPPORTED_RESPONSE_SHAPE", "AI_PROVIDER_EMPTY_RESPONSE", "AI_PROVIDER_REFUSAL", "AI_PROVIDER_TOOL_CALL_ONLY", "AI_PROVIDER_TRUNCATED_RESPONSE", "AI_PROVIDER_TRUNCATED_BEFORE_FINAL", "AI_PROVIDER_TRUNCATED_FINAL_RESPONSE", "AI_PROVIDER_INVALID_STRUCTURED_RESPONSE", "AI_PROVIDER_INVALID_RESPONSE", "AI_FEATURE_INVALID_STRUCTURED_OUTPUT", "AI_RECIPE_SCHEMA_INVALID", "STRUCTURED_RESPONSE_INVALID", "INVALID_RESPONSE"].includes(category)) return "INVALID_RESPONSE" as const;
  return "FAILED" as const;
}
