"use client";

import { useCallback, useEffect, useMemo, useState } from "react";
import { AlertTriangle, Bot, Check, ChevronDown, Download, Eye, FileWarning, HeartPulse, Loader2, Play, Plus, RefreshCw, ShieldCheck, Sparkles, Trash2, Wrench, X } from "lucide-react";
import styles from "./troubleshooting.module.css";

const categoryInfo = {
  SANITIZED_LOGS: ["Sanitized logs", "Moderate", "Relevant bounded errors and warnings. Credentials and unrelated events are excluded."],
  RECIPE_CONFIGURATION: ["Recipe configuration", "Moderate", "Related recipe filters and versions. Other recipes are excluded."],
  PROVIDER_STATUS: ["Provider status", "Low", "Health, latency, and failure category. Credentials are excluded."],
  PLEX_STATUS: ["Plex connection status", "Low", "Availability and access summaries. Tokens and addresses are excluded."],
  LIBRARY_STATISTICS: ["Library statistics", "Low", "Aggregate track and metadata counts. Track names and paths are excluded."],
  TRACK_METADATA: ["Track-level metadata", "High", "A bounded resource-specific sample. Disabled by default."],
  INTEGRATION_CONFIGURATION: ["Integration configuration", "High", "Sanitized enabled state and health. Secrets and payloads are excluded."],
  RECENT_JOB_HISTORY: ["Recent job history", "Low", "Bounded job outcomes and durations for this user."],
} as const;
type Category = keyof typeof categoryInfo;
const safeDefaults: Category[] = ["PROVIDER_STATUS", "PLEX_STATUS", "LIBRARY_STATISTICS", "RECENT_JOB_HISTORY"];

async function api(path: string, init?: RequestInit) {
  const response = await fetch(path, { ...init, headers: { ...(init?.body ? { "content-type": "application/json" } : {}), ...(init?.headers || {}) } });
  const data = response.headers.get("content-type")?.includes("json") ? await response.json() : null;
  if (!response.ok) throw new Error(data?.error?.message || data?.message || "The request failed.");
  return data;
}

export default function TroubleshootingPage() {
  const [sessions, setSessions] = useState<any[]>([]), [selected, setSelected] = useState<any | null>(null);
  const [showNew, setShowNew] = useState(false), [busy, setBusy] = useState(""), [notice, setNotice] = useState(""), [error, setError] = useState("");
  const [preview, setPreview] = useState<any | null>(null), [aiPreview, setAiPreview] = useState<any | null>(null), [simulations, setSimulations] = useState<Record<string, any>>({});
  const [form, setForm] = useState({ problemCategory: "PLAYLIST_CANDIDATES", problemDescription: "", relatedResourceType: "", relatedResourceId: "", deterministicOnly: true, privacyCategories: safeDefaults, timeWindowMinutes: 60 });

  const load = useCallback(async () => { const data = await api("/api/troubleshooting/sessions?pageSize=30"); setSessions(data.sessions); }, []);
  const open = useCallback(async (id: string) => { const data = await api(`/api/troubleshooting/sessions/${id}`); setSelected(data.session); setPreview(null); setAiPreview(null); }, []);
  useEffect(() => { load().catch((cause) => setError(cause.message)); const query = new URLSearchParams(window.location.search); const type = query.get("resourceType"), id = query.get("resourceId"), category = query.get("category"); if (type || id || category) { setForm((current) => ({ ...current, relatedResourceType: type || "", relatedResourceId: id || "", problemCategory: category || current.problemCategory })); setShowNew(true); } }, [load]);

  const health = useMemo(() => ({ active: sessions.filter((item) => !["COMPLETE", "PARTIALLY_COMPLETE", "FAILED", "CANCELLED"].includes(item.status)).length, warnings: sessions.filter((item) => ["PARTIALLY_COMPLETE", "FAILED"].includes(item.status)).length, complete: sessions.filter((item) => item.status === "COMPLETE").length }), [sessions]);
  async function run(label: string, operation: () => Promise<any>, refresh = true) { setBusy(label); setError(""); setNotice(""); try { const value = await operation(); if (value?.session) setSelected(value.session); if (refresh) await load(); return value; } catch (cause) { setError((cause as Error).message); throw cause; } finally { setBusy(""); } }
  async function create() { await run("create", async () => { const value = await api("/api/troubleshooting/sessions", { method: "POST", body: JSON.stringify({ ...form, relatedResourceType: form.relatedResourceType || undefined, relatedResourceId: form.relatedResourceId || undefined }) }); setShowNew(false); await open(value.session.id); setNotice("Session created. Preview the sanitized bundle before running diagnostics."); return value; }); }
  async function previewBundle() { const value = await run("preview", () => api(`/api/troubleshooting/sessions/${selected.id}/preview`, { method: "POST" }), false); setPreview(value); setNotice("Preview created locally. Nothing was sent to an AI provider."); }
  async function diagnose() { await run("diagnose", () => api(`/api/troubleshooting/sessions/${selected.id}/diagnose`, { method: "POST" })); setNotice("Deterministic diagnostics complete. No settings have been changed."); }
  async function previewAi() { const value = await run("ai-preview", () => api(`/api/troubleshooting/sessions/${selected.id}/ai-preview`, { method: "POST" }), false); setAiPreview(value); }
  async function explain() { if (!aiPreview) return; await run("explain", () => api(`/api/troubleshooting/sessions/${selected.id}/explain`, { method: "POST" })); setNotice("AI explanation validated. No settings have been changed."); }
  async function suggestionAction(id: string, action: string, body: Record<string, unknown> = {}) { const value = await run(`${action}-${id}`, () => api(`/api/troubleshooting/suggestions/${id}/${action}`, { method: "POST", body: JSON.stringify(body) })); if (value.simulation) setSimulations((current) => ({ ...current, [id]: value.simulation })); else await open(selected.id); setNotice(action === "apply" ? "The approved recipe diff was validated and saved as a new revision. No playlist was regenerated." : "Suggestion review recorded."); }
  async function removeSession() { if (!confirm("Permanently delete this sanitized troubleshooting session and its findings?")) return; await run("delete", () => api(`/api/troubleshooting/sessions/${selected.id}`, { method: "DELETE" })); setSelected(null); setNotice("Troubleshooting session deleted."); }

  return <main className={styles.page}>
    <header className={styles.hero}><div><span className={styles.eyebrow}><Sparkles size={14} /> Mixarr v2.4.8</span><h1>AI-Assisted Troubleshooting</h1><p>Mixarr measures first, explains second, and never changes a setting without your explicit approval.</p></div><button className={styles.primary} onClick={() => setShowNew(true)}><Plus size={17} /> New session</button></header>
    <div className={styles.safety}><ShieldCheck size={20} /><div><strong>Deterministic diagnostics are the source of truth.</strong><span>AI explanations are optional and advisory. No settings have been changed.</span></div></div>
    {(error || notice) && <div className={error ? styles.error : styles.notice} role="status">{error ? <AlertTriangle size={17} /> : <Check size={17} />}{error || notice}<button aria-label="Dismiss message" onClick={() => { setError(""); setNotice(""); }}><X size={15} /></button></div>}
    <section className={styles.healthGrid} aria-label="Troubleshooting health summary"><Metric icon={<HeartPulse />} label="Current health" value={health.warnings ? "Needs attention" : "No active warning"} tone={health.warnings ? "warning" : "ok"} /><Metric icon={<RefreshCw />} label="Active sessions" value={String(health.active)} /><Metric icon={<FileWarning />} label="Recent warnings" value={String(health.warnings)} tone={health.warnings ? "warning" : "default"} /><Metric icon={<Check />} label="Completed" value={String(health.complete)} tone="ok" /></section>
    {showNew && <section className={styles.panel}><div className={styles.panelHeader}><div><h2>Start a troubleshooting session</h2><p>Choose the problem and approve each diagnostic category.</p></div><button className={styles.iconButton} onClick={() => setShowNew(false)} aria-label="Close new session"><X /></button></div>
      <div className={styles.formGrid}><label>Problem area<select value={form.problemCategory} onChange={(event) => setForm({ ...form, problemCategory: event.target.value })}><option value="PLAYLIST_CANDIDATES">Playlist or candidate problem</option><option value="PROVIDER_AUTHENTICATION">Provider or authentication</option><option value="LIBRARY_METADATA">Library or metadata</option><option value="SCHEDULING_JOBS">Scheduling or jobs</option><option value="PERFORMANCE">Performance</option><option value="IMPORT_MIGRATION_INTEGRATION">Import, migration, backup, or integration</option></select></label><label>Time window<select value={form.timeWindowMinutes} onChange={(event) => setForm({ ...form, timeWindowMinutes: Number(event.target.value) })}><option value={15}>Last 15 minutes</option><option value={60}>Last hour</option><option value={360}>Last 6 hours</option><option value={1440}>Last 24 hours</option></select></label><label className={styles.wide}>What happened?<textarea value={form.problemDescription} maxLength={4000} onChange={(event) => setForm({ ...form, problemDescription: event.target.value })} placeholder="Describe what you expected and what Mixarr did instead." /></label><label>Related resource type<select value={form.relatedResourceType} onChange={(event) => setForm({ ...form, relatedResourceType: event.target.value })}><option value="">None</option><option value="RECIPE">Recipe</option><option value="GENERATED_PLAYLIST">Generated playlist</option><option value="JOB">Job</option><option value="LIBRARY">Library</option><option value="AI_PROVIDER">AI provider (admin)</option><option value="INTEGRATION">Integration (admin)</option></select></label><label>Related resource ID<input value={form.relatedResourceId} disabled={!form.relatedResourceType} onChange={(event) => setForm({ ...form, relatedResourceId: event.target.value })} placeholder="Prepopulated from contextual links" /></label></div>
      <fieldset className={styles.mode}><legend>Analysis mode</legend><label><input type="radio" checked={form.deterministicOnly} onChange={() => setForm({ ...form, deterministicOnly: true })} /><span><Wrench /> <strong>Deterministic only</strong><small>Everything stays local. Recommended default.</small></span></label><label><input type="radio" checked={!form.deterministicOnly} onChange={() => setForm({ ...form, deterministicOnly: false })} /><span><Bot /> <strong>AI-assisted</strong><small>Sanitized findings may be sent only after a separate request preview.</small></span></label></fieldset>
      <fieldset className={styles.categories}><legend>Approved diagnostic categories</legend>{Object.entries(categoryInfo).map(([key, info]) => { const selected = form.privacyCategories.includes(key as Category); return <label key={key} className={selected ? styles.selectedCategory : ""}><input type="checkbox" checked={selected} onChange={() => setForm({ ...form, privacyCategories: selected ? form.privacyCategories.filter((item) => item !== key) : [...form.privacyCategories, key as Category] })} /><span><strong>{info[0]} <em data-sensitivity={info[1]}>{info[1]}</em></strong><small>{info[2]}</small></span></label>; })}</fieldset>
      <div className={styles.actions}><button className={styles.primary} disabled={busy === "create" || !form.problemCategory || (!!form.relatedResourceType !== !!form.relatedResourceId)} onClick={create}>{busy === "create" ? <Loader2 className={styles.spin} /> : <Plus />} Create session</button><button onClick={() => setForm({ ...form, privacyCategories: safeDefaults, deterministicOnly: true })}>Reset to safe defaults</button></div>
    </section>}
    <div className={styles.workspace}><section className={styles.sessionList}><div className={styles.sectionTitle}><div><h2>Recent sessions</h2><p>{sessions.length} retained</p></div><button className={styles.iconButton} aria-label="Refresh sessions" onClick={() => load()}><RefreshCw size={16} /></button></div>{sessions.length === 0 ? <div className={styles.empty}><Wrench /><p>No troubleshooting sessions yet.</p></div> : sessions.map((item) => <button key={item.id} className={`${styles.sessionRow} ${selected?.id === item.id ? styles.active : ""}`} onClick={() => open(item.id)}><span className={styles.status} data-status={item.status}>{item.status.replace(/_/g, " ")}</span><strong>{item.problemCategory.replace(/_/g, " ").toLowerCase()}</strong><small>{item.problemDescription || "No description provided"}</small><time>{new Date(item.createdAt).toLocaleString()}</time></button>)}</section>
      <section className={styles.detail}>{!selected ? <div className={styles.emptyDetail}><Wrench /><h2>Select a session</h2><p>Review its approved data, deterministic findings, explanation, and suggestions.</p></div> : <SessionDetail session={selected} preview={preview} aiPreview={aiPreview} simulations={simulations} busy={busy} onPreview={previewBundle} onDiagnose={diagnose} onPreviewAi={previewAi} onExplain={explain} onAction={suggestionAction} onDelete={removeSession} />}</section></div>
  </main>;
}

function SessionDetail({ session, preview, aiPreview, simulations, busy, onPreview, onDiagnose, onPreviewAi, onExplain, onAction, onDelete }: any) {
  const bundle = preview?.bundle || session.sanitizedBundleJson, findings = session.findings || [], suggestions = session.suggestions || [], explanation = session.aiExplanationJson;
  const funnel = findings.map((item: any) => item.observedValuesJson?.candidateFunnel).find(Boolean);
  return <div><div className={styles.detailHeader}><div><span className={styles.status} data-status={session.status}>{session.status.replace(/_/g, " ")}</span><h2>{session.problemCategory.replace(/_/g, " ")}</h2><p>{session.problemDescription || "No description provided."}</p></div><div className={styles.compactActions}>{session.sanitizedBundleJson && <a href={`/api/troubleshooting/sessions/${session.id}/export`}><Download size={15} /> Export</a>}<button className={styles.danger} onClick={onDelete}><Trash2 size={15} /> Delete</button></div></div>
    {session.progressJson && <div className={styles.progress}><div><span>{String(session.progressJson.stage || session.status).replace(/_/g, " ")}</span><b>{session.progressJson.percent || 0}%</b></div><div><span style={{ width: `${session.progressJson.percent || 0}%` }} /></div></div>}
    <div className={styles.approved}><strong>Approved categories</strong><div>{(session.privacySelectionsJson || []).map((item: string) => <span key={item}>{item.replace(/_/g, " ").toLowerCase()}</span>)}</div></div>
    {!["COLLECTING", "RUNNING_CHECKS", "REQUESTING_AI"].includes(session.status) && <div className={styles.actions}><button onClick={onPreview} disabled={busy}><Eye size={16} /> {preview ? "Refresh preview" : "Preview sanitized bundle"}</button>{["AWAITING_APPROVAL", "FAILED"].includes(session.status) && <button className={styles.primary} onClick={onDiagnose} disabled={busy}>{busy === "diagnose" ? <Loader2 className={styles.spin} /> : <Play />} Run deterministic diagnostics</button>}{session.status === "READY_FOR_ANALYSIS" && !session.deterministicOnly && <button onClick={onPreviewAi} disabled={busy}><Bot size={16} /> Preview AI request</button>}</div>}
    {preview && <details className={styles.bundle} open><summary><span><ShieldCheck size={17} /> Sanitized bundle preview</span><small>{preview.estimatedBytes.toLocaleString()} bytes · not persisted · not submitted</small><ChevronDown /></summary><div className={styles.redactions}>{Object.entries(preview.bundle.redaction_summary || {}).map(([key, value]) => <span key={key}><b>{String(value)}</b> {key.replace(/_/g, " ")}</span>)}</div><pre>{JSON.stringify(preview.bundle, null, 2)}</pre></details>}
    {aiPreview && <section className={styles.aiConsent}><div><Bot /><div><h3>AI request preview</h3><p>{aiPreview.provider.name} · {aiPreview.model} · {aiPreview.privacyMode}</p></div></div><dl><div><dt>Estimated input</dt><dd>{aiPreview.estimatedInputTokens} tokens</dd></div><div><dt>Estimated cost</dt><dd>{aiPreview.estimatedCost?.toFixed?.(6) || "0"} {aiPreview.currency}</dd></div><div><dt>Track-level data</dt><dd>{aiPreview.trackLevelIncluded ? "Included" : "Excluded"}</dd></div></dl><p>Only the approved minimal context shown above will be submitted. The full bundle is not sent.</p><button className={styles.primary} onClick={onExplain} disabled={busy === "explain"}>{busy === "explain" ? <Loader2 className={styles.spin} /> : <Sparkles />} Request explanation</button></section>}
    {findings.length > 0 && <section className={styles.results}><h3>Deterministic findings</h3><div className={styles.findings}>{findings.map((item: any) => <details key={item.id} className={styles.finding} open={item.severity !== "INFORMATION"}><summary><span className={styles.severity} data-severity={item.severity}>{item.severity}</span><div><strong>{item.title}</strong><small>{item.evidenceStrength.replace(/_/g, " ")} evidence · {item.checkId}</small></div><ChevronDown /></summary><p>{item.summary}</p><div className={styles.metrics}>{Object.entries(item.observedValuesJson || {}).filter(([, value]) => typeof value !== "object").map(([key, value]) => <span key={key}><small>{key.replace(/([A-Z])/g, " $1")}</small><b>{String(value)}</b></span>)}</div>{(item.limitationsJson || []).map((text: string) => <p className={styles.limitation} key={text}><AlertTriangle size={14} /> {text}</p>)}</details>)}</div></section>}
    {funnel && <section className={styles.results}><h3>Candidate funnel</h3><p className={styles.muted}>{funnel.totalScanned.toLocaleString()} scanned · {funnel.eligible.toLocaleString()} eligible · {funnel.selected.toLocaleString()} selected · {funnel.unfilled.toLocaleString()} unfilled</p><div className={styles.funnel}>{funnel.stages.map((stage: any) => <div key={stage.id}><div><strong>{stage.label}</strong><span>−{stage.rejected.toLocaleString()} · {stage.remaining.toLocaleString()} remain</span></div><span style={{ width: `${Math.max(2, (stage.remaining / funnel.totalScanned) * 100)}%` }} /></div>)}</div></section>}
    {explanation && <section className={styles.aiExplanation}><span><Bot size={16} /> AI explanation</span><h3>{explanation.summary}</h3><p>{explanation.how_the_findings_connect}</p>{explanation.uncertainty_warnings?.length > 0 && <div className={styles.uncertainty}><strong>Uncertainty and missing data</strong>{explanation.uncertainty_warnings.map((item: string) => <p key={item}>{item}</p>)}</div>}</section>}
    {suggestions.length > 0 && <section className={styles.results}><div className={styles.sectionTitle}><div><h3>Suggested actions</h3><p>No action is preselected. Review each independently.</p></div></div><div className={styles.suggestions}>{suggestions.map((item: any) => <article key={item.id} className={styles.suggestion}><div className={styles.suggestionTop}><span>{item.source === "AI" ? <Bot size={15} /> : <Wrench size={15} />} {item.source} suggestion</span><span className={styles.risk} data-risk={item.riskLevel}>{item.riskLevel} risk</span></div><h4>{item.title}</h4><p>{item.explanation}</p><div className={styles.diff}><div><small>Before</small><code>{JSON.stringify(item.currentValueJson)}</code></div><div><small>After</small><code>{JSON.stringify(item.proposedValueJson)}</code></div></div><dl className={styles.suggestionMeta}><div><dt>Expected effect</dt><dd>{item.expectedEffect}</dd></div><div><dt>Reversible</dt><dd>{item.reversible ? "Yes" : "No"}</dd></div><div><dt>Application</dt><dd>{item.manualOnly ? "Manual workflow" : "Mixarr can apply after approval"}</dd></div><div><dt>Status</dt><dd>{item.status.replace(/_/g, " ")}</dd></div></dl>{simulations[item.id] && <div className={styles.simulation}><strong>Deterministic simulation</strong><span>{simulations[item.id].candidateCountBefore} → {simulations[item.id].candidateCountAfter} candidates</span><span>{simulations[item.id].playlistFillBefore} → {simulations[item.id].playlistFillAfter} filled</span><small>No recipe, playlist, history, notification, or integration was modified.</small></div>}<div className={styles.actions}>{["PROPOSED", "AWAITING_REVIEW"].includes(item.status) && <><button onClick={() => onAction(item.id, "simulate")} disabled={busy || item.manualOnly}><Play size={15} /> Simulate</button><button className={styles.primary} onClick={() => onAction(item.id, "accept")} disabled={busy}><Check size={15} /> Accept</button><button onClick={() => onAction(item.id, "reject", { reason: "Rejected during review" })} disabled={busy}>Reject</button><button onClick={() => onAction(item.id, "dismiss", { reason: "Dismissed during review" })} disabled={busy}>Dismiss</button></>}{item.status === "ACCEPTED" && !item.manualOnly && <button className={styles.primary} onClick={() => confirm("Apply exactly the before/after diff shown above? This creates a recipe revision and does not regenerate a playlist.") && onAction(item.id, "apply", { confirmation: "I approve this exact change.", expectedTargetVersion: item.targetVersion })} disabled={busy}><Wrench size={15} /> Apply approved diff</button>}{item.status === "ACCEPTED" && item.manualOnly && <button onClick={() => onAction(item.id, "complete-manually")}>Mark manually completed</button>}</div></article>)}</div></section>}
    {(findings.length > 0 || explanation) && <div className={styles.noChanges}><ShieldCheck /><strong>No settings have been changed.</strong><span>Suggestions require individual review, exact-diff approval, and current-state revalidation.</span></div>}
  </div>;
}

function Metric({ icon, label, value, tone = "default" }: { icon: React.ReactNode; label: string; value: string; tone?: string }) { return <div className={styles.metric} data-tone={tone}><span>{icon}</span><div><small>{label}</small><strong>{value}</strong></div></div>; }
