import crypto from "crypto";
import { NextResponse } from "next/server";
import prisma from "@/lib/prisma";
import { encryptSecret, isSecretEncryptionConfigured } from "@/lib/secretStorage";
import { INTEGRATION_EVENTS, validatePublicDestination } from "@/lib/integrations/core";
import { integrationApiError, requireIntegrationAdmin } from "@/lib/integrations/api";
const db = prisma as any;
export async function GET() { try { await requireIntegrationAdmin(); const endpoints = await db.webhookEndpoint.findMany({ orderBy: { createdAt: "desc" }, select: { id: true, displayName: true, enabled: true, eventsJson: true, timeoutMs: true, retryCount: true, backoffStrategy: true, lastSuccessAt: true, lastFailureAt: true, failureCount: true, createdAt: true } }); return NextResponse.json({ endpoints, supportedEvents: INTEGRATION_EVENTS }); } catch (error) { return integrationApiError(error); } }
export async function POST(request: Request) { try { await requireIntegrationAdmin(); if (!isSecretEncryptionConfigured()) return NextResponse.json({ error: "Configure MIXARR_SECRET_KEY before creating webhooks." }, { status: 409 }); const body = await request.json(); const destination = validatePublicDestination(String(body.destinationUrl), process.env.MIXARR_ALLOW_PRIVATE_WEBHOOKS === "true"); const events = Array.isArray(body.events) ? body.events.filter((event: string) => (INTEGRATION_EVENTS as readonly string[]).includes(event)) : []; const endpoint = await db.webhookEndpoint.create({ data: { displayName: String(body.displayName || "Webhook").slice(0, 120), destinationUrlEncrypted: encryptSecret(destination), secretEncrypted: encryptSecret(String(body.secret || crypto.randomBytes(32).toString("hex"))), enabled: !!body.enabled, eventsJson: events, customHeadersJson: body.customHeaders && typeof body.customHeaders === "object" ? body.customHeaders : {}, timeoutMs: Math.min(30000, Math.max(500, Number(body.timeoutMs || 5000))), retryCount: Math.min(10, Math.max(0, Number(body.retryCount ?? 3))), backoffStrategy: "EXPONENTIAL", includeSensitiveFields: false } }); return NextResponse.json({ endpoint: { id: endpoint.id, displayName: endpoint.displayName, enabled: endpoint.enabled, eventsJson: endpoint.eventsJson } }, { status: 201 }); } catch (error) { return integrationApiError(error); } }
