import type { Prisma } from "@prisma/client";
import { z } from "zod";
import prisma from "@/lib/prisma";
import { AiError } from "../errors";
import { aiFeatureByKey, aiFeatureRegistry } from "../features/registry";
import { isAiSecretEncryptionConfigured } from "../security";

const globalSchema = z.object({ enabled: z.boolean().optional(), defaultProviderId: z.string().uuid().nullable().optional(), defaultFallbackPolicy: z.enum(["NONE", "EXPLICIT_ONLY"]).optional(), auditRetentionDays: z.number().int().min(1).max(3650).optional(), usageReportingEnabled: z.boolean().optional(), maximumServerResponseBytes: z.number().int().min(1024).max(20_000_000).optional(), defaultTimeoutMs: z.number().int().min(30_000).max(600_000).optional(), privacyWarningAcknowledged: z.boolean().optional() });
export async function getAiGlobalSettings() { const row = await prisma.aiGlobalSetting.findUnique({ where: { id: "global" } }); return { ...(row || { id: "global", enabled: false, defaultProviderId: null, defaultFallbackPolicy: "NONE", auditRetentionDays: 90, usageReportingEnabled: true, maximumServerResponseBytes: 1048576, defaultTimeoutMs: 120000, privacyWarningAcknowledgedAt: null }), encryptionConfigured: isAiSecretEncryptionConfigured() }; }
export async function updateAiGlobalSettings(raw: unknown, actorId?: string) {
  const input = globalSchema.parse(raw);
  if (input.defaultProviderId && !(await prisma.aiProviderConfig.findFirst({ where: { id: input.defaultProviderId, deletedAt: null } }))) throw new AiError("AI_PROVIDER_NOT_FOUND");
  const previous = await prisma.aiGlobalSetting.findUnique({ where: { id: "global" } });
  return prisma.$transaction(async (tx) => { const updated = await tx.aiGlobalSetting.upsert({ where: { id: "global" }, create: { id: "global", enabled: input.enabled ?? false, defaultProviderId: input.defaultProviderId, defaultFallbackPolicy: input.defaultFallbackPolicy, auditRetentionDays: input.auditRetentionDays, usageReportingEnabled: input.usageReportingEnabled, maximumServerResponseBytes: input.maximumServerResponseBytes, defaultTimeoutMs: input.defaultTimeoutMs, privacyWarningAcknowledgedAt: input.privacyWarningAcknowledged ? new Date() : null, updatedBy: actorId }, update: { ...input, privacyWarningAcknowledgedAt: input.privacyWarningAcknowledged === true ? new Date() : input.privacyWarningAcknowledged === false ? null : undefined, privacyWarningAcknowledged: undefined, updatedBy: actorId } as any }); if (actorId) await tx.aiGovernanceAudit.create({ data: { actorId, action: "AI_GLOBAL_SETTING_UPDATED", entityType: "AiGlobalSetting", entityId: "global", previousValueJson: previous as any, newValueJson: updated as any } }); return updated; });
}

export async function listAiFeatures() { const rows = await prisma.aiFeatureSetting.findMany(); const byKey = new Map(rows.map((row) => [row.featureKey, row])); return aiFeatureRegistry.map((definition) => { const row = byKey.get(definition.key); return { ...definition, enabled: row?.enabled === true && definition.implemented, requestedEnabled: row?.enabled === true, available: definition.implemented, preferredProviderId: row?.preferredProviderId || null, preferredModel: row?.preferredModel || null, fallbackBehavior: row?.fallbackBehavior || "NONE", fallbackProviderId: row?.fallbackProviderId || null, explanation: definition.implemented ? (row?.enabled ? "Enabled" : "Disabled") : "Planned for a future release; unavailable in the v2.4.1 governance release." }; }); }
const featureSchema = z.object({ enabled: z.boolean().optional(), preferredProviderId: z.string().uuid().nullable().optional(), preferredModel: z.string().max(300).nullable().optional(), fallbackBehavior: z.enum(["NONE", "EXPLICIT_PROVIDER"]).optional(), fallbackProviderId: z.string().uuid().nullable().optional(), safeConfiguration: z.record(z.unknown()).optional() });
export async function updateAiFeature(key: string, raw: unknown, actorId?: string) {
  const definition = aiFeatureByKey.get(key); if (!definition) throw new AiError("FEATURE_DISABLED", "Unknown AI feature.", 404);
  const input = featureSchema.parse(raw); if (input.enabled && !definition.implemented) throw new AiError("FEATURE_DISABLED", "This AI feature is not implemented in v2.4.1.", 409);
  const referencedIds = [input.preferredProviderId, input.fallbackProviderId].filter((id): id is string => !!id);
  if (referencedIds.length && await prisma.aiProviderConfig.count({ where: { id: { in: referencedIds }, deletedAt: null } }) !== new Set(referencedIds).size) throw new AiError("AI_PROVIDER_NOT_FOUND");
  const previous = await prisma.aiFeatureSetting.findUnique({ where: { featureKey: key } });
  return prisma.$transaction(async (tx) => { const updated = await tx.aiFeatureSetting.upsert({ where: { featureKey: key }, create: { featureKey: key, implemented: definition.implemented, enabled: input.enabled ?? false, preferredProviderId: input.preferredProviderId, preferredModel: input.preferredModel, fallbackBehavior: input.fallbackBehavior, fallbackProviderId: input.fallbackProviderId, requiredCapabilities: definition.requiredCapabilities as Prisma.InputJsonValue, safeConfigurationJson: input.safeConfiguration as Prisma.InputJsonValue }, update: { enabled: input.enabled, implemented: definition.implemented, preferredProviderId: input.preferredProviderId, preferredModel: input.preferredModel, fallbackBehavior: input.fallbackBehavior, fallbackProviderId: input.fallbackProviderId, safeConfigurationJson: input.safeConfiguration as Prisma.InputJsonValue } }); if (actorId) await tx.aiGovernanceAudit.create({ data: { actorId, action: "AI_FEATURE_POLICY_UPDATED", entityType: "AiFeatureSetting", entityId: key, previousValueJson: previous as any, newValueJson: updated as any } }); return updated; });
}
