import prisma from "@/lib/prisma";
import { budgetPeriod } from "../governance/policy";

export type AiUsageFilters = { from?: Date; to?: Date; providerId?: string; model?: string; userId?: string; feature?: string; privacyMode?: string; requestSource?: string; location?: string; status?: string; blockReason?: string };
function whereFor(filters: AiUsageFilters, fallbackFrom: Date) { return { createdAt: { gte: filters.from || fallbackFrom, ...(filters.to ? { lte: filters.to } : {}) }, ...(filters.providerId ? { providerConfigId: filters.providerId } : {}), ...(filters.model ? { model: filters.model } : {}), ...(filters.userId ? { userId: filters.userId } : {}), ...(filters.feature ? { featureKey: filters.feature } : {}), ...(filters.privacyMode ? { privacyMode: filters.privacyMode } : {}), ...(filters.requestSource ? { requestSource: filters.requestSource } : {}), ...(filters.location ? { locationClassification: filters.location } : {}), ...(filters.status ? { status: filters.status } : {}), ...(filters.blockReason ? { blockReason: filters.blockReason } : {}) }; }
const sum = (rows: any[], key: string) => rows.reduce((total, row) => total + Number(row[key] || 0), 0);
function group(rows: any[], key: string, value: (row: any) => number = () => 1) { const result: Record<string, number> = {}; for (const row of rows) { const groupKey = String(row[key] ?? "Unknown"); result[groupKey] = (result[groupKey] || 0) + value(row); } return Object.entries(result).map(([name, value]) => ({ name, value })).sort((left, right) => right.value - left.value); }

export async function getAiUsage(filters: AiUsageFilters = {}) {
  const now = new Date(); const governance = await prisma.aiGovernanceSetting.findUnique({ where: { id: "global" } }); const period = budgetPeriod(now, governance?.budgetResetDay || 1); const today = new Date(Date.UTC(now.getUTCFullYear(), now.getUTCMonth(), now.getUTCDate()));
  const [rows, todayCount, providers, reserved] = await Promise.all([
    prisma.aiRequestAudit.findMany({ where: whereFor(filters, period.start), orderBy: { createdAt: "desc" }, select: { id: true, requestId: true, createdAt: true, status: true, latencyMs: true, inputTokenCount: true, outputTokenCount: true, totalTokenCount: true, cachedTokenCount: true, reasoningTokenCount: true, estimatedCost: true, actualCost: true, providerConfigId: true, providerDisplayName: true, model: true, userId: true, featureKey: true, privacyMode: true, requestSource: true, locationClassification: true, blockReason: true, retryCount: true, fallbackReason: true, usageSource: true } }),
    prisma.aiRequestAudit.count({ where: { createdAt: { gte: today } } }), prisma.aiProviderConfig.findMany({ select: { id: true, displayName: true, locationClassification: true, monthlyBudget: true, governanceBudget: true } }), prisma.aiBudgetReservation.aggregate({ where: { status: "ACTIVE", expiresAt: { gt: now } }, _sum: { reservedCost: true } })
  ]);
  const costFor = (row: any) => Number(row.actualCost ?? row.estimatedCost ?? 0); const costsAvailable = rows.some((row) => row.actualCost != null || row.estimatedCost != null); const totalTokens = rows.map((row) => Number(row.totalTokenCount ?? (row.inputTokenCount || 0) + (row.outputTokenCount || 0))).sort((a, b) => a - b); const totalCost = rows.reduce((total, row) => total + costFor(row), 0); const reservedCost = Number(reserved._sum.reservedCost || 0); const monthlyLimit = governance?.monthlyBudget == null ? null : Number(governance.monthlyBudget); const elapsedDays = Math.max(1, (now.getTime() - period.start.getTime()) / 86_400_000); const periodDays = Math.max(1, (period.end.getTime() - period.start.getTime()) / 86_400_000);
  const summary = { requestsToday: todayCount, requestsThisMonth: rows.length, requests: rows.length, successfulRequests: rows.filter((row) => row.status === "COMPLETED").length, failedRequests: rows.filter((row) => ["FAILED", "TIMED_OUT"].includes(row.status)).length, blockedRequests: rows.filter((row) => row.status === "BLOCKED").length, cancelledRequests: rows.filter((row) => row.status === "CANCELLED").length, averageLatencyMs: Math.round(sum(rows.filter((row) => row.latencyMs != null), "latencyMs") / Math.max(1, rows.filter((row) => row.latencyMs != null).length)), inputTokens: sum(rows, "inputTokenCount"), outputTokens: sum(rows, "outputTokenCount"), totalTokens: sum(rows, "totalTokenCount") || sum(rows, "inputTokenCount") + sum(rows, "outputTokenCount"), cachedTokens: sum(rows, "cachedTokenCount"), reasoningTokens: sum(rows, "reasoningTokenCount"), estimatedCost: costsAvailable ? totalCost : null, reservedCost, remainingBudget: monthlyLimit == null ? null : Math.max(0, monthlyLimit - totalCost - reservedCost), localRequests: rows.filter((row) => row.locationClassification === "LOCAL").length, externalRequests: rows.filter((row) => row.locationClassification === "EXTERNAL" || row.locationClassification === "REMOTE").length };
  const byDayMap = new Map<string, any>(); for (const row of rows) { const day = row.createdAt.toISOString().slice(0, 10); const entry = byDayMap.get(day) || { date: day, requests: 0, inputTokens: 0, outputTokens: 0, cost: 0, blocked: 0 }; entry.requests++; entry.inputTokens += row.inputTokenCount || 0; entry.outputTokens += row.outputTokenCount || 0; entry.cost += costFor(row); if (row.status === "BLOCKED") entry.blocked++; byDayMap.set(day, entry); }
  return { summary, budget: { usage: totalCost, limit: monthlyLimit, percentConsumed: monthlyLimit ? totalCost / monthlyLimit : null, warningThresholds: governance?.budgetWarningThresholds || [0.5, 0.75, 0.9, 1], projectedEndOfPeriod: totalCost / elapsedDays * periodDays, projectionIsEstimate: true, hardShutdownEnabled: governance?.hardShutdownEnabled ?? true, resetAt: period.end.toISOString() }, providers: providers.map((provider) => { const providerRows = rows.filter((row) => row.providerConfigId === provider.id); const cost = providerRows.reduce((total, row) => total + costFor(row), 0); const limit = provider.governanceBudget?.monthlyLimit ?? provider.monthlyBudget; return { id: provider.id, displayName: provider.displayName, locationClassification: provider.locationClassification, requests: providerRows.length, tokens: sum(providerRows, "totalTokenCount"), estimatedCost: providerRows.some((row) => row.actualCost != null || row.estimatedCost != null) ? cost : null, remainingBudget: limit == null ? null : Math.max(0, Number(limit) - cost), costLabel: provider.locationClassification === "LOCAL" ? "Local provider — configured cost" : undefined }; }), charts: { daily: Array.from(byDayMap.values()).sort((a, b) => a.date.localeCompare(b.date)), byProvider: group(rows, "providerDisplayName"), byModel: group(rows, "model"), byUser: group(rows, "userId"), byFeature: group(rows, "featureKey"), byPrivacyMode: group(rows, "privacyMode"), byLocation: group(rows, "locationClassification"), byRequestSource: group(rows, "requestSource"), byBlockReason: group(rows.filter((row) => row.blockReason), "blockReason") }, tokenAnalytics: { averageTokensPerRequest: Math.round(totalTokens.reduce((a, b) => a + b, 0) / Math.max(1, totalTokens.length)), medianTokensPerRequest: totalTokens.length ? totalTokens[Math.floor(totalTokens.length / 2)] : 0, highestTokenRequests: [...rows].sort((a, b) => Number(b.totalTokenCount || 0) - Number(a.totalTokenCount || 0)).slice(0, 10), tokensByProvider: group(rows, "providerDisplayName", (row) => Number(row.totalTokenCount || 0)), tokensByModel: group(rows, "model", (row) => Number(row.totalTokenCount || 0)), tokensByFeature: group(rows, "featureKey", (row) => Number(row.totalTokenCount || 0)), tokensByPrivacyMode: group(rows, "privacyMode", (row) => Number(row.totalTokenCount || 0)), tokensFromRetries: rows.reduce((total, row) => total + (row.retryCount ? Number(row.totalTokenCount || 0) : 0), 0), estimatedValuesLabeled: true }, records: rows.slice(0, 250) };
}

export function parseUsageFilters(url: URL): AiUsageFilters { const date = (key: string) => { const value = url.searchParams.get(key); const parsed = value ? new Date(value) : undefined; return parsed && !Number.isNaN(parsed.getTime()) ? parsed : undefined; }; return { from: date("from"), to: date("to"), providerId: url.searchParams.get("providerId") || undefined, model: url.searchParams.get("model") || undefined, userId: url.searchParams.get("userId") || undefined, feature: url.searchParams.get("feature") || undefined, privacyMode: url.searchParams.get("privacyMode") || undefined, requestSource: url.searchParams.get("requestSource") || undefined, location: url.searchParams.get("location") || undefined, status: url.searchParams.get("status") || undefined, blockReason: url.searchParams.get("blockReason") || undefined }; }
