"use client";

import { useCallback, useEffect, useMemo, useState } from "react";
import { Activity, AlertTriangle, CheckCircle2, Clock3, Network, Pause, Play, Plus, RefreshCw, ShieldCheck, Trash2 } from "lucide-react";
import styles from "./orchestration.module.css";

async function api(path: string, init?: RequestInit) {
  const response = await fetch(path, { cache: "no-store", headers: { "Content-Type": "application/json", ...(init?.headers || {}) }, ...init });
  const data = await response.json();
  if (!response.ok) throw new Error(data.error?.message || data.error || "Request failed.");
  return data;
}

function when(value?: string | null) { return value ? new Date(value).toLocaleString() : "Never"; }
function badge(status: string) { return status.toLowerCase().replaceAll("_", "-"); }

export default function OrchestrationPage() {
  const [status, setStatus] = useState<any>(null); const [playlists, setPlaylists] = useState<any[]>([]); const [available, setAvailable] = useState<any[]>([]); const [libraries, setLibraries] = useState<any[]>([]);
  const [jobs, setJobs] = useState<any[]>([]); const [audit, setAudit] = useState<any[]>([]); const [relationships, setRelationships] = useState<any[]>([]);
  const [selectedAvailable, setSelectedAvailable] = useState(""); const [libraryId, setLibraryId] = useState(""); const [sourceId, setSourceId] = useState(""); const [targetId, setTargetId] = useState(""); const [relationshipType, setRelationshipType] = useState("DEPENDS_ON");
  const [busy, setBusy] = useState(false); const [error, setError] = useState(""); const [message, setMessage] = useState("");
  const load = useCallback(async () => { try { const [s, p, j, a, r] = await Promise.all([api("/api/orchestration/status"), api("/api/orchestration/playlists?pageSize=100"), api("/api/orchestration/jobs?pageSize=50"), api("/api/orchestration/audit?pageSize=30"), api("/api/orchestration/relationships?pageSize=100")]); setStatus(s); setPlaylists(p.items); setAvailable(p.available); setLibraries(p.libraries); setJobs(j.items); setAudit(a.items); setRelationships(r.items); setSelectedAvailable((value) => value || p.available[0]?.id || ""); setLibraryId((value) => value || p.libraries[0]?.id || ""); setSourceId((value) => value || p.items[0]?.id || ""); setError(""); } catch (caught) { setError(caught instanceof Error ? caught.message : "Unable to load orchestration."); } }, []);
  useEffect(() => { void load(); }, [load]);
  useEffect(() => { if (!status?.summary.runningJobs && !status?.summary.queuedJobs) return; const timer = setTimeout(() => void load(), 5000); return () => clearTimeout(timer); }, [load, status]);
  const targets = useMemo(() => playlists.filter((playlist) => playlist.id !== sourceId), [playlists, sourceId]);
  async function action(task: () => Promise<any>, success: string) { setBusy(true); setError(""); setMessage(""); try { await task(); setMessage(success); await load(); } catch (caught) { setError(caught instanceof Error ? caught.message : "Request failed."); } finally { setBusy(false); } }
  async function register() { if (!selectedAvailable || !libraryId) return; await action(() => api("/api/orchestration/playlists", { method: "POST", body: JSON.stringify({ generatedPlaylistId: selectedAvailable, libraryId }) }), "Playlist registered with automation disabled by default."); }
  async function updatePlaylist(id: string, patch: any, success: string) { await action(() => api(`/api/orchestration/playlists/${id}`, { method: "PATCH", body: JSON.stringify(patch) }), success); }
  async function unregister(id: string) { if (!window.confirm("This removes the playlist from Mixarr orchestration. It does not delete the playlist from Plex.")) return; await action(() => api(`/api/orchestration/playlists/${id}`, { method: "DELETE" }), "Playlist removed from orchestration. Plex was not changed."); }
  async function queue(id: string, dryRun: boolean) { await action(() => api(dryRun ? "/api/orchestration/dry-run" : "/api/orchestration/jobs", { method: "POST", body: JSON.stringify({ managedPlaylistId: id, jobType: dryRun ? "DRY_RUN" : "SYNC", trigger: "MANUAL", dryRun, idempotencyKey: `ui:${id}:${dryRun ? "dry" : "sync"}:${Date.now()}` }) }), dryRun ? "Dry run queued. Plex will not be modified." : "Manual synchronization queued."); }
  async function createRelationship() { if (!sourceId || !targetId) return; await action(() => api("/api/orchestration/relationships", { method: "POST", body: JSON.stringify({ sourceManagedPlaylistId: sourceId, targetManagedPlaylistId: targetId, relationshipType }) }), "Playlist relationship created."); }
  return <main className={styles.page}>
    <header className={styles.header}><div><span className={styles.kicker}><Network size={15}/> v2.2.0 foundation</span><h1>Playlist Orchestration</h1><p>Coordinate managed playlist work through one safe, persistent queue. Legacy playlist tools remain available.</p></div><button onClick={() => void load()} disabled={busy}><RefreshCw size={16}/> Refresh</button></header>
    {error && <div className={styles.error}><AlertTriangle size={17}/>{error}</div>}{message && <div className={styles.success}><CheckCircle2 size={17}/>{message}</div>}
    {status?.health?.warning && <div className={styles.error}><AlertTriangle size={17}/>{status.health.warning}</div>}
    {!status?.settings.enabled && <div className={styles.notice}><Pause size={17}/><div><strong>Orchestration is globally disabled</strong><span>Queued work is preserved and marked waiting. An administrator can enable it in Settings.</span></div></div>}
    <section className={styles.metrics}>{[["Managed", status?.summary.managedPlaylists || 0], ["Automation enabled", status?.summary.automationEnabled || 0], ["Running", status?.summary.runningJobs || 0], ["Queued", status?.summary.queuedJobs || 0], ["Waiting / blocked", status?.summary.waitingJobs || 0], ["Active locks", status?.summary.activeLocks || 0]].map(([label, value]) => <article key={String(label)}><span>{label}</span><strong>{value}</strong></article>)}</section>
    <section className={styles.panel}><div className={styles.panelHeading}><div><h2>Register a Mixarr playlist</h2><p>Registration is opt-in and does not enable automation automatically.</p></div></div><div className={styles.inlineForm}><label>Playlist<select value={selectedAvailable} onChange={(event) => setSelectedAvailable(event.target.value)}><option value="">Select an unregistered playlist</option>{available.map((playlist) => <option key={playlist.id} value={playlist.id}>{playlist.plexPlaylistTitle} · {playlist.trackCount} tracks</option>)}</select></label><label>Library<select value={libraryId} onChange={(event) => setLibraryId(event.target.value)}>{libraries.map((library) => <option key={library.id} value={library.id}>{library.name}</option>)}</select></label><button onClick={register} disabled={busy || !selectedAvailable || !libraryId}><Plus size={16}/> Register</button></div></section>
    <section className={styles.panel}><div className={styles.panelHeading}><div><h2>Managed playlists</h2><p>Configuration and runtime state are shown separately.</p></div></div><div className={styles.tableWrap}><table><thead><tr><th>Playlist</th><th>Priority</th><th>Automation</th><th>Runtime</th><th>Dependencies</th><th>Last success</th><th>Actions</th></tr></thead><tbody>{!playlists.length && <tr><td colSpan={7} className={styles.empty}>No managed playlists yet.</td></tr>}{playlists.map((playlist) => <tr key={playlist.id}><td><strong>{playlist.displayName}</strong><small>{playlist.generatedPlaylist?.trackCount ?? 0} tracks</small></td><td><select value={playlist.priority} onChange={(event) => void updatePlaylist(playlist.id, { priority: event.target.value }, "Priority updated.")}><option>HIGH</option><option>NORMAL</option><option>LOW</option></select></td><td><button className={styles.textButton} onClick={() => void updatePlaylist(playlist.id, { automationEnabled: !playlist.automationEnabled }, playlist.automationEnabled ? "Automation disabled." : "Automation enabled.")}>{playlist.automationEnabled ? <><ShieldCheck size={14}/> Enabled</> : <><Pause size={14}/> Disabled</>}</button></td><td><span className={styles.badge} data-status={badge(playlist.automationState)}>{playlist.automationState}</span>{playlist.automationStateReason && <small title={playlist.automationStateReason}>{playlist.automationStateReason}</small>}</td><td>{playlist.relationshipSources.length + playlist.relationshipTargets.length}</td><td>{when(playlist.lastCompletedAt)}</td><td><div className={styles.actions}><button title="Queue safe dry run" onClick={() => void queue(playlist.id, true)}>Dry run</button><button title={playlist.automationState === "PAUSED" ? "Resume" : "Pause"} onClick={() => void updatePlaylist(playlist.id, { state: playlist.automationState === "PAUSED" ? "ACTIVE" : "PAUSED", reason: playlist.automationState === "PAUSED" ? null : "Paused by user" }, playlist.automationState === "PAUSED" ? "Playlist resumed." : "Playlist paused.")}>{playlist.automationState === "PAUSED" ? <Play size={14}/> : <Pause size={14}/>}</button><button title="Queue Plex sync" onClick={() => void queue(playlist.id, false)}>Sync</button><button title="Unregister" onClick={() => void unregister(playlist.id)}><Trash2 size={14}/></button></div></td></tr>)}</tbody></table></div></section>
    <div className={styles.columns}><section className={styles.panel}><div className={styles.panelHeading}><div><h2>Dependencies</h2><p>Dependencies are validated before dispatch; cycles are rejected.</p></div></div><div className={styles.inlineForm}><label>Playlist<select value={sourceId} onChange={(event) => { setSourceId(event.target.value); setTargetId(""); }}>{playlists.map((playlist) => <option key={playlist.id} value={playlist.id}>{playlist.displayName}</option>)}</select></label><label>Relationship<select value={relationshipType} onChange={(event) => setRelationshipType(event.target.value)}><option>DEPENDS_ON</option><option>RUNS_AFTER</option><option>RELATED</option></select></label><label>Target<select value={targetId} onChange={(event) => setTargetId(event.target.value)}><option value="">Select target</option>{targets.map((playlist) => <option key={playlist.id} value={playlist.id}>{playlist.displayName}</option>)}</select></label><button onClick={createRelationship} disabled={busy || !targetId}>Add</button></div><div className={styles.tree}>{!relationships.length && <p>No relationships defined.</p>}{relationships.map((relationship) => <div key={relationship.id}><Network size={14}/><span><strong>{relationship.sourceManagedPlaylist.displayName}</strong> {relationship.relationshipType.replaceAll("_", " ").toLowerCase()} <strong>{relationship.targetManagedPlaylist.displayName}</strong></span><button onClick={() => void action(() => api(`/api/orchestration/relationships/${relationship.id}`, { method: "DELETE" }), "Relationship removed.")}><Trash2 size={13}/></button></div>)}</div></section>
    <section className={styles.panel}><div className={styles.panelHeading}><div><h2>Queue</h2><p>Dependency, conflict, and dry-run reasons remain attached to each job.</p></div></div><div className={styles.jobList}>{!jobs.length && <p>No orchestration jobs yet.</p>}{jobs.map((job) => <article key={job.id}><div><strong>{job.managedPlaylist?.displayName || "Historical playlist"}</strong><span>{job.jobType} · {job.trigger}{job.dryRun ? " · DRY RUN" : ""}</span></div><span className={styles.badge} data-status={badge(job.status)}>{job.status}</span><small>{job.waitingReason || job.errorMessage || when(job.requestedAt)}</small>{["QUEUED", "WAITING", "BLOCKED"].includes(job.status) && <button onClick={() => void action(() => api(`/api/orchestration/jobs/${job.id}/cancel`, { method: "POST" }), "Job cancelled.")}>Cancel</button>}{["FAILED", "STALE"].includes(job.status) && <button onClick={() => void action(() => api(`/api/orchestration/jobs/${job.id}/retry`, { method: "POST" }), "Retry queued.")}>Retry</button>}</article>)}</div></section></div>
    <section className={styles.panel}><div className={styles.panelHeading}><div><h2>Audit activity</h2><p>Meaningful orchestration events; credentials and full track payloads are excluded.</p></div></div><div className={styles.audit}>{!audit.length && <p>No audit activity yet.</p>}{audit.map((event) => <article key={event.id}><Activity size={15}/><div><strong>{event.eventType.replaceAll("_", " ")}</strong><span>{event.message}</span></div><time>{when(event.createdAt)}</time></article>)}</div></section>
  </main>;
}
