"use client";
import { FormEvent, useEffect, useState } from "react";
import Link from "next/link";
import { ArrowLeft, ChevronLeft, ChevronRight, Search } from "lucide-react";
import styles from "../library-health.module.css";

export default function DuplicateGroupsPage({ searchParams }: { searchParams: { libraryId?: string } }) {
  const libraryId = searchParams.libraryId || ""; const [groups, setGroups] = useState<any[]>([]); const [search, setSearch] = useState(""); const [page, setPage] = useState(1); const [pagination, setPagination] = useState({ total: 0, totalPages: 1 });
  async function load(nextPage = page) { const query = new URLSearchParams({ page: String(nextPage), pageSize: "50" }); if (libraryId) query.set("libraryId", libraryId); if (search) query.set("search", search); const response = await fetch(`/api/duplicate-groups?${query}`, { cache: "no-store" }); const data = await response.json(); if (!response.ok) throw new Error(data.error); setGroups(data.groups); setPagination(data.pagination); setPage(nextPage); }
  // `load` intentionally captures the submitted search value; library changes reset to page one.
  // eslint-disable-next-line react-hooks/exhaustive-deps
  useEffect(() => { void load(1); }, [libraryId]); function submit(event: FormEvent) { event.preventDefault(); void load(1); }
  return <main className={styles.page}><header className={styles.header}><div><Link href="/settings/library-health" className={styles.back}><ArrowLeft size={15} /> Library Health</Link><h2>Duplicate Groups</h2><p>Canonical recordings organize duplicate copies without merging or deleting any Plex track instance.</p></div></header><section className="glass-panel"><form className={styles.filters} onSubmit={submit}><label>Search<input value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Artist or recording" /></label><button className={styles.primaryButton}><Search size={15} /> Search</button></form><div className={styles.tableWrap}><table><thead><tr><th>Recording</th><th>Copies</th><th>Confidence</th><th>Review</th><th>Preferred enrichment source</th><th>Shared enrichment</th><th>Actions</th></tr></thead><tbody>{groups.map((group) => <tr key={group.id}><td><strong>{group.canonicalArtist} — {group.canonicalTitle}</strong><small className={styles.trackMeta}>{group.id}</small></td><td>{group._count.tracks}</td><td>{group.confidence}</td><td>{group.reviewStatus}</td><td>{group.preferredEnrichmentTrack?.title || "Automatically selected"}</td><td>{group.sharedEnrichment ? Object.keys(group.sharedEnrichment).join(", ") : "None"}</td><td><Link className={styles.tableAction} href={`/settings/library-health/duplicate-groups/${encodeURIComponent(group.id)}`}>Open duplicate group</Link></td></tr>)}</tbody></table></div><div className={styles.pagination}><span>{pagination.total.toLocaleString()} groups</span><div><button disabled={page <= 1} onClick={() => void load(page - 1)} aria-label="Previous page"><ChevronLeft size={16} /></button><span>Page {page} of {pagination.totalPages}</span><button disabled={page >= pagination.totalPages} onClick={() => void load(page + 1)} aria-label="Next page"><ChevronRight size={16} /></button></div></div></section></main>;
}
