import { NextResponse } from "next/server";
import { z } from "zod";
import prisma from "@/lib/prisma";
import { orchestrationApiError, orchestrationSession, orchestrationUnauthorized } from "@/lib/orchestration/api";
import { unregisterManagedPlaylist, updateManagedPlaylist } from "@/lib/orchestration/service";

const schema = z.object({ automationEnabled: z.boolean().optional(), enabled: z.boolean().optional(), priority: z.enum(["HIGH", "NORMAL", "LOW"]).optional(), state: z.enum(["ACTIVE", "PAUSED", "DISABLED", "WAITING", "BLOCKED", "ERROR"]).optional(), reason: z.string().max(500).nullable().optional(), orchestrationMode: z.enum(["COORDINATED", "OBSERVE_ONLY", "DRY_RUN_ONLY"]).optional() });
export async function GET(_: Request, { params }: { params: { id: string } }) { const userId = orchestrationSession(); if (!userId) return orchestrationUnauthorized(); try { const playlist = await prisma.managedPlaylist.findFirst({ where: { id: params.id, userId }, include: { relationshipSources: { include: { targetManagedPlaylist: true } }, relationshipTargets: { include: { sourceManagedPlaylist: true } }, jobs: { orderBy: { createdAt: "desc" }, take: 20 }, auditEvents: { orderBy: { createdAt: "desc" }, take: 20 } } }); if (!playlist) return NextResponse.json({ error: { code: "MANAGED_PLAYLIST_NOT_FOUND", message: "Managed playlist not found." } }, { status: 404 }); return NextResponse.json({ playlist }); } catch (error) { return orchestrationApiError(error); } }
export async function PATCH(request: Request, { params }: { params: { id: string } }) { const userId = orchestrationSession(); if (!userId) return orchestrationUnauthorized(); try { const input = schema.parse(await request.json()); return NextResponse.json({ playlist: await updateManagedPlaylist(userId, params.id, input, userId) }); } catch (error) { return orchestrationApiError(error); } }
export async function DELETE(_: Request, { params }: { params: { id: string } }) { const userId = orchestrationSession(); if (!userId) return orchestrationUnauthorized(); try { return NextResponse.json({ playlist: await unregisterManagedPlaylist(userId, params.id, userId), plexDeleted: false }); } catch (error) { return orchestrationApiError(error); } }
