import { NextResponse } from "next/server";
import { z } from "zod";
import prisma from "@/lib/prisma";
import { aiRouteError, requireAiPermission } from "@/ai/services/api";
export const dynamic = "force-dynamic";
const providerSchema = z.object({ scope: z.literal("provider"), providerConfigId: z.string().uuid(), currency: z.string().regex(/^[A-Z]{3}$/).default("USD"), dailyLimit: z.union([z.number().nonnegative(), z.string(), z.null()]).optional(), monthlyLimit: z.union([z.number().nonnegative(), z.string(), z.null()]).optional(), warningThresholds: z.array(z.number().min(0).max(1)).default([0.5, 0.75, 0.9, 1]), hardLimitEnabled: z.boolean().default(true), selectableAfterWarning: z.boolean().default(true), allowFallbackWhenExhausted: z.boolean().default(false), dailyRequestLimit: z.number().int().positive().nullable().optional(), monthlyRequestLimit: z.number().int().positive().nullable().optional(), maximumInputTokens: z.number().int().positive().nullable().optional(), maximumOutputTokens: z.number().int().positive().nullable().optional(), maximumCombinedTokens: z.number().int().positive().nullable().optional(), reason: z.string().max(1000).optional() });
const userSchema = z.object({ scope: z.literal("user"), userId: z.string().uuid(), currency: z.string().regex(/^[A-Z]{3}$/).default("USD"), dailyCostLimit: z.union([z.number().nonnegative(), z.string(), z.null()]).optional(), monthlyCostLimit: z.union([z.number().nonnegative(), z.string(), z.null()]).optional(), dailyRequestLimit: z.number().int().positive().nullable().optional(), monthlyRequestLimit: z.number().int().positive().nullable().optional(), maximumInputTokens: z.number().int().positive().nullable().optional(), maximumOutputTokens: z.number().int().positive().nullable().optional(), maximumCombinedTokens: z.number().int().positive().nullable().optional(), allowedPrivacyModes: z.array(z.string()).optional(), allowedProviderIds: z.array(z.string().uuid()).optional(), allowedModelTiers: z.array(z.string()).optional(), paidProvidersAllowed: z.boolean().default(false), backgroundRequestsAllowed: z.boolean().default(false), reason: z.string().max(1000).optional() });
export async function GET() { try { await requireAiPermission("MANAGE_AI_BUDGETS"); const [providers, users] = await Promise.all([prisma.aiProviderBudget.findMany({ include: { provider: { select: { displayName: true } } }, orderBy: { provider: { displayName: "asc" } } }), prisma.aiUserLimit.findMany({ orderBy: { userId: "asc" } })]); return NextResponse.json({ providers, users }); } catch (error) { return aiRouteError(error); } }
export async function PUT(request: Request) { try { const actorId = await requireAiPermission("MANAGE_AI_BUDGETS"); const raw = await request.json(); if (raw.scope === "provider") { const { scope, warningThresholds, reason, ...input } = providerSchema.parse(raw); const previous = await prisma.aiProviderBudget.findUnique({ where: { providerConfigId: input.providerConfigId } }); const row = await prisma.$transaction(async (tx) => { const saved = await tx.aiProviderBudget.upsert({ where: { providerConfigId: input.providerConfigId }, create: { ...input, warningThresholdsJson: warningThresholds } as any, update: { ...input, warningThresholdsJson: warningThresholds } as any }); await tx.aiGovernanceAudit.create({ data: { actorId, action: "PROVIDER_BUDGET_UPDATED", entityType: "AiProviderBudget", entityId: saved.id, previousValueJson: previous as any, newValueJson: saved as any, reason } }); return saved; }); return NextResponse.json(row); } const { scope, allowedPrivacyModes, allowedProviderIds, allowedModelTiers, reason, ...input } = userSchema.parse(raw); const previous = await prisma.aiUserLimit.findUnique({ where: { userId: input.userId } }); const row = await prisma.$transaction(async (tx) => { const data = { ...input, allowedPrivacyModesJson: allowedPrivacyModes, allowedProviderIdsJson: allowedProviderIds, allowedModelTiersJson: allowedModelTiers } as any; const saved = await tx.aiUserLimit.upsert({ where: { userId: input.userId }, create: data, update: data }); await tx.aiGovernanceAudit.create({ data: { actorId, action: "USER_AI_LIMIT_UPDATED", entityType: "AiUserLimit", entityId: saved.id, previousValueJson: previous as any, newValueJson: saved as any, reason } }); return saved; }); return NextResponse.json(row); } catch (error) { return aiRouteError(error); } }
