import { NextResponse } from "next/server";
import { z } from "zod";
import prisma from "@/lib/prisma";
import { requireAdminUser } from "@/lib/auth";
import { inheritanceApiError, inheritanceSession, inheritanceUnauthorized } from "@/lib/recipeInheritance/api";
const schema = z.object({ fieldPath: z.string().trim().min(3).max(240), value: z.unknown(), sourceType: z.string().trim().min(1).max(80).default("GLOBAL_POLICY"), sourceEntityId: z.string().nullish(), authority: z.number().int().min(1).max(10000).default(1000), reason: z.string().trim().max(1000).nullish() });
export async function GET() { const userId = inheritanceSession(); if (!userId) return inheritanceUnauthorized(); return NextResponse.json({ locks: await prisma.recipeFieldLock.findMany({ where: { userId }, orderBy: [{ authority: "desc" }, { fieldPath: "asc" }] }) }); }
export async function POST(request: Request) { const userId = inheritanceSession(); if (!userId) return inheritanceUnauthorized(); try { await requireAdminUser(userId); const body = schema.parse(await request.json()); const lock = await prisma.recipeFieldLock.create({ data: { userId, fieldPath: body.fieldPath, valueJson: body.value as any, sourceType: body.sourceType, sourceEntityId: body.sourceEntityId || null, authority: body.authority, reason: body.reason || null, createdById: userId } }); await prisma.recipeInheritanceAudit.create({ data: { actorId: userId, action: "LOCK_CREATED", entityType: "RecipeFieldLock", entityId: lock.id, nextJson: lock as any, reason: body.reason } }); return NextResponse.json({ lock }, { status: 201 }); } catch (error) { return inheritanceApiError(error); } }
export async function DELETE(request: Request) { const userId = inheritanceSession(); if (!userId) return inheritanceUnauthorized(); try { await requireAdminUser(userId); const id = new URL(request.url).searchParams.get("id"); if (!id) throw new Error("Lock id is required."); const lock = await prisma.recipeFieldLock.findFirst({ where: { id, userId } }); if (!lock) throw new Error("Recipe field lock not found."); await prisma.$transaction([prisma.recipeFieldLock.delete({ where: { id } }), prisma.recipeInheritanceAudit.create({ data: { actorId: userId, action: "LOCK_REMOVED", entityType: "RecipeFieldLock", entityId: id, previousJson: lock as any } })]); return NextResponse.json({ deleted: true }); } catch (error) { return inheritanceApiError(error); } }
