import { NextResponse } from "next/server";
import { z } from "zod";
import prisma from "@/lib/prisma";
import { inheritanceApiError, inheritanceSession, inheritanceUnauthorized } from "@/lib/recipeInheritance/api";

const patchSchema = z.object({ name: z.string().trim().min(1).max(120).optional(), description: z.string().trim().max(1000).nullish(), config: z.record(z.unknown()).optional(), locks: z.record(z.unknown()).optional(), isArchived: z.boolean().optional(), confirmImpact: z.boolean().optional() });
async function owned(userId: string, id: string) { const preset = await prisma.recipePreset.findFirst({ where: { id, ownerId: userId }, include: { _count: { select: { categories: true, transitionRecipes: true, discoveryRecipes: true, varietyRecipes: true, automationRecipes: true } } } }); if (!preset) throw new Error("Recipe preset not found."); return preset; }
function count(preset: any) { return preset._count.categories + preset._count.transitionRecipes + preset._count.discoveryRecipes + preset._count.varietyRecipes + preset._count.automationRecipes; }
export async function GET(_request: Request, { params }: { params: { id: string } }) { const userId = inheritanceSession(); if (!userId) return inheritanceUnauthorized(); try { return NextResponse.json({ preset: await owned(userId, params.id) }); } catch (error) { return inheritanceApiError(error); } }
export async function PATCH(request: Request, { params }: { params: { id: string } }) {
  const userId = inheritanceSession(); if (!userId) return inheritanceUnauthorized();
  try { const current = await owned(userId, params.id); const body = patchSchema.parse(await request.json()); const dependents = count(current); if (dependents >= 10 && !body.confirmImpact) return NextResponse.json({ confirmationRequired: true, dependentCount: dependents, message: `This shared preset affects ${dependents} recipes or categories.` }, { status: 409 }); const nextVersion = current.version + 1; const nextConfig = body.config ?? current.configJson; const nextLocks = body.locks ?? current.locksJson; const preset = await prisma.$transaction(async (tx) => { const updated = await tx.recipePreset.update({ where: { id: current.id }, data: { name: body.name, description: body.description, configJson: nextConfig as any, locksJson: nextLocks as any, isArchived: body.isArchived, version: nextVersion, versions: { create: { version: nextVersion, configJson: nextConfig as any, locksJson: nextLocks as any, createdById: userId } } } }); await tx.recipeInheritanceAudit.create({ data: { actorId: userId, action: body.isArchived ? "PRESET_ARCHIVED" : "PRESET_UPDATED", entityType: "RecipePreset", entityId: current.id, previousJson: { version: current.version, config: current.configJson, locks: current.locksJson } as any, nextJson: { version: nextVersion, config: nextConfig, locks: nextLocks } as any } }); return updated; }); return NextResponse.json({ preset, dependentCount: dependents }); }
  catch (error) { return inheritanceApiError(error); }
}
export async function DELETE(request: Request, { params }: { params: { id: string } }) {
  const userId = inheritanceSession(); if (!userId) return inheritanceUnauthorized();
  try { const preset = await owned(userId, params.id); const dependents = count(preset); const strategy = new URL(request.url).searchParams.get("strategy"); if (dependents && !strategy) return NextResponse.json({ error: "Preset has dependents. Choose archive, remove_reference, or convert_to_explicit.", dependencyCheck: { dependentCount: dependents, strategies: ["archive", "remove_reference", "convert_to_explicit"] } }, { status: 409 }); if (strategy === "archive") { await prisma.recipePreset.update({ where: { id: preset.id }, data: { isArchived: true } }); return NextResponse.json({ archived: true, dependentCount: dependents }); } if (dependents) throw new Error("Migrate preset dependents before deletion."); await prisma.recipePreset.delete({ where: { id: preset.id } }); return NextResponse.json({ deleted: true }); }
  catch (error) { return inheritanceApiError(error); }
}
