"use client";

import { useCallback, useEffect, useMemo, useRef, useState } from "react";
import { AlertTriangle, Archive, Check, ChevronLeft, ChevronRight, Download, Eye, Filter, RefreshCw, Search, ShieldCheck, Sparkles, X } from "lucide-react";
import styles from "./AiMetadataSuggestions.module.css";

async function api(url: string, init?: RequestInit) { const response = await fetch(url, { cache: "no-store", ...init, headers: { "Content-Type": "application/json", ...(init?.headers || {}) } }); const contentType = response.headers.get("content-type") || ""; const body = contentType.includes("json") ? await response.json() : await response.text(); if (!response.ok) throw new Error(body?.error?.message || body?.message || "Request failed."); return body; }
const words = (value: string) => value.replaceAll("_", " ").toLowerCase().replace(/^./, (letter) => letter.toUpperCase());
const finalJobs = new Set(["COMPLETED", "COMPLETED_WITH_WARNINGS", "FAILED", "CANCELLED"]);

export default function AiMetadataSuggestions() {
  const [data, setData] = useState<any>({ suggestions: [], pagination: { page: 1, pageCount: 1, total: 0 } }), [stats, setStats] = useState<any>({}), [selected, setSelected] = useState<Set<string>>(new Set());
  const [filters, setFilters] = useState<any>({ status: "", confidence: "", type: "", field: "", artist: "", album: "", source: "", provider: "", detectionMethod: "", plexImpact: "", sourceLibraryImpact: "", embeddedTagImpact: "", conflictingSources: "", createdFrom: "", createdTo: "", sort: "newest" });
  const [page, setPage] = useState(1), [busy, setBusy] = useState(""), [error, setError] = useState(""), [message, setMessage] = useState(""), [note, setNote] = useState("");
  const [detail, setDetail] = useState<any>(null), [job, setJob] = useState<any>(null), [useAi, setUseAi] = useState(true); const poll = useRef<ReturnType<typeof setInterval> | null>(null);
  const query = useMemo(() => { const params = new URLSearchParams({ page: String(page), pageSize: "25" }); Object.entries(filters).forEach(([key, value]) => { if (value) params.set(key, String(value)); }); return params.toString(); }, [filters, page]);
  const load = useCallback(async () => { try { const [list, metrics] = await Promise.all([api(`/api/ai/metadata-suggestions?${query}`), api("/api/ai/metadata-suggestions/stats")]); setData(list); setStats(metrics); setSelected(new Set()); } catch (caught) { setError(caught instanceof Error ? caught.message : "Suggestions are unavailable."); } }, [query]);
  useEffect(() => { void load(); }, [load]);
  useEffect(() => () => { if (poll.current) clearInterval(poll.current); }, []);
  function updateFilter(key: string, value: string) { setFilters((current: any) => ({ ...current, [key]: value })); setPage(1); }
  function toggle(id: string) { setSelected((current) => { const next = new Set(current); next.has(id) ? next.delete(id) : next.add(id); return next; }); }
  function selectVisible() { setSelected(new Set(data.suggestions.map((item: any) => item.id))); }
  const selectedRows = data.suggestions.filter((item: any) => selected.has(item.id)); const affected = selectedRows.reduce((sum: number, item: any) => sum + item.affectedTrackCount, 0);
  async function startScan() { if (!window.confirm(`Start a ${useAi ? "deterministic and AI-assisted" : "deterministic-only"} metadata scan? Results are suggestions only.`)) return; setBusy("scan"); setError(""); try { const result = await api("/api/ai/metadata-suggestions/scan", { method: "POST", body: JSON.stringify({ useAi }) }); setJob(result.job); setMessage("Metadata scan queued. No metadata will be changed."); if (poll.current) clearInterval(poll.current); poll.current = setInterval(async () => { try { const current = await api(`/api/ai/metadata-suggestions/jobs/${result.job.id}`); setJob(current.job); if (finalJobs.has(current.job.status)) { if (poll.current) clearInterval(poll.current); poll.current = null; await load(); } } catch { /* Retain the last visible progress state. */ } }, 1500); } catch (caught) { setError(caught instanceof Error ? caught.message : "Scan could not start."); } finally { setBusy(""); } }
  async function cancelScan() { if (!job || !window.confirm("Request cancellation? Already-saved suggestions will be retained.")) return; try { const result = await api(`/api/ai/metadata-suggestions/jobs/${job.id}/cancel`, { method: "POST" }); setJob(result.job); setMessage("Cancellation requested."); } catch (caught) { setError(caught instanceof Error ? caught.message : "Cancellation failed."); } }
  async function bulk(action: string) { if (!selected.size) return; const summary = `${selected.size} suggestion${selected.size === 1 ? "" : "s"} affecting ${affected} track reference${affected === 1 ? "" : "s"}`; if (!window.confirm(`${words(action)} ${summary}? This changes review state only and will not modify metadata.`)) return; setBusy(action); try { const body: any = { action, suggestionIds: Array.from(selected), notes: note || undefined }; if (action === "APPROVE") body.confirmation = "I understand this records a recommendation only and does not modify metadata."; const result = await api("/api/ai/metadata-suggestions/bulk-review", { method: "POST", body: JSON.stringify(body) }); setMessage(`${words(action)} completed for ${result.suggestionCount} suggestions. ${result.approvalMeaning || "No metadata was applied."}`); await load(); } catch (caught) { setError(caught instanceof Error ? caught.message : "Bulk review failed."); } finally { setBusy(""); } }
  async function single(item: any, action: "approve" | "reject" | "ignore") { if (!window.confirm(`${words(action)} this suggestion affecting ${item.affectedTrackCount} tracks? This will not apply metadata.`)) return; setBusy(item.id); try { const body: any = { notes: note || undefined }; if (action === "approve") body.confirmation = "I understand this records a recommendation only and does not modify metadata."; const result = await api(`/api/ai/metadata-suggestions/${item.id}/${action}`, { method: "POST", body: JSON.stringify(body) }); setMessage(result.approvalMeaning || `Suggestion ${action}d; no metadata was applied.`); setDetail(null); await load(); } catch (caught) { setError(caught instanceof Error ? caught.message : "Review failed."); } finally { setBusy(""); } }
  async function ignoreType(item: any) { if (!window.confirm(`Ignore future ${words(item.suggestionType)} suggestions? Existing history remains auditable.`)) return; try { await api("/api/ai/metadata-ignore-rules", { method: "POST", body: JSON.stringify({ scope: "SUGGESTION_TYPE", description: `Ignore future ${words(item.suggestionType)} suggestions`, match: { suggestionType: item.suggestionType } }) }); setMessage("Ignore rule created. Historical suggestions were preserved."); } catch (caught) { setError(caught instanceof Error ? caught.message : "Ignore rule failed."); } }
  async function openDetail(item: any, trackPage = 1) { setBusy(item.id); try { setDetail(await api(`/api/ai/metadata-suggestions/${item.id}?page=${trackPage}&pageSize=50`)); } catch (caught) { setError(caught instanceof Error ? caught.message : "Suggestion detail failed."); } finally { setBusy(""); } }
  async function exportReport(format: "CSV" | "JSON") { setBusy(`export-${format}`); try { const response = await fetch("/api/ai/metadata-suggestions/export", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ format, ...(selected.size ? { suggestionIds: Array.from(selected) } : {}) }) }); if (!response.ok) { const body = await response.json(); throw new Error(body.error?.message || "Export failed."); } const blob = await response.blob(), url = URL.createObjectURL(blob), anchor = document.createElement("a"); anchor.href = url; anchor.download = response.headers.get("content-disposition")?.match(/filename="([^"]+)"/)?.[1] || `metadata-suggestions.${format.toLowerCase()}`; anchor.click(); URL.revokeObjectURL(url); setMessage(`Exported ${selected.size || data.pagination.total} suggestion records as ${format}.`); } catch (caught) { setError(caught instanceof Error ? caught.message : "Export failed."); } finally { setBusy(""); } }
  return <main className={styles.page}>
    <header className={styles.hero}><div><span className={styles.kicker}><Sparkles /> AI · advisory only</span><h1>Metadata Suggestions</h1><p>Review possible cleanup issues without changing Plex, the source library, embedded tags, filenames, or folders.</p></div><div className={styles.scan}><label><input type="checkbox" checked={useAi} onChange={(event) => setUseAi(event.target.checked)} /> AI-assisted review</label><button onClick={() => void startScan()} disabled={!!busy}><Search /> Start metadata scan</button></div></header>
    <div className={styles.safety}><ShieldCheck /><div><strong>Approval is not application</strong><span>An approved item displays as “Approved suggestion — not applied.” Mixarr v2.4.6 has no metadata-write action.</span></div></div>
    {job && <section className={styles.job}><div><strong>{words(job.status)}</strong><span>{job.tracksScanned || 0} tracks scanned · {job.candidateIssuesFound || 0} candidates · {job.suggestionsCreated || 0} suggestions · {job.suggestionsDeduplicated || 0} deduplicated · {job.suggestionsSuppressed || 0} suppressed</span></div>{!finalJobs.has(job.status) && <button onClick={() => void cancelScan()}>Cancel safely</button>}{job.status === "COMPLETED_WITH_WARNINGS" && <span className={styles.warning}><AlertTriangle /> Partial scan: valid results were retained.</span>}</section>}
    <section className={styles.metrics}>{[["High confidence", stats.high], ["Medium confidence", stats.medium], ["Low confidence", stats.low], ["Conflicting sources", stats.conflictingSources], ["Pending review", stats.pending], ["Approved — not applied", stats.approvedNotApplied]].map(([title, value]) => <article key={String(title)}><span>{title}</span><strong>{Number(value || 0).toLocaleString()}</strong></article>)}</section>
    <section className={styles.toolbar}><div className={styles.filters}><Filter /><select aria-label="Confidence" value={filters.confidence} onChange={(event) => updateFilter("confidence", event.target.value)}><option value="">All confidence</option><option value="HIGH">High</option><option value="MEDIUM">Medium</option><option value="LOW">Low</option><option value="CONFLICTING_SOURCES">Conflicting sources</option></select><select aria-label="Status" value={filters.status} onChange={(event) => updateFilter("status", event.target.value)}><option value="">All statuses</option>{["PENDING","APPROVED","REJECTED","IGNORED","SUPERSEDED","CONFLICT","ARCHIVED"].map((value) => <option key={value}>{value}</option>)}</select><input aria-label="Suggestion type" placeholder="Suggestion type" value={filters.type} onChange={(event) => updateFilter("type", event.target.value.toUpperCase().replaceAll(" ", "_"))} /><input aria-label="Metadata field" placeholder="Metadata field" value={filters.field} onChange={(event) => updateFilter("field", event.target.value)} /><select aria-label="Sort" value={filters.sort} onChange={(event) => updateFilter("sort", event.target.value)}>{[["newest","Newest"],["oldest","Oldest"],["highest_confidence","Highest confidence"],["lowest_confidence","Lowest confidence"],["most_affected_tracks","Most affected tracks"],["artist","Artist"],["album","Album"],["suggestion_type","Suggestion type"]].map(([value,text]) => <option value={value} key={value}>{text}</option>)}</select></div>
      <details className={styles.advanced}><summary>Advanced filters</summary><div>{[["artist","Artist"],["album","Album"],["source","Source"],["provider","AI provider"],["detectionMethod","Detection method"]].map(([key, title]) => <label key={key}>{title}<input value={filters[key]} onChange={(event) => updateFilter(key, event.target.value)} /></label>)}{[["plexImpact","Plex impact"],["sourceLibraryImpact","Source-library impact"],["embeddedTagImpact","Embedded-tag impact"],["conflictingSources","Conflicting sources"]].map(([key,title]) => <label key={key}>{title}<select value={filters[key]} onChange={(event) => updateFilter(key,event.target.value)}><option value="">Any</option><option value="true">Yes</option><option value="false">No</option></select></label>)}<label>Created from<input type="date" value={filters.createdFrom} onChange={(event) => updateFilter("createdFrom",event.target.value)} /></label><label>Created to<input type="date" value={filters.createdTo} onChange={(event) => updateFilter("createdTo",event.target.value)} /></label></div></details>
    </section>
    <section className={styles.bulk}><span><b>{selected.size}</b> selected · <b>{affected}</b> affected track references</span><button onClick={selectVisible}>Select all visible</button><button onClick={() => setSelected(new Set())}>Clear selection</button><input aria-label="Review note" placeholder="Optional review note" value={note} onChange={(event) => setNote(event.target.value)} /><button disabled={!selected.size || !!busy} onClick={() => void bulk("APPROVE")}><Check /> Approve selected</button><button disabled={!selected.size || !!busy} onClick={() => void bulk("REJECT")}>Reject selected</button><button disabled={!selected.size || !!busy} onClick={() => void bulk("ARCHIVE")}><Archive /> Archive selected</button><button onClick={() => void exportReport("CSV")}><Download /> CSV</button><button onClick={() => void exportReport("JSON")}><Download /> JSON</button></section>
    <div className={styles.bulk}><span>Archived selections can be restored to pending review.</span><button disabled={!selected.size || !!busy} onClick={() => void bulk("RESTORE")}>Restore archived suggestions</button></div>
    {error && <p className={styles.error} role="alert">{error}</p>}{message && <p className={styles.success} role="status">{message}</p>}
    <section className={styles.results}>{data.suggestions.length ? <div className={styles.tableWrap}><table><caption>{data.pagination.total} metadata suggestions</caption><thead><tr><th><span className={styles.srOnly}>Select</span></th><th>Suggestion</th><th>Existing → suggested</th><th>Confidence</th><th>Status</th><th>Impact</th><th>Created</th><th>Review</th></tr></thead><tbody>{data.suggestions.map((item: any) => <tr key={item.id}><td><input aria-label={`Select ${words(item.suggestionType)}`} type="checkbox" checked={selected.has(item.id)} onChange={() => toggle(item.id)} /></td><td><strong>{words(item.suggestionType)}</strong><small>{item.field} · {words(item.detectionMethod)}</small></td><td><span>{item.existingValue || "Unavailable"}</span><b>→</b><span>{item.suggestedValue || "Review required"}</span><small>{item.reason}</small></td><td><span className={styles.badge} data-level={item.confidenceLevel}>{words(item.confidenceLevel)}</span><small>{Math.round(item.confidenceScore * 100)}% confidence, not certainty</small></td><td><span className={styles.badge} data-status={item.status}>{item.status === "APPROVED" ? "Approved suggestion — not applied" : words(item.status)}</span></td><td><span>{item.affectedTrackCount} tracks</span><small>{item.plexImpact ? "Plex " : ""}{item.sourceLibraryImpact ? "Source library " : ""}{item.embeddedTagImpact ? "Embedded tags" : ""}</small></td><td>{new Date(item.createdAt).toLocaleDateString()}</td><td><div className={styles.rowActions}><button onClick={() => void openDetail(item)}><Eye /> Detail</button><button disabled={!!busy} onClick={() => void single(item,"approve")}>Approve</button><button disabled={!!busy} onClick={() => void single(item,"reject")}>Reject</button><button disabled={!!busy} onClick={() => void single(item,"ignore")}>Ignore</button><button onClick={() => void ignoreType(item)}>Ignore future type</button></div></td></tr>)}</tbody></table></div> : <div className={styles.empty}><Sparkles /><h2>No suggestions match</h2><p>Adjust filters or start a metadata scan. A scan never applies changes.</p></div>}
      <nav className={styles.pagination} aria-label="Suggestion pages"><button disabled={page <= 1} onClick={() => setPage(page - 1)}><ChevronLeft /> Previous</button><span>Page {data.pagination.page} of {Math.max(1,data.pagination.pageCount)}</span><button disabled={page >= data.pagination.pageCount} onClick={() => setPage(page + 1)}>Next <ChevronRight /></button></nav>
    </section>
    {detail && <div className={styles.drawerLayer}><button className={styles.backdrop} aria-label="Close detail" onClick={() => setDetail(null)} /><aside className={styles.drawer} aria-label="Metadata suggestion detail"><header><div><span className={styles.kicker}>Suggested correction</span><h2>{words(detail.suggestion.suggestionType)}</h2></div><button aria-label="Close" onClick={() => setDetail(null)}><X /></button></header><div className={styles.detailBody}><div className={styles.comparison}><div><span>Existing value</span><strong>{detail.suggestion.existingValue || "Unavailable"}</strong></div><div><span>Suggested value</span><strong>{detail.suggestion.suggestedValue || "Review required"}</strong></div></div>{detail.suggestion.status === "APPROVED" && <div className={styles.safety}><ShieldCheck /><b>Approved suggestion — not applied</b></div>}<section><h3>Reason and confidence</h3><p>{detail.suggestion.reason}</p><p>{Math.round(detail.suggestion.confidenceScore * 100)}% · {words(detail.suggestion.confidenceLevel)} · {words(detail.suggestion.detectionMethod)}</p></section><section><h3>Potential future impact</h3><p>Plex: {detail.suggestion.plexImpact ? "Would be affected" : "No indicated impact"} · Source library: {detail.suggestion.sourceLibraryImpact ? "Would be affected" : "No indicated impact"} · Embedded metadata: {detail.suggestion.embeddedTagImpact ? "Would require modification" : "No indicated impact"}</p></section><section><h3>Source evidence</h3>{detail.suggestion.sources.map((source:any) => <div className={styles.source} key={source.id}><b>{words(source.sourceType)}</b><span>{source.available ? source.queried ? JSON.stringify(source.valueJson) : "Available, not queried" : "Unavailable"}</span></div>)}</section><section><h3>Affected tracks ({detail.trackPagination.total})</h3>{detail.suggestion.tracks.map((track:any) => <div className={styles.source} key={track.id}><b>{track.titleSnapshot}</b><span>{track.artistSnapshot || "Unknown artist"} · {track.albumSnapshot || "Unknown album"}</span></div>)}<nav className={styles.pagination}><button disabled={detail.trackPagination.page <= 1} onClick={() => void openDetail(detail.suggestion,detail.trackPagination.page-1)}>Previous</button><span>{detail.trackPagination.page} / {Math.max(1,detail.trackPagination.pageCount)}</span><button disabled={detail.trackPagination.page >= detail.trackPagination.pageCount} onClick={() => void openDetail(detail.suggestion,detail.trackPagination.page+1)}>Next</button></nav></section><section><h3>Review notes and audit history</h3>{detail.suggestion.reviews.length ? detail.suggestion.reviews.map((review:any) => <p key={review.id}><b>{review.reviewer?.username || "Reviewer"}</b> · {words(review.previousStatus)} → {words(review.newStatus)} · {review.notes || "No note"}</p>) : <p>No review decisions yet.</p>}</section></div></aside></div>}
  </main>;
}
