"use client";
import { useCallback, useEffect, useMemo, useRef, useState } from "react";
import { AlertTriangle, Bot, CheckCircle2, Copy, Database, KeyRound, Loader2, Plus, RefreshCw, ShieldCheck, Square, TestTube2, Trash2, XCircle } from "lucide-react";
import { buildProviderPayload, PROVIDER_FIELD_STEPS, validateProviderWizard } from "@/lib/aiProviderWizard";
import styles from "./AiProviderDashboard.module.css";

type AnyRecord = Record<string, any>;
const emptyForm: AnyRecord = { providerType: "ollama", displayName: "", enabled: false, locationClassification: "LOCAL", administratorConfirmedLocal: false, trustedNetwork: false, externalAccessWarning: true, baseUrl: "http://ollama:11434", authenticationType: "NONE", apiKey: "", removeApiKey: false, secretHeadersText: "{}", removeSecretHeaders: false, nonSecretHeadersText: "{}", defaultModel: "", fastModel: "", reasoningModel: "", fallbackProviderId: "", thinkingMode: "disabled", customConfiguration: {}, timeoutOverrideEnabled: false, connectionTimeoutMs: 30000, firstTokenTimeoutMs: 600000, totalRequestTimeoutMs: 1800000, streamingIdleTimeoutMs: 600000, cancellationGraceMs: 5000, retryCount: 1, initialRetryDelayMs: 500, maximumRetryDelayMs: 10000, retryBackoffMultiplier: 2, sslVerification: true, modelDiscoveryEnabled: true, healthCheckEnabled: true, healthCheckIntervalMinutes: 15, monthlyBudget: "", notes: "" };
const providerTimeoutFields = [
  ["connectionTimeoutMs", "Connection"],
  ["firstTokenTimeoutMs", "First token"],
  ["totalRequestTimeoutMs", "Total request"],
  ["streamingIdleTimeoutMs", "Streaming idle"],
] as const;
function readableTimeout(value: unknown) { if (value === null) return "Unlimited"; const ms = Number(value); if (ms % 3_600_000 === 0) return `${ms / 3_600_000} ${ms === 3_600_000 ? "hour" : "hours"}`; if (ms % 60_000 === 0) return `${ms / 60_000} ${ms === 60_000 ? "minute" : "minutes"}`; if (ms % 1_000 === 0) return `${ms / 1_000} ${ms === 1_000 ? "second" : "seconds"}`; return `${ms} ms`; }
class ProviderRequestError extends Error { constructor(message: string, public payload: AnyRecord, public status: number) { super(message); this.name = "ProviderRequestError"; } }
async function jsonFetch(url: string, init?: RequestInit) { const response = await fetch(url, init); const body = response.status === 204 ? null : await response.json().catch(() => ({})); if (!response.ok) throw new ProviderRequestError(body?.message || body?.error?.message || `The provider request failed (${response.status}).`, body || {}, response.status); return body; }
async function createProvider(payload: AnyRecord) { return jsonFetch("/api/ai/providers", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify(payload) }); }
async function updateProvider(id: string, payload: AnyRecord) { return jsonFetch(`/api/ai/providers/${id}`, { method: "PATCH", headers: { "content-type": "application/json" }, body: JSON.stringify(payload) }); }
function statusLabel(provider: AnyRecord) { return provider.health?.healthState || (provider.lastConnectionTestAt ? "UNKNOWN" : "NOT_TESTED"); }
function formatCost(value: unknown) { return typeof value === "number" ? `$${value.toFixed(4)}` : "Cost data unavailable"; }
function auditCost(row: AnyRecord) { const labels: Record<string, string> = { CALCULATED: row.estimatedCost == null ? "Calculated" : formatCost(Number(row.estimatedCost)), PRICING_NOT_CONFIGURED: "Pricing not configured", USAGE_RECORDED_PRICING_NOT_CONFIGURED: "Usage recorded; pricing not configured", USAGE_RECORDED_REQUEST_FAILED: row.actualCost != null ? `Reported ${formatCost(Number(row.actualCost))}` : row.estimatedCost != null ? `Estimated ${formatCost(Number(row.estimatedCost))}` : "Usage recorded; cost unavailable", NO_BILLABLE_USAGE_REPORTED: "No billable usage reported", NOT_SENT: "Not sent", USAGE_UNAVAILABLE: "Usage unavailable", NOT_YET_REPORTED: "Pending" }; if (row.costState && labels[row.costState]) return labels[row.costState]; if (row.providerModelClassification === "LOCAL_FREE") return "Local / no estimated provider cost"; if (row.actualCost != null) return `Reported ${formatCost(Number(row.actualCost))}`; if (row.estimatedCost == null && row.locationClassification === "EXTERNAL") return "Pricing not configured"; return `Estimated ${formatCost(row.estimatedCost == null ? undefined : Number(row.estimatedCost))}`; }
function httpStatus(row: AnyRecord) { return row.httpStatus == null ? "Not received" : row.httpStatus >= 200 && row.httpStatus < 300 ? `Successful (${row.httpStatus})` : `Failed (${row.httpStatus})`; }
function providerStatus(row: AnyRecord) { return row.httpStatus == null ? "Not received" : row.httpStatus >= 200 && row.httpStatus < 300 ? "Response received" : "HTTP error"; }
function extractionStatus(row: AnyRecord) { if (row.testStage === "CONTENT_EXTRACTION") return "Failed"; if (row.errorCategory === "AI_FEATURE_INVALID_STRUCTURED_OUTPUT" || row.schemaValidationResult === "FAILED" || row.status === "COMPLETED") return "Passed"; return "Not reached"; }
function validationStatus(row: AnyRecord) { return row.schemaValidationResult || (row.status === "COMPLETED" && row.structuredOutputResult === "PASSED" ? "PASSED" : "NOT REQUIRED / NOT REACHED"); }
function fallbackStatus(row: AnyRecord) { return row.fallbackReason ? `Attempted after ${row.fallbackReason}` : "Not configured, disabled, or not eligible"; }
function auditTimeoutSummary(row: AnyRecord) { const policy = row.effectiveTimeoutPolicyJson; if (!policy) return "Not recorded"; return `Connect ${readableTimeout(policy.connectionTimeoutMs)} · First ${readableTimeout(policy.firstTokenTimeoutMs)} · Total ${readableTimeout(policy.totalRequestTimeoutMs)} · Idle ${readableTimeout(policy.streamingIdleTimeoutMs)} · ${String(policy.source || "unknown").replaceAll("_", " ")}`; }
function modelCompatibility(model: AnyRecord) { return model?.capabilityMetadata?.compatibility || {}; }
function testEligible(model: AnyRecord, providerType?: string) { if (model.availabilityStatus !== "AVAILABLE") return false; return providerType === "openai" ? modelCompatibility(model).suitableForConnectionTest === true && modelCompatibility(model).supportsResponsesApi === true : true; }

export default function AiProviderDashboard() {
  const [tab, setTab] = useState("overview"); const [settings, setSettings] = useState<AnyRecord | null>(null); const [providers, setProviders] = useState<AnyRecord[]>([]); const [types, setTypes] = useState<AnyRecord[]>([]); const [features, setFeatures] = useState<AnyRecord[]>([]); const [usage, setUsage] = useState<AnyRecord | null>(null); const [audit, setAudit] = useState<AnyRecord[]>([]); const [loading, setLoading] = useState(true); const [message, setMessage] = useState(""); const [error, setError] = useState(""); const [testDetails, setTestDetails] = useState<AnyRecord | null>(null); const [testProvider, setTestProvider] = useState<AnyRecord | null>(null); const [testModels, setTestModels] = useState<AnyRecord[]>([]); const [testModel, setTestModel] = useState(""); const [editing, setEditing] = useState<AnyRecord | null>(null); const [form, setForm] = useState<AnyRecord>(emptyForm); const [models, setModels] = useState<AnyRecord[]>([]); const [busyId, setBusyId] = useState<string | null>(null); const [wizardStep, setWizardStep] = useState(1); const [fieldErrors, setFieldErrors] = useState<Record<string, string>>({}); const [saveError, setSaveError] = useState<string | null>(null); const [isSaving, setIsSaving] = useState(false); const abortRef = useRef<AbortController | null>(null); const savingRef = useRef(false); const editorRef = useRef<HTMLFormElement | null>(null);
  const load = useCallback(async () => { setLoading(true); setError(""); try { const [globalData, providerData, featureData, usageData, auditData] = await Promise.all([jsonFetch("/api/ai/settings"), jsonFetch("/api/ai/providers"), jsonFetch("/api/ai/features"), jsonFetch("/api/ai/usage"), jsonFetch("/api/ai/audit?take=50")]); setSettings(globalData); setProviders(providerData.providers); setTypes(providerData.providerTypes); setFeatures(featureData.features); setUsage(usageData); setAudit(auditData.records); } catch (cause) { setError((cause as Error).message); } finally { setLoading(false); } }, []);
  useEffect(() => { void load(); return () => abortRef.current?.abort(); }, [load]);
  const connected = providers.filter((provider) => statusLabel(provider) === "HEALTHY").length; const degraded = providers.filter((provider) => ["DEGRADED", "UNAVAILABLE", "UNREACHABLE", "UNAUTHORIZED", "MISCONFIGURED"].includes(statusLabel(provider))).length;
  const [deleteTarget, setDeleteTarget] = useState<AnyRecord | null>(null);
  const providerUsage = useMemo(() => new Map((usage?.providers || []).map((row: AnyRecord) => [row.id, row])), [usage]);
  function announce(value: string, isError = false) { setMessage(isError ? "" : value); setError(isError ? value : ""); }
  async function saveGlobal(patch: AnyRecord) { try { const next = await jsonFetch("/api/ai/settings", { method: "PUT", headers: { "content-type": "application/json" }, body: JSON.stringify(patch) }); setSettings((current) => ({ ...current, ...next })); announce("AI settings saved."); } catch (cause) { announce((cause as Error).message, true); } }
  function resetProviderWizard() { setForm({ ...emptyForm }); setModels([]); setWizardStep(1); setFieldErrors({}); setSaveError(null); }
  function closeProviderWizard() { setEditing(null); }
  function startAdd() { resetProviderWizard(); setEditing({ id: null }); setTab("providers"); }
  async function startEdit(provider: AnyRecord) { resetProviderWizard(); setEditing(provider); setForm({ ...emptyForm, ...provider, thinkingMode: provider.customConfiguration?.thinkingMode || "provider_default", apiKey: "", secretHeadersText: "{}", nonSecretHeadersText: JSON.stringify(provider.nonSecretHeaders || {}, null, 2), monthlyBudget: provider.monthlyBudget ?? "" }); try { setModels((await jsonFetch(`/api/ai/providers/${provider.id}/models`)).models); } catch { setModels([]); } }
  function updateForm(field: string, value: unknown) { setForm((current: AnyRecord) => ({ ...current, [field]: value })); setFieldErrors((current) => { if (!current[field]) return current; const next = { ...current }; delete next[field]; return next; }); setSaveError(null); }
  function applyOllamaTimeoutPreset(kind: "slow" | "unlimited") {
    setForm((current: AnyRecord) => ({ ...current, timeoutOverrideEnabled: true, connectionTimeoutMs: 30_000, firstTokenTimeoutMs: kind === "slow" ? 600_000 : null, totalRequestTimeoutMs: kind === "slow" ? 1_800_000 : null, streamingIdleTimeoutMs: kind === "slow" ? 600_000 : null, cancellationGraceMs: 5_000 }));
    setFieldErrors({});
    setSaveError(null);
  }
  function validationMessage(field: string) { return fieldErrors[field] ? <span className={styles.fieldError} id={`provider-${field}-error`}>{fieldErrors[field]}</span> : null; }
  function focusInvalidField(field?: string) { if (!field) return; requestAnimationFrame(() => editorRef.current?.querySelector<HTMLElement>(`[data-field="${field}"]`)?.focus()); }
  function applyRequestFieldErrors(payload: AnyRecord) {
    const errors: Record<string, string> = { ...(payload?.field_errors || payload?.error?.field_errors || {}) };
    for (const issue of payload?.details?.issues || payload?.error?.details?.issues || []) if (issue?.path && issue?.message) { const field = issue.path === "nonSecretHeaders" ? "nonSecretHeadersText" : issue.path === "secretHeaders" ? "secretHeadersText" : issue.path; errors[field] = issue.message; }
    const firstField = Object.keys(errors).sort((left, right) => (PROVIDER_FIELD_STEPS[left] || 4) - (PROVIDER_FIELD_STEPS[right] || 4))[0];
    if (firstField) { setFieldErrors(errors); setWizardStep(PROVIDER_FIELD_STEPS[firstField] || 4); focusInvalidField(firstField); }
  }
  async function refreshProviders() { const providerData = await jsonFetch("/api/ai/providers"); setProviders(providerData.providers || []); setTypes(providerData.providerTypes || []); }
  async function loadTestModels(provider: AnyRecord) { const rows = (await jsonFetch(`/api/ai/providers/${provider.id}/models`)).models || []; setTestModels(rows); const eligible = rows.filter((row: AnyRecord) => testEligible(row, provider.providerType)); const preferred = eligible.find((row: AnyRecord) => row.modelIdentifier === provider.defaultModel) || eligible[0]; setTestModel(preferred?.modelIdentifier || ""); return rows; }
  async function openInferenceTest(provider: AnyRecord) { setTestProvider(provider); setTestDetails(null); setError(""); try { await loadTestModels(provider); } catch (cause) { announce((cause as Error).message, true); setTestModels([]); setTestModel(""); } }
  async function handleSaveProvider() {
    if (isSaving || savingRef.current) return;
    setSaveError(null); setError(""); setMessage("");
    const validation = validateProviderWizard(form);
    if (!validation.valid) { setFieldErrors(validation.fieldErrors); setWizardStep(validation.firstInvalidStep || 1); focusInvalidField(validation.firstInvalidField); return; }

    savingRef.current = true; setIsSaving(true);
    try {
      const payload = buildProviderPayload(form, !!editing?.id);
      const provider = editing?.id ? await updateProvider(editing.id, payload) : await createProvider(payload);
      let refreshWarning = "";
      try { await refreshProviders(); } catch { refreshWarning = " The provider list could not be refreshed automatically; reload the page to see it."; }
      closeProviderWizard(); resetProviderWizard();
      announce(editing?.id ? `Provider "${provider.displayName}" was updated.${refreshWarning}` : `Provider "${provider.displayName}" was saved.${refreshWarning}`);
    } catch (cause) {
      const requestError = cause as ProviderRequestError;
      applyRequestFieldErrors(requestError.payload || {});
      const message = requestError.message || "The provider could not be saved. Try again.";
      setSaveError(message); announce(message, true);
    } finally { savingRef.current = false; setIsSaving(false); }
  }
  async function action(provider: AnyRecord, kind: "verify" | "test" | "refresh" | "duplicate" | "delete") {
    if (busyId) return;
    setBusyId(`${kind}:${provider.id}`);
    if (kind === "test") setTestDetails(null);
    const controller = new AbortController();
    if (kind === "test") abortRef.current = controller;
    try {
      if (kind === "verify") { const result = await jsonFetch(`/api/ai/providers/${provider.id}/verify`, { method: "POST", signal: controller.signal }); announce(`${provider.displayName}: credentials accepted; inference remains ${String(result.inferenceResult || "not tested").replaceAll("_", " ").toLowerCase()}.`); }
      if (kind === "test") {
        try { setTestDetails(await jsonFetch(`/api/ai/providers/${provider.id}/test?model=${encodeURIComponent(testModel)}`, { method: "GET", signal: controller.signal })); }
        catch (preflightCause) { if ((preflightCause as Error).name === "AbortError") throw preflightCause; setTestDetails((preflightCause as ProviderRequestError).payload); }
        await new Promise<void>((resolve) => requestAnimationFrame(() => resolve()));
        const result = await jsonFetch(`/api/ai/providers/${provider.id}/test`, { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ model: testModel || undefined }), signal: controller.signal });
        setTestDetails(result); announce(`${provider.displayName}: ${result.message} · ${result.model} · ${result.endpointMode || result.detectedApiType} (${result.latencyMs} ms)`);
      }
      if (kind === "refresh") { const result = await jsonFetch(`/api/ai/providers/${provider.id}/models/refresh`, { method: "POST", signal: controller.signal }); announce(`${result.models.length} models discovered for ${provider.displayName}; inference health was not changed.`); if (testProvider?.id === provider.id) await loadTestModels(provider); }
      if (kind === "duplicate") { await jsonFetch("/api/ai/providers", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ duplicateProviderId: provider.id }) }); announce("Provider duplicated without secrets."); }
      if (kind === "delete") { const result = await jsonFetch(`/api/ai/providers/${provider.id}`, { method: "DELETE" }); const warningText = (result.warnings || []).map((warning: AnyRecord) => warning.message).join(" "); announce(`${provider.displayName} was deleted. Historical audit and usage records were retained.${warningText ? ` ${warningText}` : ""}`); }
      await load();
      if (kind === "delete") setDeleteTarget(null);
    } catch (cause) { if ((cause as Error).name !== "AbortError") { const requestError = cause as ProviderRequestError; if (kind === "test") setTestDetails(requestError.payload); announce(requestError.message, true); } else announce("Inference test cancelled."); }
    finally { setBusyId(null); abortRef.current = null; }
  }
  async function toggleProvider(provider: AnyRecord) { try { await jsonFetch(`/api/ai/providers/${provider.id}`, { method: "PATCH", headers: { "content-type": "application/json" }, body: JSON.stringify({ enabled: !provider.enabled }) }); await load(); announce(`${provider.displayName} ${provider.enabled ? "disabled" : "enabled"}.`); } catch (cause) { announce((cause as Error).message, true); } }
  if (loading && !settings) return <div className={styles.loading}><Loader2 className={styles.spin} /> Loading AI provider settings…</div>;
  return <main className={styles.wrapper}>
    <header className={styles.header}><div><h1><Bot size={30} /> AI Provider Foundation</h1><p>Secure, provider-neutral infrastructure for future advisory AI features. No AI output can mutate playlists.</p></div><span className={settings?.enabled ? styles.enabledBadge : styles.disabledBadge}>{settings?.enabled ? "AI enabled" : "AI disabled"}</span></header>
    {!settings?.encryptionConfigured && <div className={styles.warning} role="alert"><KeyRound size={20} /><div><strong>Credential encryption setup required</strong><p>Set <code>AI_CREDENTIAL_ENCRYPTION_KEY</code> (or the existing <code>MIXARR_SECRET_KEY</code>) before saving secret-based providers. Local providers without secrets remain available.</p></div></div>}
    <div className={styles.live} aria-live="polite">{error || message}</div>{error && <div className={styles.error}><XCircle size={18} />{error}</div>}{message && <div className={styles.success}><CheckCircle2 size={18} />{message}</div>}
    {testDetails?.code === "AI_PROVIDER_TRUNCATED_BEFORE_FINAL" && <section className={styles.testResult} aria-label="Inference test result"><strong>The provider stopped before producing a final answer</strong><p>The provider connection succeeded, but its native output handling ended the response. DeepSeek thinking is disabled for provider tests.</p><span>Decision: {testDetails.code}</span><span>HTTP status: {testDetails.http_status ?? "Not reported"}</span><span>Finish reason: {testDetails.finish_reason || "Not reported"}</span><span>Thinking mode active: {testDetails.thinking_mode_requested === "enabled" ? "yes" : "no"}</span><span>Reasoning output detected: {testDetails.has_reasoning_content ? "yes" : "no"}</span><span>Provider request ID: <code>{testDetails.provider_request_id || "Not reported"}</code></span><span>Correlation ID: <code>{testDetails.correlation_id || "Not reported"}</code></span></section>}
    {testDetails && testDetails.code !== "AI_PROVIDER_TRUNCATED_BEFORE_FINAL" && <section className={styles.testResult} aria-label="Inference test result"><strong>{testDetails.stage === "governance_preflight" ? "Effective policy resolved — ready to send one provider request" : testDetails.success ? "Inference test passed" : testDetails.stage === "governance" ? "Governance rejected the test" : testDetails.stage === "model" ? "Model validation failed" : "Inference test failed"}</strong><span>Decision: {testDetails.code || (testDetails.success ? "ALLOWED" : "UNKNOWN")}</span><span>Stage: {String(testDetails.stage || "complete").replaceAll("_", " ")}</span><span>Provider / model: {testDetails.provider || testProvider?.displayName || "Unknown"} · {testDetails.model || testModel || "Not selected"}</span><span>Endpoint: {testDetails.endpointMode || testDetails.endpoint_mode || testDetails.detectedApiType || "Provider default"}</span><span>Classification: {testDetails.classification || "Unknown"}</span>{testDetails.authenticationResult && <span>Authentication: {String(testDetails.authenticationResult).replaceAll("_", " ")}</span>}{testDetails.discoveryResult && <span>Discovery: {String(testDetails.discoveryResult).replaceAll("_", " ")}</span>}{testDetails.inferenceResult && <span>Inference: {String(testDetails.inferenceResult).replaceAll("_", " ")}</span>}{testDetails.http_status && <span>HTTP status: {testDetails.http_status}</span>}{testDetails.finish_reason && <span>Finish reason: {testDetails.finish_reason}</span>}{testDetails.retry_attempted != null && <span>Retry attempted: {testDetails.retry_attempted ? "yes" : "no"}</span>}{testDetails.sanitized_reason && <span>Reason: {testDetails.sanitized_reason}</span>}{testDetails.effectivePolicy && <span>Paid providers: {testDetails.effectivePolicy.paidProviderAllowed ? "permitted" : "denied"} ({String(testDetails.effectivePolicy.resolvedPolicySource || "unknown").replaceAll("_", " ").toLowerCase()}) · Background: {testDetails.effectivePolicy.backgroundRequestAllowed ? "permitted" : "denied"}</span>}{(testDetails.classification_reason || testDetails.classificationReason) && <span>{testDetails.classification_reason || testDetails.classificationReason}</span>}{(testDetails.provider_request_id || testDetails.providerRequestId) && <span>Provider request ID: <code>{testDetails.provider_request_id || testDetails.providerRequestId}</code></span>}{testDetails.correlation_id && <span>Correlation ID: <code>{testDetails.correlation_id}</code></span>}</section>}
    {deleteTarget && <div className={styles.modalBackdrop} role="presentation"><section className={styles.confirmDialog} role="alertdialog" aria-modal="true" aria-labelledby="delete-provider-title" aria-describedby="delete-provider-description"><h2 id="delete-provider-title">Delete {deleteTarget.displayName}?</h2><p id="delete-provider-description">Historical audit, usage, cost, and budget reservation records will be retained. The provider will be disabled immediately and its stored credentials will be removed.</p><div className={styles.wizardActions}><button onClick={() => setDeleteTarget(null)} disabled={busyId === `delete:${deleteTarget.id}`}>Cancel</button><button className={styles.danger} onClick={() => void action(deleteTarget, "delete")} disabled={busyId === `delete:${deleteTarget.id}`}>{busyId === `delete:${deleteTarget.id}` ? <><Loader2 className={styles.spin} size={15}/> Deleting…</> : "Delete provider"}</button></div></section></div>}
    <nav className={styles.tabs} aria-label="AI settings sections">{["overview", "providers", "features", "audit"].map((item) => <button key={item} aria-current={tab === item ? "page" : undefined} onClick={() => setTab(item)}>{item[0].toUpperCase() + item.slice(1)}</button>)}</nav>

    {tab === "overview" && <>
      <section className={styles.stats} aria-label="AI overview"><article><span>Configured providers</span><strong>{providers.length}</strong></article><article><span>Connected</span><strong>{connected}</strong></article><article><span>Degraded</span><strong>{degraded}</strong></article><article><span>Enabled features</span><strong>{features.filter((feature) => feature.enabled).length}</strong></article><article><span>Requests this month</span><strong>{usage?.summary?.requestsThisMonth || 0}</strong></article><article><span>Average latency</span><strong>{usage?.summary?.averageLatencyMs || 0} ms</strong></article><article><span>Estimated usage</span><strong>{formatCost(usage?.summary?.estimatedCost)}</strong></article></section>
      <section className={`glass-panel ${styles.panel}`}><h2><ShieldCheck size={20} /> Global controls</h2><label className={styles.toggle}><input type="checkbox" checked={settings?.enabled === true} onChange={(event) => void saveGlobal({ enabled: event.target.checked })}/><span>Enable AI infrastructure</span></label><p className={styles.help}>Disabled by default. Enabling the foundation does not enable any future feature or send a request. Global phase timeouts are configured under AI Governance → Timeouts &amp; Retries.</p><div className={styles.grid}><label>Default provider<select value={settings?.defaultProviderId || ""} onChange={(event) => void saveGlobal({ defaultProviderId: event.target.value || null })}><option value="">No default provider</option>{providers.map((provider) => <option key={provider.id} value={provider.id}>{provider.displayName}</option>)}</select></label><label>Maximum response bytes<input type="number" value={settings?.maximumServerResponseBytes || 1048576} min={1024} max={20000000} onChange={(event) => setSettings({ ...settings, maximumServerResponseBytes: Number(event.target.value) })} onBlur={() => void saveGlobal({ maximumServerResponseBytes: settings?.maximumServerResponseBytes })}/></label><label>Audit retention (days)<input type="number" value={settings?.auditRetentionDays || 90} min={1} max={3650} onChange={(event) => setSettings({ ...settings, auditRetentionDays: Number(event.target.value) })} onBlur={() => void saveGlobal({ auditRetentionDays: settings?.auditRetentionDays })}/></label></div><label className={styles.toggle}><input type="checkbox" checked={!!settings?.privacyWarningAcknowledgedAt} onChange={(event) => void saveGlobal({ privacyWarningAcknowledged: event.target.checked })}/><span>I acknowledge that remote providers process data outside my local network.</span></label></section>
    </>}

    {tab === "providers" && <>
      <div className={styles.sectionHeader}><div><h2>AI Providers</h2><p>Multiple configurations of every provider type are supported.</p></div><button className={styles.primary} onClick={startAdd}><Plus size={16}/> Add provider</button></div>
      {!providers.length ? <div className={styles.empty}><Bot size={36}/><h3>No AI providers configured</h3><p>Mixarr works normally without one. Add a local or remote provider when you are ready.</p><button className={styles.primary} onClick={startAdd}>Add your first provider</button></div> : <div className={styles.cards}>{providers.map((provider) => {
        const used = providerUsage.get(provider.id) as AnyRecord | undefined; const status = statusLabel(provider);
        return <article className={styles.card} key={provider.id}>
          <div className={styles.cardTop}><div><span className={styles.kind}>{types.find((item) => item.type === provider.providerType)?.displayName || provider.providerType}</span><h3>{provider.displayName}</h3></div><span className={styles.status} data-status={status}>{status.replaceAll("_", " ")}</span></div>
          <dl><div><dt>Mode</dt><dd>{provider.locationClassification}</dd></div><div><dt>Authentication</dt><dd>{provider.health?.authenticationState || "NOT TESTED"}</dd></div><div><dt>Discovery</dt><dd>{provider.health?.discoveryState || "NOT TESTED"}</dd></div><div><dt>Inference</dt><dd>{provider.health?.inferenceState || "NOT TESTED"}</dd></div><div><dt>Default model</dt><dd>{provider.defaultModel || "Not selected"}</dd></div><div><dt>Fast / reasoning</dt><dd>{provider.fastModel || "—"} / {provider.reasoningModel || "—"}</dd></div><div><dt>Models</dt><dd>{provider.modelCount || 0}</dd></div><div><dt>Last inference success</dt><dd>{provider.health?.lastSuccessfulInferenceAt ? new Date(provider.health.lastSuccessfulInferenceAt).toLocaleString() : "Never"}</dd></div><div><dt>Requests this month</dt><dd>{used?.requests || 0}</dd></div><div><dt>Cost</dt><dd>{used?.costLabel || formatCost(used?.estimatedCost)}</dd></div><div><dt>Budget</dt><dd>{provider.monthlyBudget == null ? "No budget" : `${formatCost(used?.estimatedCost || 0)} of $${Number(provider.monthlyBudget).toFixed(2)}`}</dd></div></dl>
          {provider.timeoutPolicyRecommendation && <div className={styles.warning}><AlertTriangle size={16}/><p>{provider.timeoutPolicyRecommendation}</p></div>}
          <div className={styles.capabilities}>{Object.entries(types.find((item) => item.type === provider.providerType)?.knownCapabilities || {}).slice(0, 6).map(([key, value]) => <span key={key} title={`${key}: ${value}`}>{key.replaceAll("_", " ")} · {String(value).toLowerCase()}</span>)}</div>
          <div className={styles.actions}><button onClick={() => void toggleProvider(provider)} disabled={!!busyId}>{provider.enabled ? "Disable" : "Enable"}</button><button onClick={() => void startEdit(provider)} disabled={!!busyId}>Edit</button><button onClick={() => void action(provider, "verify")} disabled={!!busyId}><KeyRound size={14}/> Verify credentials</button><button onClick={() => void action(provider, "refresh")} disabled={!!busyId || !provider.modelDiscoveryEnabled}><RefreshCw size={14}/> Discover models</button><button onClick={() => void openInferenceTest(provider)} disabled={!!busyId}><TestTube2 size={14}/> Test inference</button><button aria-label={`Duplicate ${provider.displayName} without secrets`} disabled={!!busyId} onClick={() => void action(provider, "duplicate")}><Copy size={14}/></button><button aria-label={`Delete ${provider.displayName}`} className={styles.danger} disabled={!!busyId} onClick={() => setDeleteTarget(provider)}><Trash2 size={14}/></button>{busyId === `test:${provider.id}` && <button onClick={() => abortRef.current?.abort()}><Square size={13}/> Cancel test</button>}</div>
        </article>;
      })}</div>}
      {testProvider && <section className={`glass-panel ${styles.testPanel}`} aria-label="Test inference">
        <div className={styles.editorTitle}><div><h2>Test inference</h2><p>Testing connection with {testProvider.displayName} · {testModel || "no compatible model"} · {testProvider.providerType === "openai" ? "Responses API" : "provider default endpoint"}</p></div><button onClick={() => { setTestProvider(null); setTestDetails(null); }} aria-label="Close inference test">×</button></div>
        <div className={styles.grid}><label>Test model<select value={testModel} onChange={(event) => setTestModel(event.target.value)}><option value="">No compatible model selected</option>{testModels.map((model) => <option key={model.id} value={model.modelIdentifier} disabled={!testEligible(model, testProvider.providerType)}>{model.displayName}{testEligible(model, testProvider.providerType) ? "" : " — incompatible"}</option>)}</select></label><div><span className={styles.compatibilityBadge} data-compatible={!!testModel}>{testModel ? "Compatible" : "No eligible model"}</span><p className={styles.help}>Current default: {testProvider.defaultModel || "Not configured"}. Running a test never changes it.</p></div></div>
        <div className={styles.actions}><button onClick={() => void action(testProvider, "refresh")} disabled={!!busyId}><RefreshCw size={14}/> Refresh models</button><button className={styles.primary} onClick={() => void action(testProvider, "test")} disabled={!!busyId || !testModel}>{busyId === `test:${testProvider.id}` ? <><Loader2 className={styles.spin} size={14}/> Testing inference…</> : <><TestTube2 size={14}/> Run minimal test</>}</button></div>
        {!testModel && <div className={styles.warning}><AlertTriangle size={18}/><p>No compatible text-generation models were found. Model discovery may have succeeded, but Mixarr could not identify a model suitable for an inference test.</p></div>}
      </section>}
      {editing && <form ref={editorRef} className={`glass-panel ${styles.editor}`} aria-labelledby="provider-editor" onSubmit={(event) => { event.preventDefault(); void handleSaveProvider(); }} noValidate><div className={styles.editorTitle}><div><h2 id="provider-editor">{editing.id ? "Edit provider" : "Add provider"}</h2><p>Step {wizardStep} of 4 · Existing secrets are never returned to this form.</p></div><button type="button" onClick={closeProviderWizard} aria-label="Close provider editor">×</button></div><ol className={styles.steps}><li data-active={wizardStep === 1}>Provider</li><li data-active={wizardStep === 2}>Authentication</li><li data-active={wizardStep === 3}>Models &amp; reliability</li><li data-active={wizardStep === 4}>Privacy &amp; review</li></ol>
        {wizardStep === 1 && <div className={styles.grid}>
          <label>Provider type<select data-field="providerType" aria-invalid={!!fieldErrors.providerType} aria-describedby={fieldErrors.providerType ? "provider-providerType-error" : undefined} disabled={!!editing.id} value={form.providerType} onChange={(event) => { const meta = types.find((item) => item.type === event.target.value); setForm((current: AnyRecord) => ({ ...current, providerType: event.target.value, baseUrl: meta?.defaultBaseUrl || "", authenticationType: meta?.defaultAuthenticationType || "NONE", locationClassification: meta?.defaultLocation || "UNKNOWN", thinkingMode: event.target.value === "deepseek" ? "disabled" : current.thinkingMode, administratorConfirmedLocal: false, trustedNetwork: false })); setFieldErrors({}); setSaveError(null); }}><option value="">Choose a provider</option>{types.map((item) => <option key={item.type} value={item.type}>{item.displayName}{item.available ? "" : " — unavailable"}</option>)}</select>{validationMessage("providerType")}</label>
          <label>Display name<input data-field="displayName" aria-invalid={!!fieldErrors.displayName} aria-describedby={fieldErrors.displayName ? "provider-displayName-error" : undefined} value={form.displayName} maxLength={120} onChange={(event) => updateForm("displayName", event.target.value)}/>{validationMessage("displayName")}</label>
          <label>Location classification<select data-field="locationClassification" aria-invalid={!!fieldErrors.locationClassification} aria-describedby={fieldErrors.locationClassification ? "provider-locationClassification-error" : undefined} value={form.locationClassification} onChange={(event) => { updateForm("locationClassification", event.target.value); if (event.target.value !== "LOCAL") setForm((current: AnyRecord) => ({ ...current, administratorConfirmedLocal: false, trustedNetwork: false })); }}><option>LOCAL</option><option>REMOTE</option><option>USER_CLASSIFIED</option><option>UNKNOWN</option></select>{validationMessage("locationClassification")}</label>
          <label>Base URL<input data-field="baseUrl" list={form.providerType === "ollama" ? "ollama-common-addresses" : undefined} aria-invalid={!!fieldErrors.baseUrl} aria-describedby={fieldErrors.baseUrl ? "provider-baseUrl-error" : form.providerType === "ollama" ? "ollama-address-help" : undefined} value={form.baseUrl || ""} placeholder="https://provider.example/v1" onChange={(event) => updateForm("baseUrl", event.target.value)}/>{form.providerType === "ollama" && <><datalist id="ollama-common-addresses"><option value="http://ollama:11434"/><option value="http://host.docker.internal:11434"/><option value="http://127.0.0.1:11434"/></datalist><small id="ollama-address-help">Same Compose project: ollama. Docker Desktop host: host.docker.internal. Use 127.0.0.1 only when Mixarr is not in a container or Ollama shares its network namespace; container localhost is not the Docker host.</small></>}{validationMessage("baseUrl")}</label>
          {form.providerType === "chatgpt_subscription" && <div className={styles.warning}><AlertTriangle size={18}/><p>No official supported integration is available. Mixarr never uses browser cookies, profiles, unofficial session tokens, or ChatGPT web automation. Configure OpenAI API instead.</p></div>}
        </div>}
        {wizardStep === 2 && <div className={styles.grid}>
          <label>Authentication type<select data-field="authenticationType" aria-invalid={!!fieldErrors.authenticationType} value={form.authenticationType} onChange={(event) => updateForm("authenticationType", event.target.value)}>{["NONE","BEARER","API_KEY_HEADER","BASIC","PROVIDER_SPECIFIC","CUSTOM_SECRET_HEADERS"].map((item) => <option key={item}>{item}</option>)}</select>{validationMessage("authenticationType")}</label>
          <label>API key<span className={styles.secretHint}>{editing?.apiKeyConfigured ? "API key configured · leave blank to keep" : "Stored with authenticated encryption"}</span><input data-field="apiKey" aria-invalid={!!fieldErrors.apiKey} type="password" autoComplete="new-password" disabled={form.removeApiKey} value={form.apiKey} placeholder={editing?.apiKeyConfigured ? "Replace API key" : "Enter API key"} onChange={(event) => updateForm("apiKey", event.target.value)}/>{validationMessage("apiKey")}{editing?.apiKeyConfigured && <span className={styles.toggle}><input type="checkbox" checked={form.removeApiKey} onChange={(event) => setForm({ ...form, removeApiKey: event.target.checked, apiKey: "" })}/>Remove API key when saved</span>}</label>
          <label className={styles.full}>Non-secret headers (JSON)<textarea data-field="nonSecretHeadersText" aria-invalid={!!fieldErrors.nonSecretHeadersText} aria-describedby={fieldErrors.nonSecretHeadersText ? "provider-nonSecretHeadersText-error" : undefined} value={form.nonSecretHeadersText} onChange={(event) => updateForm("nonSecretHeadersText", event.target.value)}/>{validationMessage("nonSecretHeadersText")}</label>
          <label className={styles.full}>Replacement secret headers (JSON)<span className={styles.secretHint}>{editing?.secretHeadersConfigured ? "Secret headers configured · leave {} to keep" : "Values are never returned"}</span><textarea data-field="secretHeadersText" aria-invalid={!!fieldErrors.secretHeadersText} aria-describedby={fieldErrors.secretHeadersText ? "provider-secretHeadersText-error" : undefined} disabled={form.removeSecretHeaders} value={form.secretHeadersText} onChange={(event) => updateForm("secretHeadersText", event.target.value)}/>{validationMessage("secretHeadersText")}{editing?.secretHeadersConfigured && <span className={styles.toggle}><input type="checkbox" checked={form.removeSecretHeaders} onChange={(event) => setForm({ ...form, removeSecretHeaders: event.target.checked, secretHeadersText: "{}" })}/>Remove secret headers when saved</span>}</label>
        </div>}
        {wizardStep === 3 && <div className={styles.grid}>
          <label>Default model<input data-field="defaultModel" list="ai-models" value={form.defaultModel || ""} onChange={(event) => updateForm("defaultModel", event.target.value)}/>{validationMessage("defaultModel")}</label>
          <label>Fast model<input list="ai-models" value={form.fastModel || ""} onChange={(event) => updateForm("fastModel", event.target.value)}/></label>
          <label>Reasoning model<input list="ai-models" value={form.reasoningModel || ""} onChange={(event) => updateForm("reasoningModel", event.target.value)}/></label>
          <datalist id="ai-models">{models.filter((model) => form.providerType !== "openai" || modelCompatibility(model).selectableAsDefault === true).map((model) => <option key={model.id} value={model.modelIdentifier}>{model.displayName}</option>)}</datalist>
          {form.providerType === "deepseek" && /^(deepseek-v4-pro|deepseek-v4-flash)$/i.test(String(form.defaultModel || "")) && <label>Thinking mode<select data-field="thinkingMode" value={form.thinkingMode} onChange={(event) => updateForm("thinkingMode", event.target.value)}><option value="disabled">Off — faster, cheaper, recommended for structured Mixarr requests</option><option value="enabled">On — allows additional provider reasoning</option><option value="provider_default">Provider default</option></select><small>Thinking tokens consume the output allowance and may increase latency and cost. Provider tests and structured requests keep thinking off unless a feature explicitly opts in.</small>{validationMessage("thinkingMode")}</label>}
          <label>Explicit fallback provider<select data-field="fallbackProviderId" aria-invalid={!!fieldErrors.fallbackProviderId} value={form.fallbackProviderId || ""} onChange={(event) => updateForm("fallbackProviderId", event.target.value)}><option value="">No automatic fallback</option>{providers.filter((provider) => provider.id !== editing?.id).map((provider) => <option key={provider.id} value={provider.id}>{provider.displayName} · {provider.locationClassification}</option>)}</select>{validationMessage("fallbackProviderId")}</label>
          <div className={styles.full}><label>Timeout policy<select data-field="timeoutOverrideEnabled" value={form.timeoutOverrideEnabled ? "OVERRIDE" : "GLOBAL"} onChange={(event) => updateForm("timeoutOverrideEnabled", event.target.value === "OVERRIDE")}><option value="GLOBAL">Use global AI timeout policy</option><option value="OVERRIDE">Override timeout policy for this provider</option></select><small>The provider-specific policy is used when enabled; otherwise the global AI timeout policy applies.</small></label>
          {form.providerType === "ollama" && <div className={styles.actions}><button type="button" onClick={() => applyOllamaTimeoutPreset("slow")}>Local model — slow initial load</button><button type="button" onClick={() => applyOllamaTimeoutPreset("unlimited")}>Local model — no request timeout</button></div>}
          {form.timeoutOverrideEnabled && <div className={styles.grid}>{providerTimeoutFields.map(([key, label]) => { const unlimited = form[key] === null; return <label key={key}>{label}<select value={unlimited ? "UNLIMITED" : "LIMITED"} onChange={(event) => updateForm(key, event.target.value === "UNLIMITED" ? null : 30_000)}><option value="LIMITED">Limited</option><option value="UNLIMITED">Unlimited</option></select>{!unlimited && <input data-field={key} aria-invalid={!!fieldErrors[key]} type="number" min="1" max="2147483647" step="1" value={form[key]} onChange={(event) => updateForm(key, event.target.value === "" ? "" : Number(event.target.value))}/>}<small>{unlimited ? "Unlimited — timeout disabled." : readableTimeout(form[key])}</small>{validationMessage(key)}</label>; })}<label>Cancellation grace<input data-field="cancellationGraceMs" aria-invalid={!!fieldErrors.cancellationGraceMs} type="number" min="100" max="60000" step="1" value={form.cancellationGraceMs} onChange={(event) => updateForm("cancellationGraceMs", Number(event.target.value))}/><small>{readableTimeout(form.cancellationGraceMs)} · remains finite for cleanup.</small>{validationMessage("cancellationGraceMs")}</label></div>}
          {editing?.effectiveTimeoutPolicy && <div className={styles.testResult}><strong>Effective timeout policy for {form.displayName || editing.displayName}</strong>{providerTimeoutFields.map(([key, label]) => <span key={key}>{label}: {readableTimeout(form.timeoutOverrideEnabled ? form[key] : editing.effectiveTimeoutPolicy[key])}</span>)}<span>Cancellation grace: {readableTimeout(form.timeoutOverrideEnabled ? form.cancellationGraceMs : editing.effectiveTimeoutPolicy.cancellationGraceMs)}</span><span>Source: {form.timeoutOverrideEnabled ? "Provider override" : "Global AI timeout policy"}</span></div>}</div>
          <label>Retry count<input data-field="retryCount" aria-invalid={!!fieldErrors.retryCount} type="number" min={0} max={1} value={form.retryCount} onChange={(event) => updateForm("retryCount", Number(event.target.value))}/>{validationMessage("retryCount")}</label>
          <label>Monthly budget (optional)<input data-field="monthlyBudget" aria-invalid={!!fieldErrors.monthlyBudget} type="number" min={0} step="0.01" value={form.monthlyBudget} onChange={(event) => updateForm("monthlyBudget", event.target.value)}/>{validationMessage("monthlyBudget")}</label>
          <label className={styles.toggle}><input type="checkbox" checked={form.modelDiscoveryEnabled} onChange={(event) => updateForm("modelDiscoveryEnabled", event.target.checked)}/>Model discovery</label>
          <label className={styles.toggle}><input type="checkbox" checked={form.healthCheckEnabled} onChange={(event) => updateForm("healthCheckEnabled", event.target.checked)}/>Background health checks</label>
        </div>}
        {wizardStep === 4 && <div className={styles.review}>
          <div className={styles.warning}><AlertTriangle size={18}/><p>{form.locationClassification === "REMOTE" ? "Information sent to this provider may leave your local network. Mixarr limits data to fields required by an enabled feature, but the provider processes it under its own terms." : "A provider is eligible for Local Only only after an administrator confirms the endpoint and trusted-network classification. A private-looking hostname is not trusted automatically."}</p></div>
          {form.locationClassification === "LOCAL" && <>
            <label className={styles.toggle}><input data-field="administratorConfirmedLocal" aria-invalid={!!fieldErrors.administratorConfirmedLocal} aria-describedby={fieldErrors.administratorConfirmedLocal ? "provider-administratorConfirmedLocal-error" : undefined} type="checkbox" checked={!!form.administratorConfirmedLocal} onChange={(event) => updateForm("administratorConfirmedLocal", event.target.checked)}/>I inspected and confirm this is a local endpoint{validationMessage("administratorConfirmedLocal")}</label>
            <label className={styles.toggle}><input data-field="trustedNetwork" aria-invalid={!!fieldErrors.trustedNetwork} aria-describedby={fieldErrors.trustedNetwork ? "provider-trustedNetwork-error" : undefined} type="checkbox" checked={!!form.trustedNetwork} onChange={(event) => updateForm("trustedNetwork", event.target.checked)}/>Endpoint is on an administrator-trusted network{validationMessage("trustedNetwork")}</label>
          </>}
          <label className={styles.toggle}><input type="checkbox" checked={form.enabled} disabled={form.providerType === "chatgpt_subscription"} onChange={(event) => updateForm("enabled", event.target.checked)}/>Enable provider after saving</label>
          <label>Safe notes<textarea data-field="notes" aria-invalid={!!fieldErrors.notes} value={form.notes || ""} maxLength={2000} onChange={(event) => updateForm("notes", event.target.value)}/>{validationMessage("notes")}</label>
          <p className={styles.boundary}>Saving a provider does not enable global AI, any future feature, or playlist mutations. You may save without testing.</p>
        </div>}
        {saveError && <div className={styles.saveError} role="alert"><XCircle size={18}/><span>{saveError}</span></div>}
        <div className={styles.wizardActions}><button type="button" disabled={wizardStep === 1 || isSaving} onClick={() => setWizardStep((step) => step - 1)}>Back</button>{wizardStep < 4 ? <button type="button" className={styles.primary} disabled={isSaving} onClick={() => setWizardStep((step) => step + 1)}>Continue</button> : <button type="submit" className={styles.primary} disabled={isSaving}>{isSaving && <Loader2 className={styles.spin} size={15}/>} {isSaving ? "Saving provider…" : "Save provider"}</button>}</div></form>}
    </>}

    {tab === "features" && <section className={styles.featureList}><div className={styles.sectionHeader}><div><h2>Per-feature controls</h2><p>v2.4.1 adds governance only. Future advisory features remain unavailable and off.</p></div></div>{features.map((feature) => <article className="glass-panel" key={feature.key}><div><h3>{feature.name}</h3><p>{feature.description}</p><small>{feature.explanation}</small></div><div><span>{feature.requiredCapabilities.join(", ")}</span><label className={styles.toggle}><input type="checkbox" checked={feature.enabled} disabled={!feature.available}/>Enabled</label></div></article>)}</section>}

    {tab === "audit" && <section><div className={styles.sectionHeader}><div><h2>Safe AI request audit</h2><p>Prompts, responses, credentials, Plex tokens, and raw provider errors are never shown here.</p></div><button onClick={() => void load()}><RefreshCw size={15}/> Refresh</button></div>{!audit.length ? <div className={styles.empty}><Database size={34}/><h3>No AI requests recorded</h3><p>This is expected while the foundation and all AI features are disabled.</p></div> : <div className={styles.tableWrap}><table><thead><tr><th>Time</th><th>Feature / user</th><th>Provider / model</th><th>HTTP / provider</th><th>Extraction / validation</th><th>Status / reason</th><th>Duration</th><th>Timeout policy used</th><th>Provider usage</th><th>Cost</th><th>Fallback</th><th>Request IDs</th></tr></thead><tbody>{audit.map((row) => <tr key={row.id}><td>{new Date(row.createdAt).toLocaleString()}</td><td>{row.featureKey}<br/><small>{row.userId || "—"}</small></td><td>{row.providerDisplayName || row.providerType || "—"}<br/><small>{row.model || "—"}</small></td><td>{httpStatus(row)}<br/><small>{providerStatus(row)}</small></td><td>{extractionStatus(row)}<br/><small>{validationStatus(row)}</small></td><td>{row.status}<br/><small>{row.sanitizedErrorCode || row.blockReason || "—"}</small></td><td>{row.providerDurationMs == null && row.latencyMs == null ? "—" : `${row.providerDurationMs ?? row.latencyMs} ms`}</td><td>{auditTimeoutSummary(row)}</td><td>{row.inputTokenCount ?? "—"} / {row.outputTokenCount ?? "—"}<br/><small>{row.usageSource || "UNAVAILABLE"}</small></td><td>{auditCost(row)}</td><td>{fallbackStatus(row)}</td><td><code>{row.correlationId || "—"}</code>{row.providerRequestId && <><br/><small><code>{row.providerRequestId}</code></small></>}</td></tr>)}</tbody></table></div>}</section>}
    {tab === "audit" && audit.some((row) => row.finishReason === "length" || String(row.errorCategory || "").startsWith("AI_PROVIDER_TRUNCATED")) && <section className={styles.featureList}><div className={styles.sectionHeader}><div><h2>Provider-native truncation details</h2><p>A successful HTTP response can still contain incomplete model output and incur usage.</p></div></div>{audit.filter((row) => row.finishReason === "length" || String(row.errorCategory || "").startsWith("AI_PROVIDER_TRUNCATED")).map((row) => <article className="glass-panel" key={`truncation-${row.id}`}><div><h3>{row.providerDisplayName || row.providerType} · {row.model}</h3><p>Provider request: {row.httpStatus === 200 ? "Successful" : row.httpStatus ? `HTTP ${row.httpStatus}` : "Status unavailable"} · Finish reason: Length limit reached · Final content: {row.finalContentStatus === "COMPLETE" ? "Complete and schema-validated" : "Incomplete"}</p><small>Thinking: {row.thinkingModeRequested || "not recorded"} · Reasoning detected: {row.reasoningContentDetected ? "yes" : "no"}</small></div><div><span>{row.inputTokenCount ?? "—"} input · {row.outputTokenCount ?? "—"} completion · {row.reasoningTokenCount ?? "not reported"} reasoning</span><span>{auditCost(row)}</span></div></article>)}</section>}
  </main>;
}
