"use client";
import { useCallback, useEffect, useMemo, useRef, useState } from "react";
import { AlertTriangle, Bot, CheckCircle2, Copy, Database, KeyRound, Loader2, Plus, RefreshCw, ShieldCheck, Square, TestTube2, Trash2, XCircle } from "lucide-react";
import styles from "./AiProviderDashboard.module.css";

type AnyRecord = Record<string, any>;
const emptyForm: AnyRecord = { providerType: "ollama", displayName: "", enabled: false, locationClassification: "LOCAL", baseUrl: "http://localhost:11434", authenticationType: "NONE", apiKey: "", removeApiKey: false, secretHeadersText: "{}", removeSecretHeaders: false, nonSecretHeadersText: "{}", defaultModel: "", fastModel: "", reasoningModel: "", fallbackProviderId: "", requestTimeoutMs: 30000, retryCount: 2, initialRetryDelayMs: 500, maximumRetryDelayMs: 10000, retryBackoffMultiplier: 2, sslVerification: true, modelDiscoveryEnabled: true, healthCheckEnabled: true, healthCheckIntervalMinutes: 15, monthlyBudget: "", notes: "" };
async function jsonFetch(url: string, init?: RequestInit) { const response = await fetch(url, init); const body = response.status === 204 ? null : await response.json().catch(() => ({})); if (!response.ok) throw new Error(body?.message || body?.error || "Request failed."); return body; }
function statusLabel(provider: AnyRecord) { return provider.health?.healthState || (provider.lastConnectionTestAt ? "UNKNOWN" : "NOT_TESTED"); }
function formatCost(value: unknown) { return typeof value === "number" ? `$${value.toFixed(4)}` : "Cost data unavailable"; }

export default function AiProviderDashboard() {
  const [tab, setTab] = useState("overview"); const [settings, setSettings] = useState<AnyRecord | null>(null); const [providers, setProviders] = useState<AnyRecord[]>([]); const [types, setTypes] = useState<AnyRecord[]>([]); const [features, setFeatures] = useState<AnyRecord[]>([]); const [usage, setUsage] = useState<AnyRecord | null>(null); const [audit, setAudit] = useState<AnyRecord[]>([]); const [loading, setLoading] = useState(true); const [message, setMessage] = useState(""); const [error, setError] = useState(""); const [editing, setEditing] = useState<AnyRecord | null>(null); const [form, setForm] = useState<AnyRecord>(emptyForm); const [models, setModels] = useState<AnyRecord[]>([]); const [busyId, setBusyId] = useState<string | null>(null); const [wizardStep, setWizardStep] = useState(1); const abortRef = useRef<AbortController | null>(null);
  const load = useCallback(async () => { setLoading(true); setError(""); try { const [globalData, providerData, featureData, usageData, auditData] = await Promise.all([jsonFetch("/api/ai/settings"), jsonFetch("/api/ai/providers"), jsonFetch("/api/ai/features"), jsonFetch("/api/ai/usage"), jsonFetch("/api/ai/audit?take=50")]); setSettings(globalData); setProviders(providerData.providers); setTypes(providerData.providerTypes); setFeatures(featureData.features); setUsage(usageData); setAudit(auditData.records); } catch (cause) { setError((cause as Error).message); } finally { setLoading(false); } }, []);
  useEffect(() => { void load(); return () => abortRef.current?.abort(); }, [load]);
  const connected = providers.filter((provider) => statusLabel(provider) === "HEALTHY").length; const degraded = providers.filter((provider) => ["DEGRADED", "UNAVAILABLE"].includes(statusLabel(provider))).length;
  const providerUsage = useMemo(() => new Map((usage?.providers || []).map((row: AnyRecord) => [row.id, row])), [usage]);
  function announce(value: string, isError = false) { setMessage(isError ? "" : value); setError(isError ? value : ""); }
  async function saveGlobal(patch: AnyRecord) { try { const next = await jsonFetch("/api/ai/settings", { method: "PUT", headers: { "content-type": "application/json" }, body: JSON.stringify(patch) }); setSettings((current) => ({ ...current, ...next })); announce("AI settings saved."); } catch (cause) { announce((cause as Error).message, true); } }
  function startAdd() { setEditing({ id: null }); setForm({ ...emptyForm }); setModels([]); setWizardStep(1); setTab("providers"); }
  async function startEdit(provider: AnyRecord) { setEditing(provider); setForm({ ...emptyForm, ...provider, apiKey: "", secretHeadersText: "{}", nonSecretHeadersText: JSON.stringify(provider.nonSecretHeaders || {}, null, 2), monthlyBudget: provider.monthlyBudget ?? "" }); setWizardStep(1); try { setModels((await jsonFetch(`/api/ai/providers/${provider.id}/models`)).models); } catch { setModels([]); } }
  function parseHeaderJson(value: string) { const parsed = JSON.parse(value || "{}"); if (!parsed || typeof parsed !== "object" || Array.isArray(parsed)) throw new Error("Custom headers must be a JSON object."); return parsed; }
  async function saveProvider() { setBusyId("save"); try { const payload: AnyRecord = { ...form, nonSecretHeaders: parseHeaderJson(form.nonSecretHeadersText), secretHeaders: parseHeaderJson(form.secretHeadersText), monthlyBudget: form.monthlyBudget === "" ? null : Number(form.monthlyBudget), defaultModel: form.defaultModel || null, fastModel: form.fastModel || null, reasoningModel: form.reasoningModel || null, fallbackProviderId: form.fallbackProviderId || null, baseUrl: form.baseUrl || null }; delete payload.secretHeadersText; delete payload.nonSecretHeadersText; delete payload.removeApiKey; delete payload.removeSecretHeaders; if (form.removeApiKey) { delete payload.apiKey; payload.apiKeyAction = "remove"; } else if (form.apiKey) payload.apiKeyAction = "replace"; else { delete payload.apiKey; payload.apiKeyAction = "keep"; } if (form.removeSecretHeaders) { delete payload.secretHeaders; payload.secretHeadersAction = "remove"; } else if (Object.keys(payload.secretHeaders).length) payload.secretHeadersAction = "replace"; else { delete payload.secretHeaders; payload.secretHeadersAction = "keep"; } const url = editing?.id ? `/api/ai/providers/${editing.id}` : "/api/ai/providers"; await jsonFetch(url, { method: editing?.id ? "PATCH" : "POST", headers: { "content-type": "application/json" }, body: JSON.stringify(payload) }); setEditing(null); announce(editing?.id ? "Provider updated. Existing secrets were preserved unless explicitly replaced or removed." : "Provider added."); await load(); } catch (cause) { announce((cause as Error).message, true); } finally { setBusyId(null); } }
  async function action(provider: AnyRecord, kind: "test" | "refresh" | "duplicate" | "delete") { if (kind === "delete" && !confirm(`Delete ${provider.displayName}? Historical audit records will be retained.`)) return; setBusyId(`${kind}:${provider.id}`); const controller = new AbortController(); if (kind === "test") abortRef.current = controller; try { if (kind === "test") { const result = await jsonFetch(`/api/ai/providers/${provider.id}/test`, { method: "POST", signal: controller.signal }); announce(`${provider.displayName}: ${result.message} (${result.latencyMs} ms)`); } if (kind === "refresh") { const result = await jsonFetch(`/api/ai/providers/${provider.id}/models/refresh`, { method: "POST", signal: controller.signal }); announce(`${result.models.length} models discovered for ${provider.displayName}.`); } if (kind === "duplicate") { await jsonFetch("/api/ai/providers", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ duplicateProviderId: provider.id }) }); announce("Provider duplicated without secrets."); } if (kind === "delete") { await jsonFetch(`/api/ai/providers/${provider.id}`, { method: "DELETE" }); announce("Provider deleted; historical audit records were retained."); } await load(); } catch (cause) { if ((cause as Error).name !== "AbortError") announce((cause as Error).message, true); else announce("Connection test cancelled."); } finally { setBusyId(null); abortRef.current = null; } }
  async function toggleProvider(provider: AnyRecord) { try { await jsonFetch(`/api/ai/providers/${provider.id}`, { method: "PATCH", headers: { "content-type": "application/json" }, body: JSON.stringify({ enabled: !provider.enabled }) }); await load(); announce(`${provider.displayName} ${provider.enabled ? "disabled" : "enabled"}.`); } catch (cause) { announce((cause as Error).message, true); } }
  if (loading && !settings) return <div className={styles.loading}><Loader2 className={styles.spin} /> Loading AI provider settings…</div>;
  return <main className={styles.wrapper}>
    <header className={styles.header}><div><h1><Bot size={30} /> AI Provider Foundation</h1><p>Secure, provider-neutral infrastructure for future advisory AI features. No AI output can mutate playlists.</p></div><span className={settings?.enabled ? styles.enabledBadge : styles.disabledBadge}>{settings?.enabled ? "AI enabled" : "AI disabled"}</span></header>
    {!settings?.encryptionConfigured && <div className={styles.warning} role="alert"><KeyRound size={20} /><div><strong>Credential encryption setup required</strong><p>Set <code>AI_CREDENTIAL_ENCRYPTION_KEY</code> (or the existing <code>MIXARR_SECRET_KEY</code>) before saving secret-based providers. Local providers without secrets remain available.</p></div></div>}
    <div className={styles.live} aria-live="polite">{error || message}</div>{error && <div className={styles.error}><XCircle size={18} />{error}</div>}{message && <div className={styles.success}><CheckCircle2 size={18} />{message}</div>}
    <nav className={styles.tabs} aria-label="AI settings sections">{["overview", "providers", "features", "audit"].map((item) => <button key={item} aria-current={tab === item ? "page" : undefined} onClick={() => setTab(item)}>{item[0].toUpperCase() + item.slice(1)}</button>)}</nav>

    {tab === "overview" && <>
      <section className={styles.stats} aria-label="AI overview"><article><span>Configured providers</span><strong>{providers.length}</strong></article><article><span>Connected</span><strong>{connected}</strong></article><article><span>Degraded</span><strong>{degraded}</strong></article><article><span>Enabled features</span><strong>{features.filter((feature) => feature.enabled).length}</strong></article><article><span>Requests this month</span><strong>{usage?.summary?.requestsThisMonth || 0}</strong></article><article><span>Average latency</span><strong>{usage?.summary?.averageLatencyMs || 0} ms</strong></article><article><span>Estimated usage</span><strong>{formatCost(usage?.summary?.estimatedCost)}</strong></article></section>
      <section className={`glass-panel ${styles.panel}`}><h2><ShieldCheck size={20} /> Global controls</h2><label className={styles.toggle}><input type="checkbox" checked={settings?.enabled === true} onChange={(event) => void saveGlobal({ enabled: event.target.checked })}/><span>Enable AI infrastructure</span></label><p className={styles.help}>Disabled by default. Enabling the foundation does not enable any future feature or send a request.</p><div className={styles.grid}><label>Default provider<select value={settings?.defaultProviderId || ""} onChange={(event) => void saveGlobal({ defaultProviderId: event.target.value || null })}><option value="">No default provider</option>{providers.map((provider) => <option key={provider.id} value={provider.id}>{provider.displayName}</option>)}</select></label><label>Default timeout (ms)<input type="number" value={settings?.defaultTimeoutMs || 30000} min={1000} max={300000} onChange={(event) => setSettings({ ...settings, defaultTimeoutMs: Number(event.target.value) })} onBlur={() => void saveGlobal({ defaultTimeoutMs: settings?.defaultTimeoutMs })}/></label><label>Maximum response bytes<input type="number" value={settings?.maximumServerResponseBytes || 1048576} min={1024} max={20000000} onChange={(event) => setSettings({ ...settings, maximumServerResponseBytes: Number(event.target.value) })} onBlur={() => void saveGlobal({ maximumServerResponseBytes: settings?.maximumServerResponseBytes })}/></label><label>Audit retention (days)<input type="number" value={settings?.auditRetentionDays || 90} min={1} max={3650} onChange={(event) => setSettings({ ...settings, auditRetentionDays: Number(event.target.value) })} onBlur={() => void saveGlobal({ auditRetentionDays: settings?.auditRetentionDays })}/></label></div><label className={styles.toggle}><input type="checkbox" checked={!!settings?.privacyWarningAcknowledgedAt} onChange={(event) => void saveGlobal({ privacyWarningAcknowledged: event.target.checked })}/><span>I acknowledge that remote providers process data outside my local network.</span></label></section>
    </>}

    {tab === "providers" && <>
      <div className={styles.sectionHeader}><div><h2>AI Providers</h2><p>Multiple configurations of every provider type are supported.</p></div><button className={styles.primary} onClick={startAdd}><Plus size={16}/> Add provider</button></div>
      {!providers.length ? <div className={styles.empty}><Bot size={36}/><h3>No AI providers configured</h3><p>Mixarr works normally without one. Add a local or remote provider when you are ready.</p><button className={styles.primary} onClick={startAdd}>Add your first provider</button></div> : <div className={styles.cards}>{providers.map((provider) => { const used = providerUsage.get(provider.id) as AnyRecord | undefined; const status = statusLabel(provider); return <article className={styles.card} key={provider.id}><div className={styles.cardTop}><div><span className={styles.kind}>{types.find((item) => item.type === provider.providerType)?.displayName || provider.providerType}</span><h3>{provider.displayName}</h3></div><span className={styles.status} data-status={status}>{status.replaceAll("_", " ")}</span></div><dl><div><dt>Mode</dt><dd>{provider.locationClassification}</dd></div><div><dt>Default model</dt><dd>{provider.defaultModel || "Not selected"}</dd></div><div><dt>Fast / reasoning</dt><dd>{provider.fastModel || "—"} / {provider.reasoningModel || "—"}</dd></div><div><dt>Models</dt><dd>{provider.modelCount || 0}</dd></div><div><dt>Last success</dt><dd>{provider.lastSuccessfulConnectionAt ? new Date(provider.lastSuccessfulConnectionAt).toLocaleString() : "Never"}</dd></div><div><dt>Requests this month</dt><dd>{used?.requests || 0}</dd></div><div><dt>Cost</dt><dd>{used?.costLabel || formatCost(used?.estimatedCost)}</dd></div><div><dt>Budget</dt><dd>{provider.monthlyBudget == null ? "No budget" : `${formatCost(used?.estimatedCost || 0)} of $${Number(provider.monthlyBudget).toFixed(2)}`}</dd></div></dl><div className={styles.capabilities}>{Object.entries(types.find((item) => item.type === provider.providerType)?.knownCapabilities || {}).slice(0, 6).map(([key, value]) => <span key={key} title={`${key}: ${value}`}>{key.replaceAll("_", " ")} · {String(value).toLowerCase()}</span>)}</div><div className={styles.actions}><button onClick={() => void toggleProvider(provider)}>{provider.enabled ? "Disable" : "Enable"}</button><button onClick={() => void startEdit(provider)}>Edit</button><button onClick={() => void action(provider, "test")} disabled={!!busyId}><TestTube2 size={14}/> Test</button><button onClick={() => void action(provider, "refresh")} disabled={!!busyId || !provider.modelDiscoveryEnabled}><RefreshCw size={14}/> Models</button><button aria-label={`Duplicate ${provider.displayName} without secrets`} onClick={() => void action(provider, "duplicate")}><Copy size={14}/></button><button aria-label={`Delete ${provider.displayName}`} className={styles.danger} onClick={() => void action(provider, "delete")}><Trash2 size={14}/></button>{busyId === `test:${provider.id}` && <button onClick={() => abortRef.current?.abort()}><Square size={13}/> Cancel test</button>}</div></article>; })}</div>}
      {editing && <section className={`glass-panel ${styles.editor}`} aria-labelledby="provider-editor"><div className={styles.editorTitle}><div><h2 id="provider-editor">{editing.id ? "Edit provider" : "Add provider"}</h2><p>Step {wizardStep} of 4 · Existing secrets are never returned to this form.</p></div><button onClick={() => setEditing(null)} aria-label="Close provider editor">×</button></div><ol className={styles.steps}><li data-active={wizardStep === 1}>Provider</li><li data-active={wizardStep === 2}>Authentication</li><li data-active={wizardStep === 3}>Models &amp; reliability</li><li data-active={wizardStep === 4}>Privacy &amp; review</li></ol>
        {wizardStep === 1 && <div className={styles.grid}><label>Provider type<select disabled={!!editing.id} value={form.providerType} onChange={(event) => { const meta = types.find((item) => item.type === event.target.value); setForm({ ...form, providerType: event.target.value, baseUrl: meta?.defaultBaseUrl || "", authenticationType: meta?.defaultAuthenticationType || "NONE", locationClassification: meta?.defaultLocation || "UNKNOWN" }); }}><option value="">Choose a provider</option>{types.map((item) => <option key={item.type} value={item.type}>{item.displayName}{item.available ? "" : " — unavailable"}</option>)}</select></label><label>Display name<input value={form.displayName} maxLength={120} onChange={(event) => setForm({ ...form, displayName: event.target.value })}/></label><label>Location classification<select value={form.locationClassification} onChange={(event) => setForm({ ...form, locationClassification: event.target.value })}><option>LOCAL</option><option>REMOTE</option><option>USER_CLASSIFIED</option><option>UNKNOWN</option></select></label><label>Base URL<input value={form.baseUrl || ""} placeholder="https://provider.example/v1" onChange={(event) => setForm({ ...form, baseUrl: event.target.value })}/></label>{form.providerType === "chatgpt_subscription" && <div className={styles.warning}><AlertTriangle size={18}/><p>No official supported integration is available. Mixarr never uses browser cookies, profiles, unofficial session tokens, or ChatGPT web automation. Configure OpenAI API instead.</p></div>}</div>}
        {wizardStep === 2 && <div className={styles.grid}><label>Authentication type<select value={form.authenticationType} onChange={(event) => setForm({ ...form, authenticationType: event.target.value })}>{["NONE","BEARER","API_KEY_HEADER","BASIC","PROVIDER_SPECIFIC","CUSTOM_SECRET_HEADERS"].map((item) => <option key={item}>{item}</option>)}</select></label><label>API key<span className={styles.secretHint}>{editing?.apiKeyConfigured ? "API key configured · leave blank to keep" : "Stored with authenticated encryption"}</span><input type="password" autoComplete="new-password" disabled={form.removeApiKey} value={form.apiKey} placeholder={editing?.apiKeyConfigured ? "Replace API key" : "Enter API key"} onChange={(event) => setForm({ ...form, apiKey: event.target.value })}/>{editing?.apiKeyConfigured && <span className={styles.toggle}><input type="checkbox" checked={form.removeApiKey} onChange={(event) => setForm({ ...form, removeApiKey: event.target.checked, apiKey: "" })}/>Remove API key when saved</span>}</label><label className={styles.full}>Non-secret headers (JSON)<textarea value={form.nonSecretHeadersText} onChange={(event) => setForm({ ...form, nonSecretHeadersText: event.target.value })}/></label><label className={styles.full}>Replacement secret headers (JSON)<span className={styles.secretHint}>{editing?.secretHeadersConfigured ? "Secret headers configured · leave {} to keep" : "Values are never returned"}</span><textarea disabled={form.removeSecretHeaders} value={form.secretHeadersText} onChange={(event) => setForm({ ...form, secretHeadersText: event.target.value })}/>{editing?.secretHeadersConfigured && <span className={styles.toggle}><input type="checkbox" checked={form.removeSecretHeaders} onChange={(event) => setForm({ ...form, removeSecretHeaders: event.target.checked, secretHeadersText: "{}" })}/>Remove secret headers when saved</span>}</label></div>}
        {wizardStep === 3 && <div className={styles.grid}><label>Default model<input list="ai-models" value={form.defaultModel || ""} onChange={(event) => setForm({ ...form, defaultModel: event.target.value })}/></label><label>Fast model<input list="ai-models" value={form.fastModel || ""} onChange={(event) => setForm({ ...form, fastModel: event.target.value })}/></label><label>Reasoning model<input list="ai-models" value={form.reasoningModel || ""} onChange={(event) => setForm({ ...form, reasoningModel: event.target.value })}/></label><datalist id="ai-models">{models.map((model) => <option key={model.id} value={model.modelIdentifier}>{model.displayName}</option>)}</datalist><label>Explicit fallback provider<select value={form.fallbackProviderId || ""} onChange={(event) => setForm({ ...form, fallbackProviderId: event.target.value })}><option value="">No automatic fallback</option>{providers.filter((provider) => provider.id !== editing?.id).map((provider) => <option key={provider.id} value={provider.id}>{provider.displayName} · {provider.locationClassification}</option>)}</select></label><label>Timeout (ms)<input type="number" min={1000} max={300000} value={form.requestTimeoutMs} onChange={(event) => setForm({ ...form, requestTimeoutMs: Number(event.target.value) })}/></label><label>Retry count<input type="number" min={0} max={10} value={form.retryCount} onChange={(event) => setForm({ ...form, retryCount: Number(event.target.value) })}/></label><label>Monthly budget (optional)<input type="number" min={0} step="0.01" value={form.monthlyBudget} onChange={(event) => setForm({ ...form, monthlyBudget: event.target.value })}/></label><label className={styles.toggle}><input type="checkbox" checked={form.modelDiscoveryEnabled} onChange={(event) => setForm({ ...form, modelDiscoveryEnabled: event.target.checked })}/>Model discovery</label><label className={styles.toggle}><input type="checkbox" checked={form.healthCheckEnabled} onChange={(event) => setForm({ ...form, healthCheckEnabled: event.target.checked })}/>Background health checks</label></div>}
        {wizardStep === 4 && <div className={styles.review}><div className={styles.warning}><AlertTriangle size={18}/><p>{form.locationClassification === "REMOTE" ? "Information sent to this provider may leave your local network. Mixarr limits data to fields required by an enabled feature, but the provider processes it under its own terms." : "Location is explicitly administrator-classified. Mixarr does not silently reclassify providers."}</p></div><label className={styles.toggle}><input type="checkbox" checked={form.enabled} disabled={form.providerType === "chatgpt_subscription"} onChange={(event) => setForm({ ...form, enabled: event.target.checked })}/>Enable provider after saving</label><label>Safe notes<textarea value={form.notes || ""} maxLength={2000} onChange={(event) => setForm({ ...form, notes: event.target.value })}/></label><p className={styles.boundary}>Saving a provider does not enable global AI, any future feature, or playlist mutations. You may save without testing.</p></div>}
        <div className={styles.wizardActions}><button disabled={wizardStep === 1} onClick={() => setWizardStep((step) => step - 1)}>Back</button>{wizardStep < 4 ? <button className={styles.primary} onClick={() => setWizardStep((step) => step + 1)}>Continue</button> : <button className={styles.primary} disabled={busyId === "save" || !form.displayName} onClick={() => void saveProvider()}>{busyId === "save" && <Loader2 className={styles.spin} size={15}/>} Save provider</button>}</div></section>}
    </>}

    {tab === "features" && <section className={styles.featureList}><div className={styles.sectionHeader}><div><h2>Per-feature controls</h2><p>v2.4.0 is foundation-only. Future advisory features remain unavailable and off.</p></div></div>{features.map((feature) => <article className="glass-panel" key={feature.key}><div><h3>{feature.name}</h3><p>{feature.description}</p><small>{feature.explanation}</small></div><div><span>{feature.requiredCapabilities.join(", ")}</span><label className={styles.toggle}><input type="checkbox" checked={feature.enabled} disabled={!feature.available}/>Enabled</label></div></article>)}</section>}

    {tab === "audit" && <section><div className={styles.sectionHeader}><div><h2>Safe AI request audit</h2><p>Prompts, responses, credentials, Plex tokens, and raw provider errors are never shown here.</p></div><button onClick={() => void load()}><RefreshCw size={15}/> Refresh</button></div>{!audit.length ? <div className={styles.empty}><Database size={34}/><h3>No AI requests recorded</h3><p>This is expected while the foundation and all AI features are disabled.</p></div> : <div className={styles.tableWrap}><table><thead><tr><th>Time</th><th>Feature</th><th>Provider</th><th>Model</th><th>Status</th><th>Latency</th><th>Tokens</th><th>Cost</th><th>Retries</th><th>Sanitized error</th></tr></thead><tbody>{audit.map((row) => <tr key={row.id}><td>{new Date(row.createdAt).toLocaleString()}</td><td>{row.featureKey}</td><td>{row.providerDisplayName || row.providerType || "—"}</td><td>{row.model || "—"}</td><td>{row.status}</td><td>{row.latencyMs == null ? "—" : `${row.latencyMs} ms`}</td><td>{row.totalTokenCount ?? "—"}</td><td>{formatCost(row.estimatedCost)}</td><td>{row.retryCount}</td><td>{row.sanitizedErrorCode || "—"}</td></tr>)}</tbody></table></div>}</section>}
  </main>;
}
