"use client";

import { useCallback, useEffect, useState } from "react";
import { AlertOctagon, CheckCircle2, LockKeyhole, RefreshCw, ShieldAlert } from "lucide-react";
import styles from "./AiSecurityDashboard.module.css";

type Row = Record<string, any>;
const FEATURES = ["recipe_copilot", "natural_language_playlist_requests", "playlist_ai_summaries", "metadata_suggestions", "troubleshooting_explanations"];
const CAPABILITIES = ["text_generation", "chat_messages", "system_instructions", "structured_json", "json_schema", "streaming", "model_discovery", "token_usage", "large_context"];
const EXTERNAL_DATA_CATEGORIES = ["user_request", "recipe_configuration", "library_metadata", "playlist_metadata", "diagnostic_data"];
async function api(url: string, init?: RequestInit) { const response = await fetch(url, { cache: "no-store", ...init }); const body = await response.json().catch(() => ({})); if (!response.ok) throw new Error(body?.error?.message || "AI security request failed."); return body; }

export default function AiSecurityDashboard() {
  const [shutdown, setShutdown] = useState<Row>({}); const [governance, setGovernance] = useState<Row>({}); const [providers, setProviders] = useState<Row[]>([]); const [models, setModels] = useState<Row[]>([]); const [selectedProvider, setSelectedProvider] = useState(""); const [quarantine, setQuarantine] = useState<Row[]>([]); const [jobs, setJobs] = useState<Row[]>([]); const [message, setMessage] = useState(""); const [busy, setBusy] = useState(false);
  const load = useCallback(async () => { setBusy(true); try { const [s, g, p, q, j] = await Promise.all([api("/api/ai/emergency-shutdown"), api("/api/ai/governance"), api("/api/ai/providers"), api("/api/ai/quarantine?status=OPEN&limit=25"), api("/api/ai/jobs?pageSize=25")]); setShutdown(s); setGovernance(g); setProviders(p.providers || []); setQuarantine(q.records || []); setJobs(j.jobs || []); const id = selectedProvider || p.providers?.[0]?.id || ""; setSelectedProvider(id); if (id) setModels((await api(`/api/ai/providers/${id}/models`)).models || []); } catch (error) { setMessage((error as Error).message); } finally { setBusy(false); } }, [selectedProvider]);
  useEffect(() => { void load(); }, [load]);
  async function toggleShutdown() { const active = !shutdown.databaseActive; const reason = window.prompt(active ? "Reason for emergency shutdown:" : "Reason for restoring provider access:", active ? "Administrator-initiated safety shutdown" : "Administrator review completed") || undefined; if (!window.confirm(`${active ? "Stop" : "Restore"} all provider-bound AI work?`)) return; await api("/api/ai/emergency-shutdown", { method: "PUT", headers: { "content-type": "application/json" }, body: JSON.stringify({ active, confirm: true, reason }) }); await load(); }
  async function patchProvider(provider: Row, changes: Row) { await api(`/api/ai/providers/${provider.id}`, { method: "PATCH", headers: { "content-type": "application/json" }, body: JSON.stringify(changes) }); await load(); }
  async function patchModel(model: Row, changes: Row) { await api(`/api/ai/providers/${model.providerConfigId}/models`, { method: "PATCH", headers: { "content-type": "application/json" }, body: JSON.stringify({ modelIdentifier: model.modelIdentifier, ...changes }) }); await load(); }
  async function patchGovernance(changes: Row) { await api("/api/ai/governance", { method: "PATCH", headers: { "content-type": "application/json" }, body: JSON.stringify({ ...changes, reason: "Updated from AI Security & Queue settings" }) }); await load(); }
  async function actOnQuarantine(id: string, action: "REJECT" | "DISMISS_WARNING") { await api(`/api/ai/quarantine/${id}/action`, { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ action }) }); await load(); }
  return <div className={styles.stack}>
    <section className={`${styles.emergency} ${shutdown.active ? styles.active : ""}`}><AlertOctagon/><div><h2>Emergency AI shutdown</h2><p>{shutdown.active ? "Provider-bound requests, retries, discovery, and health checks are blocked." : "Provider requests may run only after all ordinary governance checks pass."}</p>{shutdown.environmentDisabled && <strong>MIXARR_AI_ENABLED disables AI at the environment level and cannot be overridden here.</strong>}</div><button disabled={shutdown.environmentDisabled || busy} onClick={() => void toggleShutdown()}>{shutdown.databaseActive ? "Deactivate shutdown" : "Activate shutdown"}</button></section>
    <section className={styles.panel}><h2>External data and retention policy</h2><p>External providers are denied by default. Enable only the exact features and data categories your deployment permits.</p><div className={styles.settingsGrid}><label><input type="checkbox" checked={!!governance.externalProvidersAllowed} onChange={(e) => void patchGovernance({ externalProvidersAllowed: e.target.checked })}/> Allow external providers globally</label><label><input type="checkbox" checked={governance.requireExternalConfirmation !== false} onChange={(e) => void patchGovernance({ requireExternalConfirmation: e.target.checked })}/> Require per-request confirmation</label>{FEATURES.map((feature) => <label key={`external-${feature}`}><input type="checkbox" checked={(governance.allowedExternalFeaturesJson || []).includes(feature)} onChange={(e) => void patchGovernance({ allowedExternalFeaturesJson: e.target.checked ? Array.from(new Set([...(governance.allowedExternalFeaturesJson || []), feature])) : (governance.allowedExternalFeaturesJson || []).filter((item: string) => item !== feature) })}/>feature: {feature.replaceAll("_", " ")}</label>)}{EXTERNAL_DATA_CATEGORIES.map((category) => <label key={category}><input type="checkbox" checked={(governance.allowedExternalDataJson || []).includes(category)} onChange={(e) => void patchGovernance({ allowedExternalDataJson: e.target.checked ? Array.from(new Set([...(governance.allowedExternalDataJson || []), category])) : (governance.allowedExternalDataJson || []).filter((item: string) => item !== category) })}/>data: {category.replaceAll("_", " ")}</label>)}</div><div className={styles.numericGrid}><label>Request body retention days<input type="number" min="0" max="3650" defaultValue={governance.requestBodyRetentionDays ?? 0} onBlur={(e) => void patchGovernance({ requestBodyRetentionDays: Number(e.target.value) })}/></label><label>Response body retention days<input type="number" min="0" max="3650" defaultValue={governance.responseBodyRetentionDays ?? 0} onBlur={(e) => void patchGovernance({ responseBodyRetentionDays: Number(e.target.value) })}/></label><label>Quarantine retention days<input type="number" min="1" max="3650" defaultValue={governance.quarantineRetentionDays ?? 90} onBlur={(e) => void patchGovernance({ quarantineRetentionDays: Number(e.target.value) })}/></label><label>Global concurrency<input type="number" min="1" max="1000" defaultValue={governance.globalConcurrencyLimit ?? 8} onBlur={(e) => void patchGovernance({ globalConcurrencyLimit: Number(e.target.value) })}/></label><label>Maximum queue size<input type="number" min="1" max="100000" defaultValue={governance.maximumQueueSize ?? 1000} onBlur={(e) => void patchGovernance({ maximumQueueSize: Number(e.target.value) })}/></label></div></section>
    <section className={styles.panel}><h2><LockKeyhole/> Provider allowlist</h2><p>Configuration and enablement are not approval. Each provider must be approved for explicit features, privacy modes, and sensitive data categories.</p>{providers.map((provider) => <article className={styles.row} key={provider.id}><div><strong>{provider.displayName}</strong><small>{provider.locationClassification} · {provider.health?.healthState || "UNKNOWN"}</small></div><label><input type="checkbox" checked={!!provider.approved} onChange={(e) => void patchProvider(provider, { approved: e.target.checked })}/> Approved</label><label><input type="checkbox" checked={!!provider.allowExternalRequests} onChange={(e) => void patchProvider(provider, { allowExternalRequests: e.target.checked })}/> External requests</label><details><summary>Feature, privacy, and data allowlists</summary><div className={styles.checks}>{FEATURES.map((feature) => <label key={feature}><input type="checkbox" checked={(provider.allowedFeatures || []).includes(feature)} onChange={(e) => void patchProvider(provider, { allowedFeatures: e.target.checked ? Array.from(new Set([...(provider.allowedFeatures || []), feature])) : (provider.allowedFeatures || []).filter((item: string) => item !== feature) })}/>{feature.replaceAll("_", " ")}</label>)}{["LOCAL_ONLY","ANONYMOUS_METADATA","METADATA_LIMITED","FULL_METADATA"].map((mode) => <label key={mode}><input type="checkbox" checked={(provider.privacyModes || []).includes(mode)} onChange={(e) => void patchProvider(provider, { privacyModes: e.target.checked ? Array.from(new Set([...(provider.privacyModes || []), mode])) : (provider.privacyModes || []).filter((item: string) => item !== mode) })}/>{mode.replaceAll("_", " ")}</label>)}<label><input type="checkbox" checked={!!provider.allowLibraryMetadata} onChange={(e) => void patchProvider(provider, { allowLibraryMetadata: e.target.checked })}/>library metadata</label><label><input type="checkbox" checked={!!provider.allowDiagnosticData} onChange={(e) => void patchProvider(provider, { allowDiagnosticData: e.target.checked })}/>diagnostic data</label><label><input type="checkbox" checked={!!provider.allowUserNotes} onChange={(e) => void patchProvider(provider, { allowUserNotes: e.target.checked })}/>user notes</label></div></details></article>)}</section>
    <section className={styles.panel}><h2>Model allowlist and capabilities</h2><label>Provider <select value={selectedProvider} onChange={async (e) => { setSelectedProvider(e.target.value); setModels((await api(`/api/ai/providers/${e.target.value}/models`)).models || []); }}>{providers.map((p) => <option key={p.id} value={p.id}>{p.displayName}</option>)}</select></label>{models.map((model) => <article className={styles.model} key={model.id}><div><strong>{model.displayName}</strong><small>{model.modelIdentifier} · {model.availabilityStatus}</small></div><label><input type="checkbox" checked={model.enabled} onChange={(e) => void patchModel(model, { enabled: e.target.checked })}/>Enabled</label><label><input type="checkbox" checked={model.approved} onChange={(e) => void patchModel(model, { approved: e.target.checked })}/>Approved</label><details><summary>Capabilities and allowed features</summary><div className={styles.checks}>{CAPABILITIES.map((capability) => <label key={capability}><input type="checkbox" checked={(model.capabilitiesJson || []).includes(capability)} onChange={(e) => void patchModel(model, { capabilities: e.target.checked ? Array.from(new Set([...(model.capabilitiesJson || []), capability])) : (model.capabilitiesJson || []).filter((item: string) => item !== capability) })}/>{capability.replaceAll("_", " ")}</label>)}{FEATURES.map((feature) => <label key={feature}><input type="checkbox" checked={(model.allowedFeaturesJson || []).includes(feature)} onChange={(e) => void patchModel(model, { allowedFeatures: e.target.checked ? Array.from(new Set([...(model.allowedFeaturesJson || []), feature])) : (model.allowedFeaturesJson || []).filter((item: string) => item !== feature) })}/>{feature.replaceAll("_", " ")}</label>)}</div></details></article>)}</section>
    <section className={styles.panel}><h2><ShieldAlert/> Quarantine</h2>{!quarantine.length ? <p><CheckCircle2/> No open quarantined responses.</p> : quarantine.map((row) => <article className={styles.quarantine} key={row.id}><strong>{row.severity} · {row.featureKey}</strong><p>{(row.reasonCodesJson || []).join(", ")}</p><small>{new Date(row.createdAt).toLocaleString()} · {row.providerConfigId || "No provider"} · {row.model || "No model"}</small><details><summary>Safe previews</summary><pre>{row.safeRequestPreview || "No request body retained."}</pre><pre>{row.safeResponsePreview || "No response body retained."}</pre></details><button onClick={() => void actOnQuarantine(row.id, "REJECT")}>Permanently reject</button>{!row.nonOverridable && <button onClick={() => void actOnQuarantine(row.id, "DISMISS_WARNING")}>Dismiss resolved warning</button>}</article>)}</section>
    <section className={styles.panel}><h2>Durable AI queue</h2><button onClick={() => void load()}><RefreshCw/> Refresh</button><div className={styles.table}><table><thead><tr><th>Status</th><th>Feature</th><th>User</th><th>Attempts</th><th>Queued</th></tr></thead><tbody>{jobs.map((job) => <tr key={job.id}><td>{job.status}</td><td>{job.featureKey}</td><td>{job.userId || "System"}</td><td>{job.attemptCount}/{job.maximumAttempts}</td><td>{new Date(job.queuedAt).toLocaleString()}</td></tr>)}</tbody></table></div></section>
    <div aria-live="polite">{message}</div>
  </div>;
}
