"use client";

import { useEffect, useMemo, useState } from "react";
import axios from "axios";
import { AlertTriangle, Home, PartyPopper, ShieldCheck, Users, Vote } from "lucide-react";
import styles from "./HouseholdPlaylistSettings.module.css";

export type HouseholdPlaylistDraft = any;
export const defaultHouseholdPlaylistDraft = {
  householdId: "", balanceMode: "BALANCED_HOUSEHOLD", primaryMemberId: null,
  participantMemberIds: [], participantGuestIds: [], influenceOverrides: {}, sharedFavoritesWeight: 0.15,
  sharedFavoritesEnabled: true, maximumIndividualInfluence: 0.5, maximumTracksPerMemberPercent: 0.5,
  maximumConsecutiveMemberTracks: 3, requireEveryParticipant: true, redistributeUnusedInfluence: true,
  administratorOverride: false, familyRule: "STRICTEST_PROFILE", unknownRatingRule: "BLOCK", preferCleanVersions: true,
  partyModeEnabled: false, partySettings: { energyLevel: 0.75, discovery: 0.25, guestInfluence: 0.25, explicitContentAllowed: false, autoRegenerationThreshold: 10 },
  votingEnabled: false, liveFeedbackEnabled: false, approvalMode: "DISABLED", fixedApprovalCount: null,
  approvalConflictSeverity: null, maximumArtistRepetition: 3, maximumGenreConcentration: 0.6,
};

function message(error: any) { return error?.response?.data?.error?.message || error?.message || "Could not preview household influence"; }
function label(value: string) { return value.toLowerCase().replaceAll("_", " ").replace(/\b\w/g, (character) => character.toUpperCase()); }

export default function HouseholdPlaylistSettings({ mode, value, onModeChange, onChange }: { mode: "INDIVIDUAL" | "HOUSEHOLD"; value: HouseholdPlaylistDraft; onModeChange: (mode: "INDIVIDUAL" | "HOUSEHOLD") => void; onChange: (value: HouseholdPlaylistDraft) => void }) {
  const [households, setHouseholds] = useState<any[]>([]);
  const [household, setHousehold] = useState<any | null>(null);
  const [preview, setPreview] = useState<any | null>(null);
  const [error, setError] = useState("");
  const patch = (next: Partial<HouseholdPlaylistDraft>) => { onChange({ ...value, ...next }); setPreview(null); };
  useEffect(() => { axios.get("/api/households").then((response) => setHouseholds(response.data.households || [])).catch(() => setHouseholds([])); }, []);
  useEffect(() => { if (!value.householdId) { setHousehold(null); return; } axios.get(`/api/households/${value.householdId}`).then((response) => setHousehold(response.data.household)).catch((caught) => setError(message(caught))); }, [value.householdId]);
  const selected = useMemo(() => [...(household?.members || []).filter((item: any) => value.participantMemberIds.includes(item.id)), ...(household?.guests || []).filter((item: any) => value.participantGuestIds.includes(item.id))], [household, value.participantMemberIds, value.participantGuestIds]);
  const chooseHousehold = async (householdId: string) => { if (!householdId) { onChange({ ...defaultHouseholdPlaylistDraft }); return; } try { const response = await axios.get(`/api/households/${householdId}`); const detail = response.data.household; setHousehold(detail); onChange({ ...defaultHouseholdPlaylistDraft, householdId, balanceMode: detail.defaultBalanceMode, maximumIndividualInfluence: detail.defaultMaximumInfluence, familyRule: detail.defaultFamilyRule, participantMemberIds: detail.members.filter((member: any) => member.isActive && !member.temporarilyExcluded).map((member: any) => member.id), participantGuestIds: detail.guests.filter((guest: any) => guest.isActive && (!guest.expiresAt || new Date(guest.expiresAt) > new Date())).map((guest: any) => guest.id) }); } catch (caught) { setError(message(caught)); } };
  const toggle = (kind: "member" | "guest", id: string, checked: boolean) => { const key = kind === "member" ? "participantMemberIds" : "participantGuestIds"; patch({ [key]: checked ? [...value[key], id] : value[key].filter((current: string) => current !== id) }); };
  const runPreview = async () => { setError(""); try { const response = await axios.post("/api/households/influence-preview", value); setPreview(response.data); } catch (caught) { setError(message(caught)); } };
  return <section className={styles.panel} aria-labelledby="personalization-mode-heading">
    <div className={styles.header}><div><h3 id="personalization-mode-heading"><Users size={17} /> Personalization mode</h3><p>Individual keeps existing behavior. Household combines only the participants selected below.</p></div><div className={styles.segmented}><button type="button" className={mode === "INDIVIDUAL" ? styles.active : ""} onClick={() => onModeChange("INDIVIDUAL")}>Individual</button><button type="button" className={mode === "HOUSEHOLD" ? styles.active : ""} onClick={() => onModeChange("HOUSEHOLD")}><Home size={14} /> Household</button></div></div>
    {mode === "HOUSEHOLD" && <div className={styles.body}>
      <label>Household<select value={value.householdId} onChange={(event) => void chooseHousehold(event.target.value)}><option value="">Select household</option>{households.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select></label>
      {household && <>
        <div className={styles.participants}><strong>Participating profiles</strong><div>{household.members.filter((item: any) => item.isActive).map((member: any) => <label key={member.id}><input type="checkbox" checked={value.participantMemberIds.includes(member.id)} onChange={(event) => toggle("member", member.id, event.target.checked)} /> <span>{member.displayName}</span><em>{member.memberType.toLowerCase()}</em></label>)}{household.guests.filter((item: any) => item.isActive).map((guest: any) => <label key={guest.id}><input type="checkbox" checked={value.participantGuestIds.includes(guest.id)} onChange={(event) => toggle("guest", guest.id, event.target.checked)} /> <span>{guest.displayName}</span><em>guest</em></label>)}</div></div>
        <div className={styles.grid}><label>Balance mode<select value={value.balanceMode} onChange={(event) => patch({ balanceMode: event.target.value })}>{["INDIVIDUAL_FIRST", "BALANCED_HOUSEHOLD", "WEIGHTED_HOUSEHOLD", "SHARED_FAVORITES", "DISCOVERY_CONSENSUS", "PARTY_MODE"].map((item) => <option key={item} value={item}>{label(item)}</option>)}</select></label><label>Maximum individual influence <span>{Math.round(value.maximumIndividualInfluence * 100)}%</span><input type="range" min="5" max="100" value={value.maximumIndividualInfluence * 100} onChange={(event) => patch({ maximumIndividualInfluence: Number(event.target.value) / 100 })} /></label><label>Shared favorites <span>{Math.round(value.sharedFavoritesWeight * 100)}%</span><input type="range" min="0" max="50" value={value.sharedFavoritesWeight * 100} disabled={!value.sharedFavoritesEnabled} onChange={(event) => patch({ sharedFavoritesWeight: Number(event.target.value) / 100 })} /></label><label>Tracks primarily for one profile <span>{Math.round(value.maximumTracksPerMemberPercent * 100)}% max</span><input type="range" min="5" max="100" value={value.maximumTracksPerMemberPercent * 100} onChange={(event) => patch({ maximumTracksPerMemberPercent: Number(event.target.value) / 100 })} /></label></div>
        {selected.length > 0 && <div className={styles.weights}><strong>Configured influence</strong>{selected.map((participant: any) => { const configured = value.influenceOverrides[participant.id] ?? participant.influenceWeight; return <label key={participant.id}><span>{participant.displayName}</span><input type="number" min="0" max="100" step="0.1" value={configured} onChange={(event) => patch({ influenceOverrides: { ...value.influenceOverrides, [participant.id]: Number(event.target.value) } })} /></label>; })}<label><span>Shared favorites enabled</span><input type="checkbox" checked={value.sharedFavoritesEnabled} onChange={(event) => patch({ sharedFavoritesEnabled: event.target.checked })} /></label></div>}
        <div className={styles.cards}><article><h4><ShieldCheck size={15} /> Family-friendly</h4><label>Rule<select value={value.familyRule} onChange={(event) => patch({ familyRule: event.target.value })}><option value="STRICTEST_PROFILE">Use strictest profile</option><option value="BLOCK">Block explicit</option><option value="ALLOW">Allow explicit</option><option value="ADMINISTRATOR_OVERRIDE">Administrator override</option></select></label><label><input type="checkbox" checked={value.unknownRatingRule === "BLOCK"} onChange={(event) => patch({ unknownRatingRule: event.target.checked ? "BLOCK" : "ALLOW" })} /> Block unknown ratings</label><label><input type="checkbox" checked={value.preferCleanVersions} onChange={(event) => patch({ preferCleanVersions: event.target.checked })} /> Prefer clean versions</label></article><article><h4><Vote size={15} /> Voting & approvals</h4><label><input type="checkbox" checked={value.votingEnabled} onChange={(event) => patch({ votingEnabled: event.target.checked })} /> Enable voting</label><label>Approval<select value={value.approvalMode} onChange={(event) => patch({ approvalMode: event.target.value })}>{["DISABLED", "FIXED", "MAJORITY", "UNANIMOUS", "ADMINISTRATOR_ONLY", "CONFLICT_SEVERITY"].map((item) => <option key={item} value={item}>{label(item)}</option>)}</select></label>{value.approvalMode === "FIXED" && <label>Required approvals<input type="number" min="1" value={value.fixedApprovalCount || 1} onChange={(event) => patch({ fixedApprovalCount: Number(event.target.value) })} /></label>}</article><article><h4><PartyPopper size={15} /> Party mode</h4><label><input type="checkbox" checked={value.partyModeEnabled} onChange={(event) => patch({ partyModeEnabled: event.target.checked, balanceMode: event.target.checked ? "PARTY_MODE" : value.balanceMode })} /> Enable party preset</label><label><input type="checkbox" checked={value.liveFeedbackEnabled} onChange={(event) => patch({ liveFeedbackEnabled: event.target.checked })} /> Live feedback</label><label>Maximum consecutive profile tracks<input type="number" min="1" max="20" value={value.maximumConsecutiveMemberTracks} onChange={(event) => patch({ maximumConsecutiveMemberTracks: Number(event.target.value) })} /></label></article></div>
        <button type="button" className={styles.previewButton} disabled={!selected.length} onClick={() => void runPreview()}>Preview household influence</button>
        {error && <div className={styles.error}><AlertTriangle size={15} /> {error}</div>}
        {preview && <div className={styles.preview}><h4>Household influence preview</h4>{preview.influence.participants.map((participant: any) => <div key={participant.id} className={styles.bar}><span>{participant.displayName}</span><div><i style={{ width: `${participant.effectiveInfluence * 100}%` }} /></div><strong>{Math.round(participant.effectiveInfluence * 100)}%</strong>{participant.capReduction > 0 && <em>cap −{Math.round(participant.capReduction * 100)}%</em>}</div>)}<div className={styles.bar}><span>Shared favorites</span><div><i style={{ width: `${preview.influence.sharedPreferenceInfluence * 100}%` }} /></div><strong>{Math.round(preview.influence.sharedPreferenceInfluence * 100)}%</strong></div>{preview.influence.warnings.map((warning: string) => <p key={warning}><AlertTriangle size={13} /> {warning}</p>)}{preview.conflicts.map((conflict: any) => <p key={`${conflict.category}-${conflict.severity}`}><AlertTriangle size={13} /> {label(conflict.category)} conflict · severity {conflict.severity} · resolved by {label(conflict.resolutionMethod)}</p>)}<p><ShieldCheck size={13} /> {preview.familyRule.reason}</p><p><Vote size={13} /> {preview.approvals.required ? `${preview.approvals.required} approval(s) required before Plex sync.` : "No approval gate."}</p></div>}
      </>}
    </div>}
  </section>;
}
