"use client";
import { useEffect, useState } from "react";
import { BookOpen, Loader2, Plus, Save, Trash2 } from "lucide-react";

async function api(path: string, init?: RequestInit) { const response = await fetch(path, { ...init, headers: { "Content-Type": "application/json", ...(init?.headers || {}) } }); const body = await response.json(); if (!response.ok) throw new Error(body.error?.message || "Request failed."); return body; }
const categories = ["relaxing","focus","coding","reading","studying","workout","running","driving","party","dinner","sleep","morning","late_night","background_listening","nostalgic","romantic","energetic","melancholic","aggressive","cinematic"];

export default function IntentInterpretationSettings() {
  const [settings, setSettings] = useState<any>(null), [entries, setEntries] = useState<any[]>([]), [phrase, setPhrase] = useState(""), [category, setCategory] = useState("relaxing"), [busy, setBusy] = useState(""), [message, setMessage] = useState("");
  useEffect(() => { Promise.all([api("/api/intent-settings"), api("/api/intent-dictionary")]).then(([settingBody, dictionaryBody]) => { setSettings(settingBody.settings); setEntries(dictionaryBody.entries || []); }).catch((caught) => setMessage(caught instanceof Error ? caught.message : "Intent settings unavailable.")); }, []);
  async function save() { setBusy("save"); setMessage(""); try { const body = await api("/api/intent-settings", { method: "PUT", body: JSON.stringify({ enabled: settings.enabled, localEnabled: settings.localEnabled, providerAssistanceEnabled: settings.providerAssistanceEnabled, defaultProviderId: settings.defaultProviderId, automaticSoftPreferenceMinimum: Number(settings.automaticSoftPreferenceMinimum), inferredHardRequirementMinimum: Number(settings.inferredHardRequirementMinimum), maximumPhases: Number(settings.maximumPhases), defaultEnergyTolerance: Number(settings.defaultEnergyTolerance), defaultBpmTolerance: Number(settings.defaultBpmTolerance), coverageEstimationEnabled: settings.coverageEstimationEnabled, reviewRequired: settings.reviewRequired, personalDictionariesEnabled: settings.personalDictionariesEnabled, householdDictionariesEnabled: settings.householdDictionariesEnabled, presetsEnabled: settings.presetsEnabled, retainSourceText: settings.retainSourceText, retentionDays: Number(settings.retentionDays), auditDetailLevel: settings.auditDetailLevel }) }); setSettings(body.settings); setMessage("Intent interpretation settings saved."); } catch (caught) { setMessage(caught instanceof Error ? caught.message : "Save failed."); } finally { setBusy(""); } }
  async function addEntry() { setBusy("dictionary"); setMessage(""); try { await api("/api/intent-dictionary", { method: "POST", body: JSON.stringify({ phrase, definition: { categories: [category] } }) }); const body = await api("/api/intent-dictionary"); setEntries(body.entries || []); setPhrase(""); setMessage("Personal phrase saved locally."); } catch (caught) { setMessage(caught instanceof Error ? caught.message : "Dictionary update failed."); } finally { setBusy(""); } }
  async function removeEntry(id: string) { setBusy(id); try { await api(`/api/intent-dictionary/${id}`, { method: "DELETE" }); setEntries(entries.filter((entry) => entry.id !== id)); } catch (caught) { setMessage(caught instanceof Error ? caught.message : "Delete failed."); } finally { setBusy(""); } }
  if (!settings) return <p aria-live="polite">{message || "Loading intent interpretation settings…"}</p>;
  const toggle = (key: string, title: string, description: string) => <label className="settings-toggle-row"><input type="checkbox" checked={Boolean(settings[key])} onChange={(event) => setSettings({ ...settings, [key]: event.target.checked })}/><span><strong>{title}</strong><small>{description}</small></span></label>;
  return <div className="intent-settings">
    <div className="intent-toggle-grid">{toggle("enabled", "Enable intent interpretation", "Show structured mood, activity, phase, curve, and preference interpretation.")}{toggle("localEnabled", "Local deterministic interpretation", "Works without a provider and remains the authoritative fallback.")}{toggle("providerAssistanceEnabled", "Allow provider-assisted enhancement", "Uses the existing AI provider, governance, privacy, budget, token, and request controls.")}{toggle("reviewRequired", "Require interpretation review", "Keep generated intent in review until a person approves it.")}{toggle("coverageEstimationEnabled", "Estimate library coverage", "Estimate hard-filter and phase coverage before generation.")}{toggle("retainSourceText", "Retain original request text", "Store source wording for the configured retention period.")}</div>
    <div className="intent-number-grid"><label>Maximum phases<input type="number" min="2" max="6" value={settings.maximumPhases} onChange={(event) => setSettings({ ...settings, maximumPhases: event.target.value })}/></label><label>Energy tolerance<input type="number" min="0.02" max="0.5" step="0.01" value={settings.defaultEnergyTolerance} onChange={(event) => setSettings({ ...settings, defaultEnergyTolerance: event.target.value })}/></label><label>BPM tolerance<input type="number" min="1" max="80" value={settings.defaultBpmTolerance} onChange={(event) => setSettings({ ...settings, defaultBpmTolerance: event.target.value })}/></label><label>Soft preference confidence<input type="number" min="0" max="1" step="0.05" value={settings.automaticSoftPreferenceMinimum} onChange={(event) => setSettings({ ...settings, automaticSoftPreferenceMinimum: event.target.value })}/></label><label>Hard requirement confidence<input type="number" min="0" max="1" step="0.05" value={settings.inferredHardRequirementMinimum} onChange={(event) => setSettings({ ...settings, inferredHardRequirementMinimum: event.target.value })}/></label><label>Retention days<input type="number" min="1" max="3650" value={settings.retentionDays} onChange={(event) => setSettings({ ...settings, retentionDays: event.target.value })}/></label></div>
    <button onClick={() => void save()} disabled={!!busy}>{busy === "save" ? <Loader2 className="animate-spin"/> : <Save/>} Save intent settings</button>
    <div className="intent-dictionary"><h4><BookOpen/> Personal interpretation dictionary</h4><p>Definitions stay local. Remote providers receive neither private definitions nor aliases.</p><div><input aria-label="Personal phrase" value={phrase} maxLength={200} onChange={(event) => setPhrase(event.target.value)} placeholder="Sunday cleaning"/><select aria-label="Canonical category" value={category} onChange={(event) => setCategory(event.target.value)}>{categories.map((item) => <option value={item} key={item}>{item.replaceAll("_", " ")}</option>)}</select><button disabled={phrase.trim().length < 2 || !!busy} onClick={() => void addEntry()}><Plus/> Add phrase</button></div><ul>{entries.map((entry) => <li key={entry.id}><span><strong>{entry.phrase}</strong><small>{(entry.definition?.categories || []).join(", ")} · {entry.visibility.toLowerCase()}</small></span>{entry.canEdit && <button aria-label={`Delete ${entry.phrase}`} disabled={!!busy} onClick={() => void removeEntry(entry.id)}>{busy === entry.id ? <Loader2 className="animate-spin"/> : <Trash2/>}</button>}</li>)}</ul></div>
    {message && <p role="status">{message}</p>}
  </div>;
}
