"use client";

import Link from "next/link";
import { useEffect, useState } from "react";
import { useRouter } from "next/navigation";
import { AlertTriangle, ArrowLeft, Check, CheckCircle2, Clock3, Eye, FilePenLine, Loader2, Play, RefreshCw, Save, Send, ShieldCheck, Sparkles, X } from "lucide-react";
import styles from "./NaturalLanguageRequests.module.css";

async function api(path: string, init?: RequestInit) { const response = await fetch(path, { ...init, headers: { "Content-Type": "application/json", ...(init?.headers || {}) } }); const body = await response.json(); if (!response.ok) throw new Error(body.error?.message || body.error || "Request failed."); return body; }
function label(value: string) { return String(value || "").replaceAll("_", " ").toLowerCase().replace(/^./, (character) => character.toUpperCase()); }
function confidence(value: number) { return value >= .8 ? "High" : value >= .5 ? "Medium" : "Low"; }
function fmt(value: unknown) { return typeof value === "object" ? JSON.stringify(value) : String(value ?? ""); }

export function NaturalLanguageRequestHome() {
  const router = useRouter();
  const [text, setText] = useState(""); const [privacyMode, setPrivacyMode] = useState("METADATA_LIMITED"); const [retain, setRetain] = useState(true);
  const [preflight, setPreflight] = useState<any>(null); const [requests, setRequests] = useState<any[]>([]); const [busy, setBusy] = useState(""); const [error, setError] = useState("");
  useEffect(() => { api("/api/natural-language-requests").then((value) => setRequests(value.requests || [])).catch(() => undefined); }, []);
  async function preview() { setBusy("preview"); setError(""); try { setPreflight(await api("/api/natural-language-requests/preflight", { method: "POST", body: JSON.stringify({ request: text, privacyMode, retainOriginalRequest: retain }) })); } catch (caught) { setError(caught instanceof Error ? caught.message : "Preflight failed."); } finally { setBusy(""); } }
  async function submit() { setBusy("submit"); setError(""); try { const body = await api("/api/natural-language-requests", { method: "POST", body: JSON.stringify({ request: text, privacyMode, retainOriginalRequest: retain }) }); router.push(`/ask-mixarr/${body.request.id}`); } catch (caught) { setError(caught instanceof Error ? caught.message : "Interpretation failed."); setBusy(""); } }
  return <main className={styles.page}>
    <header className={styles.hero}><div><span className={styles.eyebrow}><Sparkles size={15}/> Natural-language playlist requests</span><h1>Ask Mixarr</h1><p>Describe the mix you want. Mixarr will propose an editable recipe and deterministic preview; Plex remains unchanged until you explicitly approve and create it.</p></div><Link className={styles.secondary} href="/recipes/new">Create manually</Link></header>
    <section className={styles.compose} aria-labelledby="request-title"><h2 id="request-title">What should the playlist feel like?</h2><textarea value={text} maxLength={10000} onChange={(event) => { setText(event.target.value); setPreflight(null); }} placeholder="A focused coding playlist that starts calm, builds gradually, and avoids vocals." aria-describedby="request-help"/><small id="request-help">Include duration, genres, exclusions, energy, discovery, repetition, or a source playlist when useful.</small>
      <div className={styles.options}><label>Privacy mode<select value={privacyMode} onChange={(event) => { setPrivacyMode(event.target.value); setPreflight(null); }}><option value="LOCAL_ONLY">Local Only</option><option value="METADATA_LIMITED">Metadata Limited</option><option value="ANONYMOUS_METADATA">Anonymous Metadata</option><option value="FULL_METADATA">Full Metadata</option></select></label><label className={styles.check}><input type="checkbox" checked={retain} onChange={(event) => setRetain(event.target.checked)}/> Retain original wording for revision history</label></div>
      {error && <p className={styles.error} role="alert"><AlertTriangle size={16}/>{error}</p>}
      {preflight && <div className={styles.preflight} aria-live="polite"><ShieldCheck size={20}/><div><strong>{preflight.provider.name} · {preflight.model}</strong><p>{label(preflight.privacyMode)} · {preflight.provider.location} · estimated maximum cost {preflight.cost.currency} {Number(preflight.cost.maximumEstimatedCost || 0).toFixed(6)}</p><small>Estimated input {preflight.limits.estimatedInputTokens} tokens · maximum output {preflight.limits.maxOutputTokens}. Not shared: {preflight.notShared.join(", ")}. Plex changes: none.</small></div></div>}
      <div className={styles.actions}><button className={styles.secondary} disabled={text.trim().length < 3 || !!busy} onClick={() => void preview()}>{busy === "preview" ? <Loader2 className="animate-spin"/> : <Eye/>} Review privacy & cost</button><button className={styles.primary} disabled={!preflight || !!busy} onClick={() => void submit()}>{busy === "submit" ? <Loader2 className="animate-spin"/> : <Send/>} Interpret request</button></div>
    </section>
    <section className={styles.history}><h2>Recent requests</h2>{requests.length ? <div className={styles.requestList}>{requests.map((request) => <Link href={`/ask-mixarr/${request.id}`} key={request.id}><span data-status={request.status}>{request.status === "READY_FOR_APPROVAL" ? <CheckCircle2/> : <Clock3/>}</span><div><strong>{request.interpretation?.summary || request.originalRequest || "Private request"}</strong><small>Revision {request.currentRevision} · {label(request.status)} · {new Date(request.updatedAt).toLocaleString()}</small></div></Link>)}</div> : <p className={styles.empty}>No natural-language requests yet. Manual recipe creation remains available.</p>}</section>
  </main>;
}

export function NaturalLanguageRequestReview({ requestId }: { requestId: string }) {
  const [request, setRequest] = useState<any>(null); const [busy, setBusy] = useState(""); const [error, setError] = useState(""); const [revision, setRevision] = useState("");
  async function load() { setError(""); try { const body = await api(`/api/natural-language-requests/${requestId}`); setRequest(body.request); } catch (caught) { setError(caught instanceof Error ? caught.message : "Unable to load request."); } }
  useEffect(() => { void load(); }, [requestId]); // eslint-disable-line react-hooks/exhaustive-deps
  async function action(name: string, path: string, body?: unknown) { setBusy(name); setError(""); try { const value = await api(path, { method: "POST", body: JSON.stringify(body || {}) }); if (value.request) setRequest(value.request); else await load(); return value; } catch (caught) { setError(caught instanceof Error ? caught.message : "Action failed."); } finally { setBusy(""); } }
  async function approve() { if (!window.confirm("Approve this exact recipe revision? Approval does not change Plex. Any later edit will invalidate approval.")) return; await action("approve", `/api/natural-language-requests/${requestId}/approve`); }
  async function execute() { if (!window.confirm("Create this playlist in Plex now using Mixarr's deterministic engine? This is the first action in this flow that changes Plex.")) return; await action("execute", `/api/natural-language-requests/${requestId}/execute`, { playlistName: request.draftRecipe.metadata.name, idempotencyKey: `${requestId}:${request.currentRevision}` }); }
  async function resolveAmbiguity(id: string, body: unknown) { await action(`ambiguity-${id}`, `/api/natural-language-requests/${requestId}/ambiguities/${id}`, body); }
  async function resolveAssumption(id: string, body: unknown) { await action(`assumption-${id}`, `/api/natural-language-requests/${requestId}/assumptions/${id}`, body); }
  if (!request) return <main className={styles.state} aria-busy={!error}>{error ? <><AlertTriangle/><p>{error}</p></> : <><Loader2 className="animate-spin"/><p>Loading request review…</p></>}</main>;
  const interpretation = request.interpretation, recipe = request.draftRecipe, preview = request.preview;
  return <main className={styles.page}>
    <header className={styles.reviewHeader}><Link href="/ask-mixarr"><ArrowLeft/> Ask Mixarr</Link><div><span className={styles.eyebrow}><Sparkles/> Request review</span><h1>{recipe?.metadata?.name || "Playlist request"}</h1><p>{interpretation?.summary}</p></div><div className={styles.status} data-status={request.status}><strong>{label(request.status)}</strong><small>Revision {request.currentRevision}{request.approvalCurrent ? " · approved" : ""}</small></div></header>
    {error && <p className={styles.error} role="alert"><AlertTriangle/>{error}</p>}
    {request.status === "FAILED" && <section className={styles.card}><h2>Interpretation needs attention</h2><p>{request.errorMessage || "The provider or analysis step failed. Your request was preserved."}</p><div className={styles.actions}><button className={styles.secondary} disabled={!!busy || !request.originalRequest} onClick={() => void action("retry", `/api/natural-language-requests/${requestId}/interpret`)}><RefreshCw/> Retry interpretation</button><Link className={styles.secondary} href="/settings/ai">Review AI settings</Link></div></section>}
    <section className={styles.guardrail}><ShieldCheck/><div><strong>AI interprets; Mixarr selects.</strong><p>No provider output can select tracks or mutate Plex. The draft below passed through the canonical recipe schema and the preview came from Mixarr’s deterministic engine.</p></div></section>
    <div className={styles.reviewGrid}>
      <section className={styles.card}><h2>Original request</h2><blockquote>{request.originalRequest || "Original wording was not retained under the selected privacy setting."}</blockquote><dl><div><dt>Language</dt><dd>{interpretation?.detectedLanguage || "—"}</dd></div><div><dt>Provider</dt><dd>{request.providerDisplayName || request.providerConfigId || "—"}</dd></div><div><dt>Model</dt><dd>{request.model || "—"}</dd></div><div><dt>Privacy</dt><dd>{label(request.privacyMode)}</dd></div><div><dt>Cost</dt><dd>{request.actualCost == null ? `estimated ${Number(request.estimatedCost || 0).toFixed(6)}` : Number(request.actualCost).toFixed(6)}</dd></div></dl></section>
      <section className={styles.card}><h2>Interpretation</h2><div className={styles.confidence} data-level={confidence(interpretation?.confidence?.overall || 0)}><strong>{confidence(interpretation?.confidence?.overall || 0)} confidence</strong><span>{Math.round((interpretation?.confidence?.overall || 0) * 100)}%</span></div><h3>Explicit requirements</h3><ul>{interpretation?.explicitConstraints?.map((item: any) => <li key={item.id}><strong>{label(item.field)}:</strong> {fmt(item.value)}<small>{item.originalWording} · {confidence(item.confidence)}</small></li>)}</ul><h3>Inferred requirements</h3><ul>{interpretation?.inferredConstraints?.map((item: any) => <li key={item.id}><strong>{label(item.field)}:</strong> {fmt(item.value)}<small>{item.explanation} · {confidence(item.confidence)}</small></li>)}</ul></section>
    </div>
    <section className={styles.card}><div className={styles.sectionHeading}><div><h2>Assumptions and ambiguities</h2><p>Material low-confidence choices must be resolved before approval.</p></div><span>{request.blockingAmbiguities} blocking</span></div>
      <div className={styles.issueGrid}>{interpretation?.assumptions?.map((item: any) => <article className={styles.issue} key={item.id} data-blocking={item.blocking && !item.accepted}><header><strong>Assumption · {confidence(item.confidence)}</strong>{item.accepted ? <span>Accepted</span> : item.blocking && <span>Review required</span>}</header><p>{item.explanation}</p><small>{label(item.field)} → {fmt(item.proposedValue)}</small><div><button onClick={() => void resolveAssumption(item.id, { action: "accept" })} disabled={!!busy || item.accepted}><Check/> Accept</button><Link href={`/ask-mixarr/${requestId}/edit`}><FilePenLine/> Edit</Link><button onClick={() => void resolveAssumption(item.id, { action: "remove" })} disabled={!!busy}><X/> Remove</button></div></article>)}
      {interpretation?.ambiguities?.map((item: any) => <article className={styles.issue} key={item.id} data-blocking={item.requiresConfirmation && !item.resolution}><header><strong>Ambiguity · {confidence(item.confidence)}</strong>{item.resolution ? <span>Resolved</span> : item.requiresConfirmation && <span>Review required</span>}</header><p><q>{item.originalPhrase}</q> — {item.proposedInterpretation}</p><small>{item.reason}</small><div><button onClick={() => void resolveAmbiguity(item.id, { action: "accept" })} disabled={!!busy}><Check/> Accept</button>{item.alternatives.map((alternative: any) => <button key={alternative.id} onClick={() => void resolveAmbiguity(item.id, { action: "alternative", alternativeId: alternative.id })} disabled={!!busy}>{alternative.label}</button>)}<button onClick={() => void resolveAmbiguity(item.id, { action: "remove" })} disabled={!!busy}><X/> Remove</button></div></article>)}</div>
    </section>
    <section className={styles.card}>
      <div className={styles.sectionHeading}>
        <div><h2>Draft recipe</h2><p>Every behavior is represented in the normal Mixarr recipe schema.</p></div>
        <Link className={styles.secondary} href={`/ask-mixarr/${requestId}/edit`}><FilePenLine/> Edit in Recipe Studio</Link>
      </div>
      {recipe && <div className={styles.recipeGrid}>
        <Metric label="Tracks" value={recipe.generation.limit}/>
        <Metric label="BPM" value={`${recipe.bpmFlow.minimumBpm ?? "any"}–${recipe.bpmFlow.maximumBpm ?? "any"}`}/>
        <Metric label="Energy" value={label(recipe.targets.energyProgression)}/>
        <Metric label="Discovery" value={`${recipe.discovery.familiarityBalance}% familiar`}/>
        <Metric label="Artist spacing" value={`${recipe.variety.minimumArtistSpacing} tracks`}/>
        <Metric label="Refresh" value={label(recipe.refreshPolicy.mode)}/>
        <Metric label="Automation" value="Off until separately confirmed"/>
        <Metric label="Plex changes" value="None"/>
      </div>}
    </section>
    <div className={styles.reviewGrid}><section className={styles.card}><h2>Candidate analysis</h2><div className={styles.recipeGrid}><Metric label="Matching candidates" value={request.candidateEstimate?.matchingCandidates?.toLocaleString() || "0"}/><Metric label="Unique artists" value={request.candidateEstimate?.uniqueArtists?.toLocaleString() || "0"}/><Metric label="Expected size" value={request.candidateEstimate?.requestedPlaylistSize || recipe?.generation?.limit || "—"}/><Metric label="Headroom" value={`${request.candidateEstimate?.headroom || 0}×`}/><Metric label="Compatibility" value={`${request.compatibility?.score || 0}%`}/><Metric label="Analysis" value={request.analysisStale ? "Stale" : "Current"}/></div>{request.compatibility?.findings?.map((finding: any) => <p className={styles.finding} key={finding.code}><AlertTriangle/>{finding.message}</p>)}</section>
      <section className={styles.card}><div className={styles.sectionHeading}><div><h2>Deterministic preview</h2><p>{preview?.summary?.finalTrackCount || 0} tracks · {preview?.summary?.estimatedDurationMinutes || 0} minutes</p></div><button className={styles.secondary} disabled={!!busy} onClick={() => void action("preview", `/api/natural-language-requests/${requestId}/preview`)}><RefreshCw/> Refresh</button></div>{preview?.tracks?.length ? <ol className={styles.tracks}>{preview.tracks.slice(0, 12).map((track: any, index: number) => <li key={track.id || index}><span>{index + 1}</span><div><strong>{track.title}</strong><small>{track.artist?.title || track.artist || "Unknown artist"}{track.bpm ? ` · ${Math.round(track.bpm)} BPM` : ""}</small></div></li>)}</ol> : <p className={styles.empty}>Preview unavailable. Review the error and refresh analysis.</p>}</section></div>
    <section className={styles.card}><h2>Revise without starting over</h2><div className={styles.revise}><input value={revision} onChange={(event) => setRevision(event.target.value)} placeholder="Keep everything else, but start at 100 BPM."/><button className={styles.secondary} disabled={revision.trim().length < 2 || !!busy} onClick={async () => { await action("revise", `/api/natural-language-requests/${requestId}/revisions`, { revision }); setRevision(""); }}><RefreshCw/> Revise</button></div>{request.revisions?.[0]?.changeSummaryJson?.length > 0 && <details><summary>Latest before-and-after changes</summary><ul>{request.revisions[0].changeSummaryJson.map((item: any) => <li key={item.path}><strong>{item.path}</strong>: {fmt(item.before)} → {fmt(item.after)}</li>)}</ul></details>}</section>
    <footer className={styles.approval}><div><strong>Approval applies only to revision {request.currentRevision}.</strong><p>Editing or revising invalidates it. Saving creates a reusable recipe; executing creates the Plex playlist.</p></div><div><button className={styles.secondary} onClick={() => void action("cancel", `/api/natural-language-requests/${requestId}/cancel`)} disabled={!!busy || ["COMPLETED","CANCELLED","EXECUTING"].includes(request.status)}><X/> Cancel</button><button className={styles.primary} onClick={() => void approve()} disabled={!!busy || request.status !== "READY_FOR_APPROVAL"}><CheckCircle2/> Approve</button><button className={styles.secondary} onClick={() => void action("save", `/api/natural-language-requests/${requestId}/save`)} disabled={!!busy || !request.approvalCurrent}><Save/> Save recipe</button><button className={styles.danger} onClick={() => void execute()} disabled={!!busy || !request.approvalCurrent}><Play/> Approve & create</button></div></footer>
  </main>;
}

function Metric({ label: name, value }: { label: string; value: React.ReactNode }) { return <div className={styles.metric}><small>{name}</small><strong>{value}</strong></div>; }
