"use client";

import Link from "next/link";
import { useEffect, useState } from "react";
import { useRouter } from "next/navigation";
import { AlertTriangle, ArrowDown, ArrowLeft, ArrowUp, Check, CheckCircle2, Clock3, Copy, Eye, FilePenLine, Loader2, Play, Plus, RefreshCw, Save, Send, ShieldCheck, Sparkles, Trash2, X } from "lucide-react";
import styles from "./NaturalLanguageRequests.module.css";

async function api(path: string, init?: RequestInit) { const response = await fetch(path, { ...init, headers: { "Content-Type": "application/json", ...(init?.headers || {}) } }); const body = await response.json(); if (!response.ok) throw new Error(body.error?.message || body.error || "Request failed."); return body; }
function label(value: string) { return String(value || "").replaceAll("_", " ").toLowerCase().replace(/^./, (character) => character.toUpperCase()); }
function confidence(value: number) { return value >= .8 ? "High" : value >= .5 ? "Medium" : "Low"; }
function fmt(value: unknown) { return typeof value === "object" ? JSON.stringify(value) : String(value ?? ""); }

export function NaturalLanguageRequestHome() {
  const router = useRouter();
  const [text, setText] = useState(""); const [privacyMode, setPrivacyMode] = useState("LOCAL_ONLY"); const [retain, setRetain] = useState(true);
  const [preflight, setPreflight] = useState<any>(null); const [requests, setRequests] = useState<any[]>([]); const [busy, setBusy] = useState(""); const [error, setError] = useState("");
  useEffect(() => { api("/api/natural-language-requests").then((value) => setRequests(value.requests || [])).catch(() => undefined); }, []);
  async function preview() { setBusy("preview"); setError(""); try { setPreflight(await api("/api/natural-language-requests/preflight", { method: "POST", body: JSON.stringify({ request: text, privacyMode, retainOriginalRequest: retain }) })); } catch (caught) { setError(caught instanceof Error ? caught.message : "Preflight failed."); } finally { setBusy(""); } }
  async function submit() { setBusy("submit"); setError(""); try { const body = await api("/api/natural-language-requests", { method: "POST", body: JSON.stringify({ request: text, privacyMode, retainOriginalRequest: retain }) }); router.push(`/ask-mixarr/${body.request.id}`); } catch (caught) { setError(caught instanceof Error ? caught.message : "Interpretation failed."); setBusy(""); } }
  return <main className={styles.page}>
    <header className={styles.hero}><div><span className={styles.eyebrow}><Sparkles size={15}/> Mood, activity &amp; intent intelligence</span><h1>Ask Mixarr</h1><p>Describe the mood, activity, progression, energy, or tempo you want. Local interpretation works without AI; final track selection remains deterministic and nothing changes in Plex before approval.</p></div><Link className={styles.secondary} href="/recipes/new">Create manually</Link></header>
    <section className={styles.compose} aria-labelledby="request-title"><h2 id="request-title">What should the playlist feel like?</h2><textarea value={text} maxLength={10000} onChange={(event) => { setText(event.target.value); setPreflight(null); }} placeholder="A focused coding playlist that starts calm, builds gradually, and avoids vocals." aria-describedby="request-help"/><small id="request-help">Include duration, genres, exclusions, energy, discovery, repetition, or a source playlist when useful.</small>
      <div className={styles.options}><label>Privacy mode<select value={privacyMode} onChange={(event) => { setPrivacyMode(event.target.value); setPreflight(null); }}><option value="LOCAL_ONLY">Local Only</option><option value="METADATA_LIMITED">Metadata Limited</option><option value="ANONYMOUS_METADATA">Anonymous Metadata</option><option value="FULL_METADATA">Full Metadata</option></select></label><label className={styles.check}><input type="checkbox" checked={retain} onChange={(event) => setRetain(event.target.checked)}/> Retain original wording for revision history</label></div>
      {error && <p className={styles.error} role="alert"><AlertTriangle size={16}/>{error}</p>}
      {preflight && <div className={styles.preflight} aria-live="polite"><ShieldCheck size={20}/><div><strong>{preflight.provider.name} · {preflight.model}</strong><p>{label(preflight.privacyMode)} · {preflight.provider.location} · estimated maximum cost {preflight.cost.currency} {Number(preflight.cost.maximumEstimatedCost || 0).toFixed(6)}</p><small>{preflight.localFirst ? "Interpreted entirely on this Mixarr server. " : `Estimated input ${preflight.limits.estimatedInputTokens} tokens. `}Not shared: {preflight.notShared.join(", ")}. Plex changes: none.</small></div></div>}
      <div className={styles.actions}><button className={styles.secondary} disabled={text.trim().length < 3 || !!busy} onClick={() => void preview()}>{busy === "preview" ? <Loader2 className="animate-spin"/> : <Eye/>} Review privacy & cost</button><button className={styles.primary} disabled={!preflight || !!busy} onClick={() => void submit()}>{busy === "submit" ? <Loader2 className="animate-spin"/> : <Send/>} Interpret locally</button></div>
    </section>
    <section className={styles.history}><h2>Recent requests</h2>{requests.length ? <div className={styles.requestList}>{requests.map((request) => <Link href={`/ask-mixarr/${request.id}`} key={request.id}><span data-status={request.status}>{request.status === "READY_FOR_APPROVAL" ? <CheckCircle2/> : <Clock3/>}</span><div><strong>{request.interpretation?.summary || request.originalRequest || "Private request"}</strong><small>Revision {request.currentRevision} · {label(request.status)} · {new Date(request.updatedAt).toLocaleString()}</small></div></Link>)}</div> : <p className={styles.empty}>No natural-language requests yet. Manual recipe creation remains available.</p>}</section>
  </main>;
}

export function NaturalLanguageRequestReview({ requestId }: { requestId: string }) {
  const [request, setRequest] = useState<any>(null); const [busy, setBusy] = useState(""); const [error, setError] = useState(""); const [revision, setRevision] = useState("");
  async function load() { setError(""); try { const body = await api(`/api/natural-language-requests/${requestId}`); setRequest(body.request); } catch (caught) { setError(caught instanceof Error ? caught.message : "Unable to load request."); } }
  useEffect(() => { void load(); }, [requestId]); // eslint-disable-line react-hooks/exhaustive-deps
  async function action(name: string, path: string, body?: unknown) { setBusy(name); setError(""); try { const value = await api(path, { method: "POST", body: JSON.stringify(body || {}) }); if (value.request) setRequest(value.request); else await load(); return value; } catch (caught) { setError(caught instanceof Error ? caught.message : "Action failed."); } finally { setBusy(""); } }
  async function approve() { if (!window.confirm("Approve this exact recipe revision? Approval does not change Plex. Any later edit will invalidate approval.")) return; await action("approve", `/api/natural-language-requests/${requestId}/approve`); }
  async function execute() { if (!window.confirm("Create this playlist in Plex now using Mixarr's deterministic engine? This is the first action in this flow that changes Plex.")) return; await action("execute", `/api/natural-language-requests/${requestId}/execute`, { playlistName: request.draftRecipe.metadata.name, idempotencyKey: `${requestId}:${request.currentRevision}` }); }
  async function resolveAmbiguity(id: string, body: unknown) { await action(`ambiguity-${id}`, `/api/natural-language-requests/${requestId}/ambiguities/${id}`, body); }
  async function resolveAssumption(id: string, body: unknown) { await action(`assumption-${id}`, `/api/natural-language-requests/${requestId}/assumptions/${id}`, body); }
  async function saveStructuredIntent(intent: any) { setBusy("intent-edit"); setError(""); try { const value = await api(`/api/natural-language-requests/${requestId}/intent`, { method: "PUT", body: JSON.stringify({ intent }) }); setRequest(value.request); } catch (caught) { setError(caught instanceof Error ? caught.message : "Intent update failed."); } finally { setBusy(""); } }
  async function saveIntentPreset(intent: any) { setBusy("preset"); setError(""); try { await api("/api/intent-presets", { method: "POST", body: JSON.stringify({ name: `${request.draftRecipe?.metadata?.name || "Playlist"} intent`, description: intent.summary, intent }) }); } catch (caught) { setError(caught instanceof Error ? caught.message : "Preset save failed."); } finally { setBusy(""); } }
  if (!request) return <main className={styles.state} aria-busy={!error}>{error ? <><AlertTriangle/><p>{error}</p></> : <><Loader2 className="animate-spin"/><p>Loading request review…</p></>}</main>;
  const interpretation = request.interpretation, structured = interpretation?.structuredIntent, recipe = request.draftRecipe, preview = request.preview;
  return <main className={styles.page}>
    <header className={styles.reviewHeader}><Link href="/ask-mixarr"><ArrowLeft/> Ask Mixarr</Link><div><span className={styles.eyebrow}><Sparkles/> Request review</span><h1>{recipe?.metadata?.name || "Playlist request"}</h1><p>{interpretation?.summary}</p></div><div className={styles.status} data-status={request.status}><strong>{label(request.status)}</strong><small>Revision {request.currentRevision}{request.approvalCurrent ? " · approved" : ""}</small></div></header>
    {error && <p className={styles.error} role="alert"><AlertTriangle/>{error}</p>}
    {request.status === "FAILED" && <section className={styles.card}><h2>Interpretation needs attention</h2><p>{request.errorMessage || "The provider or analysis step failed. Your request was preserved."}</p><div className={styles.actions}><button className={styles.secondary} disabled={!!busy || !request.originalRequest} onClick={() => void action("retry", `/api/natural-language-requests/${requestId}/interpret`)}><RefreshCw/> Retry interpretation</button><Link className={styles.secondary} href="/settings/ai">Review AI settings</Link></div></section>}
    <section className={styles.guardrail}><ShieldCheck/><div><strong>AI interprets; Mixarr selects.</strong><p>No provider output can select tracks or mutate Plex. The draft below passed through the canonical recipe schema and the preview came from Mixarr’s deterministic engine.</p></div></section>
    {structured && <section className={styles.card} aria-labelledby="recognized-intent-title">
      <div className={styles.sectionHeading}><div><h2 id="recognized-intent-title">Recognized intent</h2><p>Editable structured signals passed through Mixarr&apos;s deterministic adapter.</p></div><div className={styles.actions}><span>{label(structured.interpretationSource)} · {confidence(structured.overallConfidence)}</span><button className={styles.secondary} disabled={!!busy} onClick={() => void saveIntentPreset(structured)}><Save/> Save intent preset</button></div></div>
      <IntentCategoryEditor structured={structured} disabled={!!busy} onSave={(next) => void saveStructuredIntent(next)}/>
      <div className={styles.privacyNote}><ShieldCheck/><span><strong>{structured.interpretationSource === "LOCAL_DICTIONARY" ? "Custom terminology resolved locally" : "Local-first interpretation"}</strong><small>Personal and household dictionary definitions were not sent to a remote provider.</small></span></div>
      <IntentPreferenceEditor structured={structured} disabled={!!busy} onSave={(next) => void saveStructuredIntent(next)}/>
      {structured.conflicts.length > 0 && <div className={styles.conflictList} role="alert"><h3>Conflicts and tensions</h3>{structured.conflicts.map((item: any) => <article key={item.id}><strong>{label(item.type)}</strong><p>{item.explanation}</p><small>{item.suggestion}</small>{item.resolution ? <p>Resolved: {label(item.resolution.action)}</p> : <button className={styles.secondary} disabled={!!busy} onClick={() => { const conflicts = structured.conflicts.map((conflict: any) => conflict.id === item.id ? { ...conflict, resolution: { winnerId: conflict.itemIds[0] || null, action: "SOFTEN", note: "Resolved during user review." } } : conflict); void saveStructuredIntent({ ...structured, conflicts, requiresReview: conflicts.some((conflict: any) => conflict.type === "HARD_CONFLICT" && !conflict.resolution) }); }}><Check/> Keep first and soften conflict</button>}</article>)}</div>}
      <IntentPhaseEditor structured={structured} disabled={!!busy} onSave={(next) => void saveStructuredIntent(next)}/>
      <div className={styles.curveGrid}><CurveSummary title="Energy curve" curve={structured.energyCurve}/><CurveSummary title="BPM curve" curve={structured.bpmCurve}/></div>
      {structured.warnings.map((warning: string) => <p className={styles.finding} key={warning}><AlertTriangle/>{warning}</p>)}
    </section>}
    <div className={styles.reviewGrid}>
      <section className={styles.card}><h2>Original request</h2><blockquote>{request.originalRequest || "Original wording was not retained under the selected privacy setting."}</blockquote><dl><div><dt>Language</dt><dd>{interpretation?.detectedLanguage || "—"}</dd></div><div><dt>Provider</dt><dd>{request.providerDisplayName || request.providerConfigId || "—"}</dd></div><div><dt>Model</dt><dd>{request.model || "—"}</dd></div><div><dt>Privacy</dt><dd>{label(request.privacyMode)}</dd></div><div><dt>Cost</dt><dd>{request.actualCost == null ? `estimated ${Number(request.estimatedCost || 0).toFixed(6)}` : Number(request.actualCost).toFixed(6)}</dd></div></dl></section>
      <section className={styles.card}><h2>Interpretation</h2><div className={styles.confidence} data-level={confidence(interpretation?.confidence?.overall || 0)}><strong>{confidence(interpretation?.confidence?.overall || 0)} confidence</strong><span>{Math.round((interpretation?.confidence?.overall || 0) * 100)}%</span></div><h3>Explicit requirements</h3><ul>{interpretation?.explicitConstraints?.map((item: any) => <li key={item.id}><strong>{label(item.field)}:</strong> {fmt(item.value)}<small>{item.originalWording} · {confidence(item.confidence)}</small></li>)}</ul><h3>Inferred requirements</h3><ul>{interpretation?.inferredConstraints?.map((item: any) => <li key={item.id}><strong>{label(item.field)}:</strong> {fmt(item.value)}<small>{item.explanation} · {confidence(item.confidence)}</small></li>)}</ul></section>
    </div>
    <section className={styles.card}><div className={styles.sectionHeading}><div><h2>Assumptions and ambiguities</h2><p>Material low-confidence choices must be resolved before approval.</p></div><span>{request.blockingAmbiguities} blocking</span></div>
      <div className={styles.issueGrid}>{interpretation?.assumptions?.map((item: any) => <article className={styles.issue} key={item.id} data-blocking={item.blocking && !item.accepted}><header><strong>Assumption · {confidence(item.confidence)}</strong>{item.accepted ? <span>Accepted</span> : item.blocking && <span>Review required</span>}</header><p>{item.explanation}</p><small>{label(item.field)} → {fmt(item.proposedValue)}</small><div><button onClick={() => void resolveAssumption(item.id, { action: "accept" })} disabled={!!busy || item.accepted}><Check/> Accept</button><Link href={`/ask-mixarr/${requestId}/edit`}><FilePenLine/> Edit</Link><button onClick={() => void resolveAssumption(item.id, { action: "remove" })} disabled={!!busy}><X/> Remove</button></div></article>)}
      {interpretation?.ambiguities?.map((item: any) => <article className={styles.issue} key={item.id} data-blocking={item.requiresConfirmation && !item.resolution}><header><strong>Ambiguity · {confidence(item.confidence)}</strong>{item.resolution ? <span>Resolved</span> : item.requiresConfirmation && <span>Review required</span>}</header><p><q>{item.originalPhrase}</q> — {item.proposedInterpretation}</p><small>{item.reason}</small><div><button onClick={() => void resolveAmbiguity(item.id, { action: "accept" })} disabled={!!busy}><Check/> Accept</button>{item.alternatives.map((alternative: any) => <button key={alternative.id} onClick={() => void resolveAmbiguity(item.id, { action: "alternative", alternativeId: alternative.id })} disabled={!!busy}>{alternative.label}</button>)}<button onClick={() => void resolveAmbiguity(item.id, { action: "remove" })} disabled={!!busy}><X/> Remove</button></div></article>)}</div>
    </section>
    <section className={styles.card}>
      <div className={styles.sectionHeading}>
        <div><h2>Draft recipe</h2><p>Every behavior is represented in the normal Mixarr recipe schema.</p></div>
        <Link className={styles.secondary} href={`/ask-mixarr/${requestId}/edit`}><FilePenLine/> Edit in Recipe Studio</Link>
      </div>
      {recipe && <div className={styles.recipeGrid}>
        <Metric label="Tracks" value={recipe.generation.limit}/>
        <Metric label="BPM" value={`${recipe.bpmFlow.minimumBpm ?? "any"}–${recipe.bpmFlow.maximumBpm ?? "any"}`}/>
        <Metric label="Energy" value={label(recipe.targets.energyProgression)}/>
        <Metric label="Discovery" value={`${recipe.discovery.familiarityBalance}% familiar`}/>
        <Metric label="Artist spacing" value={`${recipe.variety.minimumArtistSpacing} tracks`}/>
        <Metric label="Refresh" value={label(recipe.refreshPolicy.mode)}/>
        <Metric label="Automation" value="Off until separately confirmed"/>
        <Metric label="Plex changes" value="None"/>
      </div>}
    </section>
    <div className={styles.reviewGrid}><section className={styles.card}><h2>Candidate analysis</h2><div className={styles.recipeGrid}><Metric label="Matching candidates" value={request.candidateEstimate?.matchingCandidates?.toLocaleString() || "0"}/><Metric label="Unique artists" value={request.candidateEstimate?.uniqueArtists?.toLocaleString() || "0"}/><Metric label="Expected size" value={request.candidateEstimate?.requestedPlaylistSize || recipe?.generation?.limit || "—"}/><Metric label="Headroom" value={`${request.candidateEstimate?.headroom || 0}×`}/><Metric label="Compatibility" value={`${request.compatibility?.score || 0}%`}/><Metric label="Analysis" value={request.analysisStale ? "Stale" : "Current"}/></div>{request.compatibility?.findings?.map((finding: any) => <p className={styles.finding} key={finding.code}><AlertTriangle/>{finding.message}</p>)}</section>
      <section className={styles.card}><div className={styles.sectionHeading}><div><h2>Deterministic preview</h2><p>{preview?.summary?.finalTrackCount || 0} tracks · {preview?.summary?.estimatedDurationMinutes || 0} minutes</p></div><button className={styles.secondary} disabled={!!busy} onClick={() => void action("preview", `/api/natural-language-requests/${requestId}/preview`)}><RefreshCw/> Refresh</button></div>{preview?.tracks?.length ? <ol className={styles.tracks}>{preview.tracks.slice(0, 12).map((track: any, index: number) => <li key={track.id || index}><span>{index + 1}</span><div><strong>{track.title}</strong><small>{track.artist?.title || track.artist || "Unknown artist"}{track.bpm ? ` · ${Math.round(track.bpm)} BPM` : ""}</small></div></li>)}</ol> : <p className={styles.empty}>Preview unavailable. Review the error and refresh analysis.</p>}</section></div>
    <section className={styles.card}><h2>Revise without starting over</h2><div className={styles.revise}><input value={revision} onChange={(event) => setRevision(event.target.value)} placeholder="Keep everything else, but start at 100 BPM."/><button className={styles.secondary} disabled={revision.trim().length < 2 || !!busy} onClick={async () => { await action("revise", `/api/natural-language-requests/${requestId}/revisions`, { revision }); setRevision(""); }}><RefreshCw/> Revise</button></div>{request.revisions?.[0]?.changeSummaryJson?.length > 0 && <details><summary>Latest before-and-after changes</summary><ul>{request.revisions[0].changeSummaryJson.map((item: any) => <li key={item.path}><strong>{item.path}</strong>: {fmt(item.before)} → {fmt(item.after)}</li>)}</ul></details>}</section>
    <footer className={styles.approval}><div><strong>Approval applies only to revision {request.currentRevision}.</strong><p>Editing or revising invalidates it. Saving creates a reusable recipe; executing creates the Plex playlist.</p></div><div><button className={styles.secondary} onClick={() => void action("cancel", `/api/natural-language-requests/${requestId}/cancel`)} disabled={!!busy || ["COMPLETED","CANCELLED","EXECUTING"].includes(request.status)}><X/> Cancel</button><button className={styles.primary} onClick={() => void approve()} disabled={!!busy || request.status !== "READY_FOR_APPROVAL"}><CheckCircle2/> Approve</button><button className={styles.secondary} onClick={() => void action("save", `/api/natural-language-requests/${requestId}/save`)} disabled={!!busy || !request.approvalCurrent}><Save/> Save recipe</button><button className={styles.danger} onClick={() => void execute()} disabled={!!busy || !request.approvalCurrent}><Play/> Approve & create</button></div></footer>
  </main>;
}

function IntentCategoryEditor({ structured, disabled, onSave }: { structured: any; disabled: boolean; onSave: (intent: any) => void }) {
  const [categories, setCategories] = useState<any[]>(structured.categories || []);
  useEffect(() => setCategories(structured.categories || []), [structured]);
  return <div><div className={styles.intentBadges}>{categories.map((item, index) => <label key={item.name}><span>{label(item.name)} · {confidence(item.confidence)}</span><input aria-label={`${label(item.name)} weight`} type="range" min="0" max="1" step="0.05" value={item.weight} onChange={(event) => setCategories(categories.map((category, categoryIndex) => categoryIndex === index ? { ...category, weight: Number(event.target.value) } : category))}/><button aria-label={`Remove ${label(item.name)}`} disabled={disabled} onClick={() => setCategories(categories.filter((_, categoryIndex) => categoryIndex !== index))}><X/></button></label>)}</div>{JSON.stringify(categories) !== JSON.stringify(structured.categories) && <button className={styles.secondary} disabled={disabled} onClick={() => onSave({ ...structured, categories, requiresReview: true })}><Save/> Save category edits</button>}</div>;
}

function IntentPreferenceEditor({ structured, disabled, onSave }: { structured: any; disabled: boolean; onSave: (intent: any) => void }) {
  const original = [...(structured.positivePreferences || []), ...(structured.negativePreferences || [])];
  const [items, setItems] = useState<any[]>(original);
  useEffect(() => setItems([...(structured.positivePreferences || []), ...(structured.negativePreferences || [])]), [structured]);
  const strengths = ["REQUIRED", "PREFERRED", "NEUTRAL", "DISCOURAGED", "EXCLUDED"];
  function save() {
    const edited = items.map((item) => ({ ...item, userEdited: item.strength !== original.find((source: any) => source.id === item.id)?.strength || item.userEdited, confidence: item.strength === "REQUIRED" || item.strength === "EXCLUDED" ? 1 : item.confidence, classificationConfidence: 1 }));
    const positivePreferences = edited.filter((item) => ["REQUIRED", "PREFERRED", "NEUTRAL"].includes(item.strength));
    const negativePreferences = edited.filter((item) => ["DISCOURAGED", "EXCLUDED"].includes(item.strength));
    const hardRequirements = edited.filter((item) => ["REQUIRED", "EXCLUDED"].includes(item.strength));
    const softPreferences = edited.filter((item) => ["PREFERRED", "DISCOURAGED"].includes(item.strength));
    onSave({ ...structured, positivePreferences, negativePreferences, hardRequirements, softPreferences, requiresReview: structured.conflicts.some((conflict: any) => conflict.type === "HARD_CONFLICT" && !conflict.resolution) });
  }
  return <div className={styles.preferenceEditor}><div className={styles.sectionHeading}><div><h3>Preferences and requirements</h3><p>Change any interpretation between required, preferred, neutral, discouraged, or excluded.</p></div><button className={styles.secondary} disabled={disabled} onClick={save}><Save/> Save preference edits</button></div><div className={styles.preferenceList}>{items.map((item, index) => <label key={item.id}><span><strong>{item.target}</strong><small>{label(item.type)} · {confidence(item.confidence)} · {item.scope.phaseId ? `Phase ${item.scope.phaseId}` : "Entire playlist"}</small></span><select aria-label={`${item.target} strength`} value={item.strength} onChange={(event) => setItems(items.map((preference, preferenceIndex) => preferenceIndex === index ? { ...preference, strength: event.target.value } : preference))}>{strengths.map((strength) => <option key={strength} value={strength}>{label(strength)}</option>)}</select></label>)}</div></div>;
}

function normalizeShares(phases: any[]) {
  const total = phases.reduce((sum, phase) => sum + Math.max(.01, Number(phase.targetShare) || 0), 0);
  const normalized = phases.map((phase, index) => ({ ...phase, position: index + 1, targetShare: Math.round((Math.max(.01, Number(phase.targetShare) || 0) / total) * 1000) / 1000 }));
  if (normalized.length) normalized[normalized.length - 1].targetShare = Math.round((1 - normalized.slice(0, -1).reduce((sum, phase) => sum + phase.targetShare, 0)) * 1000) / 1000;
  return normalized;
}

function IntentPhaseEditor({ structured, disabled, onSave }: { structured: any; disabled: boolean; onSave: (intent: any) => void }) {
  const [phases, setPhases] = useState<any[]>(structured.phases || []);
  useEffect(() => setPhases(structured.phases || []), [structured]);
  if (!phases.length) return <div className={styles.phaseEditor}><div className={styles.sectionHeading}><div><h3>Phases</h3><p>No phase boundaries were inferred. Add phases if you want a staged progression.</p></div><button disabled={disabled} onClick={() => setPhases(normalizeShares([{ id: `phase-${Date.now()}-1`, position: 1, label: "Opening", targetShare: .5, categories: [], energy: null, valence: null, tempo: null, vocalMode: "ANY", transition: "SMOOTH", confidence: 1, sourcePhrase: null }, { id: `phase-${Date.now()}-2`, position: 2, label: "Finish", targetShare: .5, categories: [], energy: null, valence: null, tempo: null, vocalMode: "ANY", transition: "SMOOTH", confidence: 1, sourcePhrase: null }]))}><Plus/> Add phases</button></div></div>;
  const update = (index: number, patch: any) => setPhases(phases.map((phase, phaseIndex) => phaseIndex === index ? { ...phase, ...patch } : phase));
  const move = (index: number, direction: number) => { const next = [...phases], target = index + direction; if (target < 0 || target >= next.length) return; [next[index], next[target]] = [next[target], next[index]]; setPhases(normalizeShares(next)); };
  return <div className={styles.phaseEditor}><div className={styles.sectionHeading}><div><h3>Playlist phases</h3><p>Rename, reorder, duplicate, remove, or resize phases. Percentages are normalized to 100% when saved.</p></div><button className={styles.primary} disabled={disabled} onClick={() => onSave({ ...structured, phases: normalizeShares(phases), phaseBoundaryConfidence: 1, requiresReview: structured.conflicts.some((item: any) => item.type === "HARD_CONFLICT" && !item.resolution) })}><Save/> Save phases</button></div>
    <div className={styles.phaseList}>{phases.map((phase, index) => <article key={phase.id}><div className={styles.phasePosition}>{index + 1}</div><label>Phase name<input aria-label={`Phase ${index + 1} name`} value={phase.label} maxLength={100} onChange={(event) => update(index, { label: event.target.value })}/></label><label>Share<input aria-label={`${phase.label} percentage`} type="number" min="1" max="99" value={Math.round(phase.targetShare * 100)} onChange={(event) => update(index, { targetShare: Number(event.target.value) / 100 })}/><span>%</span></label><small>{phase.energy?.label || (phase.energy?.preferred != null ? `${Math.round(phase.energy.preferred * 100)}% energy` : "Any energy")} · {phase.tempo?.preferredBpm ? `${Math.round(phase.tempo.preferredBpm)} BPM` : phase.tempo?.label || "Any tempo"}</small><div className={styles.phaseActions}><button aria-label={`Move ${phase.label} up`} disabled={disabled || index === 0} onClick={() => move(index, -1)}><ArrowUp/></button><button aria-label={`Move ${phase.label} down`} disabled={disabled || index === phases.length - 1} onClick={() => move(index, 1)}><ArrowDown/></button><button aria-label={`Duplicate ${phase.label}`} disabled={disabled || phases.length >= 6} onClick={() => setPhases(normalizeShares([...phases.slice(0, index + 1), { ...phase, id: `phase-${Date.now()}`, label: `${phase.label} copy` }, ...phases.slice(index + 1)]))}><Copy/></button><button aria-label={`Remove ${phase.label}`} disabled={disabled || phases.length <= 2} onClick={() => setPhases(normalizeShares(phases.filter((_, phaseIndex) => phaseIndex !== index)))}><Trash2/></button></div></article>)}</div>
    <button className={styles.secondary} disabled={disabled || phases.length >= 6} onClick={() => setPhases(normalizeShares([...phases, { ...phases[phases.length - 1], id: `phase-${Date.now()}`, label: `Phase ${phases.length + 1}`, sourcePhrase: null }]))}><Plus/> Add phase</button>
  </div>;
}

function CurveSummary({ title, curve }: { title: string; curve: any }) {
  if (!curve) return <div className={styles.curveCard}><h3>{title}</h3><p>No curve requested.</p></div>;
  const description = curve.points.map((point: any) => `${Math.round(point.position * 100)}%: ${title.startsWith("BPM") ? Math.round(point.value) + " BPM" : Math.round(point.value * 100) + "%"}`).join(", ");
  return <div className={styles.curveCard} aria-label={`${title}: ${label(curve.shape)}. ${description}`}><h3>{title}</h3><strong>{label(curve.shape)}</strong><div className={styles.curveBars} aria-hidden="true">{curve.points.map((point: any, index: number) => <span key={`${point.position}-${index}`} style={{ height: `${title.startsWith("BPM") ? Math.max(12, Math.min(100, ((point.value - 30) / 170) * 100)) : Math.max(8, point.value * 100)}%` }}/>)}</div><small>{description} · tolerance {curve.tolerance}{title.startsWith("BPM") ? " BPM" : ""}</small></div>;
}

function Metric({ label: name, value }: { label: string; value: React.ReactNode }) { return <div className={styles.metric}><small>{name}</small><strong>{value}</strong></div>; }
