"use client";
import { useEffect, useState } from "react";
import styles from "./OrchestrationSettings.module.css";

export default function OrchestrationSettings() {
  const [settings, setSettings] = useState<any>(null); const [message, setMessage] = useState(""); const [error, setError] = useState(""); const [busy, setBusy] = useState(false);
  useEffect(() => { fetch("/api/settings/orchestration", { cache: "no-store" }).then(async (response) => ({ response, data: await response.json() })).then(({ response, data }) => { if (response.status === 403) return setError("Administrator access is required to change global orchestration controls."); if (!response.ok) throw new Error(data.error?.message || "Settings unavailable."); setSettings(data.settings); }).catch((caught) => setError(caught instanceof Error ? caught.message : "Settings unavailable.")); }, []);
  async function save() { setBusy(true); setMessage(""); setError(""); try { const response = await fetch("/api/settings/orchestration", { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify(settings) }); const data = await response.json(); if (!response.ok) throw new Error(data.error?.message || "Unable to save orchestration settings."); setSettings(data.settings); setMessage("Playlist orchestration settings saved."); } catch (caught) { setError(caught instanceof Error ? caught.message : "Unable to save settings."); } finally { setBusy(false); } }
  if (!settings) return <p className={styles.message}>{error || "Loading orchestration settings…"}</p>;
  const number = (key: string, min: number, max: number) => <input type="number" min={min} max={max} value={settings[key]} onChange={(event) => setSettings({ ...settings, [key]: Number(event.target.value) })}/>;
  const toggle = (key: string, title: string, description: string) => <label className={styles.toggle}><input type="checkbox" checked={settings[key]} onChange={(event) => setSettings({ ...settings, [key]: event.target.checked })}/><span><strong>{title}</strong><small>{description}</small></span></label>;
  return <div className={styles.form}>{toggle("enabled", "Enable playlist orchestration", "When disabled, Mixarr stops starting coordinated playlist automation jobs. Existing playlists and data are not deleted.")}<div className={styles.grid}><label>Global concurrent jobs{number("globalMaxConcurrentJobs", 1, 16)}<small>Conservative default: 1.</small></label><label>Per-user concurrent jobs{number("perUserMaxConcurrentJobs", 1, 8)}</label><label>Per-library concurrent jobs{number("perLibraryMaxConcurrentJobs", 1, 8)}</label><label>Default priority<select value={settings.defaultPriority} onChange={(event) => setSettings({ ...settings, defaultPriority: event.target.value })}><option>HIGH</option><option>NORMAL</option><option>LOW</option></select></label><label>Stale job timeout (minutes){number("staleJobTimeoutMinutes", 5, 1440)}</label><label>Job history retention (days){number("jobHistoryRetentionDays", 7, 3650)}</label><label>Audit retention (days){number("auditRetentionDays", 30, 3650)}</label></div><details><summary>Advanced orchestration defaults</summary><div className={styles.grid}>{toggle("dryRunByDefault", "Dry run by default", "Simulate managed operations unless an explicit real job is requested.")}{toggle("autoRegisterGeneratedPlaylists", "Register newly generated playlists", "Only future Mixarr playlists are registered; existing playlists remain untouched.")}{toggle("autoEnableRegisteredPlaylists", "Enable automation after registration", "Keep disabled for the safest opt-in workflow.")}{toggle("allowScheduledOrchestration", "Allow scheduled orchestration", "Scheduled triggers remain blocked unless enabled here.")}</div></details>{error && <p className={styles.error}>{error}</p>}{message && <p className={styles.success}>{message}</p>}<button className={styles.save} onClick={save} disabled={busy}>{busy ? "Saving…" : "Save orchestration settings"}</button></div>;
}
