"use client";

import { useCallback, useEffect, useMemo, useState } from "react";
import { Archive, Check, Clipboard, Download, History, Pencil, RefreshCw, Sparkles, Star, Trash2 } from "lucide-react";
import styles from "./PlaylistAiSummaries.module.css";
import { copyTextToClipboard } from "@/lib/clipboard";

const TYPES = [
  ["ONE_SENTENCE", "One sentence"], ["DETAILED_DESCRIPTION", "Detailed description"], ["MOOD", "Mood"], ["GENRE", "Genre"],
  ["ERA", "Era"], ["ENERGY_PROGRESSION", "Energy progression"], ["BPM_PROGRESSION", "BPM progression"], ["DISCOVERY", "Discovery"],
  ["FAMILIARITY", "Familiarity"], ["PLAYLIST_CHANGE", "Playlist change"], ["REFRESH", "Refresh"],
  ["WHY_THIS_PLAYLIST_EXISTS", "Why this exists"], ["PLEX_FRIENDLY", "Plex-friendly"], ["HOUSEHOLD_SHAREABLE", "Household shareable"],
] as const;
const defaultTypes = ["ONE_SENTENCE", "DETAILED_DESCRIPTION", "PLEX_FRIENDLY"];

async function api(url: string, init?: RequestInit) { const response = await fetch(url, { cache: "no-store", ...init, headers: { "Content-Type": "application/json", ...(init?.headers || {}) } }); const body = await response.json().catch(() => ({})); if (!response.ok) { const requestId = body.error?.details?.requestId || body.requestId; throw new Error(`${body.error?.message || body.message || "Request failed."}${requestId ? ` Request ID: ${requestId}` : ""}`); } return body; }
const label = (type: string) => TYPES.find(([value]) => value === type)?.[1] || type.replaceAll("_", " ").toLowerCase();

export default function PlaylistAiSummaries({ playlistId, playlistName, openInitially = false }: { playlistId: string; playlistName: string; openInitially?: boolean }) {
  const [open, setOpen] = useState(openInitially), [summaries, setSummaries] = useState<any[]>([]), [selectedTypes, setSelectedTypes] = useState<string[]>(defaultTypes);
  const [privacyMode, setPrivacyMode] = useState("METADATA_LIMITED"), [preview, setPreview] = useState<any>(null), [busy, setBusy] = useState(""), [message, setMessage] = useState(""), [error, setError] = useState("");
  const [editing, setEditing] = useState<string | null>(null), [draft, setDraft] = useState("");
  const load = useCallback(async () => { try { const body = await api(`/api/playlists/${playlistId}/ai-summaries?includeArchived=true&pageSize=100`); setSummaries(body.summaries || []); } catch (caught) { setError(caught instanceof Error ? caught.message : "Summary history is unavailable."); } }, [playlistId]);
  useEffect(() => { if (open) void load(); }, [open, load]);
  const active = useMemo(() => summaries.filter((summary) => !summary.archivedAt && summary.status === "COMPLETED"), [summaries]);
  function toggle(type: string) { setSelectedTypes((current) => current.includes(type) ? current.filter((value) => value !== type) : [...current, type]); setPreview(null); }
  async function previewRequest() { setBusy("preview"); setError(""); setMessage(""); try { setPreview(await api(`/api/playlists/${playlistId}/ai-summaries/preview`, { method: "POST", body: JSON.stringify({ summaryTypes: selectedTypes, privacyMode }) })); } catch (caught) { setError(caught instanceof Error ? caught.message : "Preview failed."); } finally { setBusy(""); } }
  async function generate() { setBusy("generate"); setError(""); try { const result = await api(`/api/playlists/${playlistId}/ai-summaries`, { method: "POST", body: JSON.stringify({ summaryTypes: selectedTypes, privacyMode, previewAcknowledged: Boolean(preview) }) }); setMessage(`${result.summaries.length} summary type${result.summaries.length === 1 ? "" : "s"} generated.`); setPreview(null); await load(); } catch (caught) { setError(caught instanceof Error ? caught.message : "Generation failed."); } finally { setBusy(""); } }
  async function update(id: string, body: any, success: string) { setBusy(id); setError(""); try { await api(`/api/playlists/${playlistId}/ai-summaries/${id}`, { method: "PATCH", body: JSON.stringify(body) }); setMessage(success); setEditing(null); await load(); } catch (caught) { setError(caught instanceof Error ? caught.message : "Summary update failed."); } finally { setBusy(""); } }
  async function copySummary(text: string) { setError(""); setMessage(""); try { await copyTextToClipboard(text); setMessage("Summary copied to clipboard."); } catch { setError("Your browser blocked automatic copying. Select the summary text and copy it manually, or use Export."); } }
  async function remove(id: string) { if (!window.confirm("Delete this generated summary? The playlist and its metadata will not be changed.")) return; setBusy(id); try { await api(`/api/playlists/${playlistId}/ai-summaries/${id}`, { method: "DELETE" }); setMessage("Generated summary deleted."); await load(); } catch (caught) { setError(caught instanceof Error ? caught.message : "Delete failed."); } finally { setBusy(""); } }
  function download(summary: any) { const blob = new Blob([summary.generatedText], { type: "text/plain;charset=utf-8" }); const url = URL.createObjectURL(blob); const anchor = document.createElement("a"); anchor.href = url; anchor.download = `${playlistName.replace(/[^a-z0-9]+/gi, "-").replace(/^-|-$/g, "").toLowerCase() || "playlist"}-${summary.summaryType.toLowerCase()}.txt`; anchor.click(); URL.revokeObjectURL(url); }
  return <details className={styles.panel} open={open} onToggle={(event) => setOpen(event.currentTarget.open)}>
    <summary><span><Sparkles size={16} /> AI playlist summaries</span><small>{active.length ? `${active.length} current · ${summaries.length} in history` : "Generate factual, reviewable descriptions"}</small></summary>
    <div className={styles.content}>
      <div className={styles.notice}><strong>Generated summary</strong><span>Advisory text only. Nothing is sent to Plex automatically.</span></div>
      <fieldset className={styles.types}><legend>Generate selected summary types</legend>{TYPES.map(([value, text]) => <label key={value}><input type="checkbox" checked={selectedTypes.includes(value)} onChange={() => toggle(value)} /> {text}</label>)}</fieldset>
      <div className={styles.controls}><label>Privacy mode<select value={privacyMode} onChange={(event) => { setPrivacyMode(event.target.value); setPreview(null); }}><option value="LOCAL_ONLY">Local Only</option><option value="METADATA_LIMITED">Metadata Limited</option><option value="ANONYMOUS_METADATA">Anonymous Metadata</option><option value="FULL_METADATA">Full Metadata</option></select></label><button disabled={!!busy || !selectedTypes.length} onClick={() => void previewRequest()}>{busy === "preview" ? <RefreshCw className={styles.spin} /> : <Clipboard />} Preview AI request</button><button className={styles.primary} disabled={!!busy || !selectedTypes.length || !preview} onClick={() => void generate()}>{busy === "generate" ? <RefreshCw className={styles.spin} /> : <Sparkles />} Generate / regenerate</button></div>
      {preview && <div className={styles.preview}><strong>Request preview</strong><span>{preview.aggregateOnly ? "Aggregate statistics only" : "Track-level context included"} · {preview.privacyMode.replaceAll("_", " ").toLowerCase()}</span><span>Estimated input {preview.limits?.estimatedInputTokens?.toLocaleString() || "—"} tokens · maximum cost {Number(preview.cost?.maximumEstimatedCost || 0).toFixed(6)} {preview.cost?.currency || "USD"}</span><small>Blocked: {(preview.blockedFields || []).join(", ") || "none"}</small></div>}
      {error && <p className={styles.error} role="alert">{error}</p>}{message && <p className={styles.success} role="status">{message}</p>}
      <div className={styles.history}>{summaries.length === 0 ? <p className={styles.empty}>No generated summaries yet. Choose one or more types and preview the request.</p> : summaries.map((summary, index) => { const previous = summaries.slice(index + 1).find((item) => item.summaryType === summary.summaryType); return <article key={summary.id} className={summary.archivedAt ? styles.archived : ""}>
        <header><div><strong>{label(summary.summaryType)}</strong>{summary.preferred && <span className={styles.preferred}><Star /> Preferred</span>}{summary.archivedAt && <span>Archived</span>}{summary.manuallyEdited && <span>Edited</span>}</div><small>{new Date(summary.generatedAt).toLocaleString()} · {summary.privacyMode.replaceAll("_", " ").toLowerCase()}</small></header>
        {summary.status === "FAILED" ? <p className={styles.error}>{summary.errorDetails || "Generation failed."}</p> : editing === summary.id ? <div className={styles.editor}><textarea value={draft} maxLength={6000} onChange={(event) => setDraft(event.target.value)} /><button disabled={!draft.trim()} onClick={() => void update(summary.id, { generatedText: draft }, "Summary edit saved; the original AI value remains in history.")}><Check /> Save edit</button><button onClick={() => setEditing(null)}>Cancel</button></div> : <p className={styles.text}>{summary.generatedText}</p>}
        {previous && <details className={styles.compare}><summary><History /> Compare with previous</summary><div><p><b>Current</b>{summary.generatedText}</p><p><b>Previous · {new Date(previous.generatedAt).toLocaleDateString()}</b>{previous.generatedText}</p></div></details>}
        {summary.status === "COMPLETED" && <div className={styles.actions}><button onClick={() => void copySummary(summary.generatedText)}><Clipboard /> {summary.summaryType === "PLEX_FRIENDLY" ? "Copy for Plex" : "Copy"}</button><button onClick={() => download(summary)}><Download /> Export</button><button onClick={() => void update(summary.id, { saveAsPlaylistNotes: true }, "Saved as local Mixarr playlist notes. Plex was not modified.")}>Save as playlist notes</button><button onClick={() => { setEditing(summary.id); setDraft(summary.generatedText); }}><Pencil /> Edit</button><button disabled={summary.preferred} onClick={() => void update(summary.id, { preferred: true }, "Preferred summary changed.")}><Star /> Prefer</button><button onClick={() => void update(summary.id, { archived: !summary.archivedAt }, summary.archivedAt ? "Summary restored." : "Summary archived.")}><Archive /> {summary.archivedAt ? "Restore" : "Archive"}</button><button className={styles.danger} onClick={() => void remove(summary.id)}><Trash2 /> Delete</button></div>}
      </article>; })}</div>
    </div>
  </details>;
}
