"use client";
import { useEffect, useState } from "react";
import axios from "axios";
import { Loader2, Save } from "lucide-react";
import styles from "./PlaylistChainSettings.module.css";

export default function PlaylistChainSettings() {
  const [settings,setSettings]=useState<any>(null); const [busy,setBusy]=useState(false); const [message,setMessage]=useState("");
  useEffect(()=>{axios.get("/api/settings/playlist-chains").then((response)=>setSettings(response.data)).catch(()=>setMessage("Playlist-chain settings are unavailable."));},[]);
  if(!settings)return <p className={styles.muted}>Loading playlist-chain settings…</p>;
  const toggle=(key:string)=><label className={styles.toggle}><input type="checkbox" checked={Boolean(settings[key])} onChange={(event)=>setSettings({...settings,[key]:event.target.checked})}/><span><strong>{({rolesEnabled:"Enable playlist roles",chainsEnabled:"Enable progression chains",sharedTransitionTracksEnabled:"Enable shared transition tracks",masterJourneyPlaylistsEnabled:"Enable master journey playlists",automaticallyAnalyzeUpdatedChains:"Automatically analyze updated chains",automaticallyRepairWeakHandoffs:"Automatically repair weak handoffs",preserveLockedBoundaryTracks:"Preserve locked boundary tracks",showExperimentalFeatures:"Show experimental chain features"} as any)[key]}</strong><small>{key==="automaticallyRepairWeakHandoffs"?"Disabled by default. Repairs still obey conservative limits and version snapshots.":key==="automaticallyAnalyzeUpdatedChains"?"Re-evaluate handoffs after a child playlist changes.":"This is optional and does not alter existing playlist generation by itself."}</small></span></label>;
  async function save(){setBusy(true);setMessage("");try{const response=await axios.put("/api/settings/playlist-chains",settings);setSettings(response.data);setMessage("Playlist-chain settings saved.");}catch(caught:any){setMessage(caught.response?.data?.error?.message||"Settings could not be saved.");}finally{setBusy(false);}}
  return <div className={styles.panel}><div className={styles.toggles}>{["rolesEnabled","chainsEnabled","sharedTransitionTracksEnabled","masterJourneyPlaylistsEnabled","automaticallyAnalyzeUpdatedChains","automaticallyRepairWeakHandoffs","preserveLockedBoundaryTracks","showExperimentalFeatures"].map((key)=><div key={key}>{toggle(key)}</div>)}</div><div className={styles.grid}><label>Default role behavior<select value={settings.defaultRoleBehavior} onChange={(event)=>setSettings({...settings,defaultRoleBehavior:event.target.value})}><option value="LABEL_ONLY">Label only</option><option value="SUGGEST">Suggest settings</option><option value="APPLY">Apply guidance</option></select></label><label>Maximum shared tracks<input type="number" min="0" max="5" value={settings.maximumSharedTransitionTracks} onChange={(event)=>setSettings({...settings,maximumSharedTransitionTracks:Number(event.target.value)})}/></label><label>Minimum repair improvement<input type="number" min="1" max="100" value={settings.minimumAutomaticRepairImprovement} onChange={(event)=>setSettings({...settings,minimumAutomaticRepairImprovement:Number(event.target.value)})}/></label><label>Maximum automatic replacements<input type="number" min="0" max="10" value={settings.maximumTracksReplacedAutomatically} onChange={(event)=>setSettings({...settings,maximumTracksReplacedAutomatically:Number(event.target.value)})}/></label><label>Analysis concurrency<input type="number" min="1" max="4" value={settings.analysisConcurrency} onChange={(event)=>setSettings({...settings,analysisConcurrency:Number(event.target.value)})}/></label><label>Version retention count<input type="number" min="1" max="100" value={settings.versionRetentionCount} onChange={(event)=>setSettings({...settings,versionRetentionCount:Number(event.target.value)})}/></label></div><button className={styles.save} onClick={save} disabled={busy}>{busy?<Loader2 className={styles.spin}/>:<Save size={15}/>} Save playlist-chain settings</button>{message&&<p role="status" className={styles.message}>{message}</p>}</div>;
}

