"use client";
/* eslint-disable @next/next/no-img-element */

import Link from "next/link";
import { useCallback, useEffect, useMemo, useState } from "react";
import { AlertTriangle, Grid2X2, List, PauseCircle, Plus, Search } from "lucide-react";
import styles from "@/app/playlist-groups/playlist-groups.module.css";

type Group = { id: string; name: string; description: string; artworkUrl?: string | null; isPaused: boolean; playlistCount: number; warningCount: number; lastRegeneratedAt?: string | null; settingsJson: Record<string, unknown>; health: { overallScore: number } };

async function responseJson(response: Response) { const body = await response.json(); if (!response.ok) throw new Error(body.error?.message || body.error || "Request failed"); return body; }
function date(value?: string | null) { return value ? new Date(value).toLocaleDateString() : "Never"; }

export default function PlaylistGroupsBrowser() {
  const [groups, setGroups] = useState<Group[]>([]); const [loading, setLoading] = useState(true); const [error, setError] = useState("");
  const [search, setSearch] = useState(""); const [status, setStatus] = useState("all"); const [sort, setSort] = useState("custom"); const [view, setView] = useState<"grid" | "list">("grid");
  const [creating, setCreating] = useState(false); const [name, setName] = useState(""); const [description, setDescription] = useState("");
  const load = useCallback(async () => { setLoading(true); try { const data = await responseJson(await fetch(`/api/playlist-groups?search=${encodeURIComponent(search)}&status=${status}&sort=${sort}`, { cache: "no-store" })); setGroups(data.groups); setError(""); } catch (caught) { setError(caught instanceof Error ? caught.message : "Unable to load collections."); } finally { setLoading(false); } }, [search, sort, status]);
  useEffect(() => { const timer = setTimeout(() => void load(), 200); return () => clearTimeout(timer); }, [load]);
  const totals = useMemo(() => ({ playlists: groups.reduce((sum, group) => sum + group.playlistCount, 0), attention: groups.filter((group) => group.warningCount > 0).length, paused: groups.filter((group) => group.isPaused).length }), [groups]);
  async function create() { if (!name.trim()) return; setCreating(true); try { const data = await responseJson(await fetch("/api/playlist-groups", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ name, description, settings: {} }) })); window.location.href = `/playlist-groups/${data.group.id}`; } catch (caught) { setError(caught instanceof Error ? caught.message : "Unable to create collection."); setCreating(false); } }
  return <main className={styles.page}>
    <header className={styles.pageHeader}><div><p className={styles.eyebrow}>Playlist Groups</p><h1>Collections</h1><p>Organize related playlists, share settings, and monitor collection health.</p></div><button className={styles.primaryButton} onClick={() => { const dialog = document.getElementById("create-collection") as HTMLDialogElement; dialog?.showModal(); }}><Plus size={17}/> Create Collection</button></header>
    <section className={styles.summaryGrid} aria-label="Collection summary"><div><strong>{groups.length}</strong><span>Collections</span></div><div><strong>{totals.playlists}</strong><span>Grouped playlists</span></div><div><strong>{totals.attention}</strong><span>Need attention</span></div><div><strong>{totals.paused}</strong><span>Paused</span></div></section>
    <section className={styles.toolbar}><label className={styles.search}><Search size={16}/><span className="sr-only">Search collections</span><input value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Search collections" /></label><select aria-label="Filter collections" value={status} onChange={(event) => setStatus(event.target.value)}><option value="all">All statuses</option><option value="active">Active</option><option value="paused">Paused</option></select><select aria-label="Sort collections" value={sort} onChange={(event) => setSort(event.target.value)}><option value="custom">Custom order</option><option value="name">Name</option><option value="updated">Recently updated</option><option value="playlistCount">Playlist count</option><option value="health">Health score</option></select><div className={styles.viewToggle}><button aria-label="Grid view" aria-pressed={view === "grid"} onClick={() => setView("grid")}><Grid2X2 size={17}/></button><button aria-label="Compact list view" aria-pressed={view === "list"} onClick={() => setView("list")}><List size={17}/></button></div></section>
    {error && <p className={styles.error} role="alert">{error}</p>}
    {loading ? <div className={styles.loading} aria-busy="true">Loading collections…</div> : groups.length === 0 ? <section className={styles.empty}><Grid2X2 size={36}/><h2>No playlist groups yet</h2><p>Create a collection to organize related playlists and share settings between them.</p><button className={styles.primaryButton} onClick={() => (document.getElementById("create-collection") as HTMLDialogElement)?.showModal()}><Plus size={17}/> Create Collection</button></section> : <section className={view === "grid" ? styles.groupGrid : styles.groupList}>{groups.map((group) => <Link className={styles.groupCard} href={`/playlist-groups/${group.id}`} key={group.id}><div className={styles.artwork}>{group.artworkUrl ? <img src={group.artworkUrl} alt=""/> : <Grid2X2 size={28}/>}</div><div className={styles.cardBody}><div className={styles.cardTitle}><h2>{group.name}</h2><span className={group.isPaused ? styles.paused : styles.active}>{group.isPaused ? <><PauseCircle size={13}/> Paused</> : "Active"}</span></div><p>{group.description || "No description"}</p><dl className={styles.cardStats}><div><dt>Playlists</dt><dd>{group.playlistCount}</dd></div><div><dt>Health</dt><dd>{group.health.overallScore}%</dd></div><div><dt>Last regenerated</dt><dd>{date(group.lastRegeneratedAt)}</dd></div></dl>{group.warningCount > 0 && <span className={styles.warning}><AlertTriangle size={14}/>{group.warningCount} health signal{group.warningCount === 1 ? "" : "s"}</span>}</div></Link>)}</section>}
    <dialog id="create-collection" className={styles.dialog} onClose={() => { setName(""); setDescription(""); }}><form method="dialog" onSubmit={(event) => { event.preventDefault(); void create(); }}><div><h2>Create Collection</h2><p>Existing playlist behavior will not change until you explicitly enable inheritance.</p></div><label>Name<input autoFocus required maxLength={100} value={name} onChange={(event) => setName(event.target.value)}/></label><label>Description<textarea maxLength={2000} rows={4} value={description} onChange={(event) => setDescription(event.target.value)}/></label><div className={styles.dialogActions}><button value="cancel" type="button" onClick={() => (document.getElementById("create-collection") as HTMLDialogElement)?.close()}>Cancel</button><button className={styles.primaryButton} disabled={creating || !name.trim()}>{creating ? "Creating…" : "Create Collection"}</button></div></form></dialog>
  </main>;
}
