"use client";
import { useState } from "react";

export default function PlexOwnershipPanel({ playlist, onChanged }: { playlist: any; onChanged: () => void }) {
  const [busy, setBusy] = useState(false); const [message, setMessage] = useState("");
  async function request(action?: string) { setBusy(true); setMessage(""); try { const response = await fetch(`/api/generated-playlists/${playlist.id}/${action ? "reconcile" : "plex-state"}`, { method: "POST", headers: { "Content-Type": "application/json" }, body: action ? JSON.stringify({ action }) : undefined }); const data = await response.json(); if (!response.ok) throw new Error(data.error); setMessage(action ? `Reconciliation ${data.status.toLowerCase()}.` : data.classification === "NO_CHANGE" ? "Plex matches the last Mixarr state." : `${data.classification.replaceAll("_", " ").toLowerCase()} detected.`); onChanged(); } catch (error) { setMessage(error instanceof Error ? error.message : "Plex check failed."); } finally { setBusy(false); } }
  return <details style={{ border: "1px solid var(--line)", borderRadius: ".65rem", padding: ".7rem" }} open={playlist.externalChangeState !== "NO_CHANGE"}>
    <summary style={{ cursor: "pointer", fontWeight: 800 }}>Plex ownership &amp; external changes {playlist.plexCanModify ? "" : "· Read-only"}</summary>
    <dl style={{ display: "grid", gridTemplateColumns: "repeat(auto-fit,minmax(130px,1fr))", gap: ".5rem", margin: ".7rem 0", fontSize: ".76rem" }}><div><dt style={{color:"var(--muted)"}}>Owner</dt><dd style={{margin:0}}>{playlist.plexOwnerName || "Authenticated Plex account"}</dd></div><div><dt style={{color:"var(--muted)"}}>Permission</dt><dd style={{margin:0}}>{playlist.plexCanModify ? "Writable" : "Read-only"}</dd></div><div><dt style={{color:"var(--muted)"}}>Management</dt><dd style={{margin:0}}>{playlist.managedByMixarr ? "Managed by Mixarr" : "Detached"}</dd></div><div><dt style={{color:"var(--muted)"}}>External state</dt><dd style={{margin:0}}>{(playlist.externalChangeState || "NO_CHANGE").replaceAll("_", " ")}</dd></div></dl>
    <div style={{display:"flex",flexWrap:"wrap",gap:".4rem"}}><button disabled={busy} onClick={() => void request()}>{busy ? "Checking…" : "Check Plex changes"}</button>{playlist.externalChangeState !== "NO_CHANGE" && <><button disabled={busy || !playlist.plexCanModify} onClick={() => void request("RESTORE_MIXARR")}>Restore Mixarr</button><button disabled={busy} onClick={() => void request("KEEP_PLEX")}>Keep Plex</button><button disabled={busy} onClick={() => void request("MERGE_PLEX_ADDITIONS")}>Merge additions</button><button disabled={busy} onClick={() => void request("DETACH")}>Detach</button><button disabled={busy} onClick={() => void request("REVIEW_LATER")}>Review later</button></>}</div>{playlist.plexPlaylistUrl && <p><a href={playlist.plexPlaylistUrl} target="_blank" rel="noreferrer">Open in Plex</a></p>}{message && <p style={{fontSize:".75rem",color:"var(--muted)"}}>{message}</p>}
  </details>;
}
