"use client";

import { useCallback, useEffect, useMemo, useState } from "react";
import { AlertTriangle, Check, Clock3, History, Loader2, Music2, Play, RefreshCw, Save, Search, Settings2, ShieldCheck, Sparkles, Wand2 } from "lucide-react";
import styles from "@/app/recently-added/recently-added.module.css";

const presetValues: Record<string, any> = {
  conservative: { matchThreshold: 95, maxAddsPerPlaylist: 1, maxAddsPerRun: 10, metadataConfidenceThreshold: 90 },
  balanced: { matchThreshold: 90, maxAddsPerPlaylist: 3, maxAddsPerRun: 25, metadataConfidenceThreshold: 75 },
  aggressive: { matchThreshold: 80, maxAddsPerPlaylist: 5, maxAddsPerRun: 40, metadataConfidenceThreshold: 60 },
};
const tabs = ["tracks", "matches", "settings", "playlists", "history"] as const;

async function jsonFetch(url: string, options?: RequestInit) {
  const response = await fetch(url, { cache: "no-store", ...options, headers: { "Content-Type": "application/json", ...(options?.headers || {}) } });
  const data = await response.json().catch(() => ({}));
  if (!response.ok) throw new Error(data.error || `Request failed (${response.status})`);
  return data;
}

function Toggle({ checked, onChange, title, description, disabled }: { checked: boolean; onChange: (value: boolean) => void; title: string; description?: string; disabled?: boolean }) {
  return <label className={styles.toggle}><input type="checkbox" checked={checked} disabled={disabled} onChange={(event) => onChange(event.target.checked)} /><span>{title}{description && <small>{description}</small>}</span></label>;
}

export default function RecentlyAddedWorkspace() {
  const [settings, setSettings] = useState<any>(null);
  const [savedSnapshot, setSavedSnapshot] = useState("");
  const [summary, setSummary] = useState<any>(null);
  const [tracks, setTracks] = useState<any[]>([]);
  const [matches, setMatches] = useState<any[]>([]);
  const [historyRows, setHistoryRows] = useState<any[]>([]);
  const [playlists, setPlaylists] = useState<any[]>([]);
  const [selectedMatches, setSelectedMatches] = useState<Set<string>>(new Set());
  const [tab, setTab] = useState<typeof tabs[number]>("tracks");
  const [busy, setBusy] = useState<string | null>(null);
  const [message, setMessage] = useState<{ type: "success" | "error"; text: string } | null>(null);

  const load = useCallback(async () => {
    const [settingsData, summaryData, trackData, matchData, historyData, playlistData] = await Promise.all([
      jsonFetch("/api/recently-added/settings"), jsonFetch("/api/recently-added/summary"), jsonFetch("/api/recently-added/tracks?limit=100"),
      jsonFetch("/api/recently-added/matches?limit=100"), jsonFetch("/api/recently-added/history?limit=50"), jsonFetch("/api/generated-playlists"),
    ]);
    setSettings(settingsData.settings); setSavedSnapshot(JSON.stringify(settingsData.settings)); setSummary(summaryData);
    setTracks(trackData.tracks || []); setMatches(matchData.matches || []); setHistoryRows(historyData.runs || []); setPlaylists(playlistData.playlists || []);
  }, []);

  useEffect(() => { load().catch((error) => setMessage({ type: "error", text: error.message })); }, [load]);
  const dirty = settings && JSON.stringify(settings) !== savedSnapshot;
  useEffect(() => {
    const warn = (event: BeforeUnloadEvent) => { if (dirty) { event.preventDefault(); event.returnValue = ""; } };
    window.addEventListener("beforeunload", warn); return () => window.removeEventListener("beforeunload", warn);
  }, [dirty]);

  const update = (key: string, value: any) => setSettings((current: any) => ({ ...current, [key]: value }));
  const actionSummary = useMemo(() => {
    if (!settings?.enabled) return ["Automation remains disabled; manual scan, analysis, matching, and apply tools stay available."];
    return [
      settings.suggestExistingPlaylistMatches && "Generate suggestions for eligible Mixarr Smart Mix playlists.",
      settings.autoAddStrongMatches && `Automatically add matches at ${settings.matchThreshold}% or higher only where playlist-level mode is Automatic.`,
      settings.createRecentlyAddedPlaylists && "Create configured recently added mixes when enough eligible tracks exist.",
      settings.scheduledRegenerationEnabled && `Run on the ${settings.scheduleType} schedule using the Mixarr timezone.`,
      settings.notificationEnabled && "Create deduplicated in-app notifications for enabled triggers.",
    ].filter(Boolean) as string[];
  }, [settings]);

  async function runAction(name: string, url: string, body: any = {}) {
    setBusy(name); setMessage(null);
    try { const result = await jsonFetch(url, { method: "POST", body: JSON.stringify(body) }); setMessage({ type: "success", text: `${name} completed${result.discovered != null ? `: ${result.discovered} discovered` : result.matches != null ? `: ${result.matches} matches` : result.applied != null ? `: ${result.applied} applied` : ""}.` }); await load(); return result; }
    catch (error) { setMessage({ type: "error", text: error instanceof Error ? error.message : `${name} failed` }); }
    finally { setBusy(null); }
  }

  async function save() {
    if (settings.autoAddStrongMatches && !JSON.parse(savedSnapshot || "{}").autoAddStrongMatches && !window.confirm("Enable automatic playlist additions? Mixarr will save a restorable playlist version before each allowed change.")) return;
    if (settings.scheduledRegenerationEnabled && !JSON.parse(savedSnapshot || "{}").scheduledRegenerationEnabled && !window.confirm("Enable scheduled regeneration using the displayed schedule and playlist-level overrides?")) return;
    if (!["add_only", "suggestions_only"].includes(settings.regenerationBehavior) && settings.regenerationBehavior !== JSON.parse(savedSnapshot || "{}").regenerationBehavior && !window.confirm("This regeneration mode can replace existing tracks. Locked and liked tracks and saved curves remain protected, and preview behavior still applies. Continue?")) return;
    if (settings.automationPreset === "aggressive" && !window.confirm("Aggressive automation changes playlists more frequently and accepts moderate-confidence metadata. Continue?")) return;
    setBusy("Saving settings");
    try { const data = await jsonFetch("/api/recently-added/settings", { method: "PUT", body: JSON.stringify(settings) }); setSettings(data.settings); setSavedSnapshot(JSON.stringify(data.settings)); setMessage({ type: "success", text: "Recently Added settings saved." }); await load(); }
    catch (error) { setMessage({ type: "error", text: error instanceof Error ? error.message : "Save failed" }); }
    finally { setBusy(null); }
  }

  async function savePlaylistMode(playlist: any, mode: string, excluded: boolean) {
    setBusy(`Updating ${playlist.plexPlaylistTitle}`);
    try { await jsonFetch(`/api/recently-added/playlists/${playlist.id}/settings`, { method: "PUT", body: JSON.stringify({ mode, excludeFromScheduledRegeneration: excluded }) }); await load(); setMessage({ type: "success", text: `${playlist.plexPlaylistTitle} automation settings saved.` }); }
    catch (error) { setMessage({ type: "error", text: error instanceof Error ? error.message : "Playlist setting failed" }); }
    finally { setBusy(null); }
  }

  if (!settings) return <div className={styles.empty}><Loader2 className="spin" /> Loading Recently Added Automation…</div>;
  const counts = summary?.counts || {};
  return <main className={styles.page}>
    <header className={styles.header}><div><span className={styles.kicker}><Sparkles size={14} /> Mixarr v2.0.9 Beta</span><h2>Recently Added Automation</h2><p>Analyze new Plex music, review explainable Smart Mix matches, and opt into safe playlist updates.</p></div><div className={styles.status}><span>Recently Added Automation</span><strong>{String(summary?.status || "disabled").replaceAll("_", " ")}</strong><span><Clock3 size={12} /> Last scan: {summary?.lastScanAt ? new Date(summary.lastScanAt).toLocaleString() : "Never"}</span><span>Next run: {summary?.nextScheduledRunAt ? new Date(summary.nextScheduledRunAt).toLocaleString() : "Manual only"}</span></div></header>
    {!settings.enabled && <div className={styles.disabledNotice}><strong>Recently Added Automation is disabled.</strong><span>Mixarr will not automatically create, regenerate, modify, or notify about playlists. Manual tools below remain available.</span></div>}
    {settings.enabled && settings.autoAddStrongMatches && <div className={styles.warning}><strong><AlertTriangle size={15} /> Automatic playlist updates are enabled.</strong><span>Only strong, analyzed matches for playlists explicitly set to Automatic can be added. A restorable version is saved first.</span></div>}
    <section className={styles.metrics}>{[
      [counts.newTracks, "New tracks"], [counts.strongMatches, "Strong matches"], [counts.suggestions, "Suggestions"], [counts.lowConfidence, "Low confidence"], [counts.waiting, "Waiting analysis"], [counts.automaticallyAdded, "Automatically added"],
    ].map(([value, label]) => <div className={styles.metric} key={label}><b>{value || 0}</b><span>{label}</span></div>)}</section>
    <div className={styles.toolbar} aria-label="Manual recently added tools">
      <button className={styles.button} disabled={Boolean(busy)} onClick={() => runAction("Scan", "/api/recently-added/scan")}><Search size={14} /> Scan Recently Added</button>
      <button className={styles.secondary} disabled={Boolean(busy)} onClick={() => runAction("Analysis", "/api/recently-added/analyze")}><RefreshCw size={14} /> Analyze New Tracks</button>
      <button className={styles.secondary} disabled={Boolean(busy)} onClick={() => runAction("Matching", "/api/recently-added/match")}><Sparkles size={14} /> Find Playlist Matches</button>
      <button className={styles.secondary} disabled={Boolean(busy)} onClick={() => runAction("Recently added mix", "/api/recently-added/create-mix")}><Wand2 size={14} /> Create Recently Added Mix</button>
      <button className={styles.secondary} disabled={Boolean(busy)} onClick={() => runAction("Full manual run", "/api/recently-added/run")}><Play size={14} /> Run Full Workflow</button>
    </div>
    {busy && <p className={styles.muted}><Loader2 size={14} className="spin" /> {busy}…</p>}{message && <p className={message.type === "success" ? styles.success : styles.error}>{message.text}</p>}
    <nav className={styles.tabs} aria-label="Recently Added sections">{tabs.map((item) => <button key={item} data-active={tab === item} onClick={() => setTab(item)}>{item === "tracks" ? "New Tracks" : item === "matches" ? "Playlist Matches" : item[0].toUpperCase() + item.slice(1)}</button>)}</nav>

    {tab === "tracks" && <section className={styles.panel}><h3>Recently Added Tracks</h3><p className={styles.panelIntro}>New Music Score measures metadata readiness and playlist compatibility—not whether you will enjoy a song.</p><div className={styles.list}>{tracks.length ? tracks.map((state) => <article className={styles.row} key={state.id}><Music2 size={17} /><div><strong>{state.track.title}</strong><small>{state.track.artist.title} · {state.track.album.title}</small></div><span className={styles.score}>{state.newMusicScore == null ? "Not scored" : `${Math.round(state.newMusicScore)}/100`}</span><small>{String(state.status).replaceAll("_", " ")}{state.quarantineReason ? ` · ${state.quarantineReason}` : ""}</small><div className={styles.actions}>{state.status === "waiting_for_analysis" && <button className={styles.secondary} onClick={() => runAction("Manual approval", "/api/recently-added/ignore", { trackIds: [state.trackId], action: "manual_approve" })}>Approve</button>}<button className={styles.secondary} onClick={() => runAction("Ignore track", "/api/recently-added/ignore", { trackIds: [state.trackId], action: "ignore" })}>Ignore</button><button className={styles.secondary} onClick={() => runAction("Exclude artist", "/api/recently-added/ignore", { type: "artist", value: state.track.artistId })}>Artist</button><button className={styles.secondary} onClick={() => runAction("Exclude album", "/api/recently-added/ignore", { type: "album", value: state.track.albumId })}>Album</button><button className={styles.secondary} onClick={() => runAction("Exclude library", "/api/recently-added/ignore", { type: "library", value: state.track.libraryId })}>Library</button>{state.track.tags?.find((tag: any) => tag.type === "genre") && <button className={styles.secondary} onClick={() => runAction("Exclude genre", "/api/recently-added/ignore", { type: "genre", value: state.track.tags.find((tag: any) => tag.type === "genre").name })}>Genre</button>}</div></article>) : <div className={styles.empty}>No recently added tracks are tracked yet. Run a manual scan after your Plex library is synchronized.</div>}</div></section>}

    {tab === "matches" && <section className={styles.panel}><h3>Playlist Match Review</h3><p className={styles.panelIntro}>Review scores, sections, reasons, and expected score impact before applying selected additions.</p>{selectedMatches.size > 0 && <div className={styles.toolbar}><button className={styles.button} onClick={() => runAction("Selected additions", "/api/recently-added/apply", { matchIds: Array.from(selectedMatches) })}><Check size={14} /> Approve Selected ({selectedMatches.size})</button><button className={styles.secondary} onClick={() => setSelectedMatches(new Set())}>Clear Selection</button></div>}<div className={styles.list}>{matches.length ? matches.map((match) => <article className={styles.row} key={match.id}><input aria-label={`Select ${match.track.title}`} type="checkbox" checked={selectedMatches.has(match.id)} disabled={match.status === "applied" || match.status === "ignored"} onChange={(event) => setSelectedMatches((current) => { const next = new Set(current); event.target.checked ? next.add(match.id) : next.delete(match.id); return next; })} /><div><strong>{match.track.title}</strong><small>{match.track.artist.title} · {match.generatedPlaylist.plexPlaylistTitle}</small></div><span className={styles.score}>{Math.round(match.compatibilityScore)}% match</span><small>{match.recommendedSection || "Middle"} · New Music {Math.round(match.newMusicScore)} · Δ {match.expectedScoreChange ?? 0}</small><span>{String(match.status).replaceAll("_", " ")}</span><p className={styles.reason}>{Array.isArray(match.matchReasonsJson) ? match.matchReasonsJson.join(" · ") : "Explainable match details unavailable"}</p></article>) : <div className={styles.empty}>No playlist matches yet. Analyze eligible tracks, then run playlist matching.</div>}</div></section>}

    {tab === "settings" && <section className={styles.panel} id="automation-settings"><h3>Automation Settings</h3><p className={styles.panelIntro}>The master setting never enables destructive features by itself. Individual preferences remain saved when the master is off.</p><Toggle checked={settings.enabled} onChange={(value) => update("enabled", value)} title="Recently Added Automation" description="Disabled by default. Turn on only the individual features selected below." />
      <div className={styles.summaryBox}><strong>What will happen after saving</strong><ul>{actionSummary.map((item) => <li key={item}>{item}</li>)}</ul></div>
      <div className={`${styles.settingsGrid} ${!settings.enabled ? styles.dimmed : ""}`}>
        <section className={styles.section}><h4>Feature Controls</h4><Toggle disabled={!settings.enabled} checked={settings.createRecentlyAddedPlaylists} onChange={(v) => update("createRecentlyAddedPlaylists", v)} title="Create recently added Smart Mix playlists" /><Toggle disabled={!settings.enabled} checked={settings.suggestExistingPlaylistMatches} onChange={(v) => update("suggestExistingPlaylistMatches", v)} title="Suggest tracks for existing playlists" /><Toggle disabled={!settings.enabled} checked={settings.autoAddStrongMatches} onChange={(v) => update("autoAddStrongMatches", v)} title="Automatically add strong matches" description="Requires an Automatic playlist-level override." /><Toggle disabled={!settings.enabled} checked={settings.quarantineUntilAnalyzed} onChange={(v) => update("quarantineUntilAnalyzed", v)} title="Quarantine until analyzed" /><Toggle disabled={!settings.enabled} checked={settings.scheduledRegenerationEnabled} onChange={(v) => update("scheduledRegenerationEnabled", v)} title="Run scheduled Smart Mix regeneration" /><Toggle disabled={!settings.enabled} checked={settings.notificationEnabled} onChange={(v) => update("notificationEnabled", v)} title="Notify me when tracks match playlists" /></section>
        <section className={styles.section}><h4>New Track Detection</h4><label className={styles.field}>Recently added time window<select disabled={!settings.enabled} value={settings.timeWindowDays} onChange={(e) => update("timeWindowDays", Number(e.target.value))}><option value={1}>Last 24 hours</option><option value={3}>Last 3 days</option><option value={7}>Last 7 days</option><option value={14}>Last 14 days</option><option value={30}>Last 30 days</option></select></label><label className={styles.field}>Maximum tracks per run<input disabled={!settings.enabled} type="number" min="1" max="10000" value={settings.maxTracksPerRun} onChange={(e) => update("maxTracksPerRun", Number(e.target.value))} /></label></section>
        <section className={styles.section}><h4>Analysis &amp; Quarantine</h4><label className={styles.field}>Quarantine until<select disabled={!settings.enabled || !settings.quarantineUntilAnalyzed} value={settings.quarantineRule} onChange={(e) => update("quarantineRule", e.target.value)}><option value="all_core">BPM, mood, and energy are available</option><option value="two_core">Any two core fields are available</option><option value="confidence">Metadata confidence reaches threshold</option><option value="manual">Manual approval only</option></select></label><label className={styles.field}>Release low-confidence tracks after<select disabled={!settings.enabled || !settings.quarantineUntilAnalyzed} value={settings.quarantineTimeoutHours || "never"} onChange={(e) => update("quarantineTimeoutHours", e.target.value === "never" ? null : Number(e.target.value))}><option value="never">Never</option><option value={24}>24 hours</option><option value={72}>3 days</option><option value={168}>7 days</option></select></label><Toggle disabled={!settings.enabled} checked={settings.allowLowConfidenceAutomation} onChange={(v) => update("allowLowConfidenceAutomation", v)} title="Allow low-confidence automation after timeout" /></section>
        <section className={styles.section}><h4>Automatic Additions</h4><label className={styles.field}>Automation preset<select disabled={!settings.enabled} value={settings.automationPreset} onChange={(e) => { const value = e.target.value; setSettings((current: any) => ({ ...current, automationPreset: value, ...(presetValues[value] || {}) })); }}><option value="conservative">Conservative</option><option value="balanced">Balanced</option><option value="aggressive">Aggressive</option><option value="custom">Custom</option></select></label><label className={styles.field}>Automatic match threshold: {settings.matchThreshold}%<input disabled={!settings.enabled} type="range" min="50" max="100" value={settings.matchThreshold} onChange={(e) => { update("matchThreshold", Number(e.target.value)); update("automationPreset", "custom"); }} /></label><label className={styles.field}>Minimum metadata confidence: {settings.metadataConfidenceThreshold}%<input disabled={!settings.enabled} type="range" min="0" max="100" value={settings.metadataConfidenceThreshold} onChange={(e) => update("metadataConfidenceThreshold", Number(e.target.value))} /></label><label className={styles.field}>Max additions per playlist<input disabled={!settings.enabled} type="number" min="1" max="25" value={settings.maxAddsPerPlaylist} onChange={(e) => update("maxAddsPerPlaylist", Number(e.target.value))} /></label><label className={styles.field}>Max additions per run<input disabled={!settings.enabled} type="number" min="1" max="250" value={settings.maxAddsPerRun} onChange={(e) => update("maxAddsPerRun", Number(e.target.value))} /></label><Toggle disabled={!settings.enabled} checked={settings.requirePreview} onChange={(v) => update("requirePreview", v)} title="Require preview before automatic changes" /></section>
        <section className={styles.section}><h4>Recently Added Playlists</h4><label className={styles.field}>Name template<input disabled={!settings.enabled} type="text" value={settings.playlistNameTemplate} onChange={(e) => update("playlistNameTemplate", e.target.value)} /></label><label className={styles.field}>Minimum tracks<input disabled={!settings.enabled} type="number" value={settings.recentMixMinimumTrackCount} onChange={(e) => update("recentMixMinimumTrackCount", Number(e.target.value))} /></label><label className={styles.field}>Maximum tracks<input disabled={!settings.enabled} type="number" value={settings.recentMixMaximumTrackCount} onChange={(e) => update("recentMixMaximumTrackCount", Number(e.target.value))} /></label><Toggle disabled={!settings.enabled} checked={settings.recentMixPublishToPlex} onChange={(v) => update("recentMixPublishToPlex", v)} title="Automatically publish mixes to Plex" /><Toggle disabled={!settings.enabled} checked={settings.recentMixVersioned} onChange={(v) => update("recentMixVersioned", v)} title="Create dated/versioned playlists" /></section>
        <section className={styles.section}><h4>Scheduled Regeneration</h4><label className={styles.field}>Schedule<select disabled={!settings.enabled} value={settings.scheduleType} onChange={(e) => update("scheduleType", e.target.value)}><option value="manual">Manual only</option><option value="hourly">Hourly</option><option value="daily">Daily</option><option value="weekly">Weekly</option><option value="custom">Custom cron</option></select></label>{["daily", "weekly"].includes(settings.scheduleType) && <label className={styles.field}>Preferred run time<input disabled={!settings.enabled} type="time" value={settings.scheduleTime} onChange={(e) => update("scheduleTime", e.target.value)} /></label>}{settings.scheduleType === "custom" && <label className={styles.field}>Cron expression<input disabled={!settings.enabled} type="text" value={settings.scheduleExpression || ""} onChange={(e) => update("scheduleExpression", e.target.value)} /></label>}<label className={styles.field}>Regeneration behavior<select disabled={!settings.enabled} value={settings.regenerationBehavior} onChange={(e) => update("regenerationBehavior", e.target.value)}><option value="add_only">Add compatible new tracks only</option><option value="replace_weakest">Replace weakest tracks</option><option value="weak_sections">Regenerate weak sections</option><option value="rebuild_preserving_locked">Rebuild preserving locked tracks</option><option value="suggestions_only">Suggestions only</option></select></label></section>
        <section className={styles.section}><h4>Ignore &amp; Exclusion Controls</h4><p className={styles.panelIntro}>Track, artist, and album exclusions can also be added from New Tracks and remain in effect on later scans.</p><label className={styles.field}>Exclude tracks below confidence<select disabled={!settings.enabled} value={settings.exclusionsJson?.confidenceBelow ?? "none"} onChange={(e) => update("exclusionsJson", { ...(settings.exclusionsJson || {}), confidenceBelow: e.target.value === "none" ? null : Number(e.target.value) })}><option value="none">Do not exclude by confidence</option><option value={40}>40%</option><option value={60}>60%</option><option value={75}>75%</option><option value={90}>90%</option></select></label><span className={styles.muted}>{settings.exclusionsJson?.artistIds?.length || 0} artists · {settings.exclusionsJson?.albumIds?.length || 0} albums · {settings.exclusionsJson?.libraryIds?.length || 0} libraries · {settings.exclusionsJson?.genres?.length || 0} genres excluded</span></section>
        <section className={styles.section}><h4>Notifications</h4><Toggle disabled={!settings.enabled || !settings.notificationEnabled} checked={settings.notifyStrongMatches} onChange={(v) => update("notifyStrongMatches", v)} title="Strong matches found" /><Toggle disabled={!settings.enabled || !settings.notificationEnabled} checked={settings.notifySuggestionsReady} onChange={(v) => update("notifySuggestionsReady", v)} title="Suggestions ready" /><Toggle disabled={!settings.enabled || !settings.notificationEnabled} checked={settings.notifyAutomaticAdditions} onChange={(v) => update("notifyAutomaticAdditions", v)} title="Tracks added automatically" /><Toggle disabled={!settings.enabled || !settings.notificationEnabled} checked={settings.notifyMixCreated} onChange={(v) => update("notifyMixCreated", v)} title="Recently added mix created" /><Toggle disabled={!settings.enabled || !settings.notificationEnabled} checked={settings.notifyLowConfidence} onChange={(v) => update("notifyLowConfidence", v)} title="Low-confidence tracks need attention" /><Toggle disabled={!settings.enabled || !settings.notificationEnabled} checked={settings.notifyFailures} onChange={(v) => update("notifyFailures", v)} title="Automation failed" /></section>
      </div><div className={styles.actions}><button className={styles.button} disabled={!dirty || Boolean(busy)} onClick={save}><Save size={14} /> Save Settings</button>{dirty && <button className={styles.secondary} onClick={() => setSettings(JSON.parse(savedSnapshot))}>Discard Changes</button>}</div></section>}

    {tab === "playlists" && <section className={styles.panel}><h3>Playlist-level Overrides</h3><p className={styles.panelIntro}>Suggestions Only is the safe default and always overrides a global automatic-add setting.</p><div className={styles.list}>{playlists.filter((p) => p.engineVersion === "v2").map((playlist) => { const current = playlist.automationSettings || { mode: "suggestions", excludeFromScheduledRegeneration: false }; return <article className={styles.row} key={playlist.id}><ShieldCheck size={17} /><div><strong>{playlist.plexPlaylistTitle}</strong><small>{playlist._count?.tracks || playlist.trackCount} tracks · Smart Mix v2</small></div><select aria-label={`Automation mode for ${playlist.plexPlaylistTitle}`} defaultValue={current.mode} onChange={(e) => savePlaylistMode(playlist, e.target.value, current.excludeFromScheduledRegeneration)}><option value="off">Off</option><option value="suggestions">Suggestions Only</option><option value="automatic">Automatic Strong Matches</option></select><Toggle checked={current.excludeFromScheduledRegeneration} onChange={(value) => savePlaylistMode(playlist, current.mode, value)} title="Exclude from schedule" /></article>; })}</div></section>}

    {tab === "history" && <section className={styles.panel}><h3><History size={17} /> Automation History</h3><p className={styles.panelIntro}>Every run records its trigger, settings snapshot, progress, warnings, and playlist changes. Clearing this list never deletes playlist versions.</p><div>{historyRows.length ? historyRows.map((run) => <article className={styles.historyRow} key={run.id}><div><strong>{new Date(run.startedAt).toLocaleString()}</strong><small>{run.triggerType} · {run.engineVersion}</small></div><span className={run.status === "failed" ? styles.error : styles.success}>{String(run.status).replaceAll("_", " ")}</span><span>{run.tracksDiscovered} new · {run.tracksAnalyzed} analyzed · {run.playlistMatches} matches · {run.automaticallyAdded} added · {run.playlistsModified} playlists</span></article>) : <div className={styles.empty}>No Recently Added Automation runs yet.</div>}</div><button className={styles.danger} onClick={async () => { const phrase = window.prompt("Type CLEAR RECENTLY ADDED HISTORY to confirm. Playlist version history will be preserved."); if (!phrase) return; setBusy("Clearing history"); try { await jsonFetch("/api/recently-added/history", { method: "DELETE", body: JSON.stringify({ confirm: phrase }) }); await load(); } catch (error) { setMessage({ type: "error", text: error instanceof Error ? error.message : "Clear failed" }); } finally { setBusy(null); } }}>Clear History</button></section>}
  </main>;
}
