"use client";

import { useEffect, useRef, useState } from "react";
import { AlertTriangle, BrainCircuit, CheckCircle2, ChevronDown, Download, Loader2, RefreshCw, ShieldCheck } from "lucide-react";
import styles from "./RecommendationExplanationPanel.module.css";

const tabs = ["Overview", "User Intent", "AI Interpretation", "Generated Rules", "Engine Evaluation", "Track Results", "Assumptions", "Alternatives", "Reproducibility", "Export"] as const;
type Tab = typeof tabs[number];
type Props = { resourceId: string; title?: string; defaultOpen?: boolean };

const label = (value: string | null | undefined) => String(value || "unknown").replaceAll("_", " ");
const valueText = (value: unknown) => typeof value === "string" ? value : JSON.stringify(value);
const responsibilityLabel = (value: string) => ({ ai_interpretation: "AI Interpretation", deterministic_engine: "Deterministic Engine", mixarr_configuration: "Mixarr Configuration", metadata_provider: "Metadata Provider", user_override: "User Override", household_approval: "Household Approval", system_default: "System Default", user: "User" } as Record<string, string>)[value] || label(value);

export default function RecommendationExplanationPanel({ resourceId, title = "Why these recommendations?", defaultOpen = false }: Props) {
  const [open, setOpen] = useState(defaultOpen), [tab, setTab] = useState<Tab>("Overview"), [data, setData] = useState<any>(null);
  const [loading, setLoading] = useState(false), [error, setError] = useState(""), [tracks, setTracks] = useState<any>(null), [trackFilter, setTrackFilter] = useState("all");
  const [note, setNote] = useState(""), [noteDecision, setNoteDecision] = useState("comment"), [busy, setBusy] = useState("");
  const tabRefs = useRef<Array<HTMLButtonElement | null>>([]);

  async function load() {
    setLoading(true); setError("");
    try { const response = await fetch(`/api/recommendations/${encodeURIComponent(resourceId)}/explanation`), body = await response.json(); if (!response.ok) throw new Error(body?.error?.message || "Explanation unavailable."); setData(body); }
    catch (caught) { setError(caught instanceof Error ? caught.message : "Explanation unavailable."); }
    finally { setLoading(false); }
  }
  useEffect(() => { if (open && !data && !loading) void load(); }, [open]); // eslint-disable-line react-hooks/exhaustive-deps
  useEffect(() => { if (!open || tab !== "Track Results") return; const query = trackFilter === "all" ? "" : trackFilter === "selected" ? "?selected=true" : "?excluded=true"; fetch(`/api/recommendations/${encodeURIComponent(resourceId)}/explanation/tracks${query}`).then(async (response) => { const body = await response.json(); if (!response.ok) throw new Error(body?.error?.message || "Track evaluations unavailable."); setTracks(body); }).catch((caught) => setError(caught instanceof Error ? caught.message : "Track evaluations unavailable.")); }, [open, resourceId, tab, trackFilter]);

  async function assumptionAction(id: string, action: "accept" | "reject") { setBusy(id); setError(""); try { const response = await fetch(`/api/recommendations/${encodeURIComponent(resourceId)}/explanation/assumptions/${id}/${action}`, { method: "POST" }); const body = await response.json(); if (!response.ok) throw new Error(body?.error?.message || "Could not update assumption."); await load(); } catch (caught) { setError(caught instanceof Error ? caught.message : "Could not update assumption."); } finally { setBusy(""); } }
  async function modifyAssumption(id: string, current: unknown) { const raw = window.prompt("Enter the reviewed value as JSON", JSON.stringify(current)); if (raw == null) return; let value: unknown; try { value = JSON.parse(raw); } catch { setError("The reviewed assumption value must be valid JSON."); return; } setBusy(id); try { const response = await fetch(`/api/recommendations/${encodeURIComponent(resourceId)}/explanation/assumptions/${id}`, { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ value }) }); const body = await response.json(); if (!response.ok) throw new Error(body?.error?.message || "Could not modify assumption."); await load(); } catch (caught) { setError(caught instanceof Error ? caught.message : "Could not modify assumption."); } finally { setBusy(""); } }
  async function applyAlternative(id: string) { setBusy(id); setError(""); try { const response = await fetch(`/api/recommendations/${encodeURIComponent(resourceId)}/explanation/alternatives/${id}/apply`, { method: "POST" }); const body = await response.json(); if (!response.ok) throw new Error(body?.error?.message || "Could not apply alternative."); await load(); } catch (caught) { setError(caught instanceof Error ? caught.message : "Could not apply alternative."); } finally { setBusy(""); } }
  async function addNote() { if (!note.trim()) return; setBusy("note"); try { const response = await fetch(`/api/recommendations/${encodeURIComponent(resourceId)}/explanation/approval-notes`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ decision: noteDecision, note }) }); const body = await response.json(); if (!response.ok) throw new Error(body?.error?.message || "Could not add approval note."); setNote(""); await load(); } catch (caught) { setError(caught instanceof Error ? caught.message : "Could not add approval note."); } finally { setBusy(""); } }
  function keyTabs(event: React.KeyboardEvent, index: number) { if (!(["ArrowLeft", "ArrowRight", "Home", "End"] as string[]).includes(event.key)) return; event.preventDefault(); const next = event.key === "Home" ? 0 : event.key === "End" ? tabs.length - 1 : (index + (event.key === "ArrowRight" ? 1 : -1) + tabs.length) % tabs.length; setTab(tabs[next]); tabRefs.current[next]?.focus(); }

  return <section className={styles.shell} aria-label="Explainable recommendation details">
    <button type="button" className={styles.trigger} onClick={() => setOpen((current) => !current)} aria-expanded={open}><BrainCircuit size={17} /><span><strong>{title}</strong><small>AI interpretation and deterministic engine decisions</small></span><ChevronDown size={17} className={open ? styles.rotated : ""} /></button>
    {open && <div className={styles.panel}>
      {loading && <p className={styles.state}><Loader2 className="animate-spin" size={17} /> Loading structured explanation…</p>}
      {error && <p className={styles.error} role="alert"><AlertTriangle size={17} /> {error}</p>}
      {data && <>
        <header className={styles.header}><div><span>Explanation v{data.explanationSchemaVersion}</span><h3>{title}</h3><p>Generation run: <code>{data.generationRunId || "Not linked yet"}</code></p></div><div className={styles.headerBadges}><Status value={data.reproducibility.status} /><Status value={data.overallConfidenceCategory} suffix=" AI confidence" /></div></header>
        <div className={styles.tabs} role="tablist" aria-label="Explanation layers">{tabs.map((item, index) => <button key={item} ref={(node) => { tabRefs.current[index] = node; }} role="tab" aria-selected={tab === item} tabIndex={tab === item ? 0 : -1} onClick={() => setTab(item)} onKeyDown={(event) => keyTabs(event, index)}>{item}</button>)}</div>
        <div className={styles.content} role="tabpanel" tabIndex={0}>
          {tab === "Overview" && <Overview data={data} onTab={setTab} />}
          {tab === "User Intent" && <><Section title="Original request" owner="user"><blockquote>{data.originalRequest || "Detailed AI interpretation is unavailable because no retained AI request is linked to this generation."}</blockquote><small>{data.originalRequestCreatedAt ? new Date(data.originalRequestCreatedAt).toLocaleString() : "No request timestamp"} · {label(data.requestSource)}</small></Section><Section title="Approval context" owner="household_approval"><div className={styles.noteForm}><select value={noteDecision} onChange={(event) => setNoteDecision(event.target.value)} aria-label="Approval note decision"><option value="comment">Comment</option><option value="approved">Approved</option><option value="changes_requested">Changes requested</option><option value="rejected">Rejected</option></select><textarea value={note} onChange={(event) => setNote(event.target.value)} rows={3} maxLength={4000} placeholder="Add a review note tied to this explanation" aria-label="Household approval note"/><button onClick={() => void addNote()} disabled={!note.trim() || busy === "note"}>{busy === "note" ? "Saving…" : "Add note"}</button></div>{data.approvalNotes.map((item: any) => <article className={styles.note} key={item.id}><strong>{item.approver?.username || "Approver"} · {label(item.decision)}</strong><p>{item.note}</p><small>{new Date(item.createdAt).toLocaleString()}</small></article>)}</Section></>}
          {tab === "AI Interpretation" && <><Section title="Selected interpretation" owner="ai_interpretation"><p>{data.structuredInterpretation?.summary || "No AI interpretation is stored."}</p><div className={styles.badges}><Status value={data.overallConfidenceCategory} /><span>{data.overallConfidence == null ? "No AI confidence applies" : `${Math.round(data.overallConfidence * 100)}% numeric confidence`}</span></div></Section><FieldGrid fields={data.structuredInterpretation?.fields || []} />{data.uncertaintyWarnings?.length > 0 && <Section title="Uncertainty warnings" owner="ai_interpretation">{data.uncertaintyWarnings.map((item: string) => <p className={styles.warning} key={item}><AlertTriangle size={15} />{item}</p>)}</Section>}</>}
          {tab === "Generated Rules" && <><Section title="Generated deterministic settings" owner="mixarr_configuration"><div className={styles.ruleList}>{data.generatedSettings.length ? data.generatedSettings.map((item: any) => <article key={item.path}><code>{item.path}</code><strong>{valueText(item.value)}</strong><div><Status value={item.validationStatus} /><Responsibility value={item.responsibility} />{item.inferred && <span>Inferred</span>}{item.userModified && <span>User modified</span>}</div></article>) : <p>No AI-generated changes were proposed.</p>}</div></Section><DiffViewer differences={data.semanticDiff} configuration={data.generatedConfiguration} /><Section title="Deterministic validation" owner="deterministic_engine">{data.validationResults.map((item: any) => <div className={styles.validation} key={item.id}><Status value={item.result} /><span><strong>{item.message}</strong><small>{item.reasonCode}{item.path ? ` · ${item.path}` : ""}</small></span></div>)}</Section><details><summary>Raw generated configuration</summary><pre>{JSON.stringify(data.generatedConfiguration, null, 2)}</pre></details></>}
          {tab === "Engine Evaluation" && <><Section title="Responsibility boundary" owner="deterministic_engine"><p><strong>AI contribution:</strong> {data.responsibility.ai}</p><p><strong>Deterministic engine contribution:</strong> {data.responsibility.deterministic}</p></Section><Section title="Request-to-rule trace" owner="mixarr_configuration"><div className={styles.trace}>{data.ruleTraces.map((item: any) => <article key={item.id}><Responsibility value={item.responsibility} /><code>{item.nodeIdentifier}</code><span>{item.fieldPath || item.nodeType}</span><strong>{valueText(item.outputValueJson)}</strong><Status value={item.validationStatus} /></article>)}</div></Section><button className={styles.linkButton} onClick={() => setTab("Track Results")}>Open rule-to-track evaluations</button></>}
          {tab === "Track Results" && <><div className={styles.filters}><label>Track outcome<select value={trackFilter} onChange={(event) => { setTrackFilter(event.target.value); setTracks(null); }}><option value="all">All retained evaluations</option><option value="selected">Selected tracks</option><option value="excluded">Excluded tracks</option></select></label><span>Server-side pagination · up to 25 events per page</span></div>{!tracks ? <p className={styles.state}><Loader2 className="animate-spin" size={17} /> Loading retained evaluation events…</p> : tracks.evaluations.length ? <div className={styles.trackList}>{tracks.evaluations.map((item: any) => <article key={item.id}><header><strong>{item.trackTitle || item.trackId || "Deleted track"}</strong><span>{item.artistName || "Unknown artist"}{item.rank ? ` · position ${item.rank}` : ""}</span></header><div><Status value={item.result} /><Responsibility value={item.responsibility} /><code>{item.reasonCode}</code></div><p>{item.inputSnapshotJson?.explanation || `${item.ruleId} changed the score by ${item.scoreDelta >= 0 ? "+" : ""}${item.scoreDelta}.`}</p></article>)}</div> : <p className={styles.empty}>No retained track evaluations match this filter. Historical data is never fabricated.</p>}</>}
          {tab === "Assumptions" && <Section title="Review inferred values" owner="ai_interpretation">{data.assumptions.length ? data.assumptions.map((item: any) => <article className={styles.assumption} key={item.id}><div><Status value={item.status} /><Status value={item.confidenceCategory} suffix=" confidence" /></div><strong>{item.description}</strong><p>{item.fieldPath || "General interpretation"}: {valueText(item.userOverrideValueJson ?? item.inferredValueJson)}</p><div><button onClick={() => void assumptionAction(item.id, "accept")} disabled={busy === item.id}>Accept</button><button onClick={() => void modifyAssumption(item.id, item.userOverrideValueJson ?? item.inferredValueJson)} disabled={busy === item.id}>Modify</button><button onClick={() => void assumptionAction(item.id, "reject")} disabled={busy === item.id}>Reject</button></div></article>) : <p>No inferred assumptions were recorded.</p>}</Section>}
          {tab === "Alternatives" && <Section title="Stored alternative interpretations" owner="ai_interpretation">{data.alternatives.length ? data.alternatives.map((item: any) => <article className={styles.alternative} key={item.id}><div><strong>{item.label}</strong><Status value={item.confidenceCategory} suffix=" confidence" /></div>{item.differenceSummaryJson?.map((difference: any) => <p key={difference.path}><code>{difference.path}</code>: {valueText(difference.before)} → {valueText(difference.after)}</p>)}<button disabled={busy === item.id} onClick={() => void applyAlternative(item.id)}>{busy === item.id ? "Applying…" : "Preview/apply without AI"}</button><small>This updates the stored structured preview. It does not silently overwrite the recipe.</small></article>) : <p>No similarly plausible alternatives were returned for this request.</p>}</Section>}
          {tab === "Reproducibility" && <><Section title={label(data.reproducibility.status)} owner="deterministic_engine"><p>{data.reproducibility.reason}</p><div className={styles.versionGrid}><span>Explanation schema<strong>{data.versions.explanationSchema}</strong></span><span>Recipe schema<strong>{data.versions.recipeSchema}</strong></span><span>Engine<strong>{data.versions.engine}</strong></span><span>AI call for rendering<strong>No · $0 additional cost</strong></span></div></Section><button className={styles.regenerate} onClick={async () => { setBusy("regenerate"); try { const response = await fetch(`/api/recommendations/${encodeURIComponent(resourceId)}/explanation/regenerate`, { method: "POST", headers: { "Content-Type": "application/json" }, body: "{}" }); const body = await response.json(); if (!response.ok) throw new Error(body?.error?.message || "Regeneration failed."); setError(body.message || "Deterministic preview regenerated without an AI call."); } catch (caught) { setError(caught instanceof Error ? caught.message : "Regeneration failed."); } finally { setBusy(""); } }} disabled={busy === "regenerate"}><RefreshCw size={15} className={busy === "regenerate" ? "animate-spin" : ""}/> Regenerate deterministic preview</button><details><summary>Integrity snapshot and hashes</summary><pre>{JSON.stringify(data.reproducibility.snapshot, null, 2)}</pre></details></>}
          {tab === "Export" && <Section title="Privacy-aware explanation export" owner="mixarr_configuration"><p>Exports include intent, confidence, assumptions, alternatives, validation, deterministic evaluations, outcome reasons, approval notes, versions, and reproducibility data. Credentials, private prompts, authentication data, and provider secrets are excluded.</p><div className={styles.exports}>{[["json", "JSON"], ["markdown", "Markdown"], ["html", "HTML"], ["print", "Printable view"]].map(([format, text]) => <a key={format} href={`/api/recommendations/${encodeURIComponent(resourceId)}/explanation/export?format=${format}`}><Download size={15} />{text}</a>)}</div></Section>}
        </div>
      </>}
    </div>}
  </section>;
}

function Overview({ data, onTab }: { data: any; onTab: (tab: Tab) => void }) { return <><div className={styles.summaryGrid}><button onClick={() => onTab("User Intent")}><span>Original request</span><strong>{data.originalRequest || "No retained AI request"}</strong></button><button onClick={() => onTab("AI Interpretation")}><span>Selected interpretation</span><strong>{data.structuredInterpretation?.summary || "Deterministic configuration only"}</strong></button><button onClick={() => onTab("Generated Rules")}><span>Generated settings</span><strong>{data.generatedSettings.length} traced setting{data.generatedSettings.length === 1 ? "" : "s"}</strong></button><button onClick={() => onTab("Track Results")}><span>Final outcomes</span><strong>{data.summary.selectedTracks} selected · {data.summary.excludedTracks} excluded</strong></button></div><Section title="Who did what" owner="deterministic_engine"><p><Responsibility value="ai_interpretation" /> {data.responsibility.ai}</p><p><Responsibility value="deterministic_engine" /> {data.responsibility.deterministic}</p></Section><div className={styles.overviewStatus}><div><ShieldCheck size={18}/><span><strong>Deterministic validation</strong>{data.validationResults.filter((item: any) => item.result === "failed").length ? "Review required" : "Passed"}</span></div><div><CheckCircle2 size={18}/><span><strong>Reproducibility</strong>{label(data.reproducibility.status)}</span></div></div></>; }
function Section({ title, owner, children }: { title: string; owner: string; children: React.ReactNode }) { return <section className={styles.section}><header><h4>{title}</h4><Responsibility value={owner}/></header>{children}</section>; }
function Responsibility({ value }: { value: string }) { return <span className={styles.owner} data-owner={value}>{responsibilityLabel(value)}</span>; }
function Status({ value, suffix = "" }: { value: string; suffix?: string }) { return <span className={styles.status} data-status={value}>{label(value)}{suffix}</span>; }
function FieldGrid({ fields }: { fields: any[] }) { return <div className={styles.fieldGrid}>{fields.length ? fields.map((item) => <article key={item.id}><code>{item.fieldPath}</code><strong>{valueText(item.value)}</strong><div><Status value={item.confidenceCategory} suffix=" confidence"/><Responsibility value={item.responsibility}/>{item.inferred && <span>Inferred</span>}</div></article>) : <p>No field-level interpretation was retained.</p>}</div>; }
function DiffViewer({ differences, configuration }: { differences: any[]; configuration: unknown }) { const [mode, setMode] = useState<"unified" | "side-by-side">("unified"), [format, setFormat] = useState<"human" | "json" | "yaml">("human"); const yaml = (value: unknown, depth = 0): string => { if (!value || typeof value !== "object") return JSON.stringify(value); return Object.entries(value as Record<string, unknown>).map(([key, item]) => `${"  ".repeat(depth)}${key}:${item && typeof item === "object" ? `\n${yaml(item, depth + 1)}` : ` ${JSON.stringify(item)}`}`).join("\n"); }; return <Section title="Semantic generated-rule diff" owner="mixarr_configuration"><div className={styles.exports} role="group" aria-label="Diff view and format"><button onClick={() => setMode("unified")} aria-pressed={mode === "unified"}>Unified</button><button onClick={() => setMode("side-by-side")} aria-pressed={mode === "side-by-side"}>Side by side</button><button onClick={() => setFormat("human")} aria-pressed={format === "human"}>Human labels</button><button onClick={() => setFormat("json")} aria-pressed={format === "json"}>Raw JSON</button><button onClick={() => setFormat("yaml")} aria-pressed={format === "yaml"}>Raw YAML</button></div>{format === "human" ? <div className={styles.ruleList}>{differences.length ? differences.map((item) => <article key={item.path} aria-label={`${item.path} changed from ${valueText(item.before)} to ${valueText(item.after)}`}><code>{item.path}</code>{mode === "unified" ? <><span>- {valueText(item.before)}</span><strong>+ {valueText(item.after)}</strong></> : <div><span>Previous: {valueText(item.before)}</span><strong>Proposed: {valueText(item.after)}</strong></div>}<Status value={item.changeType}/></article>) : <p>No generated fields changed.</p>}</div> : <pre>{format === "json" ? JSON.stringify(configuration, null, 2) : yaml(configuration)}</pre>}</Section>; }
