"use client";

import { useEffect, useMemo, useState } from "react";
import Link from "next/link";
import { AlertTriangle, CalendarClock, Check, ChevronDown, Clock3, Download, Eye, History, ListChecks, Loader2, Play, RefreshCw, Search, ShieldCheck, Sparkles, X } from "lucide-react";
import styles from "@/app/smart-actions/smart-actions.module.css";

type Summary = { pending: number; high: number; medium: number; low: number; waiting: number; snoozed: number; recentlyCompleted: number; failed: number; byType: Record<string, number> };
type ActionItem = {
  id: string; title: string; summary: string; explanation: string; actionType: string; status: string; confidenceScore: number; confidenceLevel: string; riskLevel: string;
  priority: number; expectedImpact: Record<string, any>; previewPayload: Record<string, any>; createdAt: string; scheduledFor?: string | null; failureReason?: string | null;
  playlist?: { id: string; plexPlaylistTitle: string } | null; library?: { id: string; name: string } | null; playlistRevisions?: Array<{ id: string; revisionNumber: number }>;
};
type Queue = { items: ActionItem[]; total: number; page: number; pageSize: number; totalPages: number; bulkEligibleIds: string[] };

const typeLabels: Record<string, string> = {
  TRACK_ADDITION: "Track addition", TRACK_REMOVAL: "Track removal", PLAYLIST_OVERLAP_FIX: "Overlap fix", METADATA_CORRECTION: "Metadata correction",
  PLAYLIST_REFRESH: "Playlist refresh", IDENTITY_DRIFT: "Identity drift", TRANSITION_FIX: "Transition fix", COVERAGE_OPPORTUNITY: "Coverage opportunity",
};
const statusLabels: Record<string, string> = { PENDING: "Pending review", APPROVED: "Approved", SCHEDULED: "Scheduled", FAILED: "Requires attention", COMPLETED: "Completed", REJECTED: "Rejected", EXPIRED: "Expired", CANCELED: "Canceled", SUPERSEDED: "Superseded" };
const impactLabels: Record<string, string> = { playlistScoreBefore: "Playlist score before", playlistScoreAfter: "Playlist score after", transitionScoreBefore: "Transition score before", transitionScoreAfter: "Transition score after", identityMatchBefore: "Identity match before", identityMatchAfter: "Identity match after", libraryCoverageChange: "Library coverage change", artistVarietyChange: "Artist variety change", tracksAdded: "Tracks added", tracksRemoved: "Tracks removed", tracksReordered: "Tracks reordered", playlistsAffected: "Playlists affected", protectedTracksChanged: "Protected tracks changed" };

function metricValue(value: unknown) { return value == null ? "Not available" : typeof value === "number" ? Number.isInteger(value) ? value.toLocaleString() : value.toFixed(1) : String(value); }

export default function SmartActionCenter({ initialSummary, initialQueue, initialEnabled, initialFilters = {} }: { initialSummary: Summary; initialQueue: unknown; initialEnabled: boolean; initialFilters?: Partial<{ status: string; actionType: string; confidence: string }> }) {
  const [summary, setSummary] = useState(initialSummary); const [queue, setQueue] = useState<Queue>(initialQueue as Queue); const [enabled] = useState(initialEnabled);
  const [tab, setTab] = useState<"queue" | "history">("queue"); const [selected, setSelected] = useState<Set<string>>(new Set()); const [detail, setDetail] = useState<any>(null);
  const [loading, setLoading] = useState(false); const [detailLoading, setDetailLoading] = useState(false); const [message, setMessage] = useState<{ kind: "error" | "success"; text: string } | null>(null);
  const [filters, setFilters] = useState({ status: initialFilters.status || "", actionType: initialFilters.actionType || "", confidence: initialFilters.confidence || "", risk: "", search: "", sort: "recommended" });
  const [page, setPage] = useState(1);
  const selectedItems = useMemo(() => queue.items.filter((item) => selected.has(item.id)), [queue.items, selected]);
  const combinedImpact = useMemo(() => selectedItems.reduce((total, item) => ({ tracksAdded: total.tracksAdded + Number(item.expectedImpact?.tracksAdded || 0), tracksRemoved: total.tracksRemoved + Number(item.expectedImpact?.tracksRemoved || 0), tracksReordered: total.tracksReordered + Number(item.expectedImpact?.tracksReordered || 0), playlists: new Set([...Array.from(total.playlists), ...(item.playlist?.id ? [item.playlist.id] : [])]) }), { tracksAdded: 0, tracksRemoved: 0, tracksReordered: 0, playlists: new Set<string>() }), [selectedItems]);

  async function load(nextTab = tab, nextPage = page) {
    setLoading(true); setMessage(null);
    const params = new URLSearchParams({ page: String(nextPage), pageSize: "25", sort: filters.sort });
    Object.entries(filters).forEach(([key, value]) => { if (value && key !== "sort") params.set(key, value); });
    try {
      const [listResponse, summaryResponse] = await Promise.all([fetch(`${nextTab === "history" ? "/api/smart-actions/history" : "/api/smart-actions"}?${params}`, { cache: "no-store" }), fetch("/api/smart-actions/summary", { cache: "no-store" })]);
      const list = await listResponse.json(); const nextSummary = await summaryResponse.json();
      if (!listResponse.ok) throw new Error(list.error || "Unable to load Smart Actions.");
      setQueue(list); if (summaryResponse.ok) setSummary(nextSummary); setSelected(new Set());
    } catch (error) { setMessage({ kind: "error", text: error instanceof Error ? error.message : "Unable to load Smart Actions." }); }
    finally { setLoading(false); }
  }

  // Initial URL filters intentionally win over locally saved preferences.
  // eslint-disable-next-line react-hooks/exhaustive-deps
  useEffect(() => { const saved = window.localStorage.getItem("mixarr.smartActionFilters"); if (!saved || Object.values(initialFilters).some(Boolean)) return; try { setFilters((current) => ({ ...current, ...JSON.parse(saved), search: "" })); } catch { /* Ignore obsolete preferences. */ } }, []);
  // Reload only when the active view or serialized filter state changes.
  // eslint-disable-next-line react-hooks/exhaustive-deps
  useEffect(() => { window.localStorage.setItem("mixarr.smartActionFilters", JSON.stringify({ status: filters.status, actionType: filters.actionType, confidence: filters.confidence, risk: filters.risk, sort: filters.sort })); const timer = window.setTimeout(() => { load(tab, 1); setPage(1); }, 250); return () => window.clearTimeout(timer); }, [tab, filters]);

  async function run(endpoint: string, body?: unknown, success = "Smart Action updated.") {
    setLoading(true); setMessage(null);
    try { const response = await fetch(endpoint, { method: "POST", headers: { "Content-Type": "application/json" }, ...(body !== undefined ? { body: JSON.stringify(body) } : {}) }); const data = await response.json(); if (!response.ok) throw new Error(data.error || "Action failed."); setMessage({ kind: "success", text: success }); await load(); return true; }
    catch (error) { setMessage({ kind: "error", text: error instanceof Error ? error.message : "Action failed." }); return false; }
    finally { setLoading(false); }
  }

  async function openDetail(id: string) { setDetailLoading(true); try { const response = await fetch(`/api/smart-actions/${id}`, { cache: "no-store" }); const data = await response.json(); if (!response.ok) throw new Error(data.error); setDetail(data); } catch (error) { setMessage({ kind: "error", text: error instanceof Error ? error.message : "Unable to load details." }); } finally { setDetailLoading(false); } }
  async function reject(id: string) { const reason = window.prompt("Optional rejection reason", "I prefer the current version"); if (reason === null) return; await run(`/api/smart-actions/${id}/reject`, { reason }, "Recommendation rejected. Nothing was changed."); }
  async function applyNow(item: ActionItem) { if (item.riskLevel === "HIGH" && !window.confirm("This is a high-risk playlist change. A protected version will be created first. Apply it now?")) return; if (item.status === "PENDING" && !(await run(`/api/smart-actions/${item.id}/approve`, {}, "Action approved."))) return; await run(`/api/smart-actions/${item.id}/apply`, {}, "Action completed. A restore point was retained when the playlist changed."); }
  async function bulk(action: string) { if (!selected.size) return; if (["APPLY", "REJECT"].includes(action) && !window.confirm(`${action === "APPLY" ? "Apply" : "Reject"} ${selected.size} selected actions? Protected tracks changed: 0.`)) return; await run("/api/smart-actions/bulk", { action, ids: Array.from(selected), ...(action === "SNOOZE" ? { snooze: { preset: "ONE_WEEK" } } : {}) }, `${selected.size} actions processed.`); }
  function toggle(id: string) { setSelected((current) => { const next = new Set(current); if (next.has(id)) next.delete(id); else next.add(id); return next; }); }

  return <main className={styles.page}>
    <header className={styles.header}><div><span className={styles.eyebrow}><ShieldCheck size={14} /> Review before change</span><h1><ListChecks size={30} /> Smart Actions</h1><p>Explainable playlist, library, and metadata improvements. Nothing changes without approval.</p></div><div className={styles.headerActions}><Link href="/settings#smart-actions" className={styles.secondaryButton}>Settings</Link><button onClick={() => run("/api/smart-actions/generate", {}, "Analysis completed and recommendations were refreshed.")} disabled={loading || !enabled} className={styles.primaryButton}>{loading ? <Loader2 className={styles.spin} size={16} /> : <Sparkles size={16} />} Analyze</button></div></header>

    {!enabled && <section className={styles.disabled}><AlertTriangle size={20} /><div><b>Smart Actions are disabled.</b><p>Enable them in Settings to receive reviewable recommendations.</p></div><Link href="/settings#smart-actions">Open Settings</Link></section>}
    {message && <div className={message.kind === "error" ? styles.errorBanner : styles.successBanner} role="status">{message.kind === "error" ? <AlertTriangle size={17} /> : <Check size={17} />}{message.text}<button aria-label="Dismiss message" onClick={() => setMessage(null)}><X size={15} /></button></div>}

    <section className={styles.summaryGrid} aria-label="Smart Action summary">
      {[{ label: "Pending", value: summary.pending, tone: "accent" }, { label: "High confidence", value: summary.high, tone: "high" }, { label: "Medium confidence", value: summary.medium, tone: "medium" }, { label: "Low confidence", value: summary.low, tone: "low" }, { label: "Waiting to apply", value: summary.waiting, tone: "accent" }, { label: "Snoozed", value: summary.snoozed, tone: "muted" }, { label: "Completed this week", value: summary.recentlyCompleted, tone: "high" }, { label: "Requires attention", value: summary.failed, tone: "danger" }].map((item) => <article key={item.label} data-tone={item.tone}><span>{item.label}</span><b>{item.value.toLocaleString()}</b></article>)}
    </section>

    <div className={styles.tabs}><button className={tab === "queue" ? styles.activeTab : ""} onClick={() => setTab("queue")}><ListChecks size={16} /> Review queue</button><button className={tab === "history" ? styles.activeTab : ""} onClick={() => setTab("history")}><History size={16} /> History</button>{tab === "history" && <a href="/api/smart-actions/history?format=csv" className={styles.exportButton}><Download size={15} /> Export CSV</a>}</div>

    <section className={styles.toolbar} aria-label="Filter Smart Actions">
      <label className={styles.search}><Search size={16} /><input aria-label="Search recommendations" value={filters.search} onChange={(event) => setFilters({ ...filters, search: event.target.value })} placeholder="Search playlist, track, artist, or explanation" /></label>
      <select aria-label="Filter by status" value={filters.status} onChange={(event) => setFilters({ ...filters, status: event.target.value })}><option value="">All statuses</option>{["PENDING", "APPROVED", "SCHEDULED", "FAILED", "COMPLETED", "REJECTED", "EXPIRED", "SUPERSEDED"].map((value) => <option key={value} value={value}>{statusLabels[value]}</option>)}</select>
      <select aria-label="Filter by type" value={filters.actionType} onChange={(event) => setFilters({ ...filters, actionType: event.target.value })}><option value="">All types</option>{Object.entries(typeLabels).map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select>
      <select aria-label="Filter by confidence" value={filters.confidence} onChange={(event) => setFilters({ ...filters, confidence: event.target.value })}><option value="">All confidence</option><option value="HIGH">High confidence</option><option value="MEDIUM">Medium confidence</option><option value="LOW">Low confidence</option></select>
      <select aria-label="Filter by risk" value={filters.risk} onChange={(event) => setFilters({ ...filters, risk: event.target.value })}><option value="">All risks</option><option value="LOW">Low risk</option><option value="MODERATE">Moderate risk</option><option value="HIGH">High risk</option></select>
      <select aria-label="Sort recommendations" value={filters.sort} onChange={(event) => setFilters({ ...filters, sort: event.target.value })}><option value="recommended">Recommended</option><option value="confidence">Highest confidence</option><option value="impact">Highest expected impact</option><option value="oldest">Oldest</option><option value="type">Action type</option></select>
    </section>

    {tab === "queue" && queue.items.length > 0 && <section className={styles.bulkBar}><label><input type="checkbox" checked={queue.bulkEligibleIds.length > 0 && queue.bulkEligibleIds.every((id) => selected.has(id))} onChange={(event) => setSelected(event.target.checked ? new Set(queue.bulkEligibleIds) : new Set())} /> Select safe high/medium-confidence actions</label><span>{selected.size} selected</span>{selected.size > 0 && <><small>{combinedImpact.tracksAdded} added · {combinedImpact.tracksRemoved} removed · {combinedImpact.tracksReordered} reordered · {combinedImpact.playlists.size} playlists</small><button onClick={() => bulk("APPROVE")}>Approve</button><button onClick={() => bulk("SCHEDULE")}>Schedule</button><button onClick={() => bulk("SNOOZE")}>Snooze</button><button onClick={() => bulk("REJECT")}>Reject</button><button className={styles.bulkApply} onClick={() => bulk("APPLY")}><Play size={14} /> Apply</button></>}</section>}

    {loading && !queue.items.length ? <div className={styles.skeletons}>{[1, 2, 3].map((item) => <div key={item} />)}</div> : queue.items.length ? <section className={styles.actionList} aria-live="polite">{queue.items.map((item) => <article key={item.id} className={styles.actionCard} data-status={item.status}>
      <div className={styles.selectColumn}>{tab === "queue" && item.status === "PENDING" && item.riskLevel !== "HIGH" && <input aria-label={`Select ${item.title}`} type="checkbox" checked={selected.has(item.id)} onChange={() => toggle(item.id)} />}</div>
      <div className={styles.actionBody}><div className={styles.cardTopline}><span className={styles.typeBadge}>{typeLabels[item.actionType] || item.actionType}</span><span className={styles.statusBadge} data-status={item.status}>{statusLabels[item.status] || item.status}</span></div><h2>{item.title}</h2><p className={styles.resource}>{item.playlist?.plexPlaylistTitle || item.library?.name || "Library metadata"}</p><div className={styles.signals}><span data-confidence={item.confidenceLevel}>{item.confidenceLevel === "HIGH" ? "High" : item.confidenceLevel === "MEDIUM" ? "Medium" : "Low"} confidence · {item.confidenceScore}%</span><span data-risk={item.riskLevel}>{item.riskLevel.toLowerCase()} risk</span><span>{new Date(item.createdAt).toLocaleDateString()}</span></div><p className={styles.cardSummary}>{item.summary}</p><div className={styles.impactLine}>{Number(item.expectedImpact?.playlistScoreBefore) || Number(item.expectedImpact?.playlistScoreAfter) ? <span>Estimated score: {metricValue(item.expectedImpact?.playlistScoreBefore)} → {metricValue(item.expectedImpact?.playlistScoreAfter)}</span> : <span>Estimated: {item.expectedImpact?.tracksAdded || 0} added · {item.expectedImpact?.tracksRemoved || 0} removed · protected changed 0</span>}</div>{item.failureReason && <p className={styles.failure}>{item.failureReason}</p>}</div>
      <div className={styles.cardActions}><button onClick={() => openDetail(item.id)}><Eye size={15} /> {tab === "history" ? "Details" : "Preview"}</button>{tab === "queue" && item.status === "PENDING" && <><button className={styles.approve} onClick={() => run(`/api/smart-actions/${item.id}/approve`, {}, "Action approved. No changes have run yet.")}><Check size={15} /> Approve</button><button onClick={() => run(`/api/smart-actions/${item.id}/snooze`, { preset: "ONE_WEEK" }, "Snoozed for one week.")}><Clock3 size={15} /> Snooze</button><button onClick={() => reject(item.id)}>Reject</button></>}{tab === "queue" && ["APPROVED", "SCHEDULED"].includes(item.status) && <><button className={styles.apply} onClick={() => applyNow(item)}><Play size={15} /> Apply now</button>{item.status === "APPROVED" && <button onClick={() => run(`/api/smart-actions/${item.id}/schedule`, {}, "Scheduled for the next maintenance window.")}><CalendarClock size={15} /> Maintenance</button>}</>}</div>
    </article>)}</section> : <section className={styles.empty}><ListChecks size={36} /><h2>{tab === "history" ? "No Smart Action history yet" : "No Smart Actions need your attention"}</h2><p>{tab === "history" ? "Completed, rejected, expired, and failed actions will appear here." : enabled ? "Your playlists are within their configured quality, identity, and maintenance targets." : "Enable Smart Actions in Settings to begin."}</p>{tab === "queue" && enabled && <button className={styles.primaryButton} onClick={() => run("/api/smart-actions/generate", {}, "Analysis completed.")}><Sparkles size={16} /> Analyze My Playlists</button>}</section>}

    {queue.totalPages > 1 && <nav className={styles.pagination} aria-label="Smart Action pages"><button disabled={page <= 1} onClick={() => { const next = page - 1; setPage(next); load(tab, next); }}>Previous</button><span>Page {page} of {queue.totalPages}</span><button disabled={page >= queue.totalPages} onClick={() => { const next = page + 1; setPage(next); load(tab, next); }}>Next</button></nav>}

    {(detail || detailLoading) && <div className={styles.drawerLayer}><button className={styles.backdrop} aria-label="Close action details" onClick={() => setDetail(null)} /><aside className={styles.drawer} role="dialog" aria-modal="true" aria-label="Smart Action details">{detailLoading && !detail ? <Loader2 className={styles.spin} size={24} /> : detail && <><header><div><span className={styles.typeBadge}>{typeLabels[detail.actionType]}</span><h2>{detail.title}</h2></div><button aria-label="Close details" onClick={() => setDetail(null)}><X size={18} /></button></header><section><h3>Why this was suggested</h3><p>{detail.explanation}</p><div className={styles.detailSignals}><b>{detail.confidenceScore}% · {detail.confidenceLevel.toLowerCase()} confidence</b><span>{detail.riskLevel.toLowerCase()} risk</span><span>Source: {detail.sourceService} {detail.sourceVersion}</span></div></section>
      {detail.conflicts?.length > 0 && <section className={styles.conflict}><h3><AlertTriangle size={17} /> Conflicting actions</h3>{detail.conflicts.map((conflict: any) => <p key={`${conflict.leftId}-${conflict.rightId}`}>{conflict.reason} <b>{conflict.recommendation}</b></p>)}</section>}
      <section><h3>Before and after preview</h3><div className={styles.previewColumns}><div><b>Current</b>{Object.entries(detail.previewPayload?.before || {}).map(([key, value]) => <span key={key}>{key.replaceAll(/([A-Z])/g, " $1")}: {metricValue(value)}</span>)}</div><div><b>Suggested</b>{Object.entries(detail.previewPayload?.after || {}).map(([key, value]) => <span key={key}>{key.replaceAll(/([A-Z])/g, " $1")}: {metricValue(value)}</span>)}</div></div>{detail.previewPayload?.added?.length > 0 && <TrackChanges title="Added" rows={detail.previewPayload.added} />}{detail.previewPayload?.removed?.length > 0 && <TrackChanges title="Removed" rows={detail.previewPayload.removed} />}{detail.previewPayload?.warnings?.map((warning: string) => <p key={warning} className={styles.warning}>{warning}</p>)}</section>
      <section><h3>Expected impact <small>Estimate</small></h3><dl className={styles.impactGrid}>{Object.entries(detail.expectedImpact || {}).filter(([key, value]) => key !== "estimateNote" && value != null).map(([key, value]) => <div key={key}><dt>{impactLabels[key] || key}</dt><dd>{metricValue(value)}</dd></div>)}</dl><p className={styles.estimate}>{detail.expectedImpact?.estimateNote}</p></section>
      <section><h3>What remains unchanged</h3><ul>{(detail.previewPayload?.unchanged || ["Protected content"]).map((item: string) => <li key={item}>{item}</li>)}</ul><p>Playlist actions create a restorable version before execution. Metadata corrections retain their previous value in correction history.</p>{detail.playlistRevisions?.[0] && <Link href={`/generated-playlists/${detail.playlistId}/versions`}>Compare or restore playlist version {detail.playlistRevisions[0].revisionNumber}</Link>}</section>
      <details><summary>Advanced details <ChevronDown size={15} /></summary><pre>{JSON.stringify({ id: detail.id, source: detail.sourceService, payloadType: detail.actionPayload?.type, deduplicationKey: detail.deduplicationKey, expiresAt: detail.expiresAt }, null, 2)}</pre></details>
      <section><h3>Approval & execution history</h3><div className={styles.audit}>{detail.auditEvents?.map((event: any) => <div key={event.id}><b>{event.eventType.replaceAll("_", " ")}</b><span>{new Date(event.createdAt).toLocaleString()}</span><p>{event.reason}</p></div>)}</div></section>
      <footer>{detail.status === "PENDING" && <><button onClick={() => { run(`/api/smart-actions/${detail.id}/approve`, {}, "Action approved."); setDetail(null); }} className={styles.approve}>Approve</button><button onClick={() => { run(`/api/smart-actions/${detail.id}/schedule`, {}, "Scheduled for maintenance."); setDetail(null); }}>Approve & schedule</button><button onClick={() => reject(detail.id)}>Reject</button></>}{["APPROVED", "SCHEDULED"].includes(detail.status) && <button className={styles.apply} onClick={() => { applyNow(detail); setDetail(null); }}><Play size={15} /> Apply now</button>}</footer></>}</aside></div>}
  </main>;
}

function TrackChanges({ title, rows }: { title: string; rows: Array<{ id: string; title: string; artist?: string | null; reason?: string }> }) { return <div className={styles.trackChanges}><b>{title}</b>{rows.map((row) => <div key={row.id}><span>{row.title}{row.artist ? ` — ${row.artist}` : ""}</span><small>{row.reason}</small></div>)}</div>; }
