"use client";

import { useEffect, useState } from "react";
import axios from "axios";
import { AlertTriangle, CheckCircle2, ChevronDown, Clock3, Eye, RefreshCw, Sparkles, X } from "lucide-react";
import styles from "./SmartRefreshPanel.module.css";

const modeLabels: Record<string, string> = { MANUAL_ONLY: "Manual only", FIXED_SCHEDULE: "Fixed schedule", SMART_REFRESH: "Smart refresh", SMART_WITH_FALLBACK: "Smart refresh with fallback", DISABLED: "Disabled" };
const recommendationLabel = (value?: string | null) => value ? value.replaceAll("_", " ").toLowerCase().replace(/^./, (letter) => letter.toUpperCase()) : "Not evaluated";
const statusLabel = (evaluation: any) => !evaluation ? "Not evaluated" : evaluation.status === "HEALTHY" ? "Healthy" : evaluation.status === "RECOMMENDED" ? "Refresh available" : evaluation.status === "DEFERRED" ? "Refresh deferred" : evaluation.status === "BLOCKED" ? "Refresh blocked" : evaluation.status === "EXECUTED" ? "Recently refreshed" : evaluation.status.replaceAll("_", " ").toLowerCase();

export default function SmartRefreshPanel({ playlistId, onOpenAdvanced, onChanged }: { playlistId: string; onOpenAdvanced: () => void; onChanged?: (message: string) => void }) {
  const [data, setData] = useState<any>(null); const [settings, setSettings] = useState<any>(null); const [evaluation, setEvaluation] = useState<any>(null); const [preview, setPreview] = useState<any>(null); const [busy, setBusy] = useState(""); const [error, setError] = useState(""); const [expanded, setExpanded] = useState(false);
  const load = async () => { try { const response = await axios.get(`/api/playlists/${playlistId}/smart-refresh`); setData(response.data); setSettings(response.data.settings); setEvaluation(response.data.latestEvaluation); } catch (requestError: any) { setError(requestError.response?.data?.error || "Smart Refresh settings are unavailable."); } };
  useEffect(() => { void load(); }, [playlistId]); // eslint-disable-line react-hooks/exhaustive-deps
  const save = async () => { setBusy("Saving settings"); setError(""); try { const response = await axios.patch(`/api/playlists/${playlistId}/smart-refresh`, { refreshMode: settings.refreshMode, sensitivity: settings.sensitivity, minimumEstimatedImprovement: Number(settings.minimumEstimatedImprovement), minimumCompatibleTracks: Number(settings.minimumCompatibleTracks), minimumRefreshIntervalHours: Number(settings.minimumRefreshIntervalHours), maximumRefreshesPerWeek: settings.maximumRefreshesPerWeek == null ? null : Number(settings.maximumRefreshesPerWeek), evaluationIntervalHours: Number(settings.evaluationIntervalHours), fallbackAfterHours: settings.refreshMode === "SMART_WITH_FALLBACK" ? Number(settings.fallbackAfterHours || 720) : settings.fallbackAfterHours, allowPlaylistGrowth: Boolean(settings.allowPlaylistGrowth), allowAutomaticWeakTrackRefresh: Boolean(settings.allowAutomaticWeakTrackRefresh), allowAutomaticFullRegeneration: Boolean(settings.allowAutomaticFullRegeneration), quietHoursOverrideJson: settings.quietHoursOverrideJson || null, ...(settings.sensitivity === "CUSTOM" ? { weakTrackThreshold: Number(settings.weakTrackThreshold), identityDriftThreshold: Number(settings.identityDriftThreshold), repetitionThreshold: Number(settings.repetitionThreshold), metadataImprovementThreshold: Number(settings.metadataImprovementThreshold) } : {}) }); setData((current: any) => ({ ...current, ...response.data })); setSettings(response.data.settings); onChanged?.("Smart Refresh settings saved."); } catch (requestError: any) { setError(requestError.response?.data?.error || "Unable to save Smart Refresh settings."); } finally { setBusy(""); } };
  const evaluate = async () => { setBusy("Checking for improvements"); setError(""); setPreview(null); try { const response = await axios.post(`/api/playlists/${playlistId}/smart-refresh/evaluate`); setEvaluation(response.data); onChanged?.("Smart Refresh evaluation completed without changing Plex."); } catch (requestError: any) { setError(requestError.response?.data?.error || "Unable to evaluate this playlist."); } finally { setBusy(""); } };
  const showPreview = async () => { if (!evaluation) return; setBusy("Loading preview"); setError(""); try { const response = await axios.get(`/api/playlists/${playlistId}/smart-refresh/preview`, { params: { evaluationId: evaluation.id } }); setPreview(response.data.preview || { changes: [] }); } catch (requestError: any) { setError(requestError.response?.data?.error || "Unable to load the preview."); } finally { setBusy(""); } };
  const execute = async () => { if (!evaluation || !window.confirm("Apply the reviewed Smart Refresh changes to Plex? Mixarr will create a restorable version first.")) return; setBusy("Applying Smart Refresh"); setError(""); try { const response = await axios.post(`/api/playlists/${playlistId}/smart-refresh/execute`, { evaluationId: evaluation.id }); setEvaluation(response.data.evaluation || { ...evaluation, status: "EXECUTED" }); setPreview(null); onChanged?.(`Smart Refresh applied ${response.data.tracksReplaced || 0} replacement${response.data.tracksReplaced === 1 ? "" : "s"}.`); } catch (requestError: any) { setError(requestError.response?.data?.error || "Unable to apply Smart Refresh."); } finally { setBusy(""); } };
  const dismiss = async () => { if (!evaluation) return; setBusy("Dismissing"); try { await axios.post(`/api/playlists/${playlistId}/smart-refresh/dismiss`, { evaluationId: evaluation.id }); setEvaluation({ ...evaluation, status: "DISMISSED" }); setPreview(null); } catch (requestError: any) { setError(requestError.response?.data?.error || "Unable to dismiss the recommendation."); } finally { setBusy(""); } };
  if (!settings) return <section className={styles.panel}><div className={styles.heading}><Sparkles size={16} /><strong>Smart Refresh</strong></div><p>{error || "Loading Smart Refresh…"}</p></section>;
  const canApply = evaluation?.previewId && evaluation?.shouldRefresh && evaluation?.recommendation !== "FULL_REGENERATION" && !["EXECUTED", "STALE", "DISMISSED"].includes(evaluation.status);
  return <section className={styles.panel} aria-label="Smart Refresh settings">
    <div className={styles.heading}><div><Sparkles size={16} /><strong>Smart Refresh</strong><span className={styles.status} data-status={evaluation?.status || "NONE"}>{statusLabel(evaluation)}</span></div><button type="button" onClick={() => setExpanded((value) => !value)} aria-expanded={expanded}>{expanded ? "Hide" : "Settings"}<ChevronDown size={14} /></button></div>
    <p className={styles.intro}>Checks whether new music, weak tracks, playback, metadata, and saved identity can meaningfully improve this playlist. An estimate is predictive, not guaranteed.</p>
    {error && <div className={styles.error} role="alert"><AlertTriangle size={14} />{error}</div>}
    {expanded && <div className={styles.settings}>
      <label><span>Refresh mode</span><select value={settings.refreshMode} onChange={(event) => setSettings({ ...settings, refreshMode: event.target.value })}>{Object.entries(modeLabels).map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select><small>{settings.refreshMode === "FIXED_SCHEDULE" ? "Uses the existing fixed scheduler without Smart Refresh gating." : settings.refreshMode === "MANUAL_ONLY" ? "Only explicit regeneration and Check for improvements run." : settings.refreshMode === "DISABLED" ? "No automatic evaluation or refresh occurs." : "Evaluates periodically and changes Plex only when safeguards pass."}</small></label>
      <label><span>Refresh sensitivity</span><select value={settings.sensitivity} onChange={(event) => setSettings({ ...settings, sensitivity: event.target.value })}><option value="LOW">Low — favor stability</option><option value="BALANCED">Balanced — conservative default</option><option value="HIGH">High — react sooner</option><option value="CUSTOM">Custom thresholds</option></select></label>
      <div className={styles.grid}><label><span>Minimum improvement</span><input type="number" min="0" max="25" value={settings.minimumEstimatedImprovement} onChange={(event) => setSettings({ ...settings, minimumEstimatedImprovement: event.target.value })} /></label><label><span>Compatible tracks</span><input type="number" min="1" max="100" value={settings.minimumCompatibleTracks} onChange={(event) => setSettings({ ...settings, minimumCompatibleTracks: event.target.value })} /></label><label><span>Refresh interval (hours)</span><input type="number" min="1" max="8760" value={settings.minimumRefreshIntervalHours} onChange={(event) => setSettings({ ...settings, minimumRefreshIntervalHours: event.target.value })} /></label><label><span>Refreshes per week</span><select value={settings.maximumRefreshesPerWeek ?? "unlimited"} onChange={(event) => setSettings({ ...settings, maximumRefreshesPerWeek: event.target.value === "unlimited" ? null : Number(event.target.value) })}>{[1,2,3,5].map((value) => <option key={value} value={value}>{value}</option>)}<option value="unlimited">Unlimited</option></select></label></div>
      {settings.refreshMode === "SMART_WITH_FALLBACK" && <label><span>Fallback after (hours)</span><input type="number" min="24" max="8760" value={settings.fallbackAfterHours || 720} onChange={(event) => setSettings({ ...settings, fallbackAfterHours: event.target.value })} /></label>}
      <div className={styles.checks}><label><input type="checkbox" checked={settings.allowAutomaticWeakTrackRefresh} onChange={(event) => setSettings({ ...settings, allowAutomaticWeakTrackRefresh: event.target.checked })} /> Automatically apply safe weak-track refreshes</label><label><input type="checkbox" checked={settings.allowPlaylistGrowth} onChange={(event) => setSettings({ ...settings, allowPlaylistGrowth: event.target.checked })} /> Allow compatible-track additions when supported</label><label><input type="checkbox" checked={settings.allowAutomaticFullRegeneration} onChange={(event) => setSettings({ ...settings, allowAutomaticFullRegeneration: event.target.checked })} /> Allow automatic full regeneration</label></div>
      <details className={styles.advanced}><summary>Per-playlist quiet hours</summary><div className={styles.checks}><label><input type="checkbox" checked={Boolean(settings.quietHoursOverrideJson)} onChange={(event) => setSettings({ ...settings, quietHoursOverrideJson: event.target.checked ? { enabled: true, start: data.globalSettings.quietHoursStart, end: data.globalSettings.quietHoursEnd, timezone: data.globalSettings.timezone, allowEvaluations: true, allowGeneration: false } : null })} /> Override global quiet-hour defaults</label></div>{settings.quietHoursOverrideJson && <div className={styles.grid}><label><span>Start</span><input type="time" value={settings.quietHoursOverrideJson.start} onChange={(event) => setSettings({ ...settings, quietHoursOverrideJson: { ...settings.quietHoursOverrideJson, start: event.target.value } })} /></label><label><span>End</span><input type="time" value={settings.quietHoursOverrideJson.end} onChange={(event) => setSettings({ ...settings, quietHoursOverrideJson: { ...settings.quietHoursOverrideJson, end: event.target.value } })} /></label><label><span>Time zone</span><input value={settings.quietHoursOverrideJson.timezone} onChange={(event) => setSettings({ ...settings, quietHoursOverrideJson: { ...settings.quietHoursOverrideJson, timezone: event.target.value } })} /></label><label><span>Playlist changes</span><select value={settings.quietHoursOverrideJson.allowGeneration ? "allow" : "defer"} onChange={(event) => setSettings({ ...settings, quietHoursOverrideJson: { ...settings.quietHoursOverrideJson, allowGeneration: event.target.value === "allow" } })}><option value="defer">Defer</option><option value="allow">Allow</option></select></label></div>}</details>
      {settings.sensitivity === "CUSTOM" && <details className={styles.advanced}><summary>Advanced custom thresholds</summary><div className={styles.grid}><label><span>Weakness threshold</span><input type="number" min="20" max="90" value={settings.weakTrackThreshold} onChange={(event) => setSettings({ ...settings, weakTrackThreshold: event.target.value })} /></label><label><span>Identity drift %</span><input type="number" min="5" max="80" value={settings.identityDriftThreshold} onChange={(event) => setSettings({ ...settings, identityDriftThreshold: event.target.value })} /></label><label><span>Repetition %</span><input type="number" min="20" max="95" value={settings.repetitionThreshold} onChange={(event) => setSettings({ ...settings, repetitionThreshold: event.target.value })} /></label><label><span>Metadata tracks</span><input type="number" min="1" max="100" value={settings.metadataImprovementThreshold} onChange={(event) => setSettings({ ...settings, metadataImprovementThreshold: event.target.value })} /></label></div></details>}
      <p className={styles.quiet}><Clock3 size={13} /> Quiet hours: {data.globalSettings.quietHoursEnabled ? `${data.globalSettings.quietHoursStart}–${data.globalSettings.quietHoursEnd} ${data.globalSettings.timezone}` : "not enabled globally"}. Evaluations {data.globalSettings.allowEvaluationsQuietHours ? "allowed" : "deferred"}; playlist changes {data.globalSettings.allowGenerationQuietHours ? "allowed" : "deferred"}.</p>
      <button type="button" onClick={save} disabled={Boolean(busy)} className={styles.primary}>{busy === "Saving settings" ? <RefreshCw size={14} className="animate-spin" /> : <CheckCircle2 size={14} />}Save Smart Refresh settings</button>
    </div>}
    <div className={styles.actions}><button type="button" onClick={evaluate} disabled={Boolean(busy) || settings.refreshMode === "DISABLED"}>{busy === "Checking for improvements" ? <RefreshCw size={14} className="animate-spin" /> : <Sparkles size={14} />}Check for improvements</button>{evaluation?.previewId && <button type="button" onClick={showPreview} disabled={Boolean(busy)}><Eye size={14} />Preview changes</button>}{canApply && <button type="button" onClick={execute} disabled={Boolean(busy)} className={styles.primary}><RefreshCw size={14} />Run recommended action</button>}<button type="button" onClick={onOpenAdvanced}>Choose another action</button></div>
    {evaluation && <div className={styles.evaluation}><div className={styles.metrics}><div><span>Current score</span><b>{evaluation.currentScore == null ? "—" : Math.round(evaluation.currentScore)}</b></div><div><span>Estimated after</span><b>{evaluation.estimatedScoreAfterRefresh == null ? "—" : Math.round(evaluation.estimatedScoreAfterRefresh)}</b></div><div><span>Expected change</span><b>{evaluation.estimatedImprovement == null ? "—" : `${evaluation.estimatedImprovement >= 0 ? "+" : ""}${evaluation.estimatedImprovement}`}</b></div><div><span>Confidence</span><b>{Math.round((evaluation.confidence || 0) * 100)}%</b></div></div><p><strong>Recommended:</strong> {recommendationLabel(evaluation.recommendation)}</p><div className={styles.signals}>{(evaluation.reasons || []).map((item: any) => <p key={item.code} data-impact={item.impact}><span>{item.impact === "positive" ? "+" : "–"}</span><b>{item.label}</b><small>{item.detail}</small></p>)}</div>{evaluation.blockers?.length > 0 && <div className={styles.blockers}>{evaluation.blockers.map((item: any) => <p key={item.code}><AlertTriangle size={13} /><span><b>{item.message}</b>{item.eligibleAt && <small>Eligible after {new Date(item.eligibleAt).toLocaleString()}</small>}</span></p>)}</div>}<button type="button" onClick={dismiss} disabled={Boolean(busy) || evaluation.status === "DISMISSED"} className={styles.dismiss}><X size={13} />Dismiss recommendation</button></div>}
    {preview && <div className={styles.preview}><div className={styles.previewHead}><strong>Bounded preview — Plex is unchanged</strong><button onClick={() => setPreview(null)} aria-label="Close preview"><X size={14} /></button></div><p>Score {preview.originalScore ?? "—"} → {preview.proposedScore ?? "—"} · {preview.changes.length} proposed change{preview.changes.length === 1 ? "" : "s"}</p>{preview.changes.length === 0 ? <small>No meaningful replacements are available.</small> : <div>{preview.changes.map((change: any) => <article key={change.position}><span>{change.position}</span><div><small>Remove</small><b>{change.originalTrack.title}</b><em>{change.originalTrack.artist?.title || "Unknown artist"}</em></div><div><small>Add</small><b>{change.proposedTrack.title}</b><em>{change.proposedTrack.artist?.title || "Unknown artist"}</em></div><strong>+{change.improvement ?? 0}</strong></article>)}</div>}</div>}
  </section>;
}
