"use client";
import { useEffect, useState } from "react";
import { AlertTriangle, Check, Loader2, Save, ShieldCheck } from "lucide-react";
import styles from "./SmartActionSettings.module.css";

const types = [
  ["TRACK_ADDITION", "Track additions"], ["TRACK_REMOVAL", "Track removals"], ["PLAYLIST_OVERLAP_FIX", "Playlist overlap"], ["METADATA_CORRECTION", "Metadata corrections"],
  ["PLAYLIST_REFRESH", "Playlist refreshes"], ["IDENTITY_DRIFT", "Identity drift"], ["TRANSITION_FIX", "Transition fixes"], ["COVERAGE_OPPORTUNITY", "Coverage opportunities"],
] as const;
const days = [[0, "Sun"], [1, "Mon"], [2, "Tue"], [3, "Wed"], [4, "Thu"], [5, "Fri"], [6, "Sat"]] as const;

export default function SmartActionSettings() {
  const [settings, setSettings] = useState<any>(null); const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false); const [message, setMessage] = useState("");
  useEffect(() => { fetch("/api/settings/smart-actions", { cache: "no-store" }).then(async (response) => { const data = await response.json(); if (!response.ok) throw new Error(data.error); setSettings(data); }).catch((error) => setMessage(error.message)).finally(() => setLoading(false)); }, []);
  async function save() { setSaving(true); setMessage(""); try { const response = await fetch("/api/settings/smart-actions", { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ enabled: settings.enabled, generateDuringNightlySync: settings.generateDuringNightlySync, generateAfterPlaylistCreation: settings.generateAfterPlaylistCreation, generateAfterMetadataAnalysis: settings.generateAfterMetadataAnalysis, minimumConfidenceToDisplay: Number(settings.minimumConfidenceToDisplay), highConfidenceThreshold: Number(settings.highConfidenceThreshold), mediumConfidenceThreshold: Number(settings.mediumConfidenceThreshold), maximumPendingActions: Number(settings.maximumPendingActions), expireAfterDays: Number(settings.expireAfterDays), recommendationTypes: settings.recommendationTypes, maintenanceEnabled: settings.maintenanceEnabled, maintenanceStartTime: settings.maintenanceStartTime, maintenanceDays: settings.maintenanceDays, maximumActionsPerWindow: Number(settings.maximumActionsPerWindow), maximumPlaylistsPerWindow: Number(settings.maximumPlaylistsPerWindow), maximumConcurrentActions: Number(settings.maximumConcurrentActions), allowPlexRefreshes: settings.allowPlexRefreshes, allowMetadataChanges: settings.allowMetadataChanges, allowPlaylistRegeneration: settings.allowPlaylistRegeneration, pauseDuringPlayback: settings.pauseDuringPlayback, automationEmergencyDisabled: settings.automationEmergencyDisabled }) }); const data = await response.json(); if (!response.ok) throw new Error(data.error); setSettings(data); setMessage("Smart Action settings saved."); } catch (error) { setMessage(error instanceof Error ? error.message : "Unable to save settings."); } finally { setSaving(false); } }
  async function savePolicy(policy: any) { setSaving(true); setMessage(""); try { const response = await fetch("/api/settings/smart-actions", { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ policy: { actionType: policy.actionType, enabled: Boolean(policy.enabled), minimumConfidence: Number(policy.minimumConfidence), maximumRisk: policy.maximumRisk, maximumPerWindow: Number(policy.maximumPerWindow) } }) }); const data = await response.json(); if (!response.ok) throw new Error(data.error); setSettings((current: any) => ({ ...current, policies: [...current.policies.filter((item: any) => item.actionType !== data.actionType), data].sort((left: any, right: any) => left.actionType.localeCompare(right.actionType)) })); setMessage(`${policy.actionType.replaceAll("_", " ")} policy saved.`); } catch (error) { setMessage(error instanceof Error ? error.message : "Unable to save policy."); } finally { setSaving(false); } }
  function policyFor(actionType: string) { return settings.policies.find((policy: any) => policy.actionType === actionType) || { actionType, enabled: false, minimumConfidence: 95, maximumRisk: "LOW", maximumPerWindow: 3 }; }
  function updatePolicy(actionType: string, changes: Record<string, unknown>) { const policy = { ...policyFor(actionType), ...changes }; setSettings((current: any) => ({ ...current, policies: [...current.policies.filter((item: any) => item.actionType !== actionType), policy] })); }
  const set = (key: string, value: any) => setSettings((current: any) => ({ ...current, [key]: value }));
  if (loading) return <p className={styles.loading}><Loader2 size={16} /> Loading Smart Action settings…</p>;
  if (!settings) return <p className={styles.error}><AlertTriangle size={16} /> {message || "Smart Action settings are unavailable."}</p>;
  return <div className={styles.wrapper}>
    <div className={styles.notice}><ShieldCheck size={18} /><p><b>User control is the default.</b> Recommendation generation never modifies Plex. Automation policies remain disabled until individually configured, and new action types never inherit permission.</p></div>
    <div className={styles.grid}>
      <fieldset><legend>Recommendation generation</legend><Toggle label="Enable Smart Actions" checked={settings.enabled} onChange={(value) => set("enabled", value)} /><Toggle label="Generate during nightly sync" checked={settings.generateDuringNightlySync} onChange={(value) => set("generateDuringNightlySync", value)} /><Toggle label="Generate after playlist creation" checked={settings.generateAfterPlaylistCreation} onChange={(value) => set("generateAfterPlaylistCreation", value)} /><Toggle label="Generate after metadata analysis" checked={settings.generateAfterMetadataAnalysis} onChange={(value) => set("generateAfterMetadataAnalysis", value)} /><NumberField label="Minimum confidence to display" value={settings.minimumConfidenceToDisplay} min={0} max={100} onChange={(value) => set("minimumConfidenceToDisplay", value)} /><NumberField label="Maximum pending actions" value={settings.maximumPendingActions} min={10} max={5000} onChange={(value) => set("maximumPendingActions", value)} /><NumberField label="Expire actions after days" value={settings.expireAfterDays} min={1} max={365} onChange={(value) => set("expireAfterDays", value)} /></fieldset>
      <fieldset><legend>Confidence thresholds</legend><NumberField label="High confidence begins" value={settings.highConfidenceThreshold} min={66} max={100} onChange={(value) => set("highConfidenceThreshold", value)} /><NumberField label="Medium confidence begins" value={settings.mediumConfidenceThreshold} min={1} max={99} onChange={(value) => set("mediumConfidenceThreshold", value)} /><p className={styles.help}>Defaults: High 85–100, Medium 65–84, Low 0–64. Confidence expresses evidence strength, not certainty.</p></fieldset>
      <fieldset className={styles.wide}><legend>Recommendation types</legend><div className={styles.typeGrid}>{types.map(([key, label]) => <Toggle key={key} label={label} checked={settings.recommendationTypes?.[key] !== false} onChange={(value) => set("recommendationTypes", { ...settings.recommendationTypes, [key]: value })} />)}</div></fieldset>
      <fieldset className={styles.wide}><legend>Maintenance window</legend><Toggle label="Enable maintenance window" checked={settings.maintenanceEnabled} onChange={(value) => set("maintenanceEnabled", value)} /><div className={styles.inline}><label>Start time<input type="time" value={settings.maintenanceStartTime} onChange={(event) => set("maintenanceStartTime", event.target.value)} /></label><NumberField label="Maximum actions" value={settings.maximumActionsPerWindow} min={1} max={500} onChange={(value) => set("maximumActionsPerWindow", value)} /><NumberField label="Maximum playlists" value={settings.maximumPlaylistsPerWindow} min={1} max={100} onChange={(value) => set("maximumPlaylistsPerWindow", value)} /><NumberField label="Concurrency" value={settings.maximumConcurrentActions} min={1} max={5} onChange={(value) => set("maximumConcurrentActions", value)} /></div><div className={styles.days}>{days.map(([value, label]) => <label key={value}><input type="checkbox" checked={settings.maintenanceDays.includes(value)} onChange={(event) => set("maintenanceDays", event.target.checked ? [...settings.maintenanceDays, value].sort() : settings.maintenanceDays.filter((day: number) => day !== value))} /> {label}</label>)}</div><div className={styles.typeGrid}><Toggle label="Allow Plex playlist changes" checked={settings.allowPlexRefreshes} onChange={(value) => set("allowPlexRefreshes", value)} /><Toggle label="Allow metadata changes" checked={settings.allowMetadataChanges} onChange={(value) => set("allowMetadataChanges", value)} /><Toggle label="Allow playlist regeneration" checked={settings.allowPlaylistRegeneration} onChange={(value) => set("allowPlaylistRegeneration", value)} /><Toggle label="Pause when playback is detected" checked={settings.pauseDuringPlayback} onChange={(value) => set("pauseDuringPlayback", value)} /></div></fieldset>
      <fieldset className={styles.wide}><legend>Automation safety</legend><Toggle label="Emergency disable for all Smart Action automation" checked={settings.automationEmergencyDisabled} onChange={(value) => set("automationEmergencyDisabled", value)} /><p className={styles.help}>Enabled by default. Disabling this emergency switch still does not enable any policy; each action type needs its own explicit policy, confidence threshold, risk limit, and action cap. A newly introduced type always starts disabled.</p><div className={styles.policyTable}>{types.map(([actionType, label]) => { const policy = policyFor(actionType); return <div key={actionType} className={styles.policyRow}><Toggle label={label} checked={policy.enabled} onChange={(value) => updatePolicy(actionType, { enabled: value })} /><label>Minimum confidence<input type="number" min={85} max={100} value={policy.minimumConfidence} onChange={(event) => updatePolicy(actionType, { minimumConfidence: Number(event.target.value) })} /></label><label>Maximum risk<select value={policy.maximumRisk} onChange={(event) => updatePolicy(actionType, { maximumRisk: event.target.value })}><option value="LOW">Low</option><option value="MODERATE">Moderate</option><option value="HIGH">High</option></select></label><label>Per window<input type="number" min={1} max={50} value={policy.maximumPerWindow} onChange={(event) => updatePolicy(actionType, { maximumPerWindow: Number(event.target.value) })} /></label><button type="button" disabled={saving} onClick={() => savePolicy(policy)}>Save policy</button></div>; })}</div></fieldset>
    </div>
    <div className={styles.footer}>{message && <span className={message.includes("saved") ? styles.success : styles.error}>{message.includes("saved") && <Check size={15} />}{message}</span>}<button disabled={saving} onClick={save}>{saving ? <Loader2 size={16} /> : <Save size={16} />} Save Smart Action settings</button></div>
  </div>;
}
function Toggle({ label, checked, onChange }: { label: string; checked: boolean; onChange: (value: boolean) => void }) { return <label className={styles.toggle}><input type="checkbox" checked={checked} onChange={(event) => onChange(event.target.checked)} /><span>{label}</span></label>; }
function NumberField({ label, value, min, max, onChange }: { label: string; value: number; min: number; max: number; onChange: (value: number) => void }) { return <label className={styles.number}>{label}<input type="number" value={value} min={min} max={max} onChange={(event) => onChange(Number(event.target.value))} /></label>; }
