import Link from "next/link";
import { Archive, ArrowRight, CalendarCheck, CheckCircle2, FlaskConical, Map, MessageCircle, Rocket, ShieldCheck, Sparkles } from "lucide-react";
import { MIXARR_BETA_DISCORD_URL } from "@/lib/releaseNotes";
import { roadmapReleaseGroups, type RoadmapRelease } from "@/lib/roadmap";
import styles from "./roadmap.module.css";

export const metadata = { title: "Roadmap | Mixarr", description: "Current, next, future, and completed Mixarr releases." };

function releaseId(version:string){return `release-${version.replaceAll(".","-")}`;}
function ReleaseCard({release,compact=false}:{release:RoadmapRelease;compact?:boolean}){return <article id={releaseId(release.version)} className={styles.releaseCard} data-status={release.status} data-compact={compact}><header><div><span className={styles.versionPill}>{release.version.includes("x")?"Release line":"Patch"} · v{release.version}</span><h3>{release.title}</h3></div><span className={styles.statusPill}>{release.status==="current"?"Current release":release.status==="completed"?"Completed":"Next"}</span></header>{!compact&&<p>{release.description}</p>}{release.progress!=null&&!compact&&<div className={styles.progress}><span><b>Progress</b><em>{release.progress}%</em></span><i aria-label={`${release.progress}% complete`}><u style={{width:`${release.progress}%`}}/></i></div>}{!compact&&release.featureLabels.length>0&&<div className={styles.featureGroups}>{release.featureLabels.map((feature)=><span key={feature}>{feature}</span>)}</div>}<footer>{release.completionDate&&<span><CalendarCheck size={14}/>{release.completionDate}</span>}{release.target&&<span>{release.target}</span>}{release.route&&<Link href={release.route}>Open feature <ArrowRight size={14}/></Link>}</footer></article>}

export default function RoadmapPage(){const groups=roadmapReleaseGroups();return <main className={styles.page}><header className={styles.hero}><div><span className={styles.kicker}><Rocket size={14}/> Product roadmap</span><h1>Mixarr Product Roadmap</h1><p>The active release and next direction stay prominent. Historical details remain available in a compact archive instead of one continuous feature wall.</p></div><Map size={34}/></header><nav className={styles.controls} aria-label="Roadmap sections"><a href="#current">Current</a><a href="#next">Next</a><a href="#future">Future</a><a href="#completed">Completed</a><a href="#all-releases">All releases</a></nav>
  <section id="current" className={styles.section}><div className={styles.sectionHeading}><span><Sparkles size={19}/></span><div><small>Current release</small><h2>Finishing the active line</h2></div></div>{groups.current.map((release)=><ReleaseCard release={release} key={release.version}/>)}</section>
  <section id="next" className={styles.section}><div className={styles.sectionHeading}><span><Rocket size={19}/></span><div><small>Next release line</small><h2>What comes next</h2></div></div>{groups.next.map((release)=><ReleaseCard release={release} key={release.version}/>) }<div className={styles.boundary}><ShieldCheck size={18}/><p><strong>Roadmap only in v2.3.9.</strong> No generative AI, provider calls, or placeholder intelligence is implemented as part of Recipe Studio &amp; Release Polish.</p></div></section>
  <section id="future" className={styles.section}><div className={styles.sectionHeading}><span><FlaskConical size={19}/></span><div><small>Future releases</small><h2>Compact planning themes</h2></div></div><div className={styles.futureGrid}>{groups.future.map((cycle)=><article key={cycle.id}><span>Release line</span><h3>{cycle.title}</h3><p>{cycle.description}</p>{cycle.futureThemes&&<details><summary>Planning themes</summary><ul>{cycle.futureThemes.map((theme)=><li key={theme}>{theme}</li>)}</ul></details>}</article>)}</div></section>
  <section id="completed" className={styles.section}><div className={styles.sectionHeading}><span><Archive size={19}/></span><div><small>Completed releases</small><h2>Historical archive</h2></div></div><p className={styles.archiveIntro}>All completed roadmap information is preserved and grouped by release line. Expand only the history you need.</p><div className={styles.archive}>{groups.completed.map((cycle)=><details key={cycle.id}><summary><span><CheckCircle2 size={17}/><strong>{cycle.title}</strong></span><em>{cycle.releases.length} completed release{cycle.releases.length===1?"":"s"}</em></summary><p>{cycle.description}</p><div className={styles.archiveGrid}>{cycle.releases.map((release)=><ReleaseCard release={release} compact key={release.version}/>)}</div></details>)}</div></section>
  <section id="all-releases" className={styles.community}><MessageCircle size={20}/><div><h2>Feedback and release notes</h2><p>Release notes retain full shipped detail; the roadmap stays focused on navigation and planning state.</p><div>{MIXARR_BETA_DISCORD_URL?<a href={MIXARR_BETA_DISCORD_URL} target="_blank" rel="noopener noreferrer">Share roadmap feedback</a>:<Link href="/support">Open Beta Support</Link>}<Link href="/release-notes">Browse release notes</Link></div></div></section>
</main>}
