"use client";
import { useEffect, useState } from "react";
import Link from "next/link";
import { ArrowLeft, Copy, RefreshCw, Star, Unlink } from "lucide-react";

export default function TrackDetailsPage({ params }: { params: { id: string } }) {
  const [track, setTrack] = useState<any>(null); const [message, setMessage] = useState(""); const [busy, setBusy] = useState(false);
  async function load() { const response = await fetch(`/api/tracks/${params.id}`, { cache: "no-store" }); const data = await response.json(); if (!response.ok) throw new Error(data.error); setTrack(data); }
  // eslint-disable-next-line react-hooks/exhaustive-deps
  useEffect(() => { void load().catch((error) => setMessage(error.message)); }, [params.id]);
  async function action(name: string) { setBusy(true); try { const response = await fetch(`/api/tracks/${params.id}`, { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ action: name }) }); const data = await response.json(); if (!response.ok) throw new Error(data.error); setMessage("Track duplicate settings updated."); await load(); } catch (error) { setMessage(error instanceof Error ? error.message : "Update failed"); } finally { setBusy(false); } }
  if (!track) return <main style={{ maxWidth: 1200, margin: "0 auto" }}><p>{message || "Loading track…"}</p></main>;
  const group = track.canonicalRecording; return <main style={{ maxWidth: 1200, margin: "0 auto", display: "grid", gap: "1rem" }}><header><Link href="/library"><ArrowLeft size={15} /> Library</Link><h2>{track.artist.title} — {track.title}</h2><p>{track.album.title} · Plex rating key {track.ratingKey} · {track.fileFormat || "Unknown format"}</p></header>{message && <p>{message}</p>}<section className="glass-panel" style={{ padding: "1rem" }}><h3><Copy size={18} /> Duplicate copies</h3><p>{group ? `${group.tracks.length} copies · ${track.duplicateConfidence || group.confidence} confidence · canonical recording ${group.id}` : "This Plex item is not in a confirmed duplicate group."}</p>{group && <><div style={{ display: "flex", flexWrap: "wrap", gap: ".5rem", marginBottom: "1rem" }}><Link href={`/settings/library-health/duplicate-groups/${encodeURIComponent(group.id)}`}>Open duplicate group</Link><button disabled={busy} onClick={() => void action("analyze_separately")}><RefreshCw size={14} /> Analyze this copy separately</button><button disabled={busy} onClick={() => void action("select_preferred")}><Star size={14} /> Use as preferred enrichment source</button><button disabled={busy} onClick={() => void action("remove_from_group")}><Unlink size={14} /> Remove from duplicate group</button><button disabled={busy} onClick={() => void action("mark_different")}>Mark tracks as different recordings</button><button disabled={busy} onClick={() => void action("propagate")}>Propagate verified correction to group</button></div><div style={{ overflow: "auto" }}><table style={{ width: "100%" }}><thead><tr><th>Copy</th><th>Album</th><th>Format</th><th>Bitrate</th><th>Duration</th><th>File path</th><th>Enrichment source</th><th>Mode</th></tr></thead><tbody>{group.tracks.map((copy: any) => <tr key={copy.id}><td>{copy.title}<br /><small>Plex {copy.ratingKey}</small></td><td>{copy.album.title}</td><td>{copy.fileFormat || "Unknown"}</td><td>{copy.bitrate || "—"}</td><td>{copy.duration ? `${Math.round(copy.duration / 1000)}s` : "—"}</td><td title={copy.mediaPath || ""}>{copy.mediaPath ? `…${copy.mediaPath.slice(-60)}` : "—"}</td><td>{copy.enrichmentProvenance ? "Duplicate group" : copy.bpmSource || copy.audioFeature?.audioFeatureSource || "Unanalyzed"}</td><td>{copy.enrichmentProvenance ? "Inherited" : copy.metadataCorrections?.length ? "Overridden" : "Track-level"}</td></tr>)}</tbody></table></div></>}</section></main>;
}
