"use client";
/* eslint-disable @next/next/no-img-element */

import { useEffect, useMemo, useRef, useState } from "react";
import Link from "next/link";
import { useSearchParams } from "next/navigation";
import axios from "axios";
import { AlertTriangle, CheckCircle2, Clipboard, Download, ExternalLink, FileArchive, Globe2, Loader2, RefreshCw, Search, ShieldCheck, Upload } from "lucide-react";
import styles from "./community.module.css";

type Message = { severity: string; code: string; message: string; field?: string; blocking: boolean; suggestion?: string };
type Preview = { status: string; installable: boolean; manifest: any; recipe: any; messages: Message[]; checksum: string; trustState: string; installedMixarrVersion: string; sourceDisplay?: string; importMethod: string; changelog?: string; assets?: Record<string, string>; conflict?: { localId: string; name: string; version: string; locallyModified: boolean }; normalization: Array<{ field: string; message: string }>; ruleCount: number; governance?: any };
type Official = { recipeId: string; name: string; version: string; description?: string; author?: string; tags: string[]; minimumMixarrVersion?: string };

const tabs = [{ id: "url", label: "From URL", icon: Globe2 }, { id: "paste", label: "Paste JSON or code", icon: Clipboard }, { id: "upload", label: "Upload bundle", icon: Upload }] as const;

export default function CommunityRecipesPage() {
  const searchParams = useSearchParams();
  const [tab, setTab] = useState<(typeof tabs)[number]["id"]>("url"); const [url, setUrl] = useState(""); const [content, setContent] = useState(""); const [busy, setBusy] = useState(false); const [error, setError] = useState(""); const [notice, setNotice] = useState("");
  const [stageId, setStageId] = useState(""); const [preview, setPreview] = useState<Preview | null>(null); const [localName, setLocalName] = useState(""); const [action, setAction] = useState<"new" | "copy" | "update" | "replace">("new"); const [confirmReplace, setConfirmReplace] = useState(false); const fileRef = useRef<HTMLInputElement>(null);
  const [official, setOfficial] = useState<Official[]>([]); const [officialEnabled, setOfficialEnabled] = useState(false); const [officialError, setOfficialError] = useState(""); const [refreshedAt, setRefreshedAt] = useState(""); const [search, setSearch] = useState(""); const [tag, setTag] = useState("");

  const loadOfficial = async (refresh = false) => { try { const response = await axios.get(`/api/recipes/community/official${refresh ? "?refresh=1" : ""}`); setOfficialEnabled(response.data.enabled); setOfficial(response.data.recipes || []); setRefreshedAt(response.data.refreshedAt || ""); setOfficialError(""); } catch (caught: any) { setOfficialError(caught.response?.data?.error || "The official recipe index is unavailable."); } };
  useEffect(() => { loadOfficial(); const source = searchParams.get("url"); if (source) { setTab("url"); setUrl(source); } }, [searchParams]);
  const filteredOfficial = useMemo(() => official.filter((item) => (!search || `${item.name} ${item.description || ""} ${item.author || ""}`.toLowerCase().includes(search.toLowerCase())) && (!tag || item.tags.some((itemTag) => itemTag.toLowerCase() === tag.toLowerCase()))), [official, search, tag]);
  const tags = useMemo(() => Array.from(new Set(official.flatMap((item) => item.tags))).sort(), [official]);

  const receivePreview = (data: any) => { setStageId(data.stageId); setPreview(data.preview); setLocalName(data.preview.manifest?.name || ""); setAction(data.preview.conflict ? "copy" : "new"); setConfirmReplace(false); setNotice(""); };
  const validate = async () => { setBusy(true); setError(""); try { const response = tab === "url" ? await axios.post("/api/recipes/community/import/url", { url }) : await axios.post("/api/recipes/community/validate", { content }); receivePreview(response.data); } catch (caught: any) { setError(caught.response?.data?.error || "The recipe could not be validated."); } finally { setBusy(false); } };
  const upload = async (file?: File) => { if (!file) return; setBusy(true); setError(""); const form = new FormData(); form.append("file", file); try { receivePreview((await axios.post("/api/recipes/community/import/upload", form)).data); } catch (caught: any) { setError(caught.response?.data?.error || "The bundle could not be validated."); } finally { setBusy(false); if (fileRef.current) fileRef.current.value = ""; } };
  const importOfficial = async (recipeId: string) => { setBusy(true); setError(""); try { receivePreview((await axios.post("/api/recipes/community/official", { recipeId })).data); window.scrollTo({ top: 0, behavior: "smooth" }); } catch (caught: any) { setError(caught.response?.data?.error || "The official recipe could not be loaded."); } finally { setBusy(false); } };
  const install = async () => { if (!stageId || !preview?.installable) return; setBusy(true); setError(""); try { const result = (await axios.post("/api/recipes/community/install", { stageId, name: localName, action, confirmReplace })).data; setNotice(`Imported “${result.name}” ${result.governance?.quarantine?.required ? "into quarantine" : "pending local approval"}. Review its permissions before enabling it.`); setPreview(null); setStageId(""); } catch (caught: any) { setError(caught.response?.data?.error || "The recipe could not be imported."); } finally { setBusy(false); } };

  return <main className={styles.page}>
    <header className={styles.header}><div><span className={styles.kicker}><Globe2 size={15} /> Portable, decentralized sharing</span><h2>Community Recipes</h2><p>Import inspectable recipe data from files, links, or copy-and-paste. Mixarr never executes recipe content.</p></div><Link href="/recipes">Back to recipes</Link></header>
    {notice && <div className={styles.success} role="status"><CheckCircle2 size={20} /><span>{notice} <Link href="/recipes">View recipes</Link></span></div>}
    {error && <div className={styles.error} role="alert"><AlertTriangle size={20} /><span>{error}</span></div>}

    <section className={styles.importCard} aria-labelledby="import-community"><div><span className={styles.kicker}>Mandatory preview</span><h3 id="import-community">Import Community Recipe</h3><p>Nothing is saved until you approve the validated preview.</p></div>
      <div className={styles.tabs} role="tablist">{tabs.map((item) => { const Icon = item.icon; return <button key={item.id} role="tab" aria-selected={tab === item.id} onClick={() => setTab(item.id)}><Icon size={16} /> {item.label}</button>; })}</div>
      {tab === "url" && <div className={styles.inputRow}><label htmlFor="community-url">Direct HTTPS URL</label><input id="community-url" type="url" value={url} onChange={(event) => setUrl(event.target.value)} placeholder="https://example.org/recipe.mixarr-recipe.json" /><small>Direct JSON, ZIP bundles, GitHub files, and release assets are supported. HTML pages and private-network addresses are rejected.</small><button onClick={validate} disabled={busy || !url.trim()}>{busy ? <Loader2 className="animate-spin" size={16} /> : <ShieldCheck size={16} />} Validate and Preview</button></div>}
      {tab === "paste" && <div className={styles.inputRow}><label htmlFor="community-content">Recipe JSON or MXR1 share code</label><textarea id="community-content" rows={9} value={content} onChange={(event) => setContent(event.target.value)} placeholder="Paste community recipe JSON or MXR1:…" /><div className={styles.count}>{content.length.toLocaleString()} characters</div><button onClick={validate} disabled={busy || !content.trim()}>{busy ? <Loader2 className="animate-spin" size={16} /> : <ShieldCheck size={16} />} Validate and Preview</button></div>}
      {tab === "upload" && <div className={styles.drop}><FileArchive size={34} /><h4>JSON or .mixarr-recipe.zip</h4><p>Maximum compressed size: 20 MB. ZIP structure, file signatures, paths, and extracted size are checked before preview.</p><input ref={fileRef} type="file" accept=".json,.zip,.mixarr-recipe.zip,application/json,application/zip" onChange={(event) => upload(event.target.files?.[0])} aria-label="Choose a community recipe file" />{busy && <Loader2 className="animate-spin" />}</div>}
    </section>

    {preview && <section className={styles.preview} aria-labelledby="preview-title"><header><div><span className={styles.kicker}>Local approval</span><h3 id="preview-title">{preview.manifest?.name}</h3><p>{preview.manifest?.description || "No description provided."}</p></div><span className={styles.badge} data-state={preview.trustState}>{preview.trustState.replaceAll("_", " ")}</span></header>
      <div className={styles.warning} role="note"><AlertTriangle size={20} /><div><strong>{preview.trustState === "official" ? "Configured official source" : "Third-party community recipe"}</strong><p>Mixarr validates structure and blocks known unsafe content, but cannot guarantee quality or authorship. Review the rules. Recipes never need scripts, credentials, environment variables, plugins, or hooks.</p></div></div>
      {preview.governance && <div className={styles.governanceReview} role="region" aria-label="Recipe safety review"><div><strong>{preview.governance.official ? "Official Recipe" : preview.governance.trustState.replaceAll("_", " ")}</strong><span>{preview.governance.signature.status.replaceAll("_", " ")} signature · {preview.governance.compatibility.status.replaceAll("_", " ")} · {preview.governance.risk.riskLevel} risk ({preview.governance.risk.score}/100)</span></div><p><b>Recommended action:</b> Import in {preview.governance.recommendedImportMode.replaceAll("_", " ")} mode. The recipe remains disabled until local approval.</p>{preview.governance.quarantine.required && <p><b>Quarantine reasons:</b> {preview.governance.quarantine.reasons.join(" ")}</p>}<h4>Requested permissions</h4>{preview.governance.permissions.map((item: any) => <div className={styles.permission} data-decision={item.decision} key={item.permission}><code>{item.permission}</code><span>{item.reason}<small>{item.riskLevel} risk · {item.decision}{item.fallback ? ` · ${item.fallback}` : ""}</small></span></div>)}{preview.governance.safetyAdjustments?.map((item: any) => <p key={item.path}><b>Safety adjustment:</b> {item.message}</p>)}</div>}
      <dl className={styles.meta}><div><dt>Author</dt><dd>{preview.manifest?.author?.name}</dd></div><div><dt>Version</dt><dd>{preview.manifest?.version}</dd></div><div><dt>License</dt><dd>{preview.manifest?.license}</dd></div><div><dt>Compatibility</dt><dd>{preview.manifest?.minimumMixarrVersion ? `Mixarr ${preview.manifest.minimumMixarrVersion}+` : "Not declared"} · installed {preview.installedMixarrVersion}</dd></div><div><dt>Rules</dt><dd>{preview.ruleCount}</dd></div><div><dt>Checksum</dt><dd className={styles.mono}>{preview.checksum?.slice(0, 20)}…</dd></div></dl>
      <div className={styles.links}>{[[preview.manifest?.documentationUrl, "Documentation"], [preview.manifest?.sourceUrl || preview.sourceDisplay, "Source"], [preview.manifest?.homepage, "Homepage"]].filter(([href]) => href).map(([href, label]) => <a key={label} href={href} target="_blank" rel="noopener noreferrer">{label} <ExternalLink size={13} /></a>)}</div>
      <div className={styles.tags}>{preview.manifest?.tags?.map((value: string) => <span key={value}>{value}</span>)}</div>
      {preview.manifest?.artwork && preview.assets?.[preview.manifest.artwork] && <img className={styles.cover} src={`data:image/*;base64,${preview.assets[preview.manifest.artwork]}`} alt={`${preview.manifest.name} artwork`} />}
      {preview.manifest?.screenshots?.length > 0 && <div className={styles.gallery}>{preview.manifest.screenshots.map((item: string, index: number) => preview.assets?.[item] && <img loading="lazy" key={item} src={`data:image/*;base64,${preview.assets[item]}`} alt={`${preview.manifest.name} screenshot ${index + 1}`} />)}</div>}
      {preview.changelog && <details><summary>Changelog</summary><pre>{preview.changelog}</pre></details>}
      <details open><summary>Validation results ({preview.messages.length})</summary><div className={styles.messages}>{preview.messages.map((message) => <div key={`${message.code}-${message.field}`} data-severity={message.severity}><strong>{message.code}</strong><span>{message.message}{message.field ? ` Field: ${message.field}.` : ""}</span>{message.suggestion && <small>{message.suggestion}</small>}</div>)}</div></details>
      {preview.normalization.length > 0 && <details><summary>Normalized values</summary>{preview.normalization.map((item) => <p key={item.field}><b>{item.field}:</b> {item.message}</p>)}</details>}
      <details><summary>Recipe settings and rules</summary><pre>{JSON.stringify(preview.recipe, null, 2)}</pre></details>
      <div className={styles.approval}><label htmlFor="local-name">Requested local recipe name</label><input id="local-name" value={localName} maxLength={120} onChange={(event) => setLocalName(event.target.value)} />
        {preview.conflict && <fieldset><legend>Existing matching recipe: {preview.conflict.name} v{preview.conflict.version || "unknown"}</legend><p>{preview.conflict.locallyModified ? "The installed copy has local modifications. Importing as a copy is safest." : "Choose how to handle this matching community recipe."}</p>{(["copy", "update", "replace"] as const).map((value) => <label key={value}><input type="radio" name="action" checked={action === value} onChange={() => { setAction(value); setConfirmReplace(false); }} /> {value === "copy" ? "Import as a separate copy" : value === "update" ? "Update the existing recipe" : "Replace the existing recipe"}</label>)}{action !== "copy" && <label className={styles.confirm}><input type="checkbox" checked={confirmReplace} onChange={(event) => setConfirmReplace(event.target.checked)} /> I understand this will replace current recipe settings and any local modifications.</label>}</fieldset>}
        <p className={styles.disabledNotice}>Imported recipes are saved disabled or quarantined. They are never scheduled, run, or used to generate a playlist automatically.</p><button className={styles.approve} onClick={install} disabled={busy || !preview.installable || !localName.trim() || (Boolean(preview.conflict) && action !== "copy" && !confirmReplace)}>{busy ? <Loader2 className="animate-spin" size={17} /> : <ShieldCheck size={17} />} Import for Local Review</button>{!preview.installable && <p role="alert">Installation is blocked until all validation errors are corrected.</p>}
      </div>
    </section>}

    <section className={styles.official}><header><div><span className={styles.kicker}>Optional, read-only</span><h3>Official Repository</h3><p>{officialEnabled ? `Static index${refreshedAt ? ` · refreshed ${new Date(refreshedAt).toLocaleString()}` : ""}` : "Configure COMMUNITY_RECIPES_REPOSITORY to enable browsing."}</p></div>{officialEnabled && <button onClick={() => loadOfficial(true)}><RefreshCw size={15} /> Refresh index</button>}</header>{officialError && <p className={styles.error} role="alert">{officialError}</p>}{officialEnabled && <><div className={styles.filters}><label><Search size={15} /><input aria-label="Search official recipes" value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Search recipes" /></label><select aria-label="Filter by community tag" value={tag} onChange={(event) => setTag(event.target.value)}><option value="">All tags</option>{tags.map((value) => <option key={value}>{value}</option>)}</select></div><div className={styles.grid}>{filteredOfficial.map((item) => <article key={item.recipeId}><h4>{item.name}</h4><p>{item.description || "No description."}</p><small>{item.author || "Unknown author"} · v{item.version} · Mixarr {item.minimumMixarrVersion || "not declared"}</small><div className={styles.tags}>{item.tags.map((value) => <span key={value}>{value}</span>)}</div><button onClick={() => importOfficial(item.recipeId)} disabled={busy}><Download size={15} /> Preview and import</button></article>)}</div>{!filteredOfficial.length && <p>No recipes match these filters.</p>}</>}
    </section>
  </main>;
}
