"use client";

import { useEffect, useMemo, useState } from "react";
import Link from "next/link";
import { AlertTriangle, ArrowLeft, CheckCircle2, GitCompareArrows, Loader2 } from "lucide-react";
import { compareRecipeDocuments } from "@/lib/recipeStudio";
import styles from "../../recipe-tools.module.css";

const strategySections = ["filters", "scoring", "targets", "bpmFlow", "discovery", "variety", "playlistIdentity", "refreshPolicy", "automationPolicy"];
function display(value: unknown) { return value === undefined ? "Not present" : value === null ? "None" : typeof value === "object" ? JSON.stringify(value, null, 2) : String(value); }

export default function RecipeComparePage({ params }: { params: { id: string } }) {
  const [recipes, setRecipes] = useState<any[]>([]); const [left, setLeft] = useState<any>(null); const [right, setRight] = useState<any>(null);
  const [rightId, setRightId] = useState(""); const [onlyChanges, setOnlyChanges] = useState(true); const [selected, setSelected] = useState<Set<string>>(new Set());
  const [loading, setLoading] = useState(true); const [busy, setBusy] = useState(false); const [error, setError] = useState(""); const [notice, setNotice] = useState("");
  useEffect(() => { Promise.all([fetch(`/api/playlist-recipes/${params.id}`).then((response) => response.json()), fetch("/api/playlist-recipes?pageSize=100&sort=name").then((response) => response.json())]).then(([detail,list]) => { if (!detail.recipe) throw new Error(detail.error || "Recipe not found."); setLeft(detail.recipe); const options=(list.recipes || []).filter((recipe:any)=>recipe.id!==params.id); setRecipes(options); if(options[0])setRightId(options[0].id); }).catch((caught)=>setError(caught.message)).finally(()=>setLoading(false)); }, [params.id]);
  useEffect(() => { if (!rightId) { setRight(null); return; } fetch(`/api/playlist-recipes/${rightId}`).then((response)=>response.json()).then((body)=>{ if(!body.recipe)throw new Error(body.error); setRight(body.recipe); setSelected(new Set()); }).catch((caught)=>setError(caught.message)); }, [rightId]);
  const differences = useMemo(() => left && right ? compareRecipeDocuments(Object.fromEntries(strategySections.map((section)=>[section,left[section]])), Object.fromEntries(strategySections.map((section)=>[section,right[section]]))) : [], [left,right]);
  const rows = useMemo(() => onlyChanges ? differences : strategySections.map((section)=>({ path:section,before:left?.[section],after:right?.[section],section })), [differences,left,right,onlyChanges]);
  const grouped = useMemo(() => Object.entries(rows.reduce<Record<string, any[]>>((result,row)=>{(result[row.section] ||= []).push(row);return result;},{})), [rows]);
  async function copySelected() { if(!left||!right||!selected.size)return; if(!window.confirm(`Replace ${selected.size} selected section(s) in “${left.name}” with values from “${right.name}”? A new recipe revision will be created.`))return; const selectedSections=Array.from(selected);setBusy(true);setError("");try{const payload:any={name:left.name,description:left.description,category:left.category,artworkUrl:left.artworkUrl,enabled:left.enabled,expectedUpdatedAt:left.updatedAt};for(const section of selectedSections)payload[section]=right[section];for(const section of strategySections)if(payload[section]===undefined)payload[section]=left[section];const response=await fetch(`/api/playlist-recipes/${left.id}`,{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify(payload)});const body=await response.json();if(!response.ok)throw new Error(body.error||"Selected settings were not copied.");setLeft(body.recipe);setSelected(new Set());setNotice(`Copied ${selectedSections.length} section(s) into a new revision of ${left.name}.`);}catch(caught){setError(caught instanceof Error?caught.message:"Selected settings were not copied.");}finally{setBusy(false);}}
  if(loading)return <main className={styles.state}><Loader2 className="animate-spin"/>Loading comparison…</main>;
  return <main className={styles.page}><header className={styles.header}><div><Link href={`/recipes/${params.id}`}><ArrowLeft size={15}/> Recipe details</Link><span><GitCompareArrows size={15}/> Recipe comparison</span><h1>{left?.name || "Recipe"}</h1><p>Compare strategy sections side by side. Nothing is overwritten without explicit confirmation.</p></div><Link className={styles.primary} href={`/recipes/${params.id}/edit`}>Open Recipe Studio</Link></header>
    {(error||notice)&&<div className={error?styles.error:styles.notice} role={error?"alert":"status"}>{error?<AlertTriangle/>:<CheckCircle2/>}{error||notice}</div>}
    <section className={styles.toolbar}><label>Compare with<select value={rightId} onChange={(event)=>setRightId(event.target.value)}><option value="">Choose a recipe</option>{recipes.map((recipe)=><option value={recipe.id} key={recipe.id}>{recipe.name} · v{recipe.recipeVersion}</option>)}</select></label><label className={styles.check}><input type="checkbox" checked={onlyChanges} onChange={(event)=>setOnlyChanges(event.target.checked)}/> Show only differences</label><button className={styles.primary} disabled={!selected.size||busy} onClick={()=>void copySelected()}>{busy?<Loader2 className="animate-spin"/>:`Copy ${selected.size} selected section(s)`}</button></section>
    {!right?<section className={styles.empty}>Choose another installed recipe or version to compare.</section>:!differences.length?<section className={styles.empty}><CheckCircle2/>These recipe strategies are identical.</section>:<div className={styles.diffGroups}>{grouped.map(([section,items])=><section key={section}><header><label><input type="checkbox" checked={selected.has(section)} onChange={(event)=>setSelected((current)=>{const next=new Set(current);event.target.checked?next.add(section):next.delete(section);return next;})}/><strong>{section.replace(/([A-Z])/g," $1")}</strong></label><span>{items.length} change{items.length===1?"":"s"}</span></header><div className={styles.diffHeader}><span>{left.name} · v{left.recipeVersion}</span><span>{right.name} · v{right.recipeVersion}</span></div>{items.map((row)=><article className={styles.diffRow} key={row.path}><code>{row.path}</code><pre>{display(row.before)}</pre><pre>{display(row.after)}</pre></article>)}</section>)}</div>}
  </main>;
}
