import { NextResponse } from "next/server";
import { z } from "zod";
import prisma from "@/lib/prisma";
import { orchestrationApiError, orchestrationSession, orchestrationUnauthorized, pageInput } from "@/lib/orchestration/api";
import { createManagedPlaylistRelationship } from "@/lib/orchestration/service";
import { getOrchestrationRelationships } from "@/lib/orchestration/ecosystem";
const schema = z.object({ sourceManagedPlaylistId: z.string().uuid(), targetManagedPlaylistId: z.string().uuid(), relationshipType: z.enum(["DEPENDS_ON", "RUNS_AFTER", "RELATED"]), priority: z.number().int().min(-100).max(100).optional(), metadata: z.record(z.unknown()).optional() });
export async function GET(request: Request) { const userId = orchestrationSession(); if (!userId) return orchestrationUnauthorized(); const { page, pageSize, skip, url } = pageInput(request); try { if (url.searchParams.get("view") === "graph") return NextResponse.json(await getOrchestrationRelationships(userId, { search: url.searchParams.get("search") || undefined, groupId: url.searchParams.get("groupId") || undefined, relationshipType: url.searchParams.get("relationshipType") || undefined, minimumStrength: Number(url.searchParams.get("minimumStrength")) || 0, health: url.searchParams.get("health") || undefined, includePaused: url.searchParams.get("includePaused") === "true", limit: Number(url.searchParams.get("limit")) || undefined })); const where = { sourceManagedPlaylist: { userId } }; const [items, total] = await Promise.all([prisma.managedPlaylistRelationship.findMany({ where, include: { sourceManagedPlaylist: { select: { id: true, displayName: true, automationState: true } }, targetManagedPlaylist: { select: { id: true, displayName: true, automationState: true } } }, orderBy: [{ priority: "desc" }, { createdAt: "asc" }], skip, take: pageSize }), prisma.managedPlaylistRelationship.count({ where })]); return NextResponse.json({ items, pagination: { page, pageSize, total, pages: Math.ceil(total / pageSize) } }); } catch (error) { return orchestrationApiError(error); } }
export async function POST(request: Request) { const userId = orchestrationSession(); if (!userId) return orchestrationUnauthorized(); try { const input = schema.parse(await request.json()); const relationship = await createManagedPlaylistRelationship({ userId, ...input, actorId: userId }); return NextResponse.json({ relationship }, { status: 201 }); } catch (error) { return orchestrationApiError(error); } }
