import { sanitizeErrorText } from "../../lib/supportRedaction";

export const AI_ERROR_CATEGORIES = [
  "AI_DISABLED", "FEATURE_DISABLED", "PROVIDER_NOT_CONFIGURED", "PROVIDER_DISABLED", "PROVIDER_NOT_FOUND", "PROVIDER_UNAVAILABLE", "PROVIDER_UNSUPPORTED", "MODEL_NOT_CONFIGURED", "MODEL_NOT_FOUND", "CAPABILITY_UNAVAILABLE", "AUTHENTICATION_FAILED", "PERMISSION_DENIED", "RATE_LIMITED", "BUDGET_EXCEEDED",
  "AI_PROVIDER_NOT_FOUND", "AI_PROVIDER_DELETE_FORBIDDEN", "AI_PROVIDER_DELETE_CONFLICT", "AI_PROVIDER_DELETE_FAILED", "AI_PROVIDER_ACTIVE_REQUEST", "AI_PROVIDER_LAST_AVAILABLE_PROVIDER",
  "AI_PRIVACY_POLICY_BLOCKED", "AI_EXTERNAL_PROVIDER_BLOCKED", "AI_PAID_FALLBACK_BLOCKED", "AI_GLOBAL_BUDGET_EXCEEDED", "AI_PROVIDER_BUDGET_EXCEEDED", "AI_USER_BUDGET_EXCEEDED", "AI_DAILY_REQUEST_LIMIT_EXCEEDED", "AI_TOKEN_LIMIT_EXCEEDED", "AI_PROMPT_TOO_LARGE", "AI_RESPONSE_LIMIT_INVALID", "AI_MODEL_PRICING_MISSING", "AI_CONTEXT_TRIMMING_FAILED", "AI_BACKGROUND_REQUEST_BLOCKED", "AI_RETRY_COST_LIMIT_EXCEEDED", "AI_NO_ELIGIBLE_PROVIDER",
  "AI_PROVIDER_UNAVAILABLE", "AI_MODEL_UNAVAILABLE", "AI_MODEL_PRICING_UNAVAILABLE", "AI_REQUEST_COST_LIMIT_EXCEEDED", "AI_DAILY_LIMIT_EXCEEDED", "AI_MONTHLY_BUDGET_EXCEEDED", "AI_PROVIDER_AUTH_FAILED", "AI_PROVIDER_RATE_LIMITED", "AI_PROVIDER_TEMPORARY_FAILURE", "AI_PROVIDER_TIMEOUT", "AI_PROVIDER_HTTP_ERROR", "AI_PROVIDER_EMPTY_RESPONSE", "AI_PROVIDER_INVALID_RESPONSE", "AI_RECIPE_SCHEMA_INVALID", "AI_RECIPE_REQUEST_FAILED",
  "PROVIDER_CLASSIFICATION_UNKNOWN", "PAID_PROVIDER_NOT_PERMITTED", "BACKGROUND_REQUEST_NOT_PERMITTED", "MODEL_UNPRICED", "PRIVACY_MODE_INCOMPATIBLE", "DAILY_REQUEST_LIMIT_REACHED", "MONTHLY_REQUEST_LIMIT_REACHED", "DAILY_COST_LIMIT_REACHED", "MONTHLY_COST_LIMIT_REACHED", "PROVIDER_CONNECTION_FAILED", "PROVIDER_TIMEOUT", "PROVIDER_UNAUTHORIZED", "PROVIDER_PERMISSION_DENIED", "PROVIDER_ENDPOINT_INVALID", "PROVIDER_RATE_LIMITED", "PROVIDER_QUOTA_EXCEEDED", "PROVIDER_REQUEST_INVALID", "PROVIDER_SERVICE_ERROR", "PROVIDER_RESPONSE_INVALID", "PROVIDER_SECRET_UNAVAILABLE", "MODEL_NOT_AVAILABLE", "MODEL_NOT_COMPATIBLE",
  "REQUEST_TIMEOUT", "REQUEST_CANCELLED", "CONNECTION_FAILED", "TLS_ERROR", "INVALID_REQUEST", "INVALID_RESPONSE", "STRUCTURED_RESPONSE_INVALID", "RESPONSE_TOO_LARGE", "STREAM_INTERRUPTED", "PROVIDER_OVERLOADED", "INTERNAL_AI_ERROR",
  "AI_EMERGENCY_SHUTDOWN", "AI_PROVIDER_NOT_APPROVED", "AI_PROVIDER_FEATURE_BLOCKED", "AI_MODEL_NOT_APPROVED", "AI_MODEL_DISABLED", "AI_MODEL_FEATURE_BLOCKED", "AI_EXTERNAL_CONFIRMATION_REQUIRED", "AI_PROMPT_INJECTION_BLOCKED", "AI_RESPONSE_QUARANTINED", "AI_QUEUE_FULL", "AI_DUPLICATE_REQUEST", "AI_JOB_NOT_FOUND", "AI_JOB_NOT_CANCELLABLE", "AI_PROMPT_TEMPLATE_INVALID"
] as const;
export type AiErrorCategory = typeof AI_ERROR_CATEGORIES[number];

const publicMessages: Record<AiErrorCategory, string> = {
  AI_DISABLED: "AI is disabled in Mixarr settings.", FEATURE_DISABLED: "This AI feature is disabled.", PROVIDER_NOT_CONFIGURED: "No AI provider is configured for this feature.", PROVIDER_DISABLED: "The selected AI provider is disabled.", PROVIDER_NOT_FOUND: "The selected AI provider no longer exists.", PROVIDER_UNAVAILABLE: "The selected AI provider is currently unavailable.", PROVIDER_UNSUPPORTED: "This provider integration is not available.", MODEL_NOT_CONFIGURED: "No model is configured for this request.", MODEL_NOT_FOUND: "The configured model is unavailable.", CAPABILITY_UNAVAILABLE: "The provider does not have a required capability.", AUTHENTICATION_FAILED: "The provider rejected its configured credentials.", PERMISSION_DENIED: "The provider denied this request.", RATE_LIMITED: "The provider is rate limiting requests.", BUDGET_EXCEEDED: "The provider monthly budget has been reached.",
  AI_PROVIDER_NOT_FOUND: "The AI provider configuration was not found.", AI_PROVIDER_DELETE_FORBIDDEN: "You do not have permission to delete this AI provider.", AI_PROVIDER_DELETE_CONFLICT: "The AI provider could not be deleted because its configuration changed. Refresh and try again.", AI_PROVIDER_DELETE_FAILED: "The AI provider could not be deleted. No settings were changed.", AI_PROVIDER_ACTIVE_REQUEST: "This provider currently has an active AI request. Try deleting it after the request completes.", AI_PROVIDER_LAST_AVAILABLE_PROVIDER: "This is the last available AI provider.",
  AI_PRIVACY_POLICY_BLOCKED: "The configured AI privacy policy blocked this request.", AI_EXTERNAL_PROVIDER_BLOCKED: "External AI providers are blocked by the active privacy policy.", AI_PAID_FALLBACK_BLOCKED: "Fallback to a paid AI provider is disabled.", AI_GLOBAL_BUDGET_EXCEEDED: "The configured monthly AI budget has been reached.", AI_PROVIDER_BUDGET_EXCEEDED: "The selected provider budget has been reached.", AI_USER_BUDGET_EXCEEDED: "The requesting user's AI budget has been reached.", AI_DAILY_REQUEST_LIMIT_EXCEEDED: "The applicable AI request limit has been reached.", AI_TOKEN_LIMIT_EXCEEDED: "The AI request exceeds the applicable token limit.", AI_PROMPT_TOO_LARGE: "The AI request prompt exceeds the configured size limit.", AI_RESPONSE_LIMIT_INVALID: "The requested response limits are invalid.", AI_MODEL_PRICING_MISSING: "Pricing is required for this external AI model.", AI_CONTEXT_TRIMMING_FAILED: "The AI request could not be reduced to the configured context limit.", AI_BACKGROUND_REQUEST_BLOCKED: "Background AI requests are disabled by policy.", AI_RETRY_COST_LIMIT_EXCEEDED: "Retrying could exceed the configured AI retry cost limit.", AI_NO_ELIGIBLE_PROVIDER: "No provider satisfies the current privacy, budget, and capability policies.",
  AI_PROVIDER_UNAVAILABLE: "No enabled AI provider is available.", AI_MODEL_UNAVAILABLE: "No usable AI model is configured for Recipe Copilot.", AI_MODEL_PRICING_UNAVAILABLE: "Pricing is unavailable for the selected AI model.", AI_REQUEST_COST_LIMIT_EXCEEDED: "The estimated cost exceeds the per-request AI cost limit.", AI_DAILY_LIMIT_EXCEEDED: "The applicable daily AI limit has been reached.", AI_MONTHLY_BUDGET_EXCEEDED: "The configured AI monthly budget has been reached.", AI_PROVIDER_AUTH_FAILED: "The AI provider rejected its configured credentials.", AI_PROVIDER_RATE_LIMITED: "The AI provider temporarily rate-limited the request.", AI_PROVIDER_TEMPORARY_FAILURE: "The AI provider is temporarily unavailable.", AI_PROVIDER_TIMEOUT: "The AI provider did not respond before the configured timeout.", AI_PROVIDER_HTTP_ERROR: "The AI provider returned an HTTP error.", AI_PROVIDER_EMPTY_RESPONSE: "The AI provider returned an empty response.", AI_PROVIDER_INVALID_RESPONSE: "The AI provider returned a response that could not be parsed.", AI_RECIPE_SCHEMA_INVALID: "The AI response could not be converted into a valid recipe.", AI_RECIPE_REQUEST_FAILED: "Recipe Copilot could not complete the request.",
  PROVIDER_CLASSIFICATION_UNKNOWN: "Mixarr could not safely classify this provider and model as local, external-free, or externally paid.", PAID_PROVIDER_NOT_PERMITTED: "This model is classified as paid and the current user is not permitted to use paid providers.", BACKGROUND_REQUEST_NOT_PERMITTED: "The current user or global policy does not permit background AI requests.", MODEL_UNPRICED: "Pricing is not configured for this external AI model.", PRIVACY_MODE_INCOMPATIBLE: "The provider is incompatible with the resolved AI privacy mode.", DAILY_REQUEST_LIMIT_REACHED: "The applicable daily AI request limit has been reached.", MONTHLY_REQUEST_LIMIT_REACHED: "The applicable monthly AI request limit has been reached.", DAILY_COST_LIMIT_REACHED: "The applicable daily AI cost limit has been reached.", MONTHLY_COST_LIMIT_REACHED: "The applicable monthly AI cost limit has been reached.", PROVIDER_CONNECTION_FAILED: "Mixarr could not establish a network connection to the provider API.", PROVIDER_TIMEOUT: "The provider request timed out after a connection was attempted.", PROVIDER_UNAUTHORIZED: "The provider rejected the configured API credential.", PROVIDER_PERMISSION_DENIED: "The API credential does not have permission to perform this operation.", PROVIDER_ENDPOINT_INVALID: "The configured provider URL or endpoint mode is invalid.", PROVIDER_RATE_LIMITED: "The provider temporarily rate-limited the request. Try again shortly.", PROVIDER_QUOTA_EXCEEDED: "The provider accepted the API key, but the project has no available API quota.", PROVIDER_REQUEST_INVALID: "The provider rejected the test request as invalid.", PROVIDER_SERVICE_ERROR: "The provider service could not complete the request.", PROVIDER_RESPONSE_INVALID: "The provider returned a successful response that Mixarr could not parse.", PROVIDER_SECRET_UNAVAILABLE: "Mixarr could not access the saved credential for this provider. Re-enter the API key and save the provider.", MODEL_NOT_AVAILABLE: "The API key is valid, but the selected model is unavailable to this provider project.", MODEL_NOT_COMPATIBLE: "The selected model cannot be used for a standard text response test.",
  REQUEST_TIMEOUT: "The AI request timed out.", REQUEST_CANCELLED: "The AI request was cancelled.", CONNECTION_FAILED: "Mixarr could not connect to the provider.", TLS_ERROR: "The provider TLS connection could not be verified.", INVALID_REQUEST: "The AI request is invalid.", INVALID_RESPONSE: "The provider returned an invalid response.", STRUCTURED_RESPONSE_INVALID: "The provider response did not match the required structure.", RESPONSE_TOO_LARGE: "The provider response exceeded the configured size limit.", STREAM_INTERRUPTED: "The provider stream ended unexpectedly.", PROVIDER_OVERLOADED: "The provider is temporarily overloaded.", INTERNAL_AI_ERROR: "The AI request could not be completed.",
  AI_EMERGENCY_SHUTDOWN: "Emergency AI shutdown is active.", AI_PROVIDER_NOT_APPROVED: "This provider is not approved for AI requests.", AI_PROVIDER_FEATURE_BLOCKED: "This provider is not approved for the requested AI feature.", AI_MODEL_NOT_APPROVED: "This model is not approved for use.", AI_MODEL_DISABLED: "This model is disabled.", AI_MODEL_FEATURE_BLOCKED: "This model is not approved for this feature.", AI_EXTERNAL_CONFIRMATION_REQUIRED: "Confirm the external data-sharing preview before this request can be sent.", AI_PROMPT_INJECTION_BLOCKED: "This request may contain instructions intended to bypass Mixarr's safety controls.", AI_RESPONSE_QUARANTINED: "The provider response could not be validated and was quarantined.", AI_QUEUE_FULL: "The AI queue is full. Try again after queued work completes.", AI_DUPLICATE_REQUEST: "This request duplicates an existing AI job.", AI_JOB_NOT_FOUND: "The AI job was not found.", AI_JOB_NOT_CANCELLABLE: "The AI job can no longer be cancelled.", AI_PROMPT_TEMPLATE_INVALID: "The AI prompt template failed validation."
};

export class AiError extends Error {
  constructor(public category: AiErrorCategory, message = publicMessages[category], public status = statusForCategory(category), public retryAfterMs?: number, public details?: Record<string, unknown>) { super(message); Object.setPrototypeOf(this, new.target.prototype); this.name = "AiError"; }
  toSafePayload() { const error = { code: this.category, message: publicMessages[this.category], ...(this.details ? { details: this.details } : {}) }; return { error, ...error }; }
}

export function statusForCategory(category: AiErrorCategory) {
  if (["AI_DISABLED", "AI_EMERGENCY_SHUTDOWN", "FEATURE_DISABLED", "PROVIDER_DISABLED", "AI_PROVIDER_NOT_APPROVED", "AI_PROVIDER_FEATURE_BLOCKED", "AI_MODEL_NOT_APPROVED", "AI_MODEL_DISABLED", "AI_MODEL_FEATURE_BLOCKED", "AI_EXTERNAL_CONFIRMATION_REQUIRED", "AI_PROMPT_INJECTION_BLOCKED", "AI_RESPONSE_QUARANTINED", "AI_QUEUE_FULL", "AI_DUPLICATE_REQUEST", "CAPABILITY_UNAVAILABLE", "BUDGET_EXCEEDED", "AI_PRIVACY_POLICY_BLOCKED", "AI_EXTERNAL_PROVIDER_BLOCKED", "AI_PAID_FALLBACK_BLOCKED", "AI_GLOBAL_BUDGET_EXCEEDED", "AI_PROVIDER_BUDGET_EXCEEDED", "AI_USER_BUDGET_EXCEEDED", "AI_DAILY_REQUEST_LIMIT_EXCEEDED", "AI_TOKEN_LIMIT_EXCEEDED", "AI_PROMPT_TOO_LARGE", "AI_RESPONSE_LIMIT_INVALID", "AI_MODEL_PRICING_MISSING", "AI_CONTEXT_TRIMMING_FAILED", "AI_BACKGROUND_REQUEST_BLOCKED", "AI_RETRY_COST_LIMIT_EXCEEDED", "AI_NO_ELIGIBLE_PROVIDER", "AI_PROVIDER_UNAVAILABLE", "AI_MODEL_UNAVAILABLE", "AI_MODEL_PRICING_UNAVAILABLE", "AI_REQUEST_COST_LIMIT_EXCEEDED", "AI_DAILY_LIMIT_EXCEEDED", "AI_MONTHLY_BUDGET_EXCEEDED", "PROVIDER_CLASSIFICATION_UNKNOWN", "PAID_PROVIDER_NOT_PERMITTED", "BACKGROUND_REQUEST_NOT_PERMITTED", "MODEL_UNPRICED", "PRIVACY_MODE_INCOMPATIBLE", "DAILY_REQUEST_LIMIT_REACHED", "MONTHLY_REQUEST_LIMIT_REACHED", "DAILY_COST_LIMIT_REACHED", "MONTHLY_COST_LIMIT_REACHED"].includes(category)) return 409;
  if (["PROVIDER_NOT_CONFIGURED", "PROVIDER_NOT_FOUND", "AI_PROVIDER_NOT_FOUND", "MODEL_NOT_FOUND", "MODEL_NOT_AVAILABLE", "AI_JOB_NOT_FOUND"].includes(category)) return 404;
  if (["AUTHENTICATION_FAILED", "PROVIDER_UNAUTHORIZED", "AI_PROVIDER_AUTH_FAILED"].includes(category)) return 401;
  if (["PERMISSION_DENIED", "PROVIDER_PERMISSION_DENIED", "AI_PROVIDER_DELETE_FORBIDDEN"].includes(category)) return 403;
  if (["AI_PROVIDER_DELETE_CONFLICT", "AI_PROVIDER_ACTIVE_REQUEST", "AI_PROVIDER_LAST_AVAILABLE_PROVIDER"].includes(category)) return 409;
  if (["INVALID_REQUEST", "MODEL_NOT_CONFIGURED", "STRUCTURED_RESPONSE_INVALID", "RESPONSE_TOO_LARGE", "PROVIDER_REQUEST_INVALID", "MODEL_NOT_COMPATIBLE", "PROVIDER_ENDPOINT_INVALID", "AI_JOB_NOT_CANCELLABLE", "AI_PROMPT_TEMPLATE_INVALID"].includes(category)) return 400;
  if (["AI_PROVIDER_INVALID_RESPONSE", "AI_RECIPE_SCHEMA_INVALID"].includes(category)) return 422;
  if (["RATE_LIMITED", "PROVIDER_RATE_LIMITED", "PROVIDER_QUOTA_EXCEEDED", "AI_PROVIDER_RATE_LIMITED"].includes(category)) return 429;
  if (["REQUEST_TIMEOUT", "PROVIDER_TIMEOUT", "AI_PROVIDER_TIMEOUT"].includes(category)) return 504;
  if (category === "INTERNAL_AI_ERROR" || category === "AI_PROVIDER_DELETE_FAILED") return 500;
  return 502;
}

export function normalizeProviderError(error: unknown, status?: number, retryAfterMs?: number): AiError {
  if (error instanceof AiError) return error;
  if ((error as Error)?.name === "AbortError") return new AiError("REQUEST_CANCELLED");
  if (status === 401) return new AiError("AUTHENTICATION_FAILED");
  if (status === 403) return new AiError("PERMISSION_DENIED");
  if (status === 408) return new AiError("REQUEST_TIMEOUT");
  if (status === 429) return new AiError("RATE_LIMITED", undefined, 429, retryAfterMs);
  if ([500, 502, 503, 504].includes(status || 0)) return new AiError("PROVIDER_OVERLOADED");
  const safe = sanitizeErrorText(error) || "Provider request failed.";
  if (/certificate|tls|ssl/i.test(safe)) return new AiError("TLS_ERROR");
  if (/timeout/i.test(safe)) return new AiError("REQUEST_TIMEOUT");
  return new AiError("CONNECTION_FAILED");
}

export function aiApiError(error: unknown) {
  const normalized = error instanceof AiError ? error : new AiError("INTERNAL_AI_ERROR");
  return { payload: normalized.toSafePayload(), status: normalized.status };
}
