import type { AiCapabilityResult, AiConnectionTestResult, AiModel, AiProviderAdapter, AiProviderExecutionContext, AiRequest, AiResponse, AiStreamEvent, ResolvedAiProviderConfig } from "../contracts";
import { AiError, normalizeProviderError } from "../errors";
import { configuredHeaders, joinUrl, parseTextLines, providerFetch, safeFetchJson, safeFetchJsonDetailed } from "./http";
import { normalizeAIResponse } from "./normalizeResponse";

export class AnthropicAdapter implements AiProviderAdapter {
  readonly providerType = "anthropic" as const; readonly available = true;
  private base(config: ResolvedAiProviderConfig) { return config.baseUrl || "https://api.anthropic.com"; }
  private headers(config: ResolvedAiProviderConfig) { const headers = configuredHeaders({ ...config, apiKey: undefined }, { "anthropic-version": String(config.customConfiguration.anthropicVersion || "2023-06-01") }); if (config.apiKey) headers["x-api-key"] = config.apiKey; return headers; }
  private capabilities(config?: ResolvedAiProviderConfig): AiCapabilityResult { return { text_generation: "CONFIRMED", chat_messages: "CONFIRMED", system_instructions: "CONFIRMED", structured_json: "ASSUMED", json_schema: "UNKNOWN", streaming: "CONFIRMED", request_cancellation: "CONFIRMED", model_discovery: "REPORTED", token_usage: "CONFIRMED", cost_reporting: "UNSUPPORTED", reasoning_models: "REPORTED", large_context: "REPORTED", custom_headers: "CONFIRMED", remote_operation: "CONFIRMED", health_testing: "CONFIRMED", ...(config?.capabilityOverrides || {}) }; }
  async discoverModels(config: ResolvedAiProviderConfig, signal?: AbortSignal): Promise<AiModel[]> { const payload = await safeFetchJson(joinUrl(this.base(config), "/v1/models"), { headers: this.headers(config), signal }, 2_000_000); return (Array.isArray(payload?.data) ? payload.data : []).map((item: any) => ({ id: String(item.id), displayName: String(item.display_name || item.id), category: /haiku/i.test(item.id) ? "FAST" : /opus/i.test(item.id) ? "REASONING" : "REMOTE", capabilities: this.capabilities(config), available: true })); }
  async detectCapabilities(config: ResolvedAiProviderConfig) { return this.capabilities(config); }
  async testConnection(config: ResolvedAiProviderConfig, signal?: AbortSignal): Promise<AiConnectionTestResult> { const started = Date.now(); const models = await this.discoverModels(config, signal); if (config.defaultModel) await this.complete({ featureKey: "connection_test", messages: [{ role: "user", content: "Reply with OK." }] }, config, { requestId: crypto.randomUUID(), providerId: config.id, model: config.defaultModel, signal: signal || new AbortController().signal, maxResponseBytes: 16_384 }); return { connected: true, message: config.defaultModel ? "Anthropic connection and Messages API completion succeeded." : "Anthropic is reachable. Select a model to test Messages API completion.", latencyMs: Date.now() - started, detectedApiType: "anthropic-messages", capabilities: this.capabilities(config), availableModelCount: models.length, defaultModelAvailable: config.defaultModel ? models.some((model) => model.id === config.defaultModel) : null, testedAt: new Date().toISOString() }; }
  async complete<T>(request: AiRequest<T>, config: ResolvedAiProviderConfig, context: AiProviderExecutionContext): Promise<AiResponse<T>> { const started = Date.now(); const system = [request.systemInstructions, request.responseFormat ? "Return only valid JSON matching the requested structure." : ""].filter(Boolean).join("\n"); const result = await safeFetchJsonDetailed(joinUrl(this.base(config), "/v1/messages"), { method: "POST", headers: this.headers(config), signal: context.signal, body: JSON.stringify({ model: context.model, system: system || undefined, messages: request.messages, temperature: request.temperature, stream: false }) }, context.maxResponseBytes, { requestId: context.requestId, provider: config.displayName, model: context.model, stage: "CHAT_COMPLETION", lifecycle: context.lifecycle, sslVerification: config.sslVerification }); const normalized = normalizeAIResponse(result.payload, { providerType: "anthropic", provider: config.displayName, requestedModel: context.model, requestId: context.requestId, transport: result.transport, allowDirectStructuredObject: !!request.responseFormat }); context.lifecycle?.responseActivity({ meaningful: true, producedOutput: normalized.text.length > 0 }); return { requestId: context.requestId, providerId: config.id, providerType: "anthropic", model: normalized.model || context.model, content: normalized.text, usage: normalized.usage, finishReason: normalized.finishReason, latencyMs: Date.now() - started, retryCount: 0, streaming: false, warnings: ["Cost data unavailable"], transport: result.transport }; }
  async *stream<T>(request: AiRequest<T>, config: ResolvedAiProviderConfig, context: AiProviderExecutionContext): AsyncIterable<AiStreamEvent> { let response: Response; try { response = await providerFetch(joinUrl(this.base(config), "/v1/messages"), { method: "POST", headers: this.headers(config), signal: context.signal, body: JSON.stringify({ model: context.model, system: request.systemInstructions, messages: request.messages, temperature: request.temperature, stream: true }) }, context.lifecycle, config.sslVerification); } catch (error) { throw normalizeProviderError(error); } if (!response.ok) throw normalizeProviderError(new Error(`Provider returned HTTP ${response.status}.`), response.status); yield { type: "started", requestId: context.requestId }; for await (const line of parseTextLines(response, context.maxResponseBytes, context.signal, context.lifecycle)) { if (!line.startsWith("data:")) continue; let event: any; try { event = JSON.parse(line.slice(5).trim()); } catch { continue; } const meaningful = event.type === "content_block_delta" && typeof event.delta?.text === "string" && event.delta.text.length > 0; context.lifecycle?.responseActivity({ meaningful, producedOutput: meaningful }); if (meaningful) yield request.responseFormat ? { type: "structured_delta", delta: event.delta.text } : { type: "text_delta", delta: event.delta.text }; if (event.type === "message_delta" && event.usage) yield { type: "usage", usage: { outputTokens: event.usage.output_tokens } }; if (event.type === "message_stop") { context.lifecycle?.responseActivity({ meaningful: true, producedOutput: false }); yield { type: "completed" }; return; } } }
}
